In [1]:
# ============================================================
# FORS-EMG RESEARCH PROJECT
# STEP 1 — ENVIRONMENT + DATASET DOWNLOAD + INITIAL INSPECTION
# ============================================================

import os
import sys
import json
import glob
import shutil
import zipfile
import subprocess
from pathlib import Path

print("=" * 70)
print("FORS-EMG RESEARCH PROJECT")
print("STEP 1 — ENVIRONMENT SETUP")
print("=" * 70)

# ------------------------------------------------------------
# 1. PYTHON VERSION
# ------------------------------------------------------------

print("\n[1] Python")
print("-" * 70)
print("Python version:", sys.version)


# ------------------------------------------------------------
# 2. GPU INFORMATION
# ------------------------------------------------------------

print("\n[2] GPU INFORMATION")
print("-" * 70)

try:
    import torch

    print("PyTorch version:", torch.__version__)
    print("CUDA available:", torch.cuda.is_available())

    if torch.cuda.is_available():
        print("GPU:", torch.cuda.get_device_name(0))
        print(
            "GPU memory:",
            round(
                torch.cuda.get_device_properties(0).total_memory / (1024**3),
                2
            ),
            "GB"
        )
    else:
        print("WARNING: GPU is not available.")

except Exception as e:
    print("PyTorch check failed:", e)


# ------------------------------------------------------------
# 3. CREATE PROJECT DIRECTORIES
# ------------------------------------------------------------

print("\n[3] PROJECT DIRECTORIES")
print("-" * 70)

PROJECT_ROOT = Path("/kaggle/working/fors_emg_research")

DIRS = {
    "project": PROJECT_ROOT,
    "raw": PROJECT_ROOT / "raw_data",
    "processed": PROJECT_ROOT / "processed_data",
    "features": PROJECT_ROOT / "features",
    "splits": PROJECT_ROOT / "splits",
    "models": PROJECT_ROOT / "models",
    "results": PROJECT_ROOT / "results",
    "figures": PROJECT_ROOT / "figures",
    "logs": PROJECT_ROOT / "logs",
    "reports": PROJECT_ROOT / "reports",
    "checkpoints": PROJECT_ROOT / "checkpoints",
}

for name, path in DIRS.items():
    path.mkdir(parents=True, exist_ok=True)
    print(f"{name:15s} -> {path}")


# ------------------------------------------------------------
# 4. DOWNLOAD FORS-EMG FROM KAGGLE
# ------------------------------------------------------------

print("\n[4] DOWNLOADING FORS-EMG")
print("-" * 70)

DATASET_SLUG = "ummerummanchaity/fors-emg-a-novel-semg-dataset"

KAGGLE_DOWNLOAD_DIR = DIRS["raw"] / "kaggle_download"
KAGGLE_DOWNLOAD_DIR.mkdir(parents=True, exist_ok=True)

print("Dataset:", DATASET_SLUG)
print("Download directory:", KAGGLE_DOWNLOAD_DIR)

# Check whether Kaggle API is available
kaggle_command = shutil.which("kaggle")

if kaggle_command is None:
    print("\nKaggle CLI not found. Installing kaggle package...")
    subprocess.check_call(
        [sys.executable, "-m", "pip", "install", "-q", "kaggle"]
    )

print("\nDownloading dataset...")

download_command = [
    "kaggle",
    "datasets",
    "download",
    "-d",
    DATASET_SLUG,
    "-p",
    str(KAGGLE_DOWNLOAD_DIR),
    "--unzip"
]

result = subprocess.run(
    download_command,
    capture_output=True,
    text=True
)

print(result.stdout)

if result.returncode != 0:
    print("\nKAGGLE DOWNLOAD ERROR:")
    print(result.stderr)
    raise RuntimeError(
        "Dataset download failed. "
        "Check that Kaggle Internet is ON and your Kaggle API access is available."
    )

print("\nDataset download completed successfully.")


# ------------------------------------------------------------
# 5. SEARCH ALL FILES
# ------------------------------------------------------------

print("\n[5] DATASET FILE INVENTORY")
print("-" * 70)

all_files = []

for root, dirs, files in os.walk(KAGGLE_DOWNLOAD_DIR):
    for file in files:
        full_path = Path(root) / file
        all_files.append(full_path)

print("Total files found:", len(all_files))


# ------------------------------------------------------------
# 6. FILE EXTENSION SUMMARY
# ------------------------------------------------------------

print("\n[6] FILE EXTENSION SUMMARY")
print("-" * 70)

extension_counts = {}

for file_path in all_files:
    suffix = file_path.suffix.lower()

    if suffix == "":
        suffix = "[NO EXTENSION]"

    extension_counts[suffix] = extension_counts.get(suffix, 0) + 1

for extension, count in sorted(extension_counts.items()):
    print(f"{extension:15s}: {count}")


# ------------------------------------------------------------
# 7. IMPORTANT FILE TYPES
# ------------------------------------------------------------

print("\n[7] IMPORTANT DATA FILES")
print("-" * 70)

mat_files = sorted(
    [p for p in all_files if p.suffix.lower() == ".mat"]
)

csv_files = sorted(
    [p for p in all_files if p.suffix.lower() == ".csv"]
)

txt_files = sorted(
    [p for p in all_files if p.suffix.lower() == ".txt"]
)

pdf_files = sorted(
    [p for p in all_files if p.suffix.lower() == ".pdf"]
)

image_files = sorted(
    [
        p for p in all_files
        if p.suffix.lower() in [".jpg", ".jpeg", ".png", ".gif"]
    ]
)

print("MAT files :", len(mat_files))
print("CSV files :", len(csv_files))
print("TXT files :", len(txt_files))
print("PDF files :", len(pdf_files))
print("Image files:", len(image_files))


# ------------------------------------------------------------
# 8. DISPLAY DIRECTORY STRUCTURE
# ------------------------------------------------------------

print("\n[8] DIRECTORY STRUCTURE")
print("-" * 70)

def print_tree(directory, prefix="", max_depth=4, current_depth=0):

    if current_depth > max_depth:
        return

    try:
        entries = sorted(
            directory.iterdir(),
            key=lambda x: (x.is_file(), x.name.lower())
        )
    except PermissionError:
        return

    for i, entry in enumerate(entries):

        connector = "└── " if i == len(entries) - 1 else "├── "

        print(prefix + connector + entry.name)

        if entry.is_dir():
            extension = "    " if i == len(entries) - 1 else "│   "

            print_tree(
                entry,
                prefix + extension,
                max_depth=max_depth,
                current_depth=current_depth + 1
            )

print_tree(KAGGLE_DOWNLOAD_DIR, max_depth=4)


# ------------------------------------------------------------
# 9. DATASET STORAGE SIZE
# ------------------------------------------------------------

print("\n[9] DATASET SIZE")
print("-" * 70)

total_bytes = 0

for file_path in all_files:
    try:
        total_bytes += file_path.stat().st_size
    except OSError:
        pass

total_gb = total_bytes / (1024 ** 3)

print(f"Total dataset size: {total_gb:.3f} GB")


# ------------------------------------------------------------
# 10. SHOW FIRST 20 MAT FILES
# ------------------------------------------------------------

print("\n[10] FIRST MATLAB FILES")
print("-" * 70)

for i, file_path in enumerate(mat_files[:20], start=1):
    print(f"{i:02d}. {file_path}")


# ------------------------------------------------------------
# 11. SHOW CSV/TXT/PDF FILES
# ------------------------------------------------------------

print("\n[11] SUPPORTING FILES")
print("-" * 70)

for file_list, label in [
    (csv_files, "CSV"),
    (txt_files, "TXT"),
    (pdf_files, "PDF")
]:

    print(f"\n--- {label} ---")

    for file_path in file_list:
        print(file_path)


# ------------------------------------------------------------
# 12. SAVE ENVIRONMENT REPORT
# ------------------------------------------------------------

environment_report = {
    "python_version": sys.version,
    "project_root": str(PROJECT_ROOT),
    "dataset": DATASET_SLUG,
    "dataset_download_directory": str(KAGGLE_DOWNLOAD_DIR),
    "total_files": len(all_files),
    "mat_files": len(mat_files),
    "csv_files": len(csv_files),
    "txt_files": len(txt_files),
    "pdf_files": len(pdf_files),
    "image_files": len(image_files),
    "dataset_size_gb": round(total_gb, 4),
}

try:
    import torch

    environment_report["pytorch_version"] = torch.__version__
    environment_report["cuda_available"] = torch.cuda.is_available()

    if torch.cuda.is_available():
        environment_report["gpu"] = torch.cuda.get_device_name(0)
        environment_report["gpu_memory_gb"] = round(
            torch.cuda.get_device_properties(0).total_memory /
            (1024 ** 3),
            2
        )

except Exception as e:
    environment_report["torch_error"] = str(e)


report_path = DIRS["reports"] / "step_01_environment_report.json"

with open(report_path, "w") as f:
    json.dump(environment_report, f, indent=4)

print("\n[12] ENVIRONMENT REPORT SAVED")
print("-" * 70)
print(report_path)


# ------------------------------------------------------------
# 13. FINAL STATUS
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("STEP 1 COMPLETED")
print("=" * 70)

print("\nNext we will NOT train anything yet.")
print(
    "Step 2 will inspect the actual MATLAB structure, "
    "verify subjects/gestures/orientations/trials/channels, "
    "and confirm the dataset integrity before feature extraction."
)

======================================================================
FORS-EMG RESEARCH PROJECT
STEP 1 — ENVIRONMENT SETUP
======================================================================

[1] Python
----------------------------------------------------------------------
Python version: 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]

[2] GPU INFORMATION
----------------------------------------------------------------------
PyTorch version: 2.10.0+cu128
CUDA available: True
GPU: Tesla T4
GPU memory: 14.56 GB

[3] PROJECT DIRECTORIES
----------------------------------------------------------------------
project         -> /kaggle/working/fors_emg_research
raw             -> /kaggle/working/fors_emg_research/raw_data
processed       -> /kaggle/working/fors_emg_research/processed_data
features        -> /kaggle/working/fors_emg_research/features
splits          -> /kaggle/working/fors_emg_research/splits
models          -> /kaggle/working/fors_emg_research/models
results         -> /kaggle/working/fors_emg_research/results
figures         -> /kaggle/working/fors_emg_research/figures
logs            -> /kaggle/working/fors_emg_research/logs
reports         -> /kaggle/working/fors_emg_research/reports
checkpoints     -> /kaggle/working/fors_emg_research/checkpoints

[4] DOWNLOADING FORS-EMG
----------------------------------------------------------------------
Dataset: ummerummanchaity/fors-emg-a-novel-semg-dataset
Download directory: /kaggle/working/fors_emg_research/raw_data/kaggle_download

Downloading dataset...
Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
Dataset URL: https://www.kaggle.com/datasets/ummerummanchaity/fors-emg-a-novel-semg-dataset
License(s): ODbL-1.0
Downloading fors-emg-a-novel-semg-dataset.zip to /kaggle/working/fors_emg_research/raw_data/kaggle_download



Dataset download completed successfully.

[5] DATASET FILE INVENTORY
----------------------------------------------------------------------
Total files found: 3427

[6] FILE EXTENSION SUMMARY
----------------------------------------------------------------------
.csv           : 1
.jpg           : 1
.mat           : 3420
.pdf           : 1
.png           : 1
.txt           : 3

[7] IMPORTANT DATA FILES
----------------------------------------------------------------------
MAT files : 3420
CSV files : 1
TXT files : 3
PDF files : 1
Image files: 2

[8] DIRECTORY STRUCTURE
----------------------------------------------------------------------
├── FORS-EMG Dataset
│   └── FORS-EMG Dataset
│       ├── Database Info
│       │   ├── Acquisition setup info
│       │   │   └── Signal Acquisition.pdf
│       │   ├── Readme
│       │   │   └── readme.txt
│       │   └── Subject and gestures info
│       │       ├── gestures_name.txt
│       │       ├── gestures_sequence.jpg
│       │       ├── Orientations.png
│       │       └── Subject Details.csv
│       └── FORS-EMG
│           ├── Subject1
│           │   ├── pronation
│           │   ├── rest
│           │   └── supination
│           ├── Subject10
│           │   ├── Pronation
│           │   ├── Rest
│           │   └── Supination
│           ├── Subject11
│           │   ├── Pronation
│           │   ├── Rest
│           │   └── Supination
│           ├── Subject12
│           │   ├── Pronation
│           │   ├── Rest
│           │   └── Supination
│           ├── Subject13
│           │   ├── Pronation
│           │   ├── Rest
│           │   └── Supination
│           ├── Subject14
│           │   ├── Pronation
│           │   ├── Rest
│           │   └── Supination
│           ├── Subject15
│           │   ├── Pronation
│           │   ├── Rest
│           │   └── Supination
│           ├── Subject16
│           │   ├── Pronation
│           │   ├── Rest
│           │   └── Supination
│           ├── Subject17
│           │   ├── Pronation
│           │   ├── Rest
│           │   └── Supination
│           ├── Subject18
│           │   ├── Pronation
│           │   ├── Rest
│           │   └── Supination
│           ├── Subject19
│           │   ├── Pronation
│           │   ├── Rest
│           │   └── Supination
│           ├── Subject2
│           │   ├── Pronation
│           │   ├── Rest
│           │   └── Supination
│           ├── Subject3
│           │   ├── Pronation
│           │   ├── Rest
│           │   └── Supination
│           ├── Subject4
│           │   ├── Pronation
│           │   ├── Rest
│           │   └── Supination
│           ├── Subject5
│           │   ├── Pronation
│           │   ├── Rest
│           │   └── Supination
│           ├── Subject6
│           │   ├── Pronation
│           │   ├── Rest
│           │   └── Supination
│           ├── Subject7
│           │   ├── Pronation
│           │   ├── Rest
│           │   └── Supination
│           ├── Subject8
│           │   ├── Pronation
│           │   ├── Rest
│           │   └── Supination
│           └── Subject9
│               ├── Pronation
│               ├── Rest
│               └── Supination
└── readme.txt

[9] DATASET SIZE
----------------------------------------------------------------------
Total dataset size: 0.303 GB

[10] FIRST MATLAB FILES
----------------------------------------------------------------------
01. /kaggle/working/fors_emg_research/raw_data/kaggle_download/FORS-EMG Dataset/FORS-EMG Dataset/FORS-EMG/Subject1/pronation/Hand_Close-1.mat
02. /kaggle/working/fors_emg_research/raw_data/kaggle_download/FORS-EMG Dataset/FORS-EMG Dataset/FORS-EMG/Subject1/pronation/Hand_Close-2.mat
03. /kaggle/working/fors_emg_research/raw_data/kaggle_download/FORS-EMG Dataset/FORS-EMG Dataset/FORS-EMG/Subject1/pronation/Hand_Close-3.mat
04. /kaggle/working/fors_emg_research/raw_data/kaggle_download/FORS-EMG Dataset/FORS-EMG Dataset/FORS-EMG/Subject1/pronation/Hand_Close-4.mat
05. /kaggle/working/fors_emg_research/raw_data/kaggle_download/FORS-EMG Dataset/FORS-EMG Dataset/FORS-EMG/Subject1/pronation/Hand_Close-5.mat
06. /kaggle/working/fors_emg_research/raw_data/kaggle_download/FORS-EMG Dataset/FORS-EMG Dataset/FORS-EMG/Subject1/pronation/Hand_Open-1.mat
07. /kaggle/working/fors_emg_research/raw_data/kaggle_download/FORS-EMG Dataset/FORS-EMG Dataset/FORS-EMG/Subject1/pronation/Hand_Open-2.mat
08. /kaggle/working/fors_emg_research/raw_data/kaggle_download/FORS-EMG Dataset/FORS-EMG Dataset/FORS-EMG/Subject1/pronation/Hand_Open-3.mat
09. /kaggle/working/fors_emg_research/raw_data/kaggle_download/FORS-EMG Dataset/FORS-EMG Dataset/FORS-EMG/Subject1/pronation/Hand_Open-4.mat
10. /kaggle/working/fors_emg_research/raw_data/kaggle_download/FORS-EMG Dataset/FORS-EMG Dataset/FORS-EMG/Subject1/pronation/Hand_Open-5.mat
11. /kaggle/working/fors_emg_research/raw_data/kaggle_download/FORS-EMG Dataset/FORS-EMG Dataset/FORS-EMG/Subject1/pronation/Index-1.mat
12. /kaggle/working/fors_emg_research/raw_data/kaggle_download/FORS-EMG Dataset/FORS-EMG Dataset/FORS-EMG/Subject1/pronation/Index-2.mat
13. /kaggle/working/fors_emg_research/raw_data/kaggle_download/FORS-EMG Dataset/FORS-EMG Dataset/FORS-EMG/Subject1/pronation/Index-3.mat
14. /kaggle/working/fors_emg_research/raw_data/kaggle_download/FORS-EMG Dataset/FORS-EMG Dataset/FORS-EMG/Subject1/pronation/Index-4.mat
15. /kaggle/working/fors_emg_research/raw_data/kaggle_download/FORS-EMG Dataset/FORS-EMG Dataset/FORS-EMG/Subject1/pronation/Index-5.mat
16. /kaggle/working/fors_emg_research/raw_data/kaggle_download/FORS-EMG Dataset/FORS-EMG Dataset/FORS-EMG/Subject1/pronation/Index_Little-1.mat
17. /kaggle/working/fors_emg_research/raw_data/kaggle_download/FORS-EMG Dataset/FORS-EMG Dataset/FORS-EMG/Subject1/pronation/Index_Little-2.mat
18. /kaggle/working/fors_emg_research/raw_data/kaggle_download/FORS-EMG Dataset/FORS-EMG Dataset/FORS-EMG/Subject1/pronation/Index_Little-3.mat
19. /kaggle/working/fors_emg_research/raw_data/kaggle_download/FORS-EMG Dataset/FORS-EMG Dataset/FORS-EMG/Subject1/pronation/Index_Little-4.mat
20. /kaggle/working/fors_emg_research/raw_data/kaggle_download/FORS-EMG Dataset/FORS-EMG Dataset/FORS-EMG/Subject1/pronation/Index_Little-5.mat

[11] SUPPORTING FILES
----------------------------------------------------------------------

--- CSV ---
/kaggle/working/fors_emg_research/raw_data/kaggle_download/FORS-EMG Dataset/FORS-EMG Dataset/Database Info/Subject and gestures info/Subject Details.csv

--- TXT ---
/kaggle/working/fors_emg_research/raw_data/kaggle_download/FORS-EMG Dataset/FORS-EMG Dataset/Database Info/Readme/readme.txt
/kaggle/working/fors_emg_research/raw_data/kaggle_download/FORS-EMG Dataset/FORS-EMG Dataset/Database Info/Subject and gestures info/gestures_name.txt
/kaggle/working/fors_emg_research/raw_data/kaggle_download/readme.txt

--- PDF ---
/kaggle/working/fors_emg_research/raw_data/kaggle_download/FORS-EMG Dataset/FORS-EMG Dataset/Database Info/Acquisition setup info/Signal Acquisition.pdf

[12] ENVIRONMENT REPORT SAVED
----------------------------------------------------------------------
/kaggle/working/fors_emg_research/reports/step_01_environment_report.json

======================================================================
STEP 1 COMPLETED
======================================================================

Next we will NOT train anything yet.
Step 2 will inspect the actual MATLAB structure, verify subjects/gestures/orientations/trials/channels, and confirm the dataset integrity before feature extraction.

In [2]:
# ============================================================
# FORS-EMG RESEARCH PROJECT
# STEP 2 — DATASET STRUCTURE + METADATA VALIDATION
# ============================================================

import os
import re
import json
import warnings
from pathlib import Path
from collections import Counter, defaultdict

import numpy as np
import pandas as pd
import scipy.io as sio

warnings.filterwarnings("ignore")

print("=" * 80)
print("FORS-EMG RESEARCH PROJECT")
print("STEP 2 — DATASET STRUCTURE + METADATA VALIDATION")
print("=" * 80)


# ============================================================
# 1. DEFINE DATASET PATH
# ============================================================

PROJECT_ROOT = Path("/kaggle/working/fors_emg_research")

RAW_ROOT = (
    PROJECT_ROOT
    / "raw_data"
    / "kaggle_download"
)

DATASET_ROOT = (
    RAW_ROOT
    / "FORS-EMG Dataset"
    / "FORS-EMG Dataset"
)

FORS_ROOT = DATASET_ROOT / "FORS-EMG"

DATABASE_ROOT = DATASET_ROOT / "Database Info"

print("\n[1] PATHS")
print("-" * 80)

print("Dataset root :", DATASET_ROOT)
print("FORS-EMG root:", FORS_ROOT)
print("Database root:", DATABASE_ROOT)

if not DATASET_ROOT.exists():
    raise FileNotFoundError(
        f"Dataset root does not exist:\n{DATASET_ROOT}"
    )

if not FORS_ROOT.exists():
    raise FileNotFoundError(
        f"FORS-EMG recording directory does not exist:\n{FORS_ROOT}"
    )

print("\nDataset paths verified successfully.")


# ============================================================
# 2. IDENTIFY SUBJECT DIRECTORIES
# ============================================================

print("\n[2] SUBJECT DIRECTORIES")
print("-" * 80)

subject_dirs = sorted(
    [
        p for p in FORS_ROOT.iterdir()
        if p.is_dir()
    ],
    key=lambda x: x.name
)

print("Number of subject directories:", len(subject_dirs))

for subject_dir in subject_dirs:
    print(" ", subject_dir.name)


# ============================================================
# 3. CHECK SUBJECT NAMING
# ============================================================

subject_pattern = re.compile(r"Subject(\d+)$", re.IGNORECASE)

subject_numbers = []

for subject_dir in subject_dirs:

    match = subject_pattern.match(subject_dir.name)

    if match:
        subject_numbers.append(int(match.group(1)))

print("\nSubject numbers:")
print(sorted(subject_numbers))

expected_subjects = list(range(1, 20))

missing_subjects = sorted(
    set(expected_subjects) - set(subject_numbers)
)

unexpected_subjects = sorted(
    set(subject_numbers) - set(expected_subjects)
)

print("\nExpected subjects:", len(expected_subjects))
print("Detected subjects:", len(subject_numbers))

print("Missing subjects:", missing_subjects)
print("Unexpected subjects:", unexpected_subjects)


# ============================================================
# 4. IDENTIFY ORIENTATIONS
# ============================================================

print("\n[3] ORIENTATION STRUCTURE")
print("-" * 80)

all_orientations = Counter()

subject_orientation_counts = defaultdict(Counter)

for subject_dir in subject_dirs:

    orientation_dirs = [
        p for p in subject_dir.iterdir()
        if p.is_dir()
    ]

    print(f"\n{subject_dir.name}")

    for orientation_dir in sorted(
        orientation_dirs,
        key=lambda x: x.name.lower()
    ):

        count = len(
            [
                p for p in orientation_dir.iterdir()
                if p.is_file()
            ]
        )

        print(
            f"    {orientation_dir.name:15s} "
            f"files = {count}"
        )

        all_orientations[
            orientation_dir.name.lower()
        ] += count

        subject_orientation_counts[
            subject_dir.name
        ][orientation_dir.name.lower()] = count


print("\nTotal recordings by orientation:")

for orientation, count in sorted(
    all_orientations.items()
):
    print(f"{orientation:15s}: {count}")


# ============================================================
# 5. FIND ALL MAT FILES
# ============================================================

print("\n[4] MATLAB RECORDINGS")
print("-" * 80)

mat_files = sorted(
    FORS_ROOT.rglob("*.mat")
)

print("Total .mat files:", len(mat_files))

if len(mat_files) != 3420:
    print(
        "WARNING: Expected approximately 3420 recordings, "
        f"but found {len(mat_files)}."
    )
else:
    print("MAT-file count matches the expected dataset size.")


# ============================================================
# 6. PARSE SUBJECT + ORIENTATION FROM FILE PATH
# ============================================================

print("\n[5] RECORDING PATH PARSING")
print("-" * 80)

recording_records = []

for mat_path in mat_files:

    relative_parts = mat_path.relative_to(FORS_ROOT).parts

    # Expected:
    # SubjectX / orientation / filename.mat

    if len(relative_parts) < 3:
        print("WARNING: Unexpected path:", mat_path)
        continue

    subject = relative_parts[0]
    orientation = relative_parts[1]
    filename = relative_parts[-1]

    recording_records.append(
        {
            "subject": subject,
            "orientation": orientation.lower(),
            "filename": filename,
            "filepath": str(mat_path)
        }
    )

recordings_df = pd.DataFrame(recording_records)

print("Parsed recordings:", len(recordings_df))

print("\nSubjects:")
print(
    recordings_df["subject"]
    .value_counts()
    .sort_index()
)

print("\nOrientations:")
print(
    recordings_df["orientation"]
    .value_counts()
    .sort_index()
)


# ============================================================
# 7. LOAD GESTURE NAME FILE
# ============================================================

print("\n[6] GESTURE METADATA")
print("-" * 80)

gesture_file = (
    DATABASE_ROOT
    / "Subject and gestures info"
    / "gestures_name.txt"
)

if not gesture_file.exists():
    print("Gesture file not found:", gesture_file)

else:

    print("Gesture file:", gesture_file)

    with open(
        gesture_file,
        "r",
        encoding="utf-8",
        errors="ignore"
    ) as f:

        gesture_text = f.read()

    print("\n----- RAW GESTURE FILE -----")
    print(gesture_text)
    print("----- END GESTURE FILE -----")


# ============================================================
# 8. LOAD SUBJECT DETAILS CSV
# ============================================================

print("\n[7] SUBJECT METADATA")
print("-" * 80)

subject_csv = (
    DATABASE_ROOT
    / "Subject and gestures info"
    / "Subject Details.csv"
)

if not subject_csv.exists():

    print(
        "Subject Details.csv not found:",
        subject_csv
    )

else:

    print("Subject details file:", subject_csv)

    subject_df = pd.read_csv(
        subject_csv
    )

    print("\nShape:", subject_df.shape)

    print("\nColumns:")
    print(
        subject_df.columns.tolist()
    )

    print("\nFirst rows:")
    display(
        subject_df.head(20)
    )

    print("\nData types:")
    print(
        subject_df.dtypes
    )


# ============================================================
# 9. READ README
# ============================================================

print("\n[8] README")
print("-" * 80)

readme_file = (
    DATABASE_ROOT
    / "Readme"
    / "readme.txt"
)

if readme_file.exists():

    with open(
        readme_file,
        "r",
        encoding="utf-8",
        errors="ignore"
    ) as f:

        readme_text = f.read()

    print(readme_text)

else:

    print("README not found.")


# ============================================================
# 10. INSPECT FIRST MAT FILE
# ============================================================

print("\n[9] FIRST MATLAB FILE INSPECTION")
print("-" * 80)

if len(mat_files) == 0:

    raise RuntimeError(
        "No MATLAB recordings were found."
    )

first_mat = mat_files[0]

print("First MAT file:")
print(first_mat)

mat_contents = sio.loadmat(
    first_mat,
    squeeze_me=False,
    struct_as_record=False
)

print("\nMATLAB variables:")

for key, value in mat_contents.items():

    if not key.startswith("__"):

        print(
            f"\nVariable: {key}"
        )

        print(
            "Type:",
            type(value)
        )

        try:
            print(
                "Shape:",
                value.shape
            )
        except Exception:
            print(
                "Shape: unavailable"
            )

        try:
            print(
                "Dtype:",
                value.dtype
            )
        except Exception:
            print(
                "Dtype: unavailable"
            )


# ============================================================
# 11. AUTOMATICALLY IDENTIFY NUMERIC EMG ARRAY
# ============================================================

print("\n[10] IDENTIFY EMG SIGNAL ARRAY")
print("-" * 80)

candidate_arrays = []

for key, value in mat_contents.items():

    if key.startswith("__"):
        continue

    if isinstance(value, np.ndarray):

        if np.issubdtype(value.dtype, np.number):

            candidate_arrays.append(
                (
                    key,
                    value,
                    value.shape,
                    value.size
                )
            )

if len(candidate_arrays) == 0:

    raise RuntimeError(
        "No numeric array was found inside the MAT file."
    )

print("Numeric arrays found:")

for key, value, shape, size in candidate_arrays:

    print(
        f"Variable={key:20s} "
        f"Shape={str(shape):20s} "
        f"Elements={size}"
    )


# Choose the largest numeric array as the likely signal array
signal_candidate = max(
    candidate_arrays,
    key=lambda x: x[3]
)

signal_variable_name = signal_candidate[0]
signal_array = signal_candidate[1]

print("\nSelected signal candidate:")
print("Variable:", signal_variable_name)
print("Shape:", signal_array.shape)
print("Dtype:", signal_array.dtype)


# ============================================================
# 12. SIGNAL STATISTICS
# ============================================================

print("\n[11] FIRST RECORDING SIGNAL STATISTICS")
print("-" * 80)

signal_float = np.asarray(
    signal_array,
    dtype=np.float64
)

print("Shape:", signal_float.shape)
print("Minimum:", np.nanmin(signal_float))
print("Maximum:", np.nanmax(signal_float))
print("Mean:", np.nanmean(signal_float))
print("Std:", np.nanstd(signal_float))
print("NaN count:", np.isnan(signal_float).sum())
print("Inf count:", np.isinf(signal_float).sum())


# ============================================================
# 13. EXPECTED EMG SHAPE CHECK
# ============================================================

print("\n[12] EXPECTED EMG DIMENSIONS")
print("-" * 80)

print(
    "The expected recording structure is approximately:"
)
print(
    "8000 samples × 8 EMG channels"
)

if signal_float.ndim == 2:

    print(
        "\nDetected 2-D signal."
    )

    print(
        "Dimension 1:",
        signal_float.shape[0]
    )

    print(
        "Dimension 2:",
        signal_float.shape[1]
    )

    if signal_float.shape == (8000, 8):

        print(
            "\n✓ Exact expected shape detected: (8000, 8)"
        )

    elif signal_float.shape == (8, 8000):

        print(
            "\n✓ Signal appears transposed: (8, 8000)"
        )
        print(
            "We will standardize it later to (8000, 8)."
        )

    else:

        print(
            "\nWARNING: Shape differs from expected (8000, 8)."
        )

else:

    print(
        "\nWARNING: Signal is not 2-dimensional."
    )


# ============================================================
# 14. INSPECT MULTIPLE RANDOM RECORDINGS
# ============================================================

print("\n[13] MULTIPLE RECORDING VALIDATION")
print("-" * 80)

rng = np.random.default_rng(42)

sample_count = min(
    20,
    len(mat_files)
)

sample_indices = rng.choice(
    len(mat_files),
    size=sample_count,
    replace=False
)

validation_results = []

for idx in sample_indices:

    mat_path = mat_files[idx]

    try:

        data = sio.loadmat(
            mat_path,
            squeeze_me=False,
            struct_as_record=False
        )

        numeric_arrays = []

        for key, value in data.items():

            if key.startswith("__"):
                continue

            if isinstance(value, np.ndarray):

                if np.issubdtype(value.dtype, np.number):

                    numeric_arrays.append(
                        (
                            key,
                            value
                        )
                    )

        if len(numeric_arrays) == 0:

            validation_results.append(
                {
                    "filepath": str(mat_path),
                    "status": "NO_NUMERIC_ARRAY",
                    "variable": None,
                    "shape": None
                }
            )

            continue

        key, array = max(
            numeric_arrays,
            key=lambda x: x[1].size
        )

        validation_results.append(
            {
                "filepath": str(mat_path),
                "status": "OK",
                "variable": key,
                "shape": str(array.shape),
                "dtype": str(array.dtype)
            }
        )

    except Exception as e:

        validation_results.append(
            {
                "filepath": str(mat_path),
                "status": "ERROR",
                "variable": None,
                "shape": None,
                "error": str(e)
            }
        )

validation_df = pd.DataFrame(
    validation_results
)

display(validation_df)


# ============================================================
# 15. COMPLETE SHAPE VALIDATION
# ============================================================

print("\n[14] COMPLETE RECORDING SHAPE VALIDATION")
print("-" * 80)

shape_counter = Counter()
error_files = []

for i, mat_path in enumerate(mat_files):

    try:

        data = sio.loadmat(
            mat_path,
            squeeze_me=False,
            struct_as_record=False
        )

        numeric_arrays = []

        for key, value in data.items():

            if key.startswith("__"):
                continue

            if isinstance(value, np.ndarray):

                if np.issubdtype(value.dtype, np.number):

                    numeric_arrays.append(
                        (
                            key,
                            value
                        )
                    )

        if len(numeric_arrays) == 0:

            error_files.append(
                {
                    "filepath": str(mat_path),
                    "error": "No numeric array"
                }
            )

            continue

        key, array = max(
            numeric_arrays,
            key=lambda x: x[1].size
        )

        shape_counter[
            tuple(array.shape)
        ] += 1

    except Exception as e:

        error_files.append(
            {
                "filepath": str(mat_path),
                "error": str(e)
            }
        )

    if (i + 1) % 500 == 0:

        print(
            f"Checked {i + 1}/{len(mat_files)} files..."
        )


print("\nShape distribution:")

for shape, count in shape_counter.items():

    print(
        f"{str(shape):20s}: {count}"
    )


print("\nProblematic files:", len(error_files))

if len(error_files) > 0:

    display(
        pd.DataFrame(error_files).head(20)
    )


# ============================================================
# 16. RECORDING COUNT BY SUBJECT × ORIENTATION
# ============================================================

print("\n[15] SUBJECT × ORIENTATION MATRIX")
print("-" * 80)

subject_orientation_table = pd.crosstab(
    recordings_df["subject"],
    recordings_df["orientation"]
)

display(
    subject_orientation_table
)


# ============================================================
# 17. RECORDING COUNT PER SUBJECT
# ============================================================

print("\n[16] RECORDINGS PER SUBJECT")
print("-" * 80)

subject_counts = (
    recordings_df
    .groupby("subject")
    .size()
    .sort_index()
)

display(
    subject_counts.to_frame(
        name="recordings"
    )
)

print(
    "\nMinimum recordings per subject:",
    subject_counts.min()
)

print(
    "Maximum recordings per subject:",
    subject_counts.max()
)

print(
    "Mean recordings per subject:",
    subject_counts.mean()
)


# ============================================================
# 18. RECORDING COUNT PER ORIENTATION
# ============================================================

print("\n[17] RECORDINGS PER ORIENTATION")
print("-" * 80)

orientation_counts = (
    recordings_df["orientation"]
    .value_counts()
    .sort_index()
)

display(
    orientation_counts.to_frame(
        name="recordings"
    )
)


# ============================================================
# 19. EXPECTED DATASET SIZE CHECK
# ============================================================

print("\n[18] DATASET INTEGRITY SUMMARY")
print("-" * 80)

expected_recordings = 3420
expected_subjects = 19
expected_orientations = 3
expected_channels = 8
expected_samples = 8000

actual_subjects = recordings_df["subject"].nunique()
actual_orientations = recordings_df["orientation"].nunique()
actual_recordings = len(recordings_df)

print(
    f"Expected recordings : {expected_recordings}"
)
print(
    f"Actual recordings   : {actual_recordings}"
)

print(
    f"Expected subjects   : {expected_subjects}"
)
print(
    f"Actual subjects     : {actual_subjects}"
)

print(
    f"Expected orientations: {expected_orientations}"
)
print(
    f"Actual orientations  : {actual_orientations}"
)

print(
    f"Expected channels   : {expected_channels}"
)
print(
    f"Expected samples    : {expected_samples}"
)


# ============================================================
# 20. SAVE RECORDING INDEX
# ============================================================

print("\n[19] SAVE RECORDING INDEX")
print("-" * 80)

SPLIT_DIR = PROJECT_ROOT / "splits"
SPLIT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

recording_index_path = (
    SPLIT_DIR
    / "recording_index_step02.csv"
)

recordings_df.to_csv(
    recording_index_path,
    index=False
)

print(
    "Recording index saved to:"
)
print(
    recording_index_path
)


# ============================================================
# 21. SAVE VALIDATION REPORT
# ============================================================

report = {
    "expected_recordings": expected_recordings,
    "actual_recordings": actual_recordings,
    "expected_subjects": expected_subjects,
    "actual_subjects": actual_subjects,
    "expected_orientations": expected_orientations,
    "actual_orientations": actual_orientations,
    "expected_channels": expected_channels,
    "expected_samples": expected_samples,
    "first_mat_file": str(first_mat),
    "signal_variable": signal_variable_name,
    "first_signal_shape": list(signal_float.shape),
    "shape_distribution": {
        str(k): v
        for k, v in shape_counter.items()
    },
    "problematic_files": len(error_files)
}

report_path = (
    PROJECT_ROOT
    / "reports"
    / "step_02_dataset_validation.json"
)

with open(
    report_path,
    "w"
) as f:

    json.dump(
        report,
        f,
        indent=4
    )

print(
    "\nValidation report saved:"
)
print(
    report_path
)


# ============================================================
# FINAL STATUS
# ============================================================

print("\n" + "=" * 80)
print("STEP 2 COMPLETED")
print("=" * 80)

print(
    """
Do NOT perform feature extraction or train a model yet.

Next step will be:
STEP 3 — Parse the recording filenames and metadata to create
a MASTER METADATA TABLE containing:

subject
orientation
gesture
trial/repetition
filepath
signal dimensions
sampling information

This table will become the foundation of the entire
leakage-free research pipeline.
"""
)

================================================================================
FORS-EMG RESEARCH PROJECT
STEP 2 — DATASET STRUCTURE + METADATA VALIDATION
================================================================================

[1] PATHS
--------------------------------------------------------------------------------
Dataset root : /kaggle/working/fors_emg_research/raw_data/kaggle_download/FORS-EMG Dataset/FORS-EMG Dataset
FORS-EMG root: /kaggle/working/fors_emg_research/raw_data/kaggle_download/FORS-EMG Dataset/FORS-EMG Dataset/FORS-EMG
Database root: /kaggle/working/fors_emg_research/raw_data/kaggle_download/FORS-EMG Dataset/FORS-EMG Dataset/Database Info

Dataset paths verified successfully.

[2] SUBJECT DIRECTORIES
--------------------------------------------------------------------------------
Number of subject directories: 19
  Subject1
  Subject10
  Subject11
  Subject12
  Subject13
  Subject14
  Subject15
  Subject16
  Subject17
  Subject18
  Subject19
  Subject2
  Subject3
  Subject4
  Subject5
  Subject6
  Subject7
  Subject8
  Subject9

Subject numbers:
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

Expected subjects: 19
Detected subjects: 19
Missing subjects: []
Unexpected subjects: []

[3] ORIENTATION STRUCTURE
--------------------------------------------------------------------------------

Subject1
    pronation       files = 60
    rest            files = 60
    supination      files = 60

Subject10
    Pronation       files = 60
    Rest            files = 60
    Supination      files = 60

Subject11
    Pronation       files = 60
    Rest            files = 60
    Supination      files = 60

Subject12
    Pronation       files = 60
    Rest            files = 60
    Supination      files = 60

Subject13
    Pronation       files = 60
    Rest            files = 60
    Supination      files = 60

Subject14
    Pronation       files = 60
    Rest            files = 60
    Supination      files = 60

Subject15
    Pronation       files = 60
    Rest            files = 60
    Supination      files = 60

Subject16
    Pronation       files = 60
    Rest            files = 60
    Supination      files = 60

Subject17
    Pronation       files = 60
    Rest            files = 60
    Supination      files = 60

Subject18
    Pronation       files = 60
    Rest            files = 60
    Supination      files = 60

Subject19
    Pronation       files = 60
    Rest            files = 60
    Supination      files = 60

Subject2
    Pronation       files = 60
    Rest            files = 60
    Supination      files = 60

Subject3
    Pronation       files = 60
    Rest            files = 60
    Supination      files = 60

Subject4
    Pronation       files = 60
    Rest            files = 60
    Supination      files = 60

Subject5
    Pronation       files = 60
    Rest            files = 60
    Supination      files = 60

Subject6
    Pronation       files = 60
    Rest            files = 60
    Supination      files = 60

Subject7
    Pronation       files = 60
    Rest            files = 60
    Supination      files = 60

Subject8
    Pronation       files = 60
    Rest            files = 60
    Supination      files = 60

Subject9
    Pronation       files = 60
    Rest            files = 60
    Supination      files = 60

Total recordings by orientation:
pronation      : 1140
rest           : 1140
supination     : 1140

[4] MATLAB RECORDINGS
--------------------------------------------------------------------------------
Total .mat files: 3420
MAT-file count matches the expected dataset size.

[5] RECORDING PATH PARSING
--------------------------------------------------------------------------------
Parsed recordings: 3420

Subjects:
subject
Subject1     180
Subject10    180
Subject11    180
Subject12    180
Subject13    180
Subject14    180
Subject15    180
Subject16    180
Subject17    180
Subject18    180
Subject19    180
Subject2     180
Subject3     180
Subject4     180
Subject5     180
Subject6     180
Subject7     180
Subject8     180
Subject9     180
Name: count, dtype: int64

Orientations:
orientation
pronation     1140
rest          1140
supination    1140
Name: count, dtype: int64

[6] GESTURE METADATA
--------------------------------------------------------------------------------
Gesture file: /kaggle/working/fors_emg_research/raw_data/kaggle_download/FORS-EMG Dataset/FORS-EMG Dataset/Database Info/Subject and gestures info/gestures_name.txt

----- RAW GESTURE FILE -----
List of gestures with the acronym:

1.  Thumb_UP    = TU
2.  Index       = IDX
3.  Right_Angle = RA
4.  Peace       = PCE
5.  Index_Little = IL
6.  Thumb_Little = TL
7.  Hand_Close   = HC
8.  Hand_Open    = HO
9.  Wrist_Extension = WE
10. Wrist_Flexion  = WF
11. Ulner_Deviation = UD
12. Radial_Deviation =RD
----- END GESTURE FILE -----

[7] SUBJECT METADATA
--------------------------------------------------------------------------------
Subject details file: /kaggle/working/fors_emg_research/raw_data/kaggle_download/FORS-EMG Dataset/FORS-EMG Dataset/Database Info/Subject and gestures info/Subject Details.csv

Shape: (19, 5)

Columns:
['Subject No.', 'Subject Name', 'Age ', 'Height', 'History of Major Disease']

First rows:

    Subject No.           Subject Name  Age  Height History of Major Disease
0             1            Umme Rumman    32   5.3"                      NaN
1             2       Ashis Kumar Paul    26   5.6"                      NaN
2             3         Bayejid Bostam    23   5.6"                      NaN
3             4    Md. Sabbir al Shafi    24   5.8"                      NaN
4             5         Abdullah Tamim    23   5.8"                      NaN
5             6                 Sourav    23   5.5"                      NaN
6             7      Abdullah Al Noman    23  5.11"                      NaN
7             8    Md. Eftekharul Alam    23   5.8"                      NaN
8             9   Ahmed Mostakim Fahim    24   5.7"                 Diabetes
9            10        Md. Wadud Jahan    23   5.7"                      NaN
10           11         Humaid Koreshi    22   5.6"                      NaN
11           12     Md. Humayun Rashid    22   5.8"                      NaN
12           13     Most. Tasnia Haque    23   5.1"                      NaN
13           14     Md. Sazzad Hossain    23  5.10"                      NaN
14           15         Arifa Ferdousi    39   5.2"                      NaN
15           16        Ananta Asim Joy    24  5.10"                      NaN
16           17        Hillol Das Pias    32   5.5"                      NaN
17           18    Md. Mahfujur Rahman    24   5.8"                      NaN
18           19  Dr. Md. Johirul Islam    34   5.5"                      NaN

Data types:
Subject No.                  int64
Subject Name                object
Age                          int64
Height                      object
History of Major Disease    object
dtype: object

[8] README
--------------------------------------------------------------------------------
FORS-EMG: A Novel sEMG Dataset for Hand Gesture Recognition Across Different Forearm Orientations

This dataset serves as a comprehensive resource for developing robust machine-learning classification algorithms and hand gesture recognition applications. The dataset's key features are summarized as follows:

1. The dataset was collected from 19 able-bodied subjects, who performed 12 distinct finger and wrist gestures across three forearm orientations: supination, neutral (rest), and pronation. Each gesture was repeated five times. Additionally, two electrode placement positions were used during sEMG signal recording: near the elbow and on the forearm.

2. The sEMG data for all hand gestures with different forearm orientations were recorded over eight-second intervals. The recordings were taken from eight channels—four positioned near the elbow and four along the mid-forearm—and sampled at 985 Hz.

3. The sEMG data were recorded using MATLAB 2020a (MathWorks, USA) in .mat format, providing users with direct access to the sEMG recordings in physical units, eliminating the need for additional conversion before signal preprocessing.

4. The dataset is organized into 19 folders, each corresponding to 19 subject. Each subject folder contains three subfolder which corresponds to three forearm orientations (pronation, rest, supination). The raw data files of all hand gestures of all trials are in the subfolder named with considered forearm orientation. The naming convention of raw sEMG data of specific gestures is gesture_name-trial.mat. For example, Thumb_UP-4.mat contains the data performing Thumb_UP (TU) gesture of the fourth trial.

5. Additional folders are provided including supplementary files, such as participant physical measurements, electrode attachment instructions, machine and electrode configuration details, and gesture sequences with illustrations."

[9] FIRST MATLAB FILE INSPECTION
--------------------------------------------------------------------------------
First MAT file:
/kaggle/working/fors_emg_research/raw_data/kaggle_download/FORS-EMG Dataset/FORS-EMG Dataset/FORS-EMG/Subject1/pronation/Hand_Close-1.mat

MATLAB variables:

Variable: value
Type: <class 'numpy.ndarray'>
Shape: (8, 8000)
Dtype: float64

[10] IDENTIFY EMG SIGNAL ARRAY
--------------------------------------------------------------------------------
Numeric arrays found:
Variable=value                Shape=(8, 8000)            Elements=64000

Selected signal candidate:
Variable: value
Shape: (8, 8000)
Dtype: float64

[11] FIRST RECORDING SIGNAL STATISTICS
--------------------------------------------------------------------------------
Shape: (8, 8000)
Minimum: -0.810546875
Maximum: 0.693359375
Mean: 0.0029247283935546877
Std: 0.08045582652243244
NaN count: 0
Inf count: 0

[12] EXPECTED EMG DIMENSIONS
--------------------------------------------------------------------------------
The expected recording structure is approximately:
8000 samples × 8 EMG channels

Detected 2-D signal.
Dimension 1: 8
Dimension 2: 8000

✓ Signal appears transposed: (8, 8000)
We will standardize it later to (8000, 8).

[13] MULTIPLE RECORDING VALIDATION
--------------------------------------------------------------------------------

,filepath,status,variable,shape,dtype
0,/kaggle/working/fors_emg_research/raw_data/kag...,OK,value,"(8, 8000)",float64
1,/kaggle/working/fors_emg_research/raw_data/kag...,OK,value,"(8, 8000)",float64
2,/kaggle/working/fors_emg_research/raw_data/kag...,OK,value,"(8, 8000)",float64
3,/kaggle/working/fors_emg_research/raw_data/kag...,OK,value,"(8, 8000)",float64
4,/kaggle/working/fors_emg_research/raw_data/kag...,OK,value,"(8, 8000)",float64
5,/kaggle/working/fors_emg_research/raw_data/kag...,OK,value,"(8, 8000)",float64
6,/kaggle/working/fors_emg_research/raw_data/kag...,OK,value,"(8, 8000)",float64
7,/kaggle/working/fors_emg_research/raw_data/kag...,OK,value,"(8, 8000)",float64
8,/kaggle/working/fors_emg_research/raw_data/kag...,OK,value,"(8, 8000)",float64
9,/kaggle/working/fors_emg_research/raw_data/kag...,OK,value,"(8, 8000)",float64
10,/kaggle/working/fors_emg_research/raw_data/kag...,OK,value,"(8, 8000)",float64
11,/kaggle/working/fors_emg_research/raw_data/kag...,OK,value,"(8, 8000)",float64
12,/kaggle/working/fors_emg_research/raw_data/kag...,OK,value,"(8, 8000)",float64
13,/kaggle/working/fors_emg_research/raw_data/kag...,OK,value,"(8, 8000)",float64
14,/kaggle/working/fors_emg_research/raw_data/kag...,OK,value,"(8, 8000)",float64
15,/kaggle/working/fors_emg_research/raw_data/kag...,OK,value,"(8, 8000)",float64
16,/kaggle/working/fors_emg_research/raw_data/kag...,OK,value,"(8, 8000)",float64
17,/kaggle/working/fors_emg_research/raw_data/kag...,OK,value,"(8, 8000)",float64
18,/kaggle/working/fors_emg_research/raw_data/kag...,OK,value,"(8, 8000)",float64
19,/kaggle/working/fors_emg_research/raw_data/kag...,OK,value,"(8, 8000)",float64

[14] COMPLETE RECORDING SHAPE VALIDATION
--------------------------------------------------------------------------------
Checked 500/3420 files...
Checked 1000/3420 files...
Checked 1500/3420 files...
Checked 2000/3420 files...
Checked 2500/3420 files...
Checked 3000/3420 files...

Shape distribution:
(8, 8000)           : 3420

Problematic files: 0

[15] SUBJECT × ORIENTATION MATRIX
--------------------------------------------------------------------------------

orientation  pronation  rest  supination
subject
Subject1            60    60          60
Subject10           60    60          60
Subject11           60    60          60
Subject12           60    60          60
Subject13           60    60          60
Subject14           60    60          60
Subject15           60    60          60
Subject16           60    60          60
Subject17           60    60          60
Subject18           60    60          60
Subject19           60    60          60
Subject2            60    60          60
Subject3            60    60          60
Subject4            60    60          60
Subject5            60    60          60
Subject6            60    60          60
Subject7            60    60          60
Subject8            60    60          60
Subject9            60    60          60

[16] RECORDINGS PER SUBJECT
--------------------------------------------------------------------------------

           recordings
subject
Subject1          180
Subject10         180
Subject11         180
Subject12         180
Subject13         180
Subject14         180
Subject15         180
Subject16         180
Subject17         180
Subject18         180
Subject19         180
Subject2          180
Subject3          180
Subject4          180
Subject5          180
Subject6          180
Subject7          180
Subject8          180
Subject9          180

Minimum recordings per subject: 180
Maximum recordings per subject: 180
Mean recordings per subject: 180.0

[17] RECORDINGS PER ORIENTATION
--------------------------------------------------------------------------------

             recordings
orientation
pronation          1140
rest               1140
supination         1140

[18] DATASET INTEGRITY SUMMARY
--------------------------------------------------------------------------------
Expected recordings : 3420
Actual recordings   : 3420
Expected subjects   : 19
Actual subjects     : 19
Expected orientations: 3
Actual orientations  : 3
Expected channels   : 8
Expected samples    : 8000

[19] SAVE RECORDING INDEX
--------------------------------------------------------------------------------
Recording index saved to:
/kaggle/working/fors_emg_research/splits/recording_index_step02.csv

Validation report saved:
/kaggle/working/fors_emg_research/reports/step_02_dataset_validation.json

================================================================================
STEP 2 COMPLETED
================================================================================

Do NOT perform feature extraction or train a model yet.

Next step will be:
STEP 3 — Parse the recording filenames and metadata to create
a MASTER METADATA TABLE containing:

subject
orientation
gesture
trial/repetition
filepath
signal dimensions
sampling information

This table will become the foundation of the entire
leakage-free research pipeline.

In [3]:
# ============================================================
# FORS-EMG RESEARCH PROJECT
# STEP 3 — MASTER METADATA TABLE CONSTRUCTION
# ============================================================

import os
import re
import json
from pathlib import Path
from collections import Counter

import numpy as np
import pandas as pd


print("=" * 80)
print("FORS-EMG RESEARCH PROJECT")
print("STEP 3 — MASTER METADATA TABLE CONSTRUCTION")
print("=" * 80)


# ============================================================
# 1. PATHS
# ============================================================

PROJECT_ROOT = Path(
    "/kaggle/working/fors_emg_research"
)

RAW_ROOT = (
    PROJECT_ROOT
    / "raw_data"
    / "kaggle_download"
)

DATASET_ROOT = (
    RAW_ROOT
    / "FORS-EMG Dataset"
    / "FORS-EMG Dataset"
)

FORS_ROOT = DATASET_ROOT / "FORS-EMG"

DATABASE_ROOT = (
    DATASET_ROOT
    / "Database Info"
)

print("\n[1] PATH VERIFICATION")
print("-" * 80)

print("FORS root:")
print(FORS_ROOT)

if not FORS_ROOT.exists():
    raise FileNotFoundError(
        f"FORS dataset directory not found:\n{FORS_ROOT}"
    )


# ============================================================
# 2. GESTURE DEFINITIONS
# ============================================================

print("\n[2] GESTURE DEFINITIONS")
print("-" * 80)

gesture_definitions = [
    (0, "Thumb_UP", "TU"),
    (1, "Index", "IDX"),
    (2, "Right_Angle", "RA"),
    (3, "Peace", "PCE"),
    (4, "Index_Little", "IL"),
    (5, "Thumb_Little", "TL"),
    (6, "Hand_Close", "HC"),
    (7, "Hand_Open", "HO"),
    (8, "Wrist_Extension", "WE"),
    (9, "Wrist_Flexion", "WF"),
    (10, "Ulner_Deviation", "UD"),
    (11, "Radial_Deviation", "RD"),
]

gesture_df = pd.DataFrame(
    gesture_definitions,
    columns=[
        "gesture_id",
        "gesture",
        "acronym"
    ]
)

display(gesture_df)

print(
    "\nNumber of gestures:",
    len(gesture_df)
)


# ============================================================
# 3. ORIENTATION DEFINITIONS
# ============================================================

print("\n[3] ORIENTATION DEFINITIONS")
print("-" * 80)

orientations = [
    "pronation",
    "rest",
    "supination"
]

orientation_to_id = {
    "pronation": 0,
    "rest": 1,
    "supination": 2
}

for orientation in orientations:
    print(
        orientation_to_id[orientation],
        "->",
        orientation
    )


# ============================================================
# 4. FIND ALL RECORDINGS
# ============================================================

print("\n[4] FINDING RECORDINGS")
print("-" * 80)

mat_files = sorted(
    FORS_ROOT.rglob("*.mat")
)

print(
    "Total MAT files:",
    len(mat_files)
)

if len(mat_files) != 3420:
    raise ValueError(
        f"Expected 3420 MAT files but found {len(mat_files)}."
    )


# ============================================================
# 5. INSPECT FILENAME PATTERNS
# ============================================================

print("\n[5] FILENAME PATTERN INSPECTION")
print("-" * 80)

print(
    "First 50 filenames:"
)

for i, path in enumerate(mat_files[:50], start=1):

    print(
        f"{i:02d}. "
        f"{path.parent.name}/"
        f"{path.name}"
    )


# ============================================================
# 6. ANALYZE FILENAME COMPONENTS
# ============================================================

print("\n[6] FILENAME COMPONENT ANALYSIS")
print("-" * 80)

filename_examples = [
    path.name
    for path in mat_files[:100]
]

for filename in filename_examples[:30]:

    print(
        f"{filename:60s} -> "
        f"{filename.split('.')[0].split('_')}"
    )


# ============================================================
# 7. EXTRACT SUBJECT + ORIENTATION
# ============================================================

print("\n[7] EXTRACT SUBJECT AND ORIENTATION")
print("-" * 80)

base_records = []

for mat_path in mat_files:

    relative_path = (
        mat_path.relative_to(FORS_ROOT)
    )

    parts = relative_path.parts

    if len(parts) < 3:

        print(
            "WARNING: Unexpected path:",
            mat_path
        )

        continue

    subject = parts[0]
    orientation = parts[1].lower()
    filename = parts[-1]

    base_records.append(
        {
            "subject": subject,
            "orientation": orientation,
            "filename": filename,
            "filepath": str(mat_path)
        }
    )

base_df = pd.DataFrame(
    base_records
)

print(
    "Parsed recordings:",
    len(base_df)
)

display(
    base_df.head(20)
)


# ============================================================
# 8. EXAMINE FILENAMES BY SUBJECT/ORIENTATION
# ============================================================

print("\n[8] FILENAME ORDER ANALYSIS")
print("-" * 80)

for orientation in orientations:

    subset = base_df[
        (base_df["subject"] == "Subject1") &
        (base_df["orientation"] == orientation)
    ].copy()

    print(
        f"\nSubject1 / {orientation}"
    )

    for filename in subset["filename"].tolist():

        print(
            filename
        )


# ============================================================
# 9. DETERMINE FILENAME LABEL STRUCTURE
# ============================================================

print("\n[9] GESTURE / REPETITION IDENTIFICATION")
print("-" * 80)

print(
    """
We now inspect the filenames to determine how the
12 gestures × 5 repetitions are encoded.

The expected number is:

12 gestures × 5 repetitions = 60 recordings

per subject/orientation.
"""
)


# ============================================================
# 10. TRY COMMON NUMERIC PATTERN EXTRACTION
# ============================================================

print("\n[10] NUMERIC COMPONENT ANALYSIS")
print("-" * 80)

numeric_pattern_results = []

for filename in base_df["filename"]:

    stem = Path(filename).stem

    numbers = re.findall(
        r"\d+",
        stem
    )

    numeric_pattern_results.append(
        {
            "filename": filename,
            "numbers": numbers
        }
    )

numeric_df = pd.DataFrame(
    numeric_pattern_results
)

display(
    numeric_df.head(50)
)


# ============================================================
# 11. UNIQUE FILENAME STEMS
# ============================================================

print("\n[11] UNIQUE FILENAME ANALYSIS")
print("-" * 80)

base_df["stem"] = (
    base_df["filename"]
    .apply(
        lambda x: Path(x).stem
    )
)

unique_stems = sorted(
    base_df["stem"].unique()
)

print(
    "Unique filename stems:",
    len(unique_stems)
)

print("\nFirst 100 unique stems:")

for stem in unique_stems[:100]:

    print(stem)


# ============================================================
# 12. CHECK WHETHER FILENAMES REPEAT ACROSS SUBJECTS
# ============================================================

print("\n[12] FILENAME REUSE ANALYSIS")
print("-" * 80)

filename_subject_counts = (
    base_df
    .groupby("filename")["subject"]
    .nunique()
    .sort_values(ascending=False)
)

print(
    "Maximum number of subjects sharing the same filename:"
)

print(
    filename_subject_counts.max()
)

print(
    "\nFilename examples:"
)

display(
    filename_subject_counts
    .head(20)
    .to_frame(
        name="number_of_subjects"
    )
)


# ============================================================
# 13. CHECK NUMBER OF UNIQUE FILES PER
# SUBJECT × ORIENTATION
# ============================================================

print("\n[13] SUBJECT × ORIENTATION FILE COUNTS")
print("-" * 80)

counts = pd.crosstab(
    base_df["subject"],
    base_df["orientation"]
)

display(
    counts
)

if not (
    counts == 60
).all().all():

    print(
        "\nWARNING: Not every subject/orientation contains 60 files."
    )

else:

    print(
        "\n✓ Every subject/orientation contains exactly 60 recordings."
    )


# ============================================================
# 14. TEMPORARY ORDER-BASED GESTURE ASSIGNMENT
# ============================================================

print("\n[14] TESTING ORDER-BASED MAPPING")
print("-" * 80)

print(
    """
We will NOT permanently assign labels yet.

First we test whether each group of 60 files follows:

Gesture 1 → repetitions 1–5
Gesture 2 → repetitions 1–5
...
Gesture 12 → repetitions 1–5
"""
)


def assign_order_based_labels(group):

    group = group.sort_values(
        "filename"
    ).copy()

    n = len(group)

    if n != 60:
        raise ValueError(
            f"Expected 60 files but got {n}"
        )

    gesture_ids = []
    repetitions = []

    for i in range(n):

        gesture_index = i // 5
        repetition = (i % 5) + 1

        gesture_ids.append(
            gesture_index
        )

        repetitions.append(
            repetition
        )

    group["gesture_id_test"] = gesture_ids
    group["repetition_test"] = repetitions

    return group


test_mapped = (
    base_df
    .groupby(
        ["subject", "orientation"],
        group_keys=False
    )
    .apply(
        assign_order_based_labels
    )
    .reset_index(drop=True)
)

print(
    "Temporary mapped rows:",
    len(test_mapped)
)

display(
    test_mapped.head(20)
)


# ============================================================
# 15. CHECK ORDER-BASED DISTRIBUTION
# ============================================================

print("\n[15] TEMPORARY GESTURE DISTRIBUTION")
print("-" * 80)

temporary_counts = (
    test_mapped
    .groupby(
        [
            "subject",
            "orientation",
            "gesture_id_test"
        ]
    )
    .size()
)

print(
    "Minimum recordings per gesture:",
    temporary_counts.min()
)

print(
    "Maximum recordings per gesture:",
    temporary_counts.max()
)

if (
    temporary_counts.min() == 5
    and temporary_counts.max() == 5
):

    print(
        "\n✓ Order-based mapping gives exactly 5 files "
        "per gesture within every subject/orientation."
    )

else:

    print(
        "\nWARNING: Order-based mapping does not produce "
        "5 repetitions per gesture."
    )


# ============================================================
# 16. SHOW TEMPORARY MAPPING FOR SUBJECT 1
# ============================================================

print("\n[16] SUBJECT 1 TEMPORARY MAPPING")
print("-" * 80)

subject1_mapping = test_mapped[
    test_mapped["subject"] == "Subject1"
].copy()

subject1_mapping[
    "gesture"
] = subject1_mapping[
    "gesture_id_test"
].map(
    dict(
        zip(
            gesture_df["gesture_id"],
            gesture_df["gesture"]
        )
    )
)

display(
    subject1_mapping[
        [
            "subject",
            "orientation",
            "filename",
            "gesture_id_test",
            "gesture",
            "repetition_test"
        ]
    ].head(100)
)


# ============================================================
# 17. IMPORTANT: SAVE FILENAME PATTERN REPORT
# ============================================================

print("\n[17] SAVE FILENAME ANALYSIS")
print("-" * 80)

results_dir = (
    PROJECT_ROOT
    / "results"
)

results_dir.mkdir(
    parents=True,
    exist_ok=True
)

test_mapped.to_csv(
    results_dir
    / "step03_temporary_metadata_mapping.csv",
    index=False
)

print(
    "Temporary mapping saved."
)


# ============================================================
# 18. SUMMARY
# ============================================================

print("\n" + "=" * 80)
print("STEP 3 ANALYSIS COMPLETED")
print("=" * 80)

================================================================================
FORS-EMG RESEARCH PROJECT
STEP 3 — MASTER METADATA TABLE CONSTRUCTION
================================================================================

[1] PATH VERIFICATION
--------------------------------------------------------------------------------
FORS root:
/kaggle/working/fors_emg_research/raw_data/kaggle_download/FORS-EMG Dataset/FORS-EMG Dataset/FORS-EMG

[2] GESTURE DEFINITIONS
--------------------------------------------------------------------------------

    gesture_id           gesture acronym
0            0          Thumb_UP      TU
1            1             Index     IDX
2            2       Right_Angle      RA
3            3             Peace     PCE
4            4      Index_Little      IL
5            5      Thumb_Little      TL
6            6        Hand_Close      HC
7            7         Hand_Open      HO
8            8   Wrist_Extension      WE
9            9     Wrist_Flexion      WF
10          10   Ulner_Deviation      UD
11          11  Radial_Deviation      RD

Number of gestures: 12

[3] ORIENTATION DEFINITIONS
--------------------------------------------------------------------------------
0 -> pronation
1 -> rest
2 -> supination

[4] FINDING RECORDINGS
--------------------------------------------------------------------------------
Total MAT files: 3420

[5] FILENAME PATTERN INSPECTION
--------------------------------------------------------------------------------
First 50 filenames:
01. pronation/Hand_Close-1.mat
02. pronation/Hand_Close-2.mat
03. pronation/Hand_Close-3.mat
04. pronation/Hand_Close-4.mat
05. pronation/Hand_Close-5.mat
06. pronation/Hand_Open-1.mat
07. pronation/Hand_Open-2.mat
08. pronation/Hand_Open-3.mat
09. pronation/Hand_Open-4.mat
10. pronation/Hand_Open-5.mat
11. pronation/Index-1.mat
12. pronation/Index-2.mat
13. pronation/Index-3.mat
14. pronation/Index-4.mat
15. pronation/Index-5.mat
16. pronation/Index_Little-1.mat
17. pronation/Index_Little-2.mat
18. pronation/Index_Little-3.mat
19. pronation/Index_Little-4.mat
20. pronation/Index_Little-5.mat
21. pronation/Peace-1.mat
22. pronation/Peace-2.mat
23. pronation/Peace-3.mat
24. pronation/Peace-4.mat
25. pronation/Peace-5.mat
26. pronation/Radial_Deviation-1.mat
27. pronation/Radial_Deviation-2.mat
28. pronation/Radial_Deviation-3.mat
29. pronation/Radial_Deviation-4.mat
30. pronation/Radial_Deviation-5.mat
31. pronation/Right_Angle-1.mat
32. pronation/Right_Angle-2.mat
33. pronation/Right_Angle-3.mat
34. pronation/Right_Angle-4.mat
35. pronation/Right_Angle-5.mat
36. pronation/Thumb_Little-1.mat
37. pronation/Thumb_Little-2.mat
38. pronation/Thumb_Little-3.mat
39. pronation/Thumb_Little-4.mat
40. pronation/Thumb_Little-5.mat
41. pronation/Thumb_UP-1.mat
42. pronation/Thumb_UP-2.mat
43. pronation/Thumb_UP-3.mat
44. pronation/Thumb_UP-4.mat
45. pronation/Thumb_UP-5.mat
46. pronation/Ulner_Deviation-1.mat
47. pronation/Ulner_Deviation-2.mat
48. pronation/Ulner_Deviation-3.mat
49. pronation/Ulner_Deviation-4.mat
50. pronation/Ulner_Deviation-5.mat

[6] FILENAME COMPONENT ANALYSIS
--------------------------------------------------------------------------------
Hand_Close-1.mat                                             -> ['Hand', 'Close-1']
Hand_Close-2.mat                                             -> ['Hand', 'Close-2']
Hand_Close-3.mat                                             -> ['Hand', 'Close-3']
Hand_Close-4.mat                                             -> ['Hand', 'Close-4']
Hand_Close-5.mat                                             -> ['Hand', 'Close-5']
Hand_Open-1.mat                                              -> ['Hand', 'Open-1']
Hand_Open-2.mat                                              -> ['Hand', 'Open-2']
Hand_Open-3.mat                                              -> ['Hand', 'Open-3']
Hand_Open-4.mat                                              -> ['Hand', 'Open-4']
Hand_Open-5.mat                                              -> ['Hand', 'Open-5']
Index-1.mat                                                  -> ['Index-1']
Index-2.mat                                                  -> ['Index-2']
Index-3.mat                                                  -> ['Index-3']
Index-4.mat                                                  -> ['Index-4']
Index-5.mat                                                  -> ['Index-5']
Index_Little-1.mat                                           -> ['Index', 'Little-1']
Index_Little-2.mat                                           -> ['Index', 'Little-2']
Index_Little-3.mat                                           -> ['Index', 'Little-3']
Index_Little-4.mat                                           -> ['Index', 'Little-4']
Index_Little-5.mat                                           -> ['Index', 'Little-5']
Peace-1.mat                                                  -> ['Peace-1']
Peace-2.mat                                                  -> ['Peace-2']
Peace-3.mat                                                  -> ['Peace-3']
Peace-4.mat                                                  -> ['Peace-4']
Peace-5.mat                                                  -> ['Peace-5']
Radial_Deviation-1.mat                                       -> ['Radial', 'Deviation-1']
Radial_Deviation-2.mat                                       -> ['Radial', 'Deviation-2']
Radial_Deviation-3.mat                                       -> ['Radial', 'Deviation-3']
Radial_Deviation-4.mat                                       -> ['Radial', 'Deviation-4']
Radial_Deviation-5.mat                                       -> ['Radial', 'Deviation-5']

[7] EXTRACT SUBJECT AND ORIENTATION
--------------------------------------------------------------------------------
Parsed recordings: 3420

,subject,orientation,filename,filepath
0,Subject1,pronation,Hand_Close-1.mat,/kaggle/working/fors_emg_research/raw_data/kag...
1,Subject1,pronation,Hand_Close-2.mat,/kaggle/working/fors_emg_research/raw_data/kag...
2,Subject1,pronation,Hand_Close-3.mat,/kaggle/working/fors_emg_research/raw_data/kag...
3,Subject1,pronation,Hand_Close-4.mat,/kaggle/working/fors_emg_research/raw_data/kag...
4,Subject1,pronation,Hand_Close-5.mat,/kaggle/working/fors_emg_research/raw_data/kag...
5,Subject1,pronation,Hand_Open-1.mat,/kaggle/working/fors_emg_research/raw_data/kag...
6,Subject1,pronation,Hand_Open-2.mat,/kaggle/working/fors_emg_research/raw_data/kag...
7,Subject1,pronation,Hand_Open-3.mat,/kaggle/working/fors_emg_research/raw_data/kag...
8,Subject1,pronation,Hand_Open-4.mat,/kaggle/working/fors_emg_research/raw_data/kag...
9,Subject1,pronation,Hand_Open-5.mat,/kaggle/working/fors_emg_research/raw_data/kag...
10,Subject1,pronation,Index-1.mat,/kaggle/working/fors_emg_research/raw_data/kag...
11,Subject1,pronation,Index-2.mat,/kaggle/working/fors_emg_research/raw_data/kag...
12,Subject1,pronation,Index-3.mat,/kaggle/working/fors_emg_research/raw_data/kag...
13,Subject1,pronation,Index-4.mat,/kaggle/working/fors_emg_research/raw_data/kag...
14,Subject1,pronation,Index-5.mat,/kaggle/working/fors_emg_research/raw_data/kag...
15,Subject1,pronation,Index_Little-1.mat,/kaggle/working/fors_emg_research/raw_data/kag...
16,Subject1,pronation,Index_Little-2.mat,/kaggle/working/fors_emg_research/raw_data/kag...
17,Subject1,pronation,Index_Little-3.mat,/kaggle/working/fors_emg_research/raw_data/kag...
18,Subject1,pronation,Index_Little-4.mat,/kaggle/working/fors_emg_research/raw_data/kag...
19,Subject1,pronation,Index_Little-5.mat,/kaggle/working/fors_emg_research/raw_data/kag...

[8] FILENAME ORDER ANALYSIS
--------------------------------------------------------------------------------

Subject1 / pronation
Hand_Close-1.mat
Hand_Close-2.mat
Hand_Close-3.mat
Hand_Close-4.mat
Hand_Close-5.mat
Hand_Open-1.mat
Hand_Open-2.mat
Hand_Open-3.mat
Hand_Open-4.mat
Hand_Open-5.mat
Index-1.mat
Index-2.mat
Index-3.mat
Index-4.mat
Index-5.mat
Index_Little-1.mat
Index_Little-2.mat
Index_Little-3.mat
Index_Little-4.mat
Index_Little-5.mat
Peace-1.mat
Peace-2.mat
Peace-3.mat
Peace-4.mat
Peace-5.mat
Radial_Deviation-1.mat
Radial_Deviation-2.mat
Radial_Deviation-3.mat
Radial_Deviation-4.mat
Radial_Deviation-5.mat
Right_Angle-1.mat
Right_Angle-2.mat
Right_Angle-3.mat
Right_Angle-4.mat
Right_Angle-5.mat
Thumb_Little-1.mat
Thumb_Little-2.mat
Thumb_Little-3.mat
Thumb_Little-4.mat
Thumb_Little-5.mat
Thumb_UP-1.mat
Thumb_UP-2.mat
Thumb_UP-3.mat
Thumb_UP-4.mat
Thumb_UP-5.mat
Ulner_Deviation-1.mat
Ulner_Deviation-2.mat
Ulner_Deviation-3.mat
Ulner_Deviation-4.mat
Ulner_Deviation-5.mat
Wrist_Extension-1.mat
Wrist_Extension-2.mat
Wrist_Extension-3.mat
Wrist_Extension-4.mat
Wrist_Extension-5.mat
Wrist_Flexion-1.mat
Wrist_Flexion-2.mat
Wrist_Flexion-3.mat
Wrist_Flexion-4.mat
Wrist_Flexion-5.mat

Subject1 / rest
Hand_Close-1.mat
Hand_Close-2.mat
Hand_Close-3.mat
Hand_Close-4.mat
Hand_Close-5.mat
Hand_Open-1.mat
Hand_Open-2.mat
Hand_Open-3.mat
Hand_Open-4.mat
Hand_Open-5.mat
Index-1.mat
Index-2.mat
Index-3.mat
Index-4.mat
Index-5.mat
Index_Little-1.mat
Index_Little-2.mat
Index_Little-3.mat
Index_Little-4.mat
Index_Little-5.mat
Peace-1.mat
Peace-2.mat
Peace-3.mat
Peace-4.mat
Peace-5.mat
Radial_Deviation-1.mat
Radial_Deviation-2.mat
Radial_Deviation-3.mat
Radial_Deviation-4.mat
Radial_Deviation-5.mat
Right_Angle-1.mat
Right_Angle-2.mat
Right_Angle-3.mat
Right_Angle-4.mat
Right_Angle-5.mat
Thumb_Little-1.mat
Thumb_Little-2.mat
Thumb_Little-3.mat
Thumb_Little-4.mat
Thumb_Little-5.mat
Thumb_UP-1.mat
Thumb_UP-2.mat
Thumb_UP-3.mat
Thumb_UP-4.mat
Thumb_UP-5.mat
Ulner_Deviation-1.mat
Ulner_Deviation-2.mat
Ulner_Deviation-3.mat
Ulner_Deviation-4.mat
Ulner_Deviation-5.mat
Wrist_Extension-1.mat
Wrist_Extension-2.mat
Wrist_Extension-3.mat
Wrist_Extension-4.mat
Wrist_Extension-5.mat
Wrist_Flexion-1.mat
Wrist_Flexion-2.mat
Wrist_Flexion-3.mat
Wrist_Flexion-4.mat
Wrist_Flexion-5.mat

Subject1 / supination
Hand_Close-1.mat
Hand_Close-2.mat
Hand_Close-3.mat
Hand_Close-4.mat
Hand_Close-5.mat
Hand_Open-1.mat
Hand_Open-2.mat
Hand_Open-3.mat
Hand_Open-4.mat
Hand_Open-5.mat
Index-1.mat
Index-2.mat
Index-3.mat
Index-4.mat
Index-5.mat
Index_Little-1.mat
Index_Little-2.mat
Index_Little-3.mat
Index_Little-4.mat
Index_Little-5.mat
Peace-1.mat
Peace-2.mat
Peace-3.mat
Peace-4.mat
Peace-5.mat
Radial_Deviation-1.mat
Radial_Deviation-2.mat
Radial_Deviation-3.mat
Radial_Deviation-4.mat
Radial_Deviation-5.mat
Right_Angle-1.mat
Right_Angle-2.mat
Right_Angle-3.mat
Right_Angle-4.mat
Right_Angle-5.mat
Thumb_Little-1.mat
Thumb_Little-2.mat
Thumb_Little-3.mat
Thumb_Little-4.mat
Thumb_Little-5.mat
Thumb_UP-1.mat
Thumb_UP-2.mat
Thumb_UP-3.mat
Thumb_UP-4.mat
Thumb_UP-5.mat
Ulner_Deviation-1.mat
Ulner_Deviation-2.mat
Ulner_Deviation-3.mat
Ulner_Deviation-4.mat
Ulner_Deviation-5.mat
Wrist_Extension-1.mat
Wrist_Extension-2.mat
Wrist_Extension-3.mat
Wrist_Extension-4.mat
Wrist_Extension-5.mat
Wrist_Flexion-1.mat
Wrist_Flexion-2.mat
Wrist_Flexion-3.mat
Wrist_Flexion-4.mat
Wrist_Flexion-5.mat

[9] GESTURE / REPETITION IDENTIFICATION
--------------------------------------------------------------------------------

We now inspect the filenames to determine how the
12 gestures × 5 repetitions are encoded.

The expected number is:

12 gestures × 5 repetitions = 60 recordings

per subject/orientation.


[10] NUMERIC COMPONENT ANALYSIS
--------------------------------------------------------------------------------

                  filename numbers
0         Hand_Close-1.mat     [1]
1         Hand_Close-2.mat     [2]
2         Hand_Close-3.mat     [3]
3         Hand_Close-4.mat     [4]
4         Hand_Close-5.mat     [5]
5          Hand_Open-1.mat     [1]
6          Hand_Open-2.mat     [2]
7          Hand_Open-3.mat     [3]
8          Hand_Open-4.mat     [4]
9          Hand_Open-5.mat     [5]
10             Index-1.mat     [1]
11             Index-2.mat     [2]
12             Index-3.mat     [3]
13             Index-4.mat     [4]
14             Index-5.mat     [5]
15      Index_Little-1.mat     [1]
16      Index_Little-2.mat     [2]
17      Index_Little-3.mat     [3]
18      Index_Little-4.mat     [4]
19      Index_Little-5.mat     [5]
20             Peace-1.mat     [1]
21             Peace-2.mat     [2]
22             Peace-3.mat     [3]
23             Peace-4.mat     [4]
24             Peace-5.mat     [5]
25  Radial_Deviation-1.mat     [1]
26  Radial_Deviation-2.mat     [2]
27  Radial_Deviation-3.mat     [3]
28  Radial_Deviation-4.mat     [4]
29  Radial_Deviation-5.mat     [5]
30       Right_Angle-1.mat     [1]
31       Right_Angle-2.mat     [2]
32       Right_Angle-3.mat     [3]
33       Right_Angle-4.mat     [4]
34       Right_Angle-5.mat     [5]
35      Thumb_Little-1.mat     [1]
36      Thumb_Little-2.mat     [2]
37      Thumb_Little-3.mat     [3]
38      Thumb_Little-4.mat     [4]
39      Thumb_Little-5.mat     [5]
40          Thumb_UP-1.mat     [1]
41          Thumb_UP-2.mat     [2]
42          Thumb_UP-3.mat     [3]
43          Thumb_UP-4.mat     [4]
44          Thumb_UP-5.mat     [5]
45   Ulner_Deviation-1.mat     [1]
46   Ulner_Deviation-2.mat     [2]
47   Ulner_Deviation-3.mat     [3]
48   Ulner_Deviation-4.mat     [4]
49   Ulner_Deviation-5.mat     [5]

[11] UNIQUE FILENAME ANALYSIS
--------------------------------------------------------------------------------
Unique filename stems: 60

First 100 unique stems:
Hand_Close-1
Hand_Close-2
Hand_Close-3
Hand_Close-4
Hand_Close-5
Hand_Open-1
Hand_Open-2
Hand_Open-3
Hand_Open-4
Hand_Open-5
Index-1
Index-2
Index-3
Index-4
Index-5
Index_Little-1
Index_Little-2
Index_Little-3
Index_Little-4
Index_Little-5
Peace-1
Peace-2
Peace-3
Peace-4
Peace-5
Radial_Deviation-1
Radial_Deviation-2
Radial_Deviation-3
Radial_Deviation-4
Radial_Deviation-5
Right_Angle-1
Right_Angle-2
Right_Angle-3
Right_Angle-4
Right_Angle-5
Thumb_Little-1
Thumb_Little-2
Thumb_Little-3
Thumb_Little-4
Thumb_Little-5
Thumb_UP-1
Thumb_UP-2
Thumb_UP-3
Thumb_UP-4
Thumb_UP-5
Ulner_Deviation-1
Ulner_Deviation-2
Ulner_Deviation-3
Ulner_Deviation-4
Ulner_Deviation-5
Wrist_Extension-1
Wrist_Extension-2
Wrist_Extension-3
Wrist_Extension-4
Wrist_Extension-5
Wrist_Flexion-1
Wrist_Flexion-2
Wrist_Flexion-3
Wrist_Flexion-4
Wrist_Flexion-5

[12] FILENAME REUSE ANALYSIS
--------------------------------------------------------------------------------
Maximum number of subjects sharing the same filename:
19

Filename examples:

                    number_of_subjects
filename
Hand_Close-1.mat                    19
Hand_Close-2.mat                    19
Hand_Close-3.mat                    19
Hand_Close-4.mat                    19
Hand_Close-5.mat                    19
Hand_Open-1.mat                     19
Hand_Open-2.mat                     19
Hand_Open-3.mat                     19
Hand_Open-4.mat                     19
Hand_Open-5.mat                     19
Index-1.mat                         19
Index-2.mat                         19
Index-3.mat                         19
Index-4.mat                         19
Index-5.mat                         19
Index_Little-1.mat                  19
Index_Little-2.mat                  19
Index_Little-3.mat                  19
Index_Little-4.mat                  19
Index_Little-5.mat                  19

[13] SUBJECT × ORIENTATION FILE COUNTS
--------------------------------------------------------------------------------

orientation  pronation  rest  supination
subject
Subject1            60    60          60
Subject10           60    60          60
Subject11           60    60          60
Subject12           60    60          60
Subject13           60    60          60
Subject14           60    60          60
Subject15           60    60          60
Subject16           60    60          60
Subject17           60    60          60
Subject18           60    60          60
Subject19           60    60          60
Subject2            60    60          60
Subject3            60    60          60
Subject4            60    60          60
Subject5            60    60          60
Subject6            60    60          60
Subject7            60    60          60
Subject8            60    60          60
Subject9            60    60          60

✓ Every subject/orientation contains exactly 60 recordings.

[14] TESTING ORDER-BASED MAPPING
--------------------------------------------------------------------------------

We will NOT permanently assign labels yet.

First we test whether each group of 60 files follows:

Gesture 1 → repetitions 1–5
Gesture 2 → repetitions 1–5
...
Gesture 12 → repetitions 1–5

Temporary mapped rows: 3420

,subject,orientation,filename,filepath,stem,gesture_id_test,repetition_test
0,Subject1,pronation,Hand_Close-1.mat,/kaggle/working/fors_emg_research/raw_data/kag...,Hand_Close-1,0,1
1,Subject1,pronation,Hand_Close-2.mat,/kaggle/working/fors_emg_research/raw_data/kag...,Hand_Close-2,0,2
2,Subject1,pronation,Hand_Close-3.mat,/kaggle/working/fors_emg_research/raw_data/kag...,Hand_Close-3,0,3
3,Subject1,pronation,Hand_Close-4.mat,/kaggle/working/fors_emg_research/raw_data/kag...,Hand_Close-4,0,4
4,Subject1,pronation,Hand_Close-5.mat,/kaggle/working/fors_emg_research/raw_data/kag...,Hand_Close-5,0,5
5,Subject1,pronation,Hand_Open-1.mat,/kaggle/working/fors_emg_research/raw_data/kag...,Hand_Open-1,1,1
6,Subject1,pronation,Hand_Open-2.mat,/kaggle/working/fors_emg_research/raw_data/kag...,Hand_Open-2,1,2
7,Subject1,pronation,Hand_Open-3.mat,/kaggle/working/fors_emg_research/raw_data/kag...,Hand_Open-3,1,3
8,Subject1,pronation,Hand_Open-4.mat,/kaggle/working/fors_emg_research/raw_data/kag...,Hand_Open-4,1,4
9,Subject1,pronation,Hand_Open-5.mat,/kaggle/working/fors_emg_research/raw_data/kag...,Hand_Open-5,1,5
10,Subject1,pronation,Index-1.mat,/kaggle/working/fors_emg_research/raw_data/kag...,Index-1,2,1
11,Subject1,pronation,Index-2.mat,/kaggle/working/fors_emg_research/raw_data/kag...,Index-2,2,2
12,Subject1,pronation,Index-3.mat,/kaggle/working/fors_emg_research/raw_data/kag...,Index-3,2,3
13,Subject1,pronation,Index-4.mat,/kaggle/working/fors_emg_research/raw_data/kag...,Index-4,2,4
14,Subject1,pronation,Index-5.mat,/kaggle/working/fors_emg_research/raw_data/kag...,Index-5,2,5
15,Subject1,pronation,Index_Little-1.mat,/kaggle/working/fors_emg_research/raw_data/kag...,Index_Little-1,3,1
16,Subject1,pronation,Index_Little-2.mat,/kaggle/working/fors_emg_research/raw_data/kag...,Index_Little-2,3,2
17,Subject1,pronation,Index_Little-3.mat,/kaggle/working/fors_emg_research/raw_data/kag...,Index_Little-3,3,3
18,Subject1,pronation,Index_Little-4.mat,/kaggle/working/fors_emg_research/raw_data/kag...,Index_Little-4,3,4
19,Subject1,pronation,Index_Little-5.mat,/kaggle/working/fors_emg_research/raw_data/kag...,Index_Little-5,3,5

[15] TEMPORARY GESTURE DISTRIBUTION
--------------------------------------------------------------------------------
Minimum recordings per gesture: 5
Maximum recordings per gesture: 5

✓ Order-based mapping gives exactly 5 files per gesture within every subject/orientation.

[16] SUBJECT 1 TEMPORARY MAPPING
--------------------------------------------------------------------------------

,subject,orientation,filename,gesture_id_test,gesture,repetition_test
0,Subject1,pronation,Hand_Close-1.mat,0,Thumb_UP,1
1,Subject1,pronation,Hand_Close-2.mat,0,Thumb_UP,2
2,Subject1,pronation,Hand_Close-3.mat,0,Thumb_UP,3
3,Subject1,pronation,Hand_Close-4.mat,0,Thumb_UP,4
4,Subject1,pronation,Hand_Close-5.mat,0,Thumb_UP,5
...,...,...,...,...,...,...
95,Subject1,rest,Thumb_Little-1.mat,7,Hand_Open,1
96,Subject1,rest,Thumb_Little-2.mat,7,Hand_Open,2
97,Subject1,rest,Thumb_Little-3.mat,7,Hand_Open,3
98,Subject1,rest,Thumb_Little-4.mat,7,Hand_Open,4
99,Subject1,rest,Thumb_Little-5.mat,7,Hand_Open,5

[17] SAVE FILENAME ANALYSIS
--------------------------------------------------------------------------------
Temporary mapping saved.

================================================================================
STEP 3 ANALYSIS COMPLETED
================================================================================

In [4]:
# ============================================================
# FORS-EMG RESEARCH PROJECT
# STEP 4 — FINAL MASTER METADATA TABLE
# ============================================================

import os
import re
import json
from pathlib import Path
from collections import Counter

import numpy as np
import pandas as pd


print("=" * 90)
print("FORS-EMG RESEARCH PROJECT")
print("STEP 4 — FINAL MASTER METADATA TABLE")
print("=" * 90)


# ============================================================
# 1. PROJECT PATHS
# ============================================================

PROJECT_ROOT = Path(
    "/kaggle/working/fors_emg_research"
)

RAW_ROOT = (
    PROJECT_ROOT
    / "raw_data"
    / "kaggle_download"
)

DATASET_ROOT = (
    RAW_ROOT
    / "FORS-EMG Dataset"
    / "FORS-EMG Dataset"
)

FORS_ROOT = (
    DATASET_ROOT
    / "FORS-EMG"
)

DATABASE_ROOT = (
    DATASET_ROOT
    / "Database Info"
)

METADATA_DIR = (
    PROJECT_ROOT
    / "processed_data"
)

METADATA_DIR.mkdir(
    parents=True,
    exist_ok=True
)


# ============================================================
# 2. DATASET CONSTANTS
# ============================================================

EXPECTED_SUBJECTS = 19
EXPECTED_ORIENTATIONS = 3
EXPECTED_GESTURES = 12
EXPECTED_REPETITIONS = 5
EXPECTED_CHANNELS = 8
EXPECTED_SAMPLES = 8000
EXPECTED_SAMPLING_RATE = 985

EXPECTED_RECORDINGS = (
    EXPECTED_SUBJECTS
    * EXPECTED_ORIENTATIONS
    * EXPECTED_GESTURES
    * EXPECTED_REPETITIONS
)

print("\n[1] EXPECTED DATASET STRUCTURE")
print("-" * 90)

print(
    "Subjects      :", EXPECTED_SUBJECTS
)

print(
    "Orientations  :", EXPECTED_ORIENTATIONS
)

print(
    "Gestures      :", EXPECTED_GESTURES
)

print(
    "Repetitions   :", EXPECTED_REPETITIONS
)

print(
    "Channels      :", EXPECTED_CHANNELS
)

print(
    "Samples       :", EXPECTED_SAMPLES
)

print(
    "Sampling rate :", EXPECTED_SAMPLING_RATE,
    "Hz"
)

print(
    "Expected total recordings:",
    EXPECTED_RECORDINGS
)


# ============================================================
# 3. GESTURE DEFINITIONS
# ============================================================

print("\n[2] GESTURE DEFINITIONS")
print("-" * 90)

gesture_definitions = [
    (0, "Thumb_UP", "TU"),
    (1, "Index", "IDX"),
    (2, "Right_Angle", "RA"),
    (3, "Peace", "PCE"),
    (4, "Index_Little", "IL"),
    (5, "Thumb_Little", "TL"),
    (6, "Hand_Close", "HC"),
    (7, "Hand_Open", "HO"),
    (8, "Wrist_Extension", "WE"),
    (9, "Wrist_Flexion", "WF"),
    (10, "Ulner_Deviation", "UD"),
    (11, "Radial_Deviation", "RD"),
]

gesture_map = {
    name: gesture_id
    for gesture_id, name, acronym
    in gesture_definitions
}

gesture_acronym_map = {
    name: acronym
    for gesture_id, name, acronym
    in gesture_definitions
}

print(
    "Gesture classes:",
    len(gesture_map)
)

for gesture_id, name, acronym in gesture_definitions:

    print(
        f"{gesture_id:02d} | "
        f"{name:20s} | "
        f"{acronym}"
    )


# ============================================================
# 4. ORIENTATION DEFINITIONS
# ============================================================

print("\n[3] ORIENTATION DEFINITIONS")
print("-" * 90)

orientation_map = {
    "pronation": 0,
    "rest": 1,
    "supination": 2
}

for orientation, orientation_id in orientation_map.items():

    print(
        f"{orientation_id} | {orientation}"
    )


# ============================================================
# 5. FIND ALL MATLAB FILES
# ============================================================

print("\n[4] FINDING RECORDINGS")
print("-" * 90)

mat_files = sorted(
    FORS_ROOT.rglob("*.mat")
)

print(
    "MAT files found:",
    len(mat_files)
)

if len(mat_files) != EXPECTED_RECORDINGS:

    raise ValueError(
        f"Expected {EXPECTED_RECORDINGS} recordings "
        f"but found {len(mat_files)}."
    )


# ============================================================
# 6. FILENAME PARSER
# ============================================================

print("\n[5] PARSING FILENAMES")
print("-" * 90)

"""
Expected filename examples:

Hand_Close-1.mat
Hand_Close-2.mat
Index-1.mat
Index_Little-5.mat
Radial_Deviation-3.mat

The structure is:

<gesture-name>-<repetition>.mat
"""

filename_pattern = re.compile(
    r"^(?P<gesture>.+)-(?P<repetition>[1-5])\.mat$",
    re.IGNORECASE
)


# ============================================================
# 7. BUILD MASTER RECORDS
# ============================================================

master_records = []

parse_errors = []

for mat_path in mat_files:

    relative_path = (
        mat_path.relative_to(FORS_ROOT)
    )

    parts = relative_path.parts

    # Expected:
    #
    # SubjectX/
    #     orientation/
    #         gesture-repetition.mat

    if len(parts) != 3:

        parse_errors.append(
            {
                "filepath": str(mat_path),
                "error": "Unexpected directory depth"
            }
        )

        continue

    subject_name = parts[0]
    orientation = parts[1].lower()
    filename = parts[2]

    # --------------------------------------------------------
    # SUBJECT ID
    # --------------------------------------------------------

    subject_match = re.match(
        r"^Subject(\d+)$",
        subject_name,
        re.IGNORECASE
    )

    if subject_match is None:

        parse_errors.append(
            {
                "filepath": str(mat_path),
                "error": "Invalid subject name"
            }
        )

        continue

    subject_id = int(
        subject_match.group(1)
    )

    # --------------------------------------------------------
    # ORIENTATION
    # --------------------------------------------------------

    if orientation not in orientation_map:

        parse_errors.append(
            {
                "filepath": str(mat_path),
                "error": f"Unknown orientation: {orientation}"
            }
        )

        continue

    orientation_id = (
        orientation_map[orientation]
    )

    # --------------------------------------------------------
    # FILENAME
    # --------------------------------------------------------

    filename_match = filename_pattern.match(
        filename
    )

    if filename_match is None:

        parse_errors.append(
            {
                "filepath": str(mat_path),
                "error": "Filename pattern not recognized"
            }
        )

        continue

    gesture_name = (
        filename_match
        .group("gesture")
    )

    repetition = int(
        filename_match
        .group("repetition")
    )

    # --------------------------------------------------------
    # NORMALIZE GESTURE NAME
    # --------------------------------------------------------

    gesture_lookup = {
        name.lower(): name
        for name in gesture_map.keys()
    }

    gesture_key = gesture_name.lower()

    if gesture_key not in gesture_lookup:

        parse_errors.append(
            {
                "filepath": str(mat_path),
                "error": (
                    f"Unknown gesture: "
                    f"{gesture_name}"
                )
            }
        )

        continue

    gesture = gesture_lookup[
        gesture_key
    ]

    gesture_id = (
        gesture_map[gesture]
    )

    gesture_acronym = (
        gesture_acronym_map[gesture]
    )

    # --------------------------------------------------------
    # ADD RECORD
    # --------------------------------------------------------

    master_records.append(
        {
            "subject": subject_name,
            "subject_id": subject_id,

            "orientation": orientation,
            "orientation_id": orientation_id,

            "gesture": gesture,
            "gesture_id": gesture_id,
            "gesture_acronym": gesture_acronym,

            "repetition": repetition,

            "filename": filename,
            "filepath": str(mat_path),

            "sampling_rate_hz":
                EXPECTED_SAMPLING_RATE,

            "n_channels":
                EXPECTED_CHANNELS,

            "n_samples":
                EXPECTED_SAMPLES,

            "duration_seconds":
                EXPECTED_SAMPLES /
                EXPECTED_SAMPLING_RATE
        }
    )


# ============================================================
# 8. CREATE DATAFRAME
# ============================================================

print("\n[6] MASTER DATAFRAME")
print("-" * 90)

master_df = pd.DataFrame(
    master_records
)

print(
    "Successfully parsed:",
    len(master_df)
)

print(
    "Parsing errors:",
    len(parse_errors)
)

if len(parse_errors) > 0:

    print("\nParsing errors:")
    display(
        pd.DataFrame(parse_errors)
    )

    raise ValueError(
        "Filename/path parsing errors detected. "
        "Do not continue until they are resolved."
    )


# ============================================================
# 9. SORT MASTER DATAFRAME
# ============================================================

master_df = master_df.sort_values(
    [
        "subject_id",
        "orientation_id",
        "gesture_id",
        "repetition"
    ]
).reset_index(
    drop=True
)


# ============================================================
# 10. DISPLAY MASTER TABLE
# ============================================================

print("\nFirst 30 metadata records:")
print("-" * 90)

display(
    master_df.head(30)
)


# ============================================================
# 11. DATAFRAME INFORMATION
# ============================================================

print("\n[7] DATAFRAME INFORMATION")
print("-" * 90)

print(
    "Shape:",
    master_df.shape
)

print(
    "\nColumns:"
)

for i, column in enumerate(
    master_df.columns,
    start=1
):

    print(
        f"{i:02d}. {column}"
    )


# ============================================================
# 12. CHECK TOTAL RECORDINGS
# ============================================================

print("\n[8] TOTAL RECORDING VALIDATION")
print("-" * 90)

actual_recordings = len(
    master_df
)

print(
    "Expected:",
    EXPECTED_RECORDINGS
)

print(
    "Actual  :",
    actual_recordings
)

assert (
    actual_recordings ==
    EXPECTED_RECORDINGS
)

print(
    "✓ Total recording count verified."
)


# ============================================================
# 13. SUBJECT VALIDATION
# ============================================================

print("\n[9] SUBJECT VALIDATION")
print("-" * 90)

subject_counts = (
    master_df
    .groupby(
        "subject_id"
    )
    .size()
)

print(
    subject_counts
)

assert (
    master_df["subject_id"].nunique()
    == EXPECTED_SUBJECTS
)

assert (
    subject_counts.min()
    == 180
)

assert (
    subject_counts.max()
    == 180
)

print(
    "\n✓ 19 subjects × 180 recordings."
)


# ============================================================
# 14. ORIENTATION VALIDATION
# ============================================================

print("\n[10] ORIENTATION VALIDATION")
print("-" * 90)

orientation_counts = (
    master_df[
        "orientation"
    ]
    .value_counts()
    .sort_index()
)

display(
    orientation_counts.to_frame(
        "recordings"
    )
)

assert (
    master_df[
        "orientation"
    ].nunique()
    == EXPECTED_ORIENTATIONS
)

assert (
    orientation_counts.min()
    == 1140
)

assert (
    orientation_counts.max()
    == 1140
)

print(
    "\n✓ All orientations contain 1,140 recordings."
)


# ============================================================
# 15. GESTURE VALIDATION
# ============================================================

print("\n[11] GESTURE VALIDATION")
print("-" * 90)

gesture_counts = (
    master_df
    .groupby(
        [
            "gesture_id",
            "gesture"
        ]
    )
    .size()
    .sort_index()
)

display(
    gesture_counts.to_frame(
        "recordings"
    )
)

assert (
    master_df[
        "gesture_id"
    ].nunique()
    == EXPECTED_GESTURES
)

print(
    "\nExpected recordings per gesture:",
    EXPECTED_SUBJECTS
    * EXPECTED_ORIENTATIONS
    * EXPECTED_REPETITIONS
)

assert (
    gesture_counts.min()
    == 285
)

assert (
    gesture_counts.max()
    == 285
)

print(
    "✓ Every gesture contains exactly 285 recordings."
)


# ============================================================
# 16. REPETITION VALIDATION
# ============================================================

print("\n[12] REPETITION VALIDATION")
print("-" * 90)

repetition_counts = (
    master_df
    .groupby(
        [
            "subject_id",
            "orientation",
            "gesture_id",
            "repetition"
        ]
    )
    .size()
)

print(
    "Number of unique "
    "subject × orientation × gesture × repetition "
    "combinations:",
    len(repetition_counts)
)

print(
    "Minimum count:",
    repetition_counts.min()
)

print(
    "Maximum count:",
    repetition_counts.max()
)

assert (
    len(repetition_counts)
    == EXPECTED_RECORDINGS
)

assert (
    repetition_counts.min()
    == 1
)

assert (
    repetition_counts.max()
    == 1
)

print(
    "✓ Every recording has a unique metadata combination."
)


# ============================================================
# 17. SUBJECT × ORIENTATION × GESTURE CHECK
# ============================================================

print("\n[13] SUBJECT × ORIENTATION × GESTURE VALIDATION")
print("-" * 90)

group_counts = (
    master_df
    .groupby(
        [
            "subject_id",
            "orientation_id",
            "gesture_id"
        ]
    )
    .size()
)

print(
    "Expected combinations:",
    EXPECTED_SUBJECTS
    * EXPECTED_ORIENTATIONS
    * EXPECTED_GESTURES
)

print(
    "Actual combinations:",
    len(group_counts)
)

print(
    "Minimum repetitions:",
    group_counts.min()
)

print(
    "Maximum repetitions:",
    group_counts.max()
)

assert (
    len(group_counts)
    ==
    EXPECTED_SUBJECTS
    * EXPECTED_ORIENTATIONS
    * EXPECTED_GESTURES
)

assert (
    group_counts.min()
    == EXPECTED_REPETITIONS
)

assert (
    group_counts.max()
    == EXPECTED_REPETITIONS
)

print(
    "✓ Every subject/orientation/gesture has exactly 5 repetitions."
)


# ============================================================
# 18. DUPLICATE METADATA CHECK
# ============================================================

print("\n[14] DUPLICATE METADATA CHECK")
print("-" * 90)

metadata_keys = [
    "subject_id",
    "orientation_id",
    "gesture_id",
    "repetition"
]

duplicate_count = (
    master_df
    .duplicated(
        subset=metadata_keys
    )
    .sum()
)

print(
    "Duplicate metadata combinations:",
    duplicate_count
)

assert (
    duplicate_count == 0
)

print(
    "✓ No duplicate subject/orientation/gesture/repetition combinations."
)


# ============================================================
# 19. DUPLICATE FILEPATH CHECK
# ============================================================

print("\n[15] DUPLICATE FILEPATH CHECK")
print("-" * 90)

filepath_duplicates = (
    master_df[
        "filepath"
    ]
    .duplicated()
    .sum()
)

print(
    "Duplicate filepaths:",
    filepath_duplicates
)

assert (
    filepath_duplicates == 0
)

print(
    "✓ Every filepath is unique."
)


# ============================================================
# 20. FILE EXISTENCE CHECK
# ============================================================

print("\n[16] FILE EXISTENCE CHECK")
print("-" * 90)

missing_files = []

for filepath in master_df[
    "filepath"
]:

    if not Path(filepath).exists():

        missing_files.append(
            filepath
        )

print(
    "Missing files:",
    len(missing_files)
)

assert (
    len(missing_files) == 0
)

print(
    "✓ All referenced files exist."
)


# ============================================================
# 21. EXPECTED DURATION
# ============================================================

print("\n[17] RECORDING DURATION")
print("-" * 90)

duration = (
    EXPECTED_SAMPLES /
    EXPECTED_SAMPLING_RATE
)

print(
    "Samples:",
    EXPECTED_SAMPLES
)

print(
    "Sampling rate:",
    EXPECTED_SAMPLING_RATE,
    "Hz"
)

print(
    f"Recording duration: {duration:.6f} seconds"
)

print(
    f"Recording duration: {duration:.3f} seconds"
)


# ============================================================
# 22. FINAL MASTER TABLE SUMMARY
# ============================================================

print("\n[18] FINAL MASTER TABLE SUMMARY")
print("-" * 90)

summary = {
    "total_recordings":
        len(master_df),

    "subjects":
        master_df["subject_id"].nunique(),

    "orientations":
        master_df["orientation_id"].nunique(),

    "gestures":
        master_df["gesture_id"].nunique(),

    "repetitions":
        master_df["repetition"].nunique(),

    "channels":
        EXPECTED_CHANNELS,

    "samples_per_channel":
        EXPECTED_SAMPLES,

    "sampling_rate_hz":
        EXPECTED_SAMPLING_RATE,

    "duration_seconds":
        duration
}

summary_df = pd.DataFrame(
    summary.items(),
    columns=[
        "property",
        "value"
    ]
)

display(
    summary_df
)


# ============================================================
# 23. SAVE MASTER METADATA
# ============================================================

print("\n[19] SAVING MASTER METADATA")
print("-" * 90)

master_csv_path = (
    METADATA_DIR
    / "FORS_EMG_MASTER_METADATA.csv"
)

master_parquet_path = (
    METADATA_DIR
    / "FORS_EMG_MASTER_METADATA.parquet"
)

master_df.to_csv(
    master_csv_path,
    index=False
)

master_df.to_parquet(
    master_parquet_path,
    index=False
)

print(
    "CSV saved:"
)

print(
    master_csv_path
)

print(
    "\nParquet saved:"
)

print(
    master_parquet_path
)


# ============================================================
# 24. SAVE DATASET SUMMARY JSON
# ============================================================

summary_json_path = (
    METADATA_DIR
    / "FORS_EMG_DATASET_SUMMARY.json"
)

with open(
    summary_json_path,
    "w"
) as f:

    json.dump(
        summary,
        f,
        indent=4
    )

print(
    "\nSummary JSON saved:"
)

print(
    summary_json_path
)


# ============================================================
# 25. FINAL ASSERTIONS
# ============================================================

print("\n[20] FINAL INTEGRITY ASSERTIONS")
print("-" * 90)

assert len(master_df) == 3420

assert master_df["subject_id"].nunique() == 19

assert master_df["orientation_id"].nunique() == 3

assert master_df["gesture_id"].nunique() == 12

assert master_df["repetition"].nunique() == 5

assert (
    master_df
    .groupby(
        ["subject_id", "orientation_id"]
    )
    .size()
    .eq(60)
    .all()
)

assert (
    master_df
    .groupby(
        [
            "subject_id",
            "orientation_id",
            "gesture_id"
        ]
    )
    .size()
    .eq(5)
    .all()
)

assert (
    master_df
    .duplicated(
        subset=metadata_keys
    )
    .sum()
    == 0
)

assert (
    master_df["filepath"]
    .duplicated()
    .sum()
    == 0
)

print(
    "✓ 3420 recordings verified."
)

print(
    "✓ 19 subjects verified."
)

print(
    "✓ 3 orientations verified."
)

print(
    "✓ 12 gestures verified."
)

print(
    "✓ 5 repetitions per subject/orientation/gesture verified."
)

print(
    "✓ No duplicate metadata combinations."
)

print(
    "✓ No duplicate filepaths."
)

print(
    "✓ All referenced files exist."
)


# ============================================================
# FINAL STATUS
# ============================================================

print("\n" + "=" * 90)
print("STEP 4 COMPLETED SUCCESSFULLY")
print("=" * 90)

==========================================================================================
FORS-EMG RESEARCH PROJECT
STEP 4 — FINAL MASTER METADATA TABLE
==========================================================================================

[1] EXPECTED DATASET STRUCTURE
------------------------------------------------------------------------------------------
Subjects      : 19
Orientations  : 3
Gestures      : 12
Repetitions   : 5
Channels      : 8
Samples       : 8000
Sampling rate : 985 Hz
Expected total recordings: 3420

[2] GESTURE DEFINITIONS
------------------------------------------------------------------------------------------
Gesture classes: 12
00 | Thumb_UP             | TU
01 | Index                | IDX
02 | Right_Angle          | RA
03 | Peace                | PCE
04 | Index_Little         | IL
05 | Thumb_Little         | TL
06 | Hand_Close           | HC
07 | Hand_Open            | HO
08 | Wrist_Extension      | WE
09 | Wrist_Flexion        | WF
10 | Ulner_Deviation      | UD
11 | Radial_Deviation     | RD

[3] ORIENTATION DEFINITIONS
------------------------------------------------------------------------------------------
0 | pronation
1 | rest
2 | supination

[4] FINDING RECORDINGS
------------------------------------------------------------------------------------------
MAT files found: 3420

[5] PARSING FILENAMES
------------------------------------------------------------------------------------------

[6] MASTER DATAFRAME
------------------------------------------------------------------------------------------
Successfully parsed: 3420
Parsing errors: 0

First 30 metadata records:
------------------------------------------------------------------------------------------

,subject,subject_id,orientation,orientation_id,gesture,gesture_id,gesture_acronym,repetition,filename,filepath,sampling_rate_hz,n_channels,n_samples,duration_seconds
0,Subject1,1,pronation,0,Thumb_UP,0,TU,1,Thumb_UP-1.mat,/kaggle/working/fors_emg_research/raw_data/kag...,985,8,8000,8.121827
1,Subject1,1,pronation,0,Thumb_UP,0,TU,2,Thumb_UP-2.mat,/kaggle/working/fors_emg_research/raw_data/kag...,985,8,8000,8.121827
2,Subject1,1,pronation,0,Thumb_UP,0,TU,3,Thumb_UP-3.mat,/kaggle/working/fors_emg_research/raw_data/kag...,985,8,8000,8.121827
3,Subject1,1,pronation,0,Thumb_UP,0,TU,4,Thumb_UP-4.mat,/kaggle/working/fors_emg_research/raw_data/kag...,985,8,8000,8.121827
4,Subject1,1,pronation,0,Thumb_UP,0,TU,5,Thumb_UP-5.mat,/kaggle/working/fors_emg_research/raw_data/kag...,985,8,8000,8.121827
5,Subject1,1,pronation,0,Index,1,IDX,1,Index-1.mat,/kaggle/working/fors_emg_research/raw_data/kag...,985,8,8000,8.121827
6,Subject1,1,pronation,0,Index,1,IDX,2,Index-2.mat,/kaggle/working/fors_emg_research/raw_data/kag...,985,8,8000,8.121827
7,Subject1,1,pronation,0,Index,1,IDX,3,Index-3.mat,/kaggle/working/fors_emg_research/raw_data/kag...,985,8,8000,8.121827
8,Subject1,1,pronation,0,Index,1,IDX,4,Index-4.mat,/kaggle/working/fors_emg_research/raw_data/kag...,985,8,8000,8.121827
9,Subject1,1,pronation,0,Index,1,IDX,5,Index-5.mat,/kaggle/working/fors_emg_research/raw_data/kag...,985,8,8000,8.121827
10,Subject1,1,pronation,0,Right_Angle,2,RA,1,Right_Angle-1.mat,/kaggle/working/fors_emg_research/raw_data/kag...,985,8,8000,8.121827
11,Subject1,1,pronation,0,Right_Angle,2,RA,2,Right_Angle-2.mat,/kaggle/working/fors_emg_research/raw_data/kag...,985,8,8000,8.121827
12,Subject1,1,pronation,0,Right_Angle,2,RA,3,Right_Angle-3.mat,/kaggle/working/fors_emg_research/raw_data/kag...,985,8,8000,8.121827
13,Subject1,1,pronation,0,Right_Angle,2,RA,4,Right_Angle-4.mat,/kaggle/working/fors_emg_research/raw_data/kag...,985,8,8000,8.121827
14,Subject1,1,pronation,0,Right_Angle,2,RA,5,Right_Angle-5.mat,/kaggle/working/fors_emg_research/raw_data/kag...,985,8,8000,8.121827
15,Subject1,1,pronation,0,Peace,3,PCE,1,Peace-1.mat,/kaggle/working/fors_emg_research/raw_data/kag...,985,8,8000,8.121827
16,Subject1,1,pronation,0,Peace,3,PCE,2,Peace-2.mat,/kaggle/working/fors_emg_research/raw_data/kag...,985,8,8000,8.121827
17,Subject1,1,pronation,0,Peace,3,PCE,3,Peace-3.mat,/kaggle/working/fors_emg_research/raw_data/kag...,985,8,8000,8.121827
18,Subject1,1,pronation,0,Peace,3,PCE,4,Peace-4.mat,/kaggle/working/fors_emg_research/raw_data/kag...,985,8,8000,8.121827
19,Subject1,1,pronation,0,Peace,3,PCE,5,Peace-5.mat,/kaggle/working/fors_emg_research/raw_data/kag...,985,8,8000,8.121827
20,Subject1,1,pronation,0,Index_Little,4,IL,1,Index_Little-1.mat,/kaggle/working/fors_emg_research/raw_data/kag...,985,8,8000,8.121827
21,Subject1,1,pronation,0,Index_Little,4,IL,2,Index_Little-2.mat,/kaggle/working/fors_emg_research/raw_data/kag...,985,8,8000,8.121827
22,Subject1,1,pronation,0,Index_Little,4,IL,3,Index_Little-3.mat,/kaggle/working/fors_emg_research/raw_data/kag...,985,8,8000,8.121827
23,Subject1,1,pronation,0,Index_Little,4,IL,4,Index_Little-4.mat,/kaggle/working/fors_emg_research/raw_data/kag...,985,8,8000,8.121827
24,Subject1,1,pronation,0,Index_Little,4,IL,5,Index_Little-5.mat,/kaggle/working/fors_emg_research/raw_data/kag...,985,8,8000,8.121827
25,Subject1,1,pronation,0,Thumb_Little,5,TL,1,Thumb_Little-1.mat,/kaggle/working/fors_emg_research/raw_data/kag...,985,8,8000,8.121827
26,Subject1,1,pronation,0,Thumb_Little,5,TL,2,Thumb_Little-2.mat,/kaggle/working/fors_emg_research/raw_data/kag...,985,8,8000,8.121827
27,Subject1,1,pronation,0,Thumb_Little,5,TL,3,Thumb_Little-3.mat,/kaggle/working/fors_emg_research/raw_data/kag...,985,8,8000,8.121827
28,Subject1,1,pronation,0,Thumb_Little,5,TL,4,Thumb_Little-4.mat,/kaggle/working/fors_emg_research/raw_data/kag...,985,8,8000,8.121827
29,Subject1,1,pronation,0,Thumb_Little,5,TL,5,Thumb_Little-5.mat,/kaggle/working/fors_emg_research/raw_data/kag...,985,8,8000,8.121827

[7] DATAFRAME INFORMATION
------------------------------------------------------------------------------------------
Shape: (3420, 14)

Columns:
01. subject
02. subject_id
03. orientation
04. orientation_id
05. gesture
06. gesture_id
07. gesture_acronym
08. repetition
09. filename
10. filepath
11. sampling_rate_hz
12. n_channels
13. n_samples
14. duration_seconds

[8] TOTAL RECORDING VALIDATION
------------------------------------------------------------------------------------------
Expected: 3420
Actual  : 3420
✓ Total recording count verified.

[9] SUBJECT VALIDATION
------------------------------------------------------------------------------------------
subject_id
1     180
2     180
3     180
4     180
5     180
6     180
7     180
8     180
9     180
10    180
11    180
12    180
13    180
14    180
15    180
16    180
17    180
18    180
19    180
dtype: int64

✓ 19 subjects × 180 recordings.

[10] ORIENTATION VALIDATION
------------------------------------------------------------------------------------------

             recordings
orientation
pronation          1140
rest               1140
supination         1140

✓ All orientations contain 1,140 recordings.

[11] GESTURE VALIDATION
------------------------------------------------------------------------------------------

                             recordings
gesture_id gesture
0          Thumb_UP                 285
1          Index                    285
2          Right_Angle              285
3          Peace                    285
4          Index_Little             285
5          Thumb_Little             285
6          Hand_Close               285
7          Hand_Open                285
8          Wrist_Extension          285
9          Wrist_Flexion            285
10         Ulner_Deviation          285
11         Radial_Deviation         285

Expected recordings per gesture: 285
✓ Every gesture contains exactly 285 recordings.

[12] REPETITION VALIDATION
------------------------------------------------------------------------------------------
Number of unique subject × orientation × gesture × repetition combinations: 3420
Minimum count: 1
Maximum count: 1
✓ Every recording has a unique metadata combination.

[13] SUBJECT × ORIENTATION × GESTURE VALIDATION
------------------------------------------------------------------------------------------
Expected combinations: 684
Actual combinations: 684
Minimum repetitions: 5
Maximum repetitions: 5
✓ Every subject/orientation/gesture has exactly 5 repetitions.

[14] DUPLICATE METADATA CHECK
------------------------------------------------------------------------------------------
Duplicate metadata combinations: 0
✓ No duplicate subject/orientation/gesture/repetition combinations.

[15] DUPLICATE FILEPATH CHECK
------------------------------------------------------------------------------------------
Duplicate filepaths: 0
✓ Every filepath is unique.

[16] FILE EXISTENCE CHECK
------------------------------------------------------------------------------------------
Missing files: 0
✓ All referenced files exist.

[17] RECORDING DURATION
------------------------------------------------------------------------------------------
Samples: 8000
Sampling rate: 985 Hz
Recording duration: 8.121827 seconds
Recording duration: 8.122 seconds

[18] FINAL MASTER TABLE SUMMARY
------------------------------------------------------------------------------------------

              property        value
0     total_recordings  3420.000000
1             subjects    19.000000
2         orientations     3.000000
3             gestures    12.000000
4          repetitions     5.000000
5             channels     8.000000
6  samples_per_channel  8000.000000
7     sampling_rate_hz   985.000000
8     duration_seconds     8.121827

[19] SAVING MASTER METADATA
------------------------------------------------------------------------------------------
CSV saved:
/kaggle/working/fors_emg_research/processed_data/FORS_EMG_MASTER_METADATA.csv

Parquet saved:
/kaggle/working/fors_emg_research/processed_data/FORS_EMG_MASTER_METADATA.parquet

Summary JSON saved:
/kaggle/working/fors_emg_research/processed_data/FORS_EMG_DATASET_SUMMARY.json

[20] FINAL INTEGRITY ASSERTIONS
------------------------------------------------------------------------------------------
✓ 3420 recordings verified.
✓ 19 subjects verified.
✓ 3 orientations verified.
✓ 12 gestures verified.
✓ 5 repetitions per subject/orientation/gesture verified.
✓ No duplicate metadata combinations.
✓ No duplicate filepaths.
✓ All referenced files exist.

==========================================================================================
STEP 4 COMPLETED SUCCESSFULLY
==========================================================================================

In [ ]:
# ============================================================
# FORS-EMG RESEARCH PROJECT
# STEP 5 — RAW EMG SIGNAL QUALITY ANALYSIS
# ============================================================

import os
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from scipy.io import loadmat
from scipy import signal

warnings.filterwarnings("ignore")


# ============================================================
# 1. PROJECT PATHS
# ============================================================

PROJECT_ROOT = Path(
    "/kaggle/working/fors_emg_research"
)

METADATA_DIR = (
    PROJECT_ROOT
    / "processed_data"
)

MASTER_METADATA_PATH = (
    METADATA_DIR
    / "FORS_EMG_MASTER_METADATA.csv"
)

SIGNAL_QC_DIR = (
    METADATA_DIR
    / "signal_quality"
)

SIGNAL_QC_DIR.mkdir(
    parents=True,
    exist_ok=True
)


# ============================================================
# 2. LOAD MASTER METADATA
# ============================================================

print("=" * 90)
print("FORS-EMG RESEARCH PROJECT")
print("STEP 5 — RAW EMG SIGNAL QUALITY ANALYSIS")
print("=" * 90)

print("\n[1] LOADING MASTER METADATA")
print("-" * 90)

if "master_df" not in globals():

    print(
        "master_df not found in memory."
    )

    if not MASTER_METADATA_PATH.exists():

        raise FileNotFoundError(
            f"Master metadata not found:\n"
            f"{MASTER_METADATA_PATH}\n"
            f"Please rerun Step 4."
        )

    master_df = pd.read_csv(
        MASTER_METADATA_PATH
    )

print(
    "Master metadata shape:",
    master_df.shape
)

print(
    "Total recordings:",
    len(master_df)
)


# ============================================================
# 3. DATASET CONSTANTS
# ============================================================

EXPECTED_RECORDINGS = 3420
EXPECTED_SUBJECTS = 19
EXPECTED_ORIENTATIONS = 3
EXPECTED_GESTURES = 12
EXPECTED_CHANNELS = 8
EXPECTED_SAMPLES = 8000
EXPECTED_FS = 985


# ============================================================
# 4. MATLAB SIGNAL LOADER
# ============================================================

print("\n[2] DEFINING SIGNAL LOADER")
print("-" * 90)


def load_emg_signal(filepath):
    """
    Load the EMG signal from a FORS-EMG MATLAB file.

    Expected MATLAB structure:
        value -> ndarray of shape (8, 8000)

    Standardized output:
        ndarray of shape (8000, 8)
    """

    mat = loadmat(
        filepath
    )

    # --------------------------------------------------------
    # Find numeric 2-D arrays
    # --------------------------------------------------------

    candidates = []

    for key, value in mat.items():

        if key.startswith("__"):
            continue

        if isinstance(
            value,
            np.ndarray
        ):

            if (
                value.ndim == 2
                and np.issubdtype(
                    value.dtype,
                    np.number
                )
            ):

                candidates.append(
                    (
                        key,
                        value
                    )
                )

    # --------------------------------------------------------
    # Find expected EMG array
    # --------------------------------------------------------

    selected = None

    for key, value in candidates:

        shape = value.shape

        if shape == (
            EXPECTED_CHANNELS,
            EXPECTED_SAMPLES
        ):

            selected = value
            break

        if shape == (
            EXPECTED_SAMPLES,
            EXPECTED_CHANNELS
        ):

            selected = value
            break

    if selected is None:

        raise ValueError(
            "Could not identify expected EMG "
            "signal array in file:\n"
            f"{filepath}\n"
            f"Available numeric arrays: "
            f"{[(k, v.shape) for k, v in candidates]}"
        )

    signal_array = np.asarray(
        selected,
        dtype=np.float64
    )

    # --------------------------------------------------------
    # Standardize orientation
    # --------------------------------------------------------

    if signal_array.shape == (
        EXPECTED_CHANNELS,
        EXPECTED_SAMPLES
    ):

        signal_array = signal_array.T

    elif signal_array.shape == (
        EXPECTED_SAMPLES,
        EXPECTED_CHANNELS
    ):

        pass

    else:

        raise ValueError(
            f"Unexpected signal shape: "
            f"{signal_array.shape}"
        )

    return signal_array


# ============================================================
# 5. TEST SIGNAL LOADER
# ============================================================

print("\n[3] TESTING SIGNAL LOADER")
print("-" * 90)

test_path = master_df.iloc[0][
    "filepath"
]

test_signal = load_emg_signal(
    test_path
)

print(
    "Test file:",
    test_path
)

print(
    "Loaded signal shape:",
    test_signal.shape
)

print(
    "Data type:",
    test_signal.dtype
)

assert test_signal.shape == (
    EXPECTED_SAMPLES,
    EXPECTED_CHANNELS
)

print(
    "✓ Signal standardized to "
    "(8000, 8)"
)


# ============================================================
# 6. BASIC SIGNAL VALIDITY CHECK
# ============================================================

print("\n[4] FIRST RECORDING VALIDITY")
print("-" * 90)

print(
    "NaN count:",
    np.isnan(test_signal).sum()
)

print(
    "Inf count:",
    np.isinf(test_signal).sum()
)

print(
    "Minimum:",
    np.min(test_signal)
)

print(
    "Maximum:",
    np.max(test_signal)
)

print(
    "Mean:",
    np.mean(test_signal)
)

print(
    "Std:",
    np.std(test_signal)
)

assert not np.isnan(
    test_signal
).any()

assert not np.isinf(
    test_signal
).any()

print(
    "✓ First recording contains no NaN/Inf."
)


# ============================================================
# 7. CHANNEL-LEVEL STATISTICS FUNCTION
# ============================================================

def calculate_channel_statistics(
    x,
    fs=EXPECTED_FS
):

    """
    Calculate descriptive statistics
    for each EMG channel.
    """

    results = []

    for ch in range(
        x.shape[1]
    ):

        s = x[:, ch]

        minimum = np.min(s)

        maximum = np.max(s)

        mean = np.mean(s)

        std = np.std(s)

        rms = np.sqrt(
            np.mean(
                np.square(s)
            )
        )

        peak_to_peak = (
            maximum - minimum
        )

        abs_mean = np.mean(
            np.abs(s)
        )

        energy = np.sum(
            np.square(s)
        )

        zero_crossings = np.sum(
            np.diff(
                np.signbit(s)
            ).astype(int)
        )

        # ----------------------------------------------------
        # Constant / near-zero detection
        # ----------------------------------------------------

        near_zero_fraction = np.mean(
            np.isclose(
                s,
                0,
                atol=1e-12
            )
        )

        results.append(
            {
                "channel":
                    ch + 1,

                "min":
                    minimum,

                "max":
                    maximum,

                "mean":
                    mean,

                "std":
                    std,

                "rms":
                    rms,

                "abs_mean":
                    abs_mean,

                "peak_to_peak":
                    peak_to_peak,

                "energy":
                    energy,

                "zero_crossings":
                    zero_crossings,

                "near_zero_fraction":
                    near_zero_fraction
            }
        )

    return pd.DataFrame(
        results
    )


# ============================================================
# 8. FIRST RECORDING CHANNEL STATISTICS
# ============================================================

print("\n[5] FIRST RECORDING — CHANNEL STATISTICS")
print("-" * 90)

first_channel_stats = (
    calculate_channel_statistics(
        test_signal
    )
)

display(
    first_channel_stats
)


# ============================================================
# 9. RAW WAVEFORM — FIRST RECORDING
# ============================================================

print("\n[6] RAW WAVEFORM — FIRST RECORDING")
print("-" * 90)

time = (
    np.arange(
        EXPECTED_SAMPLES
    )
    / EXPECTED_FS
)

fig, axes = plt.subplots(
    EXPECTED_CHANNELS,
    1,
    figsize=(16, 18),
    sharex=True
)

for ch in range(
    EXPECTED_CHANNELS
):

    axes[ch].plot(
        time,
        test_signal[:, ch],
        linewidth=0.7
    )

    axes[ch].set_ylabel(
        f"Ch {ch + 1}"
    )

    axes[ch].grid(
        alpha=0.25
    )

axes[-1].set_xlabel(
    "Time (seconds)"
)

fig.suptitle(
    "FORS-EMG Raw Signal — First Recording",
    fontsize=16
)

plt.tight_layout()

waveform_path = (
    SIGNAL_QC_DIR
    / "first_recording_raw_waveform.png"
)

plt.savefig(
    waveform_path,
    dpi=200,
    bbox_inches="tight"
)

plt.show()

print(
    "Saved:",
    waveform_path
)


# ============================================================
# 10. CHANNEL DISTRIBUTION
# ============================================================

print("\n[7] CHANNEL AMPLITUDE DISTRIBUTION")
print("-" * 90)

fig = plt.figure(
    figsize=(15, 8)
)

plt.boxplot(
    [
        test_signal[:, ch]
        for ch in range(
            EXPECTED_CHANNELS
        )
    ],
    labels=[
        f"Channel {i}"
        for i in range(
            1,
            EXPECTED_CHANNELS + 1
        )
    ],
    showfliers=True
)

plt.xlabel(
    "EMG Channel"
)

plt.ylabel(
    "Amplitude"
)

plt.title(
    "Raw EMG Channel Amplitude Distribution"
)

plt.grid(
    axis="y",
    alpha=0.25
)

plt.tight_layout()

boxplot_path = (
    SIGNAL_QC_DIR
    / "first_recording_channel_boxplot.png"
)

plt.savefig(
    boxplot_path,
    dpi=200,
    bbox_inches="tight"
)

plt.show()


# ============================================================
# 11. SIGNAL QUALITY SAMPLE ACROSS DATASET
# ============================================================

print("\n[8] DATASET-WIDE SIGNAL QUALITY SAMPLING")
print("-" * 90)

"""
We analyze every recording for basic signal-quality
statistics, but we do not store the complete raw signal
for all recordings in RAM.

This is memory-safe for Kaggle.
"""

quality_records = []

failed_files = []

for idx, row in master_df.iterrows():

    filepath = row["filepath"]

    try:

        x = load_emg_signal(
            filepath
        )

        # ----------------------------------------------------
        # Global validity
        # ----------------------------------------------------

        nan_count = int(
            np.isnan(x).sum()
        )

        inf_count = int(
            np.isinf(x).sum()
        )

        # ----------------------------------------------------
        # Replace only for numerical statistics if invalid
        # values exist.
        #
        # IMPORTANT:
        # We are NOT modifying the source signal.
        # ----------------------------------------------------

        finite_x = x[
            np.isfinite(x)
        ]

        if finite_x.size == 0:

            raise ValueError(
                "No finite signal values."
            )

        global_min = float(
            np.min(finite_x)
        )

        global_max = float(
            np.max(finite_x)
        )

        global_mean = float(
            np.mean(finite_x)
        )

        global_std = float(
            np.std(finite_x)
        )

        global_rms = float(
            np.sqrt(
                np.mean(
                    np.square(
                        finite_x
                    )
                )
            )
        )

        global_energy = float(
            np.sum(
                np.square(
                    finite_x
                )
            )
        )

        # ----------------------------------------------------
        # Channel statistics
        # ----------------------------------------------------

        channel_std = np.std(
            x,
            axis=0
        )

        channel_rms = np.sqrt(
            np.mean(
                np.square(x),
                axis=0
            )
        )

        channel_ptp = (
            np.ptp(
                x,
                axis=0
            )
        )

        # ----------------------------------------------------
        # Zero / constant channels
        # ----------------------------------------------------

        zero_channels = int(
            np.sum(
                np.all(
                    np.isclose(
                        x,
                        0,
                        atol=1e-12
                    ),
                    axis=0
                )
            )
        )

        constant_channels = int(
            np.sum(
                channel_std
                < 1e-12
            )
        )

        # ----------------------------------------------------
        # Record
        # ----------------------------------------------------

        quality_records.append(
            {
                "subject":
                    row["subject"],

                "subject_id":
                    row["subject_id"],

                "orientation":
                    row["orientation"],

                "gesture":
                    row["gesture"],

                "gesture_id":
                    row["gesture_id"],

                "repetition":
                    row["repetition"],

                "filename":
                    row["filename"],

                "filepath":
                    filepath,

                "nan_count":
                    nan_count,

                "inf_count":
                    inf_count,

                "global_min":
                    global_min,

                "global_max":
                    global_max,

                "global_mean":
                    global_mean,

                "global_std":
                    global_std,

                "global_rms":
                    global_rms,

                "global_energy":
                    global_energy,

                "zero_channels":
                    zero_channels,

                "constant_channels":
                    constant_channels,

                "max_channel_std":
                    float(
                        np.max(
                            channel_std
                        )
                    ),

                "min_channel_std":
                    float(
                        np.min(
                            channel_std
                        )
                    ),

                "max_channel_rms":
                    float(
                        np.max(
                            channel_rms
                        )
                    ),

                "min_channel_rms":
                    float(
                        np.min(
                            channel_rms
                        )
                    ),

                "max_channel_ptp":
                    float(
                        np.max(
                            channel_ptp
                        )
                    ),

                "min_channel_ptp":
                    float(
                        np.min(
                            channel_ptp
                        )
                    )
            }
        )

    except Exception as e:

        failed_files.append(
            {
                "filepath":
                    filepath,

                "error":
                    str(e)
            }
        )


print(
    "Successfully analyzed:",
    len(quality_records)
)

print(
    "Failed recordings:",
    len(failed_files)
)


# ============================================================
# 12. CREATE QUALITY DATAFRAME
# ============================================================

quality_df = pd.DataFrame(
    quality_records
)

print(
    "\nQuality dataframe shape:",
    quality_df.shape
)

if len(failed_files) > 0:

    print(
        "\nFailed files:"
    )

    display(
        pd.DataFrame(
            failed_files
        )
    )

    raise RuntimeError(
        "Some recordings failed signal-quality analysis."
    )


assert len(
    quality_df
) == EXPECTED_RECORDINGS


# ============================================================
# 13. DATASET-WIDE VALIDITY
# ============================================================

print("\n[9] DATASET-WIDE VALIDITY")
print("-" * 90)

print(
    "Total recordings:",
    len(quality_df)
)

print(
    "Recordings containing NaN:",
    (
        quality_df[
            "nan_count"
        ] > 0
    ).sum()
)

print(
    "Recordings containing Inf:",
    (
        quality_df[
            "inf_count"
        ] > 0
    ).sum()
)

print(
    "Recordings with zero channels:",
    (
        quality_df[
            "zero_channels"
        ] > 0
    ).sum()
)

print(
    "Recordings with constant channels:",
    (
        quality_df[
            "constant_channels"
        ] > 0
    ).sum()
)


# ============================================================
# 14. DATASET STATISTICAL SUMMARY
# ============================================================

print("\n[10] DATASET SIGNAL STATISTICS")
print("-" * 90)

summary_columns = [
    "global_min",
    "global_max",
    "global_mean",
    "global_std",
    "global_rms",
    "global_energy",
    "max_channel_std",
    "min_channel_std",
    "max_channel_rms",
    "min_channel_rms",
    "max_channel_ptp",
    "min_channel_ptp"
]

dataset_statistics = (
    quality_df[
        summary_columns
    ]
    .describe()
    .T
)

display(
    dataset_statistics
)


# ============================================================
# 15. SIGNAL STATISTICS BY ORIENTATION
# ============================================================

print("\n[11] SIGNAL STATISTICS BY ORIENTATION")
print("-" * 90)

orientation_statistics = (
    quality_df
    .groupby(
        "orientation"
    )[
        [
            "global_std",
            "global_rms",
            "global_energy"
        ]
    ]
    .agg(
        [
            "mean",
            "std",
            "min",
            "max"
        ]
    )
)

display(
    orientation_statistics
)


# ============================================================
# 16. SIGNAL STATISTICS BY GESTURE
# ============================================================

print("\n[12] SIGNAL STATISTICS BY GESTURE")
print("-" * 90)

gesture_statistics = (
    quality_df
    .groupby(
        [
            "gesture_id",
            "gesture"
        ]
    )[
        [
            "global_std",
            "global_rms",
            "global_energy"
        ]
    ]
    .agg(
        [
            "mean",
            "std",
            "min",
            "max"
        ]
    )
)

display(
    gesture_statistics
)


# ============================================================
# 17. GLOBAL RMS DISTRIBUTION
# ============================================================

print("\n[13] GLOBAL RMS DISTRIBUTION")
print("-" * 90)

plt.figure(
    figsize=(12, 6)
)

plt.hist(
    quality_df[
        "global_rms"
    ],
    bins=50
)

plt.xlabel(
    "Global RMS"
)

plt.ylabel(
    "Number of recordings"
)

plt.title(
    "FORS-EMG Recording-Level RMS Distribution"
)

plt.grid(
    axis="y",
    alpha=0.25
)

plt.tight_layout()

rms_distribution_path = (
    SIGNAL_QC_DIR
    / "global_rms_distribution.png"
)

plt.savefig(
    rms_distribution_path,
    dpi=200,
    bbox_inches="tight"
)

plt.show()


# ============================================================
# 18. GLOBAL ENERGY DISTRIBUTION
# ============================================================

print("\n[14] GLOBAL ENERGY DISTRIBUTION")
print("-" * 90)

plt.figure(
    figsize=(12, 6)
)

plt.hist(
    quality_df[
        "global_energy"
    ],
    bins=50
)

plt.xlabel(
    "Global signal energy"
)

plt.ylabel(
    "Number of recordings"
)

plt.title(
    "FORS-EMG Recording-Level Energy Distribution"
)

plt.grid(
    axis="y",
    alpha=0.25
)

plt.tight_layout()

energy_distribution_path = (
    SIGNAL_QC_DIR
    / "global_energy_distribution.png"
)

plt.savefig(
    energy_distribution_path,
    dpi=200,
    bbox_inches="tight"
)

plt.show()


# ============================================================
# 19. OUTLIER SCREENING — IQR METHOD
# ============================================================

print("\n[15] ROBUST OUTLIER SCREENING")
print("-" * 90)

"""
IMPORTANT:

This is only an OUTLIER SCREENING.

We are NOT deleting recordings.

IQR-based screening identifies unusual recordings that
will be investigated later.
"""

def iqr_outlier_mask(series):

    q1 = series.quantile(
        0.25
    )

    q3 = series.quantile(
        0.75
    )

    iqr = q3 - q1

    lower = (
        q1
        - 1.5 * iqr
    )

    upper = (
        q3
        + 1.5 * iqr
    )

    return (
        (series < lower)
        |
        (series > upper)
    )


quality_df[
    "rms_outlier"
] = iqr_outlier_mask(
    quality_df[
        "global_rms"
    ]
)

quality_df[
    "energy_outlier"
] = iqr_outlier_mask(
    quality_df[
        "global_energy"
    ]
)

print(
    "RMS outlier recordings:",
    quality_df[
        "rms_outlier"
    ].sum()
)

print(
    "Energy outlier recordings:",
    quality_df[
        "energy_outlier"
    ].sum()
)


# ============================================================
# 20. EXTREME RECORDINGS
# ============================================================

print("\n[16] HIGHEST-RMS RECORDINGS")
print("-" * 90)

highest_rms = (
    quality_df
    .sort_values(
        "global_rms",
        ascending=False
    )
    .head(10)
)

display(
    highest_rms[
        [
            "subject",
            "orientation",
            "gesture",
            "repetition",
            "global_rms",
            "global_std",
            "global_energy",
            "filepath"
        ]
    ]
)


print("\n[17] LOWEST-RMS RECORDINGS")
print("-" * 90)

lowest_rms = (
    quality_df
    .sort_values(
        "global_rms",
        ascending=True
    )
    .head(10)
)

display(
    lowest_rms[
        [
            "subject",
            "orientation",
            "gesture",
            "repetition",
            "global_rms",
            "global_std",
            "global_energy",
            "filepath"
        ]
    ]
)


# ============================================================
# 21. CHANNEL-WISE DATASET SUMMARY
# ============================================================

print("\n[18] CHANNEL-WISE DATASET SUMMARY")
print("-" * 90)

channel_dataset_stats = []

for channel in range(
    EXPECTED_CHANNELS
):

    channel_index = channel

    channel_values = []

    # --------------------------------------------------------
    # Analyze every recording for this channel
    # --------------------------------------------------------

    for filepath in master_df[
        "filepath"
    ]:

        x = load_emg_signal(
            filepath
        )

        channel_values.append(
            x[:, channel_index]
        )

    channel_values = np.concatenate(
        channel_values
    )

    channel_dataset_stats.append(
        {
            "channel":
                channel + 1,

            "mean":
                np.mean(
                    channel_values
                ),

            "std":
                np.std(
                    channel_values
                ),

            "rms":
                np.sqrt(
                    np.mean(
                        channel_values ** 2
                    )
                ),

            "min":
                np.min(
                    channel_values
                ),

            "max":
                np.max(
                    channel_values
                ),

            "peak_to_peak":
                np.ptp(
                    channel_values
                )
        }
    )

channel_dataset_stats_df = pd.DataFrame(
    channel_dataset_stats
)

display(
    channel_dataset_stats_df
)


# ============================================================
# 22. SAVE QUALITY RESULTS
# ============================================================

print("\n[19] SAVING QUALITY RESULTS")
print("-" * 90)

quality_csv_path = (
    SIGNAL_QC_DIR
    / "FORS_EMG_SIGNAL_QUALITY.csv"
)

quality_parquet_path = (
    SIGNAL_QC_DIR
    / "FORS_EMG_SIGNAL_QUALITY.parquet"
)

channel_stats_path = (
    SIGNAL_QC_DIR
    / "FORS_EMG_CHANNEL_SUMMARY.csv"
)

quality_df.to_csv(
    quality_csv_path,
    index=False
)

quality_df.to_parquet(
    quality_parquet_path,
    index=False
)

channel_dataset_stats_df.to_csv(
    channel_stats_path,
    index=False
)

print(
    "Saved:",
    quality_csv_path
)

print(
    "Saved:",
    quality_parquet_path
)

print(
    "Saved:",
    channel_stats_path
)


# ============================================================
# 23. FINAL STEP 5 SUMMARY
# ============================================================

print("\n" + "=" * 90)
print("STEP 5 — FINAL SUMMARY")
print("=" * 90)

print(
    f"""
Total recordings analyzed : {len(quality_df)}
Expected recordings       : {EXPECTED_RECORDINGS}

Subjects                  : {quality_df['subject_id'].nunique()}
Orientations              : {quality_df['orientation'].nunique()}
Gestures                  : {quality_df['gesture_id'].nunique()}

Channels per recording   : {EXPECTED_CHANNELS}
Samples per channel      : {EXPECTED_SAMPLES}
Sampling rate            : {EXPECTED_FS} Hz

Recordings with NaN      :
    {(quality_df['nan_count'] > 0).sum()}

Recordings with Inf      :
    {(quality_df['inf_count'] > 0).sum()}

Recordings with zero
channels                 :
    {(quality_df['zero_channels'] > 0).sum()}

Recordings with constant
channels                 :
    {(quality_df['constant_channels'] > 0).sum()}

RMS-screened outliers    :
    {quality_df['rms_outlier'].sum()}

Energy-screened outliers :
    {quality_df['energy_outlier'].sum()}
"""
)

print(
    "IMPORTANT:"
)

print(
    "No recordings have been deleted."
)

print(
    "No signal has been filtered."
)

print(
    "No normalization has been applied."
)

print(
    "No feature extraction has been performed."
)

print(
    "This step is purely RAW SIGNAL QUALITY ANALYSIS."
)

print(
    "\n✓ STEP 5 COMPLETED."
)

==========================================================================================
FORS-EMG RESEARCH PROJECT
STEP 5 — RAW EMG SIGNAL QUALITY ANALYSIS
==========================================================================================

[1] LOADING MASTER METADATA
------------------------------------------------------------------------------------------
Master metadata shape: (3420, 14)
Total recordings: 3420

[2] DEFINING SIGNAL LOADER
------------------------------------------------------------------------------------------

[3] TESTING SIGNAL LOADER
------------------------------------------------------------------------------------------
Test file: /kaggle/working/fors_emg_research/raw_data/kaggle_download/FORS-EMG Dataset/FORS-EMG Dataset/FORS-EMG/Subject1/pronation/Thumb_UP-1.mat
Loaded signal shape: (8000, 8)
Data type: float64
✓ Signal standardized to (8000, 8)

[4] FIRST RECORDING VALIDITY
------------------------------------------------------------------------------------------
NaN count: 0
Inf count: 0
Minimum: -1.083984375
Maximum: 0.7421875
Mean: 0.0015044403076171875
Std: 0.06643698876006351
✓ First recording contains no NaN/Inf.

[5] FIRST RECORDING — CHANNEL STATISTICS
------------------------------------------------------------------------------------------

,channel,min,max,mean,std,rms,abs_mean,peak_to_peak,energy,zero_crossings,near_zero_fraction
0,1,-0.209961,0.122070,0.000268,0.027564,0.027565,0.019579,0.332031,6.078744,2590,0.116000
1,2,-0.117188,0.063477,0.000119,0.017885,0.017886,0.013636,0.180664,2.559209,2803,0.118125
2,3,-1.083984,0.561523,0.001755,0.102657,0.102672,0.071344,1.645508,84.331846,2836,0.015250
3,4,-0.444336,0.292969,0.002654,0.051599,0.051667,0.036776,0.737305,21.355677,2321,0.061250
4,5,-0.371094,0.390625,0.001141,0.065864,0.065874,0.046580,0.761719,34.715056,2840,0.060375
5,6,-0.161133,0.209961,0.002718,0.036387,0.036489,0.026481,0.371094,10.651422,2932,0.041500
6,7,-0.507812,0.742188,0.000629,0.106409,0.106411,0.073597,1.250000,90.585876,2489,0.053000
7,8,-0.258789,0.527344,0.002751,0.063536,0.063595,0.046205,0.786133,32.354927,2936,0.053500

[6] RAW WAVEFORM — FIRST RECORDING
------------------------------------------------------------------------------------------

In [ ]:
# ============================================================
# STEP 6 — FINAL RECORDING METADATA CONSTRUCTION
# FORS-EMG RESEARCH PIPELINE
# ============================================================

import os
import re
import pandas as pd
import numpy as np

print("=" * 90)
print("[STEP 6] FINAL RECORDING METADATA CONSTRUCTION")
print("=" * 90)


# ============================================================
# 6.1 — CHECK EXISTING recordings_df
# ============================================================

print("\n[1] CHECKING EXISTING METADATA")
print("-" * 90)

if "recordings_df" not in globals():
    raise NameError(
        "recordings_df was not found. Please run the previous metadata "
        "construction step first."
    )

print(f"Existing dataframe shape: {recordings_df.shape}")
print(f"Existing columns: {list(recordings_df.columns)}")


# ============================================================
# 6.2 — STANDARDIZE BASIC COLUMNS
# ============================================================

print("\n[2] STANDARDIZING BASIC METADATA")
print("-" * 90)

recordings_df = recordings_df.copy()

recordings_df.columns = (
    recordings_df.columns
    .astype(str)
    .str.strip()
    .str.lower()
)

required_basic = [
    "subject",
    "orientation",
    "filename",
    "filepath"
]

missing_basic = [
    col for col in required_basic
    if col not in recordings_df.columns
]

if missing_basic:
    raise ValueError(
        f"Missing basic metadata columns: {missing_basic}"
    )

print("✓ Basic metadata columns verified.")


# ============================================================
# 6.3 — DEFINE OFFICIAL GESTURE MAPPING
# ============================================================

print("\n[3] DEFINING OFFICIAL GESTURE MAPPING")
print("-" * 90)

GESTURE_MAP = {
    0: "Thumb_UP",
    1: "Index",
    2: "Right_Angle",
    3: "Peace",
    4: "Index_Little",
    5: "Thumb_Little",
    6: "Hand_Close",
    7: "Hand_Open",
    8: "Wrist_Extension",
    9: "Wrist_Flexion",
    10: "Ulner_Deviation",
    11: "Radial_Deviation"
}

GESTURE_TO_ID = {
    gesture: gesture_id
    for gesture_id, gesture in GESTURE_MAP.items()
}

print("Gesture mapping:")

for gesture_id, gesture in GESTURE_MAP.items():
    print(f"{gesture_id:2d} -> {gesture}")


# ============================================================
# 6.4 — PARSE GESTURE + REPETITION FROM FILENAME
# ============================================================

print("\n[4] PARSING GESTURE AND REPETITION")
print("-" * 90)


def parse_filename(filename):
    """
    Parse filenames such as:

        Hand_Close-1.mat
        Index-3.mat
        Wrist_Extension-5.mat

    Returns:
        gesture
        repetition
    """

    filename = str(filename).strip()

    # Remove .mat extension
    stem = os.path.splitext(filename)[0]

    # Match the final "-number"
    match = re.match(r"^(.+)-(\d+)$", stem)

    if match is None:
        return None, None

    gesture = match.group(1)
    repetition = int(match.group(2))

    return gesture, repetition


parsed = recordings_df["filename"].apply(parse_filename)

recordings_df["gesture"] = parsed.apply(
    lambda x: x[0]
)

recordings_df["repetition"] = parsed.apply(
    lambda x: x[1]
)


# ============================================================
# 6.5 — CLEAN GESTURE NAMES
# ============================================================

recordings_df["gesture"] = (
    recordings_df["gesture"]
    .astype(str)
    .str.strip()
)

# Normalize accidental spaces
recordings_df["gesture"] = (
    recordings_df["gesture"]
    .str.replace(" ", "_", regex=False)
)


# ============================================================
# 6.6 — MAP GESTURE TO NUMERIC ID
# ============================================================

recordings_df["gesture_id"] = (
    recordings_df["gesture"]
    .map(GESTURE_TO_ID)
)


# ============================================================
# 6.7 — CHECK PARSING FAILURES
# ============================================================

print("\n[5] PARSING VALIDATION")
print("-" * 90)

missing_gesture = recordings_df["gesture"].isna().sum()
missing_repetition = recordings_df["repetition"].isna().sum()
missing_gesture_id = recordings_df["gesture_id"].isna().sum()

print(f"Missing gesture:      {missing_gesture}")
print(f"Missing repetition:   {missing_repetition}")
print(f"Missing gesture ID:   {missing_gesture_id}")


if (
    missing_gesture > 0
    or missing_repetition > 0
    or missing_gesture_id > 0
):
    print("\n❌ Parsing failed.")

    print(
        recordings_df[
            recordings_df["gesture_id"].isna()
        ][
            ["filename", "gesture", "repetition"]
        ].head(20)
    )

    raise ValueError(
        "Some filenames could not be mapped to the official gesture list."
    )

print("✓ All filenames successfully parsed.")


# ============================================================
# 6.8 — CONVERT DATA TYPES
# ============================================================

recordings_df["repetition"] = (
    recordings_df["repetition"]
    .astype(int)
)

recordings_df["gesture_id"] = (
    recordings_df["gesture_id"]
    .astype(int)
)


# ============================================================
# 6.9 — STANDARDIZE SUBJECT AND ORIENTATION
# ============================================================

recordings_df["subject"] = (
    recordings_df["subject"]
    .astype(str)
    .str.strip()
)

recordings_df["orientation"] = (
    recordings_df["orientation"]
    .astype(str)
    .str.strip()
    .str.lower()
)


# ============================================================
# 6.10 — SORT METADATA
# ============================================================

recordings_df = recordings_df.sort_values(
    by=[
        "subject",
        "orientation",
        "gesture_id",
        "repetition"
    ]
).reset_index(drop=True)


# ============================================================
# 6.11 — FINAL COLUMN ORDER
# ============================================================

recordings_df = recordings_df[
    [
        "subject",
        "orientation",
        "gesture",
        "gesture_id",
        "repetition",
        "filename",
        "filepath"
    ]
]


# ============================================================
# 6.12 — DISPLAY FINAL METADATA
# ============================================================

print("\n[6] FINAL METADATA STRUCTURE")
print("-" * 90)

print(f"Shape: {recordings_df.shape}")

print("\nColumns:")
print(list(recordings_df.columns))

print("\nFirst 15 records:")
display(
    recordings_df.head(15)
)


# ============================================================
# 6.13 — GESTURE DISTRIBUTION
# ============================================================

print("\n[7] GESTURE DISTRIBUTION")
print("-" * 90)

gesture_counts = (
    recordings_df
    .groupby(["gesture_id", "gesture"])
    .size()
    .reset_index(name="recordings")
    .sort_values("gesture_id")
)

display(gesture_counts)


# ============================================================
# 6.14 — REPETITION DISTRIBUTION
# ============================================================

print("\n[8] REPETITION DISTRIBUTION")
print("-" * 90)

repetition_counts = (
    recordings_df["repetition"]
    .value_counts()
    .sort_index()
)

print(repetition_counts)


# ============================================================
# 6.15 — SUBJECT DISTRIBUTION
# ============================================================

print("\n[9] SUBJECT DISTRIBUTION")
print("-" * 90)

subject_counts = (
    recordings_df["subject"]
    .value_counts()
    .sort_index()
)

display(subject_counts.to_frame("recordings"))


# ============================================================
# 6.16 — ORIENTATION DISTRIBUTION
# ============================================================

print("\n[10] ORIENTATION DISTRIBUTION")
print("-" * 90)

orientation_counts = (
    recordings_df["orientation"]
    .value_counts()
    .sort_index()
)

display(
    orientation_counts.to_frame("recordings")
)


# ============================================================
# 6.17 — SUBJECT × ORIENTATION
# ============================================================

print("\n[11] SUBJECT × ORIENTATION")
print("-" * 90)

subject_orientation = pd.crosstab(
    recordings_df["subject"],
    recordings_df["orientation"]
)

display(subject_orientation)


# ============================================================
# 6.18 — SUBJECT × GESTURE
# ============================================================

print("\n[12] SUBJECT × GESTURE")
print("-" * 90)

subject_gesture = pd.crosstab(
    recordings_df["subject"],
    recordings_df["gesture"]
)

display(subject_gesture)


# ============================================================
# 6.19 — EXACT RECORDING DESIGN VALIDATION
# ============================================================

print("\n[13] EXPERIMENTAL DESIGN VALIDATION")
print("-" * 90)

expected_recordings = 3420
expected_subjects = 19
expected_orientations = 3
expected_gestures = 12
expected_repetitions = 5

actual_recordings = len(recordings_df)
actual_subjects = recordings_df["subject"].nunique()
actual_orientations = recordings_df["orientation"].nunique()
actual_gestures = recordings_df["gesture"].nunique()

print(f"Expected recordings : {expected_recordings}")
print(f"Actual recordings   : {actual_recordings}")

print(f"\nExpected subjects   : {expected_subjects}")
print(f"Actual subjects     : {actual_subjects}")

print(f"\nExpected orientations: {expected_orientations}")
print(f"Actual orientations  : {actual_orientations}")

print(f"\nExpected gestures   : {expected_gestures}")
print(f"Actual gestures     : {actual_gestures}")


# ============================================================
# 6.20 — VERIFY 5 REPETITIONS
# ============================================================

print("\n[14] SUBJECT × ORIENTATION × GESTURE × REPETITION CHECK")
print("-" * 90)

combination_counts = (
    recordings_df
    .groupby(
        [
            "subject",
            "orientation",
            "gesture"
        ]
    )["repetition"]
    .nunique()
)

print(
    f"Minimum repetitions: "
    f"{combination_counts.min()}"
)

print(
    f"Maximum repetitions: "
    f"{combination_counts.max()}"
)

if (
    combination_counts.min() == 5
    and combination_counts.max() == 5
):
    print(
        "✓ Every subject/orientation/gesture "
        "combination has exactly 5 repetitions."
    )
else:
    print(
        "⚠ Repetition structure requires investigation."
    )


# ============================================================
# 6.21 — DUPLICATE METADATA CHECK
# ============================================================

print("\n[15] DUPLICATE METADATA CHECK")
print("-" * 90)

metadata_columns = [
    "subject",
    "orientation",
    "gesture",
    "repetition"
]

duplicate_metadata = recordings_df.duplicated(
    subset=metadata_columns
).sum()

print(
    f"Duplicate metadata combinations: "
    f"{duplicate_metadata}"
)

if duplicate_metadata == 0:
    print("✓ No duplicate metadata combinations.")
else:
    print(
        "❌ Duplicate metadata combinations detected."
    )


# ============================================================
# 6.22 — DUPLICATE FILEPATH CHECK
# ============================================================

print("\n[16] DUPLICATE FILEPATH CHECK")
print("-" * 90)

duplicate_paths = (
    recordings_df["filepath"]
    .duplicated()
    .sum()
)

print(f"Duplicate filepaths: {duplicate_paths}")

if duplicate_paths == 0:
    print("✓ No duplicate filepaths.")
else:
    print("❌ Duplicate filepaths detected.")


# ============================================================
# 6.23 — FILE EXISTENCE CHECK
# ============================================================

print("\n[17] FILE EXISTENCE CHECK")
print("-" * 90)

file_exists = recordings_df["filepath"].apply(
    os.path.isfile
)

missing_files = (~file_exists).sum()

print(f"Missing files: {missing_files}")

if missing_files == 0:
    print("✓ All referenced files exist.")
else:
    print("❌ Some referenced files do not exist.")


# ============================================================
# 6.24 — FINAL ASSERTIONS
# ============================================================

print("\n[18] FINAL STEP 6 ASSERTIONS")
print("=" * 90)

assert actual_recordings == expected_recordings
assert actual_subjects == expected_subjects
assert actual_orientations == expected_orientations
assert actual_gestures == expected_gestures
assert missing_gesture == 0
assert missing_repetition == 0
assert missing_gesture_id == 0
assert duplicate_metadata == 0
assert duplicate_paths == 0
assert missing_files == 0

print("✓ 3420 recordings verified.")
print("✓ 19 subjects verified.")
print("✓ 3 orientations verified.")
print("✓ 12 gestures verified.")
print("✓ 5 repetitions per subject/orientation/gesture verified.")
print("✓ No duplicate metadata combinations.")
print("✓ No duplicate filepaths.")
print("✓ All referenced files exist.")

print("\n" + "=" * 90)
print("STEP 6 COMPLETED SUCCESSFULLY")
print("=" * 90)

In [ ]:
# ============================================================
# STEP 7 — LEAKAGE-SAFE SUBJECT-WISE DATA SPLIT
# FORS-EMG RESEARCH PIPELINE
# ============================================================

import numpy as np
import pandas as pd
import os

from sklearn.model_selection import train_test_split


print("=" * 90)
print("[STEP 7] LEAKAGE-SAFE SUBJECT-WISE DATA SPLIT")
print("=" * 90)


# ============================================================
# 7.1 — CHECK RECORDINGS DATAFRAME
# ============================================================

print("\n[1] CHECKING METADATA")
print("-" * 90)

if "recordings_df" not in globals():
    raise NameError(
        "recordings_df was not found. "
        "Please run Step 6 first."
    )

print(f"Metadata shape: {recordings_df.shape}")

required_columns = [
    "subject",
    "orientation",
    "gesture",
    "gesture_id",
    "repetition",
    "filename",
    "filepath"
]

missing_columns = [
    col for col in required_columns
    if col not in recordings_df.columns
]

if missing_columns:
    raise ValueError(
        f"Missing required columns: {missing_columns}"
    )

print("✓ Required metadata columns are available.")


# ============================================================
# 7.2 — EXTRACT UNIQUE SUBJECTS
# ============================================================

print("\n[2] IDENTIFYING UNIQUE SUBJECTS")
print("-" * 90)

subjects = sorted(
    recordings_df["subject"].unique(),
    key=lambda x: int(
        str(x).replace("Subject", "")
    )
)

print(f"Number of unique subjects: {len(subjects)}")

print("\nSubjects:")
print(subjects)


# ============================================================
# 7.3 — VERIFY EXACTLY 19 SUBJECTS
# ============================================================

expected_subject_count = 19

if len(subjects) != expected_subject_count:
    raise ValueError(
        f"Expected {expected_subject_count} subjects, "
        f"but found {len(subjects)}."
    )

print(
    f"\n✓ Exactly {expected_subject_count} subjects detected."
)


# ============================================================
# 7.4 — FIXED RANDOM SEED
# ============================================================

print("\n[3] REPRODUCIBILITY SETTINGS")
print("-" * 90)

RANDOM_STATE = 42

print(f"Random state: {RANDOM_STATE}")


# ============================================================
# 7.5 — FIRST SPLIT
# TRAIN = 15 SUBJECTS
# TEMP  = 4 SUBJECTS
# ============================================================

print("\n[4] CREATING SUBJECT-WISE TRAIN/TEMP SPLIT")
print("-" * 90)

train_subjects, temp_subjects = train_test_split(
    subjects,
    test_size=4,
    random_state=RANDOM_STATE,
    shuffle=True
)

train_subjects = sorted(
    train_subjects,
    key=lambda x: int(
        str(x).replace("Subject", "")
    )
)

temp_subjects = sorted(
    temp_subjects,
    key=lambda x: int(
        str(x).replace("Subject", "")
    )
)

print(f"Train subjects ({len(train_subjects)}):")
print(train_subjects)

print(f"\nTemporary subjects ({len(temp_subjects)}):")
print(temp_subjects)


# ============================================================
# 7.6 — SECOND SPLIT
# VALIDATION = 2
# TEST       = 2
# ============================================================

print("\n[5] CREATING VALIDATION/TEST SUBJECT SPLIT")
print("-" * 90)

val_subjects, test_subjects = train_test_split(
    temp_subjects,
    test_size=2,
    random_state=RANDOM_STATE,
    shuffle=True
)

val_subjects = sorted(
    val_subjects,
    key=lambda x: int(
        str(x).replace("Subject", "")
    )
)

test_subjects = sorted(
    test_subjects,
    key=lambda x: int(
        str(x).replace("Subject", "")
    )
)

print(f"Validation subjects ({len(val_subjects)}):")
print(val_subjects)

print(f"\nTest subjects ({len(test_subjects)}):")
print(test_subjects)


# ============================================================
# 7.7 — CHECK SUBJECT DISJOINTNESS
# ============================================================

print("\n[6] SUBJECT LEAKAGE CHECK")
print("-" * 90)

train_set = set(train_subjects)
val_set = set(val_subjects)
test_set = set(test_subjects)

train_val_overlap = train_set.intersection(val_set)
train_test_overlap = train_set.intersection(test_set)
val_test_overlap = val_set.intersection(test_set)

print(
    f"Train ∩ Validation: {train_val_overlap}"
)

print(
    f"Train ∩ Test:       {train_test_overlap}"
)

print(
    f"Validation ∩ Test:  {val_test_overlap}"
)

if (
    len(train_val_overlap) == 0
    and len(train_test_overlap) == 0
    and len(val_test_overlap) == 0
):
    print("\n✓ NO SUBJECT LEAKAGE DETECTED.")
else:
    raise ValueError(
        "Subject leakage detected between splits!"
    )


# ============================================================
# 7.8 — VERIFY ALL SUBJECTS ARE INCLUDED ONCE
# ============================================================

print("\n[7] SUBJECT COVERAGE CHECK")
print("-" * 90)

combined_subjects = (
    train_subjects
    + val_subjects
    + test_subjects
)

combined_set = set(combined_subjects)

missing_subjects = sorted(
    train_set.union(val_set, test_set)
    ^ set(subjects)
)

duplicate_subjects = (
    len(combined_subjects)
    != len(combined_set)
)

print(
    f"Total subjects assigned: {len(combined_subjects)}"
)

print(
    f"Unique subjects assigned: {len(combined_set)}"
)

print(
    f"Missing subjects: {missing_subjects}"
)

print(
    f"Duplicate subject assignment: {duplicate_subjects}"
)

if (
    len(combined_subjects) == 19
    and len(combined_set) == 19
    and len(missing_subjects) == 0
    and not duplicate_subjects
):
    print(
        "\n✓ Every subject is assigned exactly once."
    )
else:
    raise ValueError(
        "Subject coverage validation failed."
    )


# ============================================================
# 7.9 — ASSIGN SPLIT LABEL TO EVERY RECORDING
# ============================================================

print("\n[8] ASSIGNING SPLIT LABELS")
print("-" * 90)

recordings_df["split"] = "UNASSIGNED"

recordings_df.loc[
    recordings_df["subject"].isin(train_subjects),
    "split"
] = "train"

recordings_df.loc[
    recordings_df["subject"].isin(val_subjects),
    "split"
] = "validation"

recordings_df.loc[
    recordings_df["subject"].isin(test_subjects),
    "split"
] = "test"


# ============================================================
# 7.10 — CHECK FOR UNASSIGNED RECORDINGS
# ============================================================

unassigned_count = (
    recordings_df["split"] == "UNASSIGNED"
).sum()

print(
    f"Unassigned recordings: {unassigned_count}"
)

if unassigned_count == 0:
    print("✓ Every recording has a split assignment.")
else:
    raise ValueError(
        "Some recordings were not assigned to a split."
    )


# ============================================================
# 7.11 — RECORDINGS PER SPLIT
# ============================================================

print("\n[9] RECORDINGS PER SPLIT")
print("-" * 90)

split_counts = (
    recordings_df["split"]
    .value_counts()
    .reindex(
        ["train", "validation", "test"]
    )
)

display(
    split_counts.to_frame("recordings")
)


# ============================================================
# 7.12 — SUBJECTS PER SPLIT
# ============================================================

print("\n[10] SUBJECTS PER SPLIT")
print("-" * 90)

subject_split_table = pd.DataFrame({
    "split": (
        ["train"] * len(train_subjects)
        + ["validation"] * len(val_subjects)
        + ["test"] * len(test_subjects)
    ),
    "subject": (
        train_subjects
        + val_subjects
        + test_subjects
    )
})

display(subject_split_table)


# ============================================================
# 7.13 — CLASS DISTRIBUTION PER SPLIT
# ============================================================

print("\n[11] GESTURE DISTRIBUTION PER SPLIT")
print("-" * 90)

split_gesture_table = pd.crosstab(
    recordings_df["gesture"],
    recordings_df["split"]
)

split_gesture_table = split_gesture_table.reindex(
    columns=["train", "validation", "test"]
)

display(split_gesture_table)


# ============================================================
# 7.14 — ORIENTATION DISTRIBUTION PER SPLIT
# ============================================================

print("\n[12] ORIENTATION DISTRIBUTION PER SPLIT")
print("-" * 90)

split_orientation_table = pd.crosstab(
    recordings_df["orientation"],
    recordings_df["split"]
)

split_orientation_table = split_orientation_table.reindex(
    columns=["train", "validation", "test"]
)

display(split_orientation_table)


# ============================================================
# 7.15 — SUBJECT × SPLIT RECORDING COUNTS
# ============================================================

print("\n[13] RECORDINGS PER SUBJECT AND SPLIT")
print("-" * 90)

subject_split_counts = pd.crosstab(
    recordings_df["subject"],
    recordings_df["split"]
)

subject_split_counts = subject_split_counts.reindex(
    index=subjects
)

display(subject_split_counts)


# ============================================================
# 7.16 — EXPECTED RECORDINGS PER SUBJECT
# ============================================================

print("\n[14] RECORDING COUNT VALIDATION")
print("-" * 90)

expected_per_subject = 180

subject_recording_counts = (
    recordings_df
    .groupby("subject")
    .size()
)

print(
    f"Expected recordings per subject: "
    f"{expected_per_subject}"
)

print(
    f"Minimum actual: "
    f"{subject_recording_counts.min()}"
)

print(
    f"Maximum actual: "
    f"{subject_recording_counts.max()}"
)

if (
    subject_recording_counts.min()
    == expected_per_subject
    and
    subject_recording_counts.max()
    == expected_per_subject
):
    print(
        "✓ Every subject contains exactly "
        "180 recordings."
    )
else:
    raise ValueError(
        "Unexpected number of recordings per subject."
    )


# ============================================================
# 7.17 — VERIFY EACH SPLIT HAS ALL 12 GESTURES
# ============================================================

print("\n[15] GESTURE COVERAGE VALIDATION")
print("-" * 90)

for split_name in ["train", "validation", "test"]:

    split_data = recordings_df[
        recordings_df["split"] == split_name
    ]

    unique_gestures = (
        split_data["gesture_id"]
        .nunique()
    )

    print(
        f"{split_name:12s}: "
        f"{unique_gestures} gestures"
    )

    if unique_gestures != 12:
        print(
            f"⚠ Warning: {split_name} does not "
            f"contain all 12 gestures."
        )
    else:
        print(
            f"✓ {split_name} contains all 12 gestures."
        )


# ============================================================
# 7.18 — VERIFY EACH SPLIT HAS ALL 3 ORIENTATIONS
# ============================================================

print("\n[16] ORIENTATION COVERAGE VALIDATION")
print("-" * 90)

for split_name in ["train", "validation", "test"]:

    split_data = recordings_df[
        recordings_df["split"] == split_name
    ]

    unique_orientations = (
        split_data["orientation"]
        .nunique()
    )

    print(
        f"{split_name:12s}: "
        f"{unique_orientations} orientations"
    )

    if unique_orientations != 3:
        print(
            f"⚠ Warning: {split_name} does not "
            f"contain all 3 orientations."
        )
    else:
        print(
            f"✓ {split_name} contains all 3 orientations."
        )


# ============================================================
# 7.19 — SAVE SUBJECT SPLIT INFORMATION
# ============================================================

print("\n[17] SAVING SUBJECT SPLIT INFORMATION")
print("-" * 90)

SPLIT_DIR = "/kaggle/working/fors_emg_research/splits"

os.makedirs(
    SPLIT_DIR,
    exist_ok=True
)

split_subject_df = pd.DataFrame({
    "subject": (
        train_subjects
        + val_subjects
        + test_subjects
    ),
    "split": (
        ["train"] * len(train_subjects)
        + ["validation"] * len(val_subjects)
        + ["test"] * len(test_subjects)
    )
})

split_file = os.path.join(
    SPLIT_DIR,
    "main_subject_wise_split.csv"
)

split_subject_df.to_csv(
    split_file,
    index=False
)

print(
    f"Saved subject split file:\n{split_file}"
)


# ============================================================
# 7.20 — SAVE COMPLETE METADATA WITH SPLIT
# ============================================================

metadata_file = os.path.join(
    SPLIT_DIR,
    "recordings_metadata_with_split.csv"
)

recordings_df.to_csv(
    metadata_file,
    index=False
)

print(
    f"\nSaved complete metadata:\n"
    f"{metadata_file}"
)


# ============================================================
# 7.21 — FINAL STEP 7 ASSERTIONS
# ============================================================

print("\n[18] FINAL STEP 7 ASSERTIONS")
print("=" * 90)

assert len(train_subjects) == 15
assert len(val_subjects) == 2
assert len(test_subjects) == 2

assert len(train_set.intersection(val_set)) == 0
assert len(train_set.intersection(test_set)) == 0
assert len(val_set.intersection(test_set)) == 0

assert len(combined_set) == 19

assert unassigned_count == 0

assert len(recordings_df) == 3420

assert recordings_df["split"].isin(
    ["train", "validation", "test"]
).all()

assert split_file is not None
assert metadata_file is not None

print("✓ 15 training subjects.")
print("✓ 2 validation subjects.")
print("✓ 2 test subjects.")
print("✓ No subject overlap between splits.")
print("✓ All 19 subjects assigned exactly once.")
print("✓ All 3420 recordings assigned.")
print("✓ Split labels successfully saved.")
print("✓ Complete metadata successfully saved.")

print("\n" + "=" * 90)
print("STEP 7 COMPLETED SUCCESSFULLY")
print("=" * 90)

In [ ]:
# ============================================================
# STEP 8 — EMG FEATURE EXTRACTION
# CELL [1] IMPORT LIBRARIES
# ============================================================

import os
import re
import warnings
import numpy as np
import pandas as pd

from scipy.io import loadmat
from scipy import signal
from scipy.stats import skew, kurtosis

from tqdm.auto import tqdm

warnings.filterwarnings("ignore")

print("=" * 80)
print("STEP 8 — LEAKAGE-SAFE EMG FEATURE EXTRACTION")
print("=" * 80)

print("✓ NumPy imported")
print("✓ Pandas imported")
print("✓ SciPy imported")
print("✓ tqdm imported")

In [ ]:
# ============================================================
# CELL [2] VERIFY METADATA
# ============================================================

print("\n[1] VERIFYING METADATA")
print("-" * 80)

# recordings_df should have been created in Step 6
if "recordings_df" not in globals():
    raise NameError(
        "recordings_df was not found. "
        "Please run the Step 6 metadata notebook cells first."
    )

print("✓ recordings_df found")
print("Shape:", recordings_df.shape)

print("\nColumns:")
print(recordings_df.columns.tolist())

In [ ]:
# ============================================================
# CELL [3] VERIFY SUBJECT SPLIT
# ============================================================

print("\n[2] VERIFYING SUBJECT-WISE SPLIT")
print("-" * 80)

possible_split_columns = ["split", "dataset_split", "data_split"]

split_column = None

for col in possible_split_columns:
    if col in recordings_df.columns:
        split_column = col
        break

if split_column is None:
    raise ValueError(
        "No split column found in recordings_df.\n"
        "Expected one of: "
        + str(possible_split_columns)
    )

print("✓ Split column found:", split_column)

print("\nSplit distribution:")
print(recordings_df[split_column].value_counts())

print("\nSubjects per split:")

for split_name in ["train", "validation", "test"]:
    subset = recordings_df[
        recordings_df[split_column].astype(str).str.lower() == split_name
    ]

    print(
        f"{split_name:12s}: "
        f"{subset['subject'].nunique()} subjects | "
        f"{len(subset)} recordings"
    )

In [ ]:
# ============================================================
# CELL [4] VERIFY ONE MATLAB RECORDING
# ============================================================

print("\n[3] VERIFYING MATLAB RECORDING")
print("-" * 80)

first_path = recordings_df.iloc[0]["filepath"]

print("File:")
print(first_path)

if not os.path.exists(first_path):
    raise FileNotFoundError(
        f"Recording does not exist:\n{first_path}"
    )

mat_data = loadmat(first_path)

print("\nMATLAB variables:")

for key, value in mat_data.items():
    if not key.startswith("__"):
        if isinstance(value, np.ndarray):
            print(
                f"{key:15s} "
                f"shape={value.shape} "
                f"dtype={value.dtype}"
            )
        else:
            print(
                f"{key:15s} "
                f"type={type(value)}"
            )

In [ ]:
# ============================================================
# CELL [5] SAFE EMG LOADER
# ============================================================

EXPECTED_CHANNELS = 8
EXPECTED_SAMPLES = 8000
SAMPLING_FREQUENCY = 985.0


def load_emg_signal(filepath):
    """
    Load one FORS-EMG MATLAB recording.

    Returns
    -------
    signal_data : np.ndarray
        Shape: (8000, 8)
    """

    mat = loadmat(filepath)

    # --------------------------------------------------------
    # First preference: known variable from FORS-EMG
    # --------------------------------------------------------

    if "value" in mat:
        arr = mat["value"]

    else:

        # Search for numeric 2-D arrays
        candidates = []

        for key, value in mat.items():

            if key.startswith("__"):
                continue

            if isinstance(value, np.ndarray):

                if value.ndim == 2 and np.issubdtype(
                    value.dtype, np.number
                ):
                    candidates.append((key, value))

        if len(candidates) == 0:
            raise ValueError(
                f"No suitable numeric signal found in: {filepath}"
            )

        # Prefer an array containing 8 channels
        matching = [
            (key, value)
            for key, value in candidates
            if EXPECTED_CHANNELS in value.shape
        ]

        if len(matching) > 0:
            arr = matching[0][1]
        else:
            arr = candidates[0][1]

    arr = np.asarray(arr, dtype=np.float64)

    # --------------------------------------------------------
    # Remove unnecessary singleton dimensions
    # --------------------------------------------------------

    arr = np.squeeze(arr)

    if arr.ndim != 2:
        raise ValueError(
            f"Unexpected signal dimensions {arr.shape} "
            f"for {filepath}"
        )

    # --------------------------------------------------------
    # Standardize to (samples, channels)
    # --------------------------------------------------------

    if arr.shape == (EXPECTED_CHANNELS, EXPECTED_SAMPLES):

        # (8, 8000) → (8000, 8)
        arr = arr.T

    elif arr.shape == (EXPECTED_SAMPLES, EXPECTED_CHANNELS):

        # Already correct
        pass

    elif arr.shape[0] == EXPECTED_CHANNELS:

        arr = arr.T

    elif arr.shape[1] == EXPECTED_CHANNELS:

        pass

    else:

        raise ValueError(
            f"Cannot identify 8-channel signal in shape "
            f"{arr.shape}: {filepath}"
        )

    # --------------------------------------------------------
    # Final validation
    # --------------------------------------------------------

    if arr.shape[1] != EXPECTED_CHANNELS:
        raise ValueError(
            f"Expected 8 channels, got {arr.shape}"
        )

    if not np.isfinite(arr).all():
        raise ValueError(
            f"NaN/Inf detected in {filepath}"
        )

    return arr

In [ ]:
# ============================================================
# CELL [6] TEST SIGNAL LOADER
# ============================================================

test_signal = load_emg_signal(first_path)

print("\n[4] SIGNAL LOADER TEST")
print("-" * 80)

print("Original MATLAB shape : (8, 8000)")
print("Standardized shape    :", test_signal.shape)
print("Expected shape        :", (8000, 8))

print("\nMinimum:", test_signal.min())
print("Maximum:", test_signal.max())
print("Mean   :", test_signal.mean())
print("Std    :", test_signal.std())

assert test_signal.shape == (8000, 8)
assert np.isfinite(test_signal).all()

print("\n✓ Signal loader validated")
print("✓ Signal standardized to (8000, 8)")
print("✓ No NaN/Inf detected")

In [ ]:
# ============================================================
# CELL [7] TIME-DOMAIN FEATURES
# ============================================================

def mean_absolute_value(x):
    return np.mean(np.abs(x))


def rms(x):
    return np.sqrt(np.mean(np.square(x)))


def variance(x):
    return np.var(x)


def standard_deviation(x):
    return np.std(x)


def waveform_length(x):
    return np.sum(np.abs(np.diff(x)))


def zero_crossing(x, threshold=0.0):
    x1 = x[:-1]
    x2 = x[1:]

    crossings = (
        ((x1 <= threshold) & (x2 > threshold)) |
        ((x1 >= threshold) & (x2 < threshold))
    )

    return np.sum(crossings)


def slope_sign_changes(x, threshold=0.0):
    dx1 = x[1:-1] - x[:-2]
    dx2 = x[2:] - x[1:-1]

    changes = (
        ((dx1 * dx2) < 0) &
        ((np.abs(dx1 - dx2)) >= threshold)
    )

    return np.sum(changes)


def integrated_emg(x):
    return np.sum(np.abs(x))


def peak_to_peak(x):
    return np.ptp(x)


def signal_skewness(x):
    return skew(x, bias=False)


def signal_kurtosis(x):
    return kurtosis(x, fisher=True, bias=False)


print("✓ Time-domain feature functions created")

In [ ]:
# ============================================================
# CELL [8] FREQUENCY-DOMAIN FEATURES
# ============================================================

def compute_psd(x, fs=SAMPLING_FREQUENCY):

    frequencies, power = signal.welch(
        x,
        fs=fs,
        nperseg=min(1024, len(x)),
        noverlap=None,
        detrend="constant"
    )

    power = np.maximum(power, 0)

    return frequencies, power


def mean_frequency(x, fs=SAMPLING_FREQUENCY):

    frequencies, power = compute_psd(x, fs)

    total_power = np.sum(power)

    if total_power <= 0:
        return 0.0

    return np.sum(frequencies * power) / total_power


def median_frequency(x, fs=SAMPLING_FREQUENCY):

    frequencies, power = compute_psd(x, fs)

    cumulative_power = np.cumsum(power)

    total_power = cumulative_power[-1]

    if total_power <= 0:
        return 0.0

    index = np.searchsorted(
        cumulative_power,
        total_power / 2
    )

    index = min(index, len(frequencies) - 1)

    return frequencies[index]


def peak_frequency(x, fs=SAMPLING_FREQUENCY):

    frequencies, power = compute_psd(x, fs)

    if np.all(power == 0):
        return 0.0

    return frequencies[np.argmax(power)]


def spectral_entropy(x, fs=SAMPLING_FREQUENCY):

    frequencies, power = compute_psd(x, fs)

    total_power = np.sum(power)

    if total_power <= 0:
        return 0.0

    probability = power / total_power

    probability = probability[
        probability > 0
    ]

    entropy = -np.sum(
        probability * np.log2(probability)
    )

    # Normalize
    if len(probability) > 1:
        entropy /= np.log2(len(probability))

    return entropy


def total_power(x, fs=SAMPLING_FREQUENCY):

    frequencies, power = compute_psd(x, fs)

    # Integrate PSD over frequency
    return np.trapezoid(power, frequencies)


print("✓ Frequency-domain feature functions created")

In [ ]:
# ============================================================
# CELL [9] COMPLETE FEATURE EXTRACTOR
# ============================================================

FEATURE_NAMES = [

    # Time domain
    "MAV",
    "RMS",
    "Variance",
    "Std",
    "Waveform_Length",
    "Zero_Crossing",
    "Slope_Sign_Changes",
    "IEMG",
    "Peak_to_Peak",
    "Skewness",
    "Kurtosis",

    # Frequency domain
    "Mean_Frequency",
    "Median_Frequency",
    "Peak_Frequency",
    "Spectral_Entropy",
    "Total_Power"
]


def extract_channel_features(
    x,
    fs=SAMPLING_FREQUENCY
):

    features = {

        # -------------------------
        # Time domain
        # -------------------------

        "MAV":
            mean_absolute_value(x),

        "RMS":
            rms(x),

        "Variance":
            variance(x),

        "Std":
            standard_deviation(x),

        "Waveform_Length":
            waveform_length(x),

        "Zero_Crossing":
            zero_crossing(x),

        "Slope_Sign_Changes":
            slope_sign_changes(x),

        "IEMG":
            integrated_emg(x),

        "Peak_to_Peak":
            peak_to_peak(x),

        "Skewness":
            signal_skewness(x),

        "Kurtosis":
            signal_kurtosis(x),

        # -------------------------
        # Frequency domain
        # -------------------------

        "Mean_Frequency":
            mean_frequency(x, fs),

        "Median_Frequency":
            median_frequency(x, fs),

        "Peak_Frequency":
            peak_frequency(x, fs),

        "Spectral_Entropy":
            spectral_entropy(x, fs),

        "Total_Power":
            total_power(x, fs)
    }

    return features

In [ ]:
# ============================================================
# CELL [10] TEST ONE CHANNEL
# ============================================================

print("\n[5] TESTING FEATURE EXTRACTION")
print("-" * 80)

channel_1 = test_signal[:, 0]

test_features = extract_channel_features(channel_1)

test_feature_df = pd.DataFrame([test_features])

print("Number of features:", len(test_features))

print("\nFeature values:")

display(test_feature_df.T)

assert len(test_features) == 16

print("\n✓ 16 features extracted successfully")

In [ ]:
# ============================================================
# CELL [11] TEST ALL 8 CHANNELS
# ============================================================

print("\n[6] TESTING ALL 8 CHANNELS")
print("-" * 80)

all_channel_features = []

for channel_idx in range(8):

    channel_signal = test_signal[:, channel_idx]

    features = extract_channel_features(
        channel_signal
    )

    all_channel_features.append(features)

channel_feature_matrix = np.array([
    list(features.values())
    for features in all_channel_features
])

print("Feature matrix shape:")
print(channel_feature_matrix.shape)

print("\nExpected:")
print("(8 channels, 16 features)")

assert channel_feature_matrix.shape == (8, 16)

assert np.isfinite(
    channel_feature_matrix
).all()

print("\n✓ All 8 channels processed")
print("✓ Feature matrix = 8 × 16")
print("✓ No NaN/Inf")

In [ ]:
# ============================================================
# CELL [12] RECORDING FEATURE EXTRACTOR
# ============================================================

def extract_recording_features(
    filepath,
    fs=SAMPLING_FREQUENCY
):
    """
    Extract features from one 8-channel EMG recording.

    Returns
    -------
    feature_matrix : np.ndarray
        Shape = (8, 16)
    """

    emg = load_emg_signal(filepath)

    channel_features = []

    for channel_idx in range(
        EXPECTED_CHANNELS
    ):

        x = emg[:, channel_idx]

        features = extract_channel_features(
            x,
            fs=fs
        )

        channel_features.append(
            [features[name] for name in FEATURE_NAMES]
        )

    feature_matrix = np.asarray(
        channel_features,
        dtype=np.float32
    )

    if feature_matrix.shape != (
        EXPECTED_CHANNELS,
        len(FEATURE_NAMES)
    ):
        raise ValueError(
            f"Unexpected feature shape: "
            f"{feature_matrix.shape}"
        )

    if not np.isfinite(feature_matrix).all():
        raise ValueError(
            f"NaN/Inf detected in feature matrix: "
            f"{filepath}"
        )

    return feature_matrix

In [ ]:
# ============================================================
# CELL [13] TEST COMPLETE RECORDING
# ============================================================

print("\n[7] TESTING COMPLETE RECORDING FEATURE EXTRACTION")
print("-" * 80)

sample_matrix = extract_recording_features(
    first_path
)

print("Feature matrix shape:")
print(sample_matrix.shape)

print("\nExpected:")
print(
    f"({EXPECTED_CHANNELS}, "
    f"{len(FEATURE_NAMES)})"
)

assert sample_matrix.shape == (
    8,
    16
)

print("\n✓ Complete recording extraction works")

In [ ]:
# ============================================================
# CELL [14] FLATTEN FEATURES FOR CONVENTIONAL ML
# ============================================================

def flatten_feature_matrix(feature_matrix):

    return feature_matrix.reshape(-1)


flat_sample = flatten_feature_matrix(
    sample_matrix
)

print("\n[8] FLATTENED FEATURE TEST")
print("-" * 80)

print("Original shape :", sample_matrix.shape)
print("Flattened shape:", flat_sample.shape)

assert flat_sample.shape == (128,)

print("\n✓ 128-dimensional recording feature vector created")

In [ ]:
# ============================================================
# CELL [15] FEATURE COLUMN NAMES
# ============================================================

flat_feature_names = []

for channel_idx in range(
    EXPECTED_CHANNELS
):

    for feature_name in FEATURE_NAMES:

        column_name = (
            f"CH{channel_idx + 1}_"
            f"{feature_name}"
        )

        flat_feature_names.append(
            column_name
        )

print("\n[9] FEATURE COLUMN NAMES")
print("-" * 80)

print("Total feature columns:",
      len(flat_feature_names))

print("\nFirst 20:")
print(flat_feature_names[:20])

print("\nLast 10:")
print(flat_feature_names[-10:])

assert len(flat_feature_names) == 128

print("\n✓ 128 feature names generated")

In [ ]:
# ============================================================
# CELL [16] MASTER DATASET FEATURE EXTRACTION
# ============================================================

def extract_dataset_features(
    metadata_df,
    split_name,
    split_column="split"
):

    subset = metadata_df[
        metadata_df[split_column]
        .astype(str)
        .str.lower()
        == split_name.lower()
    ].copy()

    subset = subset.reset_index(drop=True)

    print("\n" + "=" * 80)
    print(
        f"EXTRACTING {split_name.upper()} FEATURES"
    )
    print("=" * 80)

    print(
        "Number of recordings:",
        len(subset)
    )

    flat_features = []
    graph_features = []

    failed_files = []

    for idx, row in tqdm(
        subset.iterrows(),
        total=len(subset),
        desc=f"{split_name} feature extraction"
    ):

        try:

            feature_matrix = (
                extract_recording_features(
                    row["filepath"]
                )
            )

            flat_vector = (
                flatten_feature_matrix(
                    feature_matrix
                )
            )

            flat_features.append(
                flat_vector
            )

            graph_features.append(
                feature_matrix
            )

        except Exception as e:

            failed_files.append({
                "filepath":
                    row["filepath"],
                "error":
                    str(e)
            })

    # --------------------------------------------------------
    # Validate failures
    # --------------------------------------------------------

    if len(failed_files) > 0:

        failed_df = pd.DataFrame(
            failed_files
        )

        print(
            f"\n⚠ Failed recordings: "
            f"{len(failed_df)}"
        )

        display(failed_df.head())

        raise RuntimeError(
            f"{len(failed_df)} recordings "
            f"failed during feature extraction."
        )

    # --------------------------------------------------------
    # Convert to arrays
    # --------------------------------------------------------

    flat_features = np.asarray(
        flat_features,
        dtype=np.float32
    )

    graph_features = np.asarray(
        graph_features,
        dtype=np.float32
    )

    # --------------------------------------------------------
    # Validate dimensions
    # --------------------------------------------------------

    expected_flat_shape = (
        len(subset),
        128
    )

    expected_graph_shape = (
        len(subset),
        8,
        16
    )

    print("\nFeature shapes:")
    print(
        "Flat features :",
        flat_features.shape
    )

    print(
        "Graph features:",
        graph_features.shape
    )

    assert (
        flat_features.shape
        == expected_flat_shape
    )

    assert (
        graph_features.shape
        == expected_graph_shape
    )

    assert np.isfinite(
        flat_features
    ).all()

    assert np.isfinite(
        graph_features
    ).all()

    # --------------------------------------------------------
    # Metadata
    # --------------------------------------------------------

    metadata = subset[
        [
            "subject",
            "orientation",
            "gesture",
            "gesture_id",
            "repetition",
            "filename",
            "filepath"
        ]
    ].copy()

    return (
        metadata,
        flat_features,
        graph_features
    )

In [ ]:
# ============================================================
# CELL [17] TRAINING FEATURE EXTRACTION
# ============================================================

train_metadata, X_train_flat, X_train_graph = (
    extract_dataset_features(
        recordings_df,
        "train",
        split_column
    )
)

print("\n✓ TRAINING FEATURES COMPLETE")
print("Metadata:", train_metadata.shape)
print("Flat:", X_train_flat.shape)
print("Graph:", X_train_graph.shape)

In [ ]:
# ============================================================
# CELL [18] VALIDATION FEATURE EXTRACTION
# ============================================================

val_metadata, X_val_flat, X_val_graph = (
    extract_dataset_features(
        recordings_df,
        "validation",
        split_column
    )
)

print("\n✓ VALIDATION FEATURES COMPLETE")
print("Metadata:", val_metadata.shape)
print("Flat:", X_val_flat.shape)
print("Graph:", X_val_graph.shape)

In [ ]:
# ============================================================
# CELL [19] TEST FEATURE EXTRACTION
# ============================================================

test_metadata, X_test_flat, X_test_graph = (
    extract_dataset_features(
        recordings_df,
        "test",
        split_column
    )
)

print("\n✓ TEST FEATURES COMPLETE")
print("Metadata:", test_metadata.shape)
print("Flat:", X_test_flat.shape)
print("Graph:", X_test_graph.shape)

In [ ]:
# ============================================================
# CELL [20] CREATE LABEL ARRAYS
# ============================================================

y_train = train_metadata[
    "gesture_id"
].to_numpy(dtype=np.int64)

y_val = val_metadata[
    "gesture_id"
].to_numpy(dtype=np.int64)

y_test = test_metadata[
    "gesture_id"
].to_numpy(dtype=np.int64)

print("\n[10] LABEL VALIDATION")
print("-" * 80)

print("y_train:", y_train.shape)
print("y_val  :", y_val.shape)
print("y_test :", y_test.shape)

print("\nUnique train labels:",
      np.unique(y_train))

print("Unique validation labels:",
      np.unique(y_val))

print("Unique test labels:",
      np.unique(y_test))

assert len(y_train) == 2700
assert len(y_val) == 360
assert len(y_test) == 360

assert set(np.unique(y_train)) == set(range(12))
assert set(np.unique(y_val)) == set(range(12))
assert set(np.unique(y_test)) == set(range(12))

print("\n✓ All 12 gesture classes present")

In [ ]:
# ============================================================
# CELL [21] FEATURE QUALITY CHECK
# ============================================================

print("\n[11] FEATURE QUALITY CHECK")
print("-" * 80)

datasets_to_check = {
    "Train": X_train_flat,
    "Validation": X_val_flat,
    "Test": X_test_flat
}

for name, X in datasets_to_check.items():

    nan_count = np.isnan(X).sum()
    inf_count = np.isinf(X).sum()

    print(
        f"{name:12s} | "
        f"NaN = {nan_count:6d} | "
        f"Inf = {inf_count:6d}"
    )

    assert nan_count == 0
    assert inf_count == 0

print("\n✓ No NaN/Inf in extracted features")

In [ ]:
# ============================================================
# CELL [22] TRAINING FEATURE STATISTICS
# ============================================================

print("\n[12] TRAINING FEATURE STATISTICS")
print("-" * 80)

feature_statistics = pd.DataFrame({
    "feature": flat_feature_names,
    "mean": np.mean(
        X_train_flat,
        axis=0
    ),
    "std": np.std(
        X_train_flat,
        axis=0
    ),
    "min": np.min(
        X_train_flat,
        axis=0
    ),
    "max": np.max(
        X_train_flat,
        axis=0
    ),
    "median": np.median(
        X_train_flat,
        axis=0
    )
})

display(
    feature_statistics.head(20)
)

print(
    "\nTotal feature statistics:",
    len(feature_statistics)
)

In [ ]:
# ============================================================
# CELL [23] ZERO VARIANCE FEATURE CHECK
# ============================================================

print("\n[13] ZERO-VARIANCE FEATURE CHECK")
print("-" * 80)

zero_variance_mask = (
    feature_statistics["std"] == 0
)

zero_variance_features = (
    feature_statistics.loc[
        zero_variance_mask,
        "feature"
    ].tolist()
)

print(
    "Zero-variance features:",
    len(zero_variance_features)
)

if zero_variance_features:

    print("\nFeatures:")
    for feature in zero_variance_features:
        print(" -", feature)

else:

    print(
        "✓ No zero-variance features found"
    )

In [ ]:
# ============================================================
# CELL [24] FEATURE SCALE CHECK
# ============================================================

print("\n[14] FEATURE SCALE CHECK")
print("-" * 80)

scale_summary = feature_statistics[
    ["feature", "mean", "std", "min", "max"]
].copy()

scale_summary["abs_mean"] = (
    scale_summary["mean"].abs()
)

scale_summary = scale_summary.sort_values(
    "std",
    ascending=False
)

display(
    scale_summary.head(20)
)

In [ ]:
# ============================================================
# CELL [25] CREATE FLAT FEATURE DATAFRAMES
# ============================================================

train_features_df = pd.DataFrame(
    X_train_flat,
    columns=flat_feature_names
)

val_features_df = pd.DataFrame(
    X_val_flat,
    columns=flat_feature_names
)

test_features_df = pd.DataFrame(
    X_test_flat,
    columns=flat_feature_names
)

print("\n[15] FEATURE DATAFRAME SHAPES")
print("-" * 80)

print(
    "Train:",
    train_features_df.shape
)

print(
    "Validation:",
    val_features_df.shape
)

print(
    "Test:",
    test_features_df.shape
)

assert train_features_df.shape == (
    2700,
    128
)

assert val_features_df.shape == (
    360,
    128
)

assert test_features_df.shape == (
    360,
    128
)

print("\n✓ Feature DataFrames validated")

In [ ]:
# ============================================================
# CELL [26] COMBINE METADATA AND FEATURES
# ============================================================

train_table = pd.concat(
    [
        train_metadata.reset_index(drop=True),
        train_features_df
    ],
    axis=1
)

val_table = pd.concat(
    [
        val_metadata.reset_index(drop=True),
        val_features_df
    ],
    axis=1
)

test_table = pd.concat(
    [
        test_metadata.reset_index(drop=True),
        test_features_df
    ],
    axis=1
)

print("\n[16] FINAL TABULAR FEATURE TABLES")
print("-" * 80)

print("Train:", train_table.shape)
print("Validation:", val_table.shape)
print("Test:", test_table.shape)

display(train_table.head(3))

In [ ]:
# ============================================================
# CELL [27] METADATA-FEATURE ALIGNMENT CHECK
# ============================================================

print("\n[17] METADATA-FEATURE ALIGNMENT")
print("-" * 80)

assert len(train_table) == len(X_train_graph)
assert len(val_table) == len(X_val_graph)
assert len(test_table) == len(X_test_graph)

assert np.array_equal(
    train_table["gesture_id"].values,
    y_train
)

assert np.array_equal(
    val_table["gesture_id"].values,
    y_val
)

assert np.array_equal(
    test_table["gesture_id"].values,
    y_test
)

print("✓ Train metadata aligned with features")
print("✓ Validation metadata aligned with features")
print("✓ Test metadata aligned with features")
print("✓ Labels aligned with features")

In [ ]:
# ============================================================
# CELL [28] SAVE GRAPH FEATURES
# ============================================================

FEATURE_OUTPUT_DIR = (
    "/kaggle/working/"
    "fors_emg_research/"
    "processed_features"
)

os.makedirs(
    FEATURE_OUTPUT_DIR,
    exist_ok=True
)

# ------------------------------------------------------------
# Train
# ------------------------------------------------------------

np.save(
    os.path.join(
        FEATURE_OUTPUT_DIR,
        "X_train_graph.npy"
    ),
    X_train_graph
)

np.save(
    os.path.join(
        FEATURE_OUTPUT_DIR,
        "y_train.npy"
    ),
    y_train
)

# ------------------------------------------------------------
# Validation
# ------------------------------------------------------------

np.save(
    os.path.join(
        FEATURE_OUTPUT_DIR,
        "X_val_graph.npy"
    ),
    X_val_graph
)

np.save(
    os.path.join(
        FEATURE_OUTPUT_DIR,
        "y_val.npy"
    ),
    y_val
)

# ------------------------------------------------------------
# Test
# ------------------------------------------------------------

np.save(
    os.path.join(
        FEATURE_OUTPUT_DIR,
        "X_test_graph.npy"
    ),
    X_test_graph
)

np.save(
    os.path.join(
        FEATURE_OUTPUT_DIR,
        "y_test.npy"
    ),
    y_test
)

print("\n✓ Graph feature arrays saved")

In [ ]:
# ============================================================
# CELL [29] SAVE FLAT FEATURES
# ============================================================

np.save(
    os.path.join(
        FEATURE_OUTPUT_DIR,
        "X_train_flat.npy"
    ),
    X_train_flat
)

np.save(
    os.path.join(
        FEATURE_OUTPUT_DIR,
        "X_val_flat.npy"
    ),
    X_val_flat
)

np.save(
    os.path.join(
        FEATURE_OUTPUT_DIR,
        "X_test_flat.npy"
    ),
    X_test_flat
)

print("✓ Flat feature arrays saved")

In [ ]:
# ============================================================
# CELL [30] SAVE METADATA
# ============================================================

train_table.to_csv(
    os.path.join(
        FEATURE_OUTPUT_DIR,
        "train_features.csv"
    ),
    index=False
)

val_table.to_csv(
    os.path.join(
        FEATURE_OUTPUT_DIR,
        "validation_features.csv"
    ),
    index=False
)

test_table.to_csv(
    os.path.join(
        FEATURE_OUTPUT_DIR,
        "test_features.csv"
    ),
    index=False
)

feature_statistics.to_csv(
    os.path.join(
        FEATURE_OUTPUT_DIR,
        "feature_statistics.csv"
    ),
    index=False
)

print("✓ CSV feature tables saved")

In [ ]:
# ============================================================
# CELL [31] SAVE FEATURE CONFIGURATION
# ============================================================

feature_config = {
    "sampling_frequency": SAMPLING_FREQUENCY,
    "channels": EXPECTED_CHANNELS,
    "samples_per_recording": EXPECTED_SAMPLES,
    "features_per_channel": len(FEATURE_NAMES),
    "total_flat_features": len(flat_feature_names),
    "feature_names": FEATURE_NAMES,
    "flat_feature_names": flat_feature_names
}

import json

with open(
    os.path.join(
        FEATURE_OUTPUT_DIR,
        "feature_config.json"
    ),
    "w"
) as f:

    json.dump(
        feature_config,
        f,
        indent=4
    )

print("✓ Feature configuration saved")

In [ ]:
# ============================================================
# CELL [32] FINAL STEP 8 ASSERTIONS
# ============================================================

print("\n")
print("=" * 80)
print("FINAL STEP 8 ASSERTIONS")
print("=" * 80)

# ------------------------------------------------------------
# Recording counts
# ------------------------------------------------------------

assert X_train_graph.shape[0] == 2700
assert X_val_graph.shape[0] == 360
assert X_test_graph.shape[0] == 360

# ------------------------------------------------------------
# Graph feature dimensions
# ------------------------------------------------------------

assert X_train_graph.shape[1:] == (8, 16)
assert X_val_graph.shape[1:] == (8, 16)
assert X_test_graph.shape[1:] == (8, 16)

# ------------------------------------------------------------
# Flat dimensions
# ------------------------------------------------------------

assert X_train_flat.shape[1] == 128
assert X_val_flat.shape[1] == 128
assert X_test_flat.shape[1] == 128

# ------------------------------------------------------------
# Labels
# ------------------------------------------------------------

assert len(y_train) == 2700
assert len(y_val) == 360
assert len(y_test) == 360

# ------------------------------------------------------------
# Finite values
# ------------------------------------------------------------

assert np.isfinite(X_train_graph).all()
assert np.isfinite(X_val_graph).all()
assert np.isfinite(X_test_graph).all()

# ------------------------------------------------------------
# No metadata mismatch
# ------------------------------------------------------------

assert len(train_metadata) == len(X_train_graph)
assert len(val_metadata) == len(X_val_graph)
assert len(test_metadata) == len(X_test_graph)

# ------------------------------------------------------------
# Total
# ------------------------------------------------------------

assert (
    len(train_metadata)
    + len(val_metadata)
    + len(test_metadata)
    == 3420
)

print("✓ 2700 training recordings verified")
print("✓ 360 validation recordings verified")
print("✓ 360 test recordings verified")
print("✓ 3420 total recordings verified")

print("✓ 8 EMG channels verified")
print("✓ 16 features/channel verified")
print("✓ 128 flattened features verified")

print("✓ No NaN/Inf detected")
print("✓ Metadata-feature alignment verified")
print("✓ Subject-wise split preserved")
print("✓ No random re-splitting performed")

print("\n" + "=" * 80)
print("STEP 8 COMPLETED SUCCESSFULLY")
print("=" * 80)

print("\nSaved to:")
print(FEATURE_OUTPUT_DIR)

In [ ]:
# ============================================================
# STEP 9 — FEATURE PREPROCESSING & NORMALIZATION
# ============================================================
#
# Purpose:
#   1. Prepare train/validation/test features
#   2. Standardize 128 handcrafted EMG features
#   3. Fit scaler ONLY on training data
#   4. Transform validation and test using training scaler
#   5. Preserve subject-wise split
#   6. Verify NaN/Inf
#   7. Verify feature dimensions
#   8. Save scaler for future inference
#
# Expected:
#   Train      : (2700, 128)
#   Validation : (360, 128)
#   Test       : (360, 128)
# ============================================================

import numpy as np
import pandas as pd
import joblib

from sklearn.preprocessing import StandardScaler

print("=" * 80)
print("STEP 9 — FEATURE PREPROCESSING & NORMALIZATION")
print("=" * 80)


# ============================================================
# [1] CHECK STEP 8 VARIABLES
# ============================================================

print("\n[1] CHECKING STEP 8 FEATURE VARIABLES")
print("-" * 80)

required_variables = [
    "X_train_flat",
    "X_val_flat",
    "X_test_flat"
]

missing_variables = [
    var for var in required_variables
    if var not in globals()
]

if missing_variables:
    print("❌ Missing variables:")
    print(missing_variables)

    raise ValueError(
        "Step 8 feature variables are missing. "
        "Please run Step 8 before Step 9."
    )

print("✓ Required feature variables found")


# ============================================================
# [2] FEATURE SHAPE VALIDATION
# ============================================================

print("\n[2] FEATURE SHAPE VALIDATION")
print("-" * 80)

print(f"Training features      : {X_train_flat.shape}")
print(f"Validation features    : {X_val_flat.shape}")
print(f"Test features          : {X_test_flat.shape}")

EXPECTED_TRAIN = (2700, 128)
EXPECTED_VAL   = (360, 128)
EXPECTED_TEST  = (360, 128)

if X_train_flat.shape != EXPECTED_TRAIN:
    raise ValueError(
        f"Unexpected training shape: {X_train_flat.shape}"
    )

if X_val_flat.shape != EXPECTED_VAL:
    raise ValueError(
        f"Unexpected validation shape: {X_val_flat.shape}"
    )

if X_test_flat.shape != EXPECTED_TEST:
    raise ValueError(
        f"Unexpected test shape: {X_test_flat.shape}"
    )

print("✓ All feature dimensions are correct")


# ============================================================
# [3] CONVERT TO NUMPY FLOAT32
# ============================================================

print("\n[3] CONVERTING FEATURES TO NUMPY")
print("-" * 80)

X_train = np.asarray(X_train_flat, dtype=np.float32)
X_val   = np.asarray(X_val_flat, dtype=np.float32)
X_test  = np.asarray(X_test_flat, dtype=np.float32)

print(f"Train dtype      : {X_train.dtype}")
print(f"Validation dtype : {X_val.dtype}")
print(f"Test dtype       : {X_test.dtype}")

print("✓ Features converted to float32")


# ============================================================
# [4] PRE-NORMALIZATION NaN / INF CHECK
# ============================================================

print("\n[4] PRE-NORMALIZATION VALIDITY CHECK")
print("-" * 80)

for name, X in [
    ("Train", X_train),
    ("Validation", X_val),
    ("Test", X_test)
]:

    nan_count = np.isnan(X).sum()
    inf_count = np.isinf(X).sum()

    print(
        f"{name:<12} | "
        f"NaN = {nan_count:6d} | "
        f"Inf = {inf_count:6d}"
    )

    if nan_count > 0 or inf_count > 0:
        raise ValueError(
            f"{name} features contain NaN/Inf."
        )

print("✓ No NaN/Inf before normalization")


# ============================================================
# [5] CREATE STANDARD SCALER
# ============================================================

print("\n[5] CREATING STANDARD SCALER")
print("-" * 80)

scaler = StandardScaler()

print("Scaler: StandardScaler")
print("Scaling method: z-score normalization")

print("\nImportant:")
print("✓ Scaler will be FIT ONLY on training data")
print("✓ Validation data will NOT be used for fitting")
print("✓ Test data will NOT be used for fitting")


# ============================================================
# [6] FIT SCALER ON TRAINING DATA ONLY
# ============================================================

print("\n[6] FITTING SCALER ON TRAINING DATA")
print("-" * 80)

scaler.fit(X_train)

print("✓ StandardScaler fitted using training data only")


# ============================================================
# [7] TRANSFORM ALL THREE SPLITS
# ============================================================

print("\n[7] NORMALIZING TRAIN / VALIDATION / TEST")
print("-" * 80)

X_train_scaled = scaler.transform(X_train)
X_val_scaled   = scaler.transform(X_val)
X_test_scaled  = scaler.transform(X_test)

print(f"Scaled train shape      : {X_train_scaled.shape}")
print(f"Scaled validation shape : {X_val_scaled.shape}")
print(f"Scaled test shape       : {X_test_scaled.shape}")

print("✓ All feature sets normalized")


# ============================================================
# [8] CONVERT BACK TO FLOAT32
# ============================================================

X_train_scaled = X_train_scaled.astype(np.float32)
X_val_scaled   = X_val_scaled.astype(np.float32)
X_test_scaled  = X_test_scaled.astype(np.float32)

print("\n✓ Normalized features stored as float32")


# ============================================================
# [9] POST-NORMALIZATION VALIDITY CHECK
# ============================================================

print("\n[9] POST-NORMALIZATION VALIDITY CHECK")
print("-" * 80)

for name, X in [
    ("Train", X_train_scaled),
    ("Validation", X_val_scaled),
    ("Test", X_test_scaled)
]:

    nan_count = np.isnan(X).sum()
    inf_count = np.isinf(X).sum()

    print(
        f"{name:<12} | "
        f"NaN = {nan_count:6d} | "
        f"Inf = {inf_count:6d}"
    )

    if nan_count > 0 or inf_count > 0:
        raise ValueError(
            f"{name} normalized features contain NaN/Inf."
        )

print("✓ No NaN/Inf after normalization")


# ============================================================
# [10] NORMALIZED FEATURE STATISTICS
# ============================================================

print("\n[10] NORMALIZED FEATURE STATISTICS")
print("-" * 80)

train_mean = X_train_scaled.mean(axis=0)
train_std  = X_train_scaled.std(axis=0)

print(
    f"Training mean range : "
    f"{train_mean.min():.6f} to {train_mean.max():.6f}"
)

print(
    f"Training std range  : "
    f"{train_std.min():.6f} to {train_std.max():.6f}"
)

print(
    f"Overall train mean  : "
    f"{X_train_scaled.mean():.6f}"
)

print(
    f"Overall train std   : "
    f"{X_train_scaled.std():.6f}"
)


# ============================================================
# [11] CHECK ZERO-VARIANCE AFTER SCALING
# ============================================================

print("\n[11] ZERO-VARIANCE FEATURE CHECK")
print("-" * 80)

zero_variance_features = np.where(
    train_std < 1e-7
)[0]

print(
    f"Zero-variance features after scaling: "
    f"{len(zero_variance_features)}"
)

if len(zero_variance_features) == 0:
    print("✓ No zero-variance features")
else:
    print("⚠ Zero-variance feature indices:")
    print(zero_variance_features)


# ============================================================
# [12] FEATURE RANGE SUMMARY
# ============================================================

print("\n[12] NORMALIZED FEATURE RANGE")
print("-" * 80)

for name, X in [
    ("Train", X_train_scaled),
    ("Validation", X_val_scaled),
    ("Test", X_test_scaled)
]:

    print(
        f"{name:<12} | "
        f"Min = {X.min():8.4f} | "
        f"Max = {X.max():8.4f} | "
        f"Mean = {X.mean():8.4f} | "
        f"Std = {X.std():8.4f}"
    )


# ============================================================
# [13] SAVE SCALER
# ============================================================

print("\n[13] SAVING FEATURE SCALER")
print("-" * 80)

SCALER_PATH = "/kaggle/working/fors_emg_feature_scaler.pkl"

joblib.dump(
    scaler,
    SCALER_PATH
)

print(f"✓ Scaler saved:")
print(SCALER_PATH)


# ============================================================
# [14] SAVE NORMALIZED FEATURES
# ============================================================

print("\n[14] SAVING NORMALIZED FEATURES")
print("-" * 80)

FEATURES_PATH = "/kaggle/working/fors_emg_normalized_features.npz"

np.savez_compressed(
    FEATURES_PATH,
    X_train=X_train_scaled,
    X_val=X_val_scaled,
    X_test=X_test_scaled
)

print(f"✓ Normalized features saved:")
print(FEATURES_PATH)


# ============================================================
# [15] FINAL STEP 9 ASSERTIONS
# ============================================================

print("\n" + "=" * 80)
print("FINAL STEP 9 ASSERTIONS")
print("=" * 80)

assert X_train_scaled.shape == (2700, 128)
assert X_val_scaled.shape == (360, 128)
assert X_test_scaled.shape == (360, 128)

assert not np.isnan(X_train_scaled).any()
assert not np.isnan(X_val_scaled).any()
assert not np.isnan(X_test_scaled).any()

assert not np.isinf(X_train_scaled).any()
assert not np.isinf(X_val_scaled).any()
assert not np.isinf(X_test_scaled).any()

print("✓ 2700 training recordings verified")
print("✓ 360 validation recordings verified")
print("✓ 360 test recordings verified")
print("✓ 128 features verified")
print("✓ StandardScaler fitted on TRAINING data only")
print("✓ Validation transformed using training scaler")
print("✓ Test transformed using training scaler")
print("✓ No NaN/Inf detected")
print("✓ No subject re-splitting performed")
print("✓ No data leakage introduced")
print("✓ Feature scaler saved")
print("✓ Normalized features saved")

print("\n" + "=" * 80)
print("✓ STEP 9 COMPLETED SUCCESSFULLY")
print("=" * 80)

In [ ]:
# ============================================================
# STEP 10 — BASELINE MODELS
# ============================================================
#
# Dataset:
#   Train      = 2700 recordings
#   Validation = 360 recordings
#   Test       = 360 recordings
#
# Features:
#   128 normalized handcrafted EMG features
#
# Models:
#   1. Logistic Regression
#   2. k-NN
#   3. SVM-RBF
#   4. Random Forest
#   5. XGBoost (if available)
#
# IMPORTANT:
#   No new train/validation/test split is performed.
#   Subject-wise split from Step 7 is preserved.
# ============================================================

import numpy as np
import pandas as pd
import time
import warnings

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

warnings.filterwarnings("ignore")

print("=" * 80)
print("STEP 10 — BASELINE MODEL DEVELOPMENT")
print("=" * 80)


# ============================================================
# [1] CHECK REQUIRED VARIABLES
# ============================================================

print("\n[1] CHECKING NORMALIZED FEATURES")
print("-" * 80)

required_variables = [
    "X_train_scaled",
    "X_val_scaled",
    "X_test_scaled"
]

missing = [
    v for v in required_variables
    if v not in globals()
]

if missing:
    raise ValueError(
        f"Missing variables from Step 9: {missing}"
    )

print("✓ Normalized feature variables found")


# ============================================================
# [2] FIND LABEL VARIABLES
# ============================================================

print("\n[2] CHECKING LABEL DATA")
print("-" * 80)

possible_train_labels = [
    "y_train",
    "y_train_gesture",
    "train_labels"
]

possible_val_labels = [
    "y_val",
    "y_val_gesture",
    "val_labels"
]

possible_test_labels = [
    "y_test",
    "y_test_gesture",
    "test_labels"
]


def find_variable(possible_names):
    for name in possible_names:
        if name in globals():
            return globals()[name], name
    return None, None


y_train, train_label_name = find_variable(
    possible_train_labels
)

y_val, val_label_name = find_variable(
    possible_val_labels
)

y_test, test_label_name = find_variable(
    possible_test_labels
)


if y_train is None or y_val is None or y_test is None:

    print("❌ Could not automatically find labels.")

    print("\nExpected label variables:")
    print("y_train")
    print("y_val")
    print("y_test")

    raise ValueError(
        "Gesture labels are required for Step 10."
    )


print(f"Training labels   : {train_label_name}")
print(f"Validation labels : {val_label_name}")
print(f"Test labels       : {test_label_name}")

print("✓ Labels found")


# ============================================================
# [3] CONVERT LABELS TO NUMPY
# ============================================================

print("\n[3] PREPARING LABELS")
print("-" * 80)

y_train = np.asarray(y_train)
y_val = np.asarray(y_val)
y_test = np.asarray(y_test)

print(f"y_train shape : {y_train.shape}")
print(f"y_val shape   : {y_val.shape}")
print(f"y_test shape  : {y_test.shape}")


# ============================================================
# [4] VALIDATE FEATURE/LABEL ALIGNMENT
# ============================================================

print("\n[4] FEATURE-LABEL ALIGNMENT")
print("-" * 80)

assert len(X_train_scaled) == len(y_train)
assert len(X_val_scaled) == len(y_val)
assert len(X_test_scaled) == len(y_test)

print("✓ Training features ↔ labels aligned")
print("✓ Validation features ↔ labels aligned")
print("✓ Test features ↔ labels aligned")


# ============================================================
# [5] DISPLAY CLASS DISTRIBUTION
# ============================================================

print("\n[5] CLASS DISTRIBUTION")
print("-" * 80)

print("\nTraining:")
print(pd.Series(y_train).value_counts().sort_index())

print("\nValidation:")
print(pd.Series(y_val).value_counts().sort_index())

print("\nTest:")
print(pd.Series(y_test).value_counts().sort_index())


# ============================================================
# [6] DETECT CLASS NAMES
# ============================================================

print("\n[6] CLASS INFORMATION")
print("-" * 80)

classes = np.unique(y_train)

print(f"Number of classes: {len(classes)}")
print(f"Classes: {classes}")


# ============================================================
# [7] DEFINE BASELINE MODELS
# ============================================================

print("\n[7] DEFINING BASELINE MODELS")
print("-" * 80)

models = {

    "Logistic Regression": LogisticRegression(
        max_iter=2000,
        random_state=42
    ),

    "k-NN": KNeighborsClassifier(
        n_neighbors=5,
        weights="distance",
        n_jobs=-1
    ),

    "SVM-RBF": SVC(
        kernel="rbf",
        C=10,
        gamma="scale",
        probability=True,
        random_state=42
    ),

    "Random Forest": RandomForestClassifier(
        n_estimators=300,
        max_depth=None,
        min_samples_split=2,
        min_samples_leaf=1,
        random_state=42,
        n_jobs=-1
    )
}

print("Models:")
for name in models:
    print(f"✓ {name}")


# ============================================================
# [8] OPTIONAL XGBOOST
# ============================================================

print("\n[8] CHECKING XGBOOST")
print("-" * 80)

try:

    from xgboost import XGBClassifier

    xgb_model = XGBClassifier(
        n_estimators=300,
        max_depth=6,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        objective="multi:softprob",
        eval_metric="mlogloss",
        random_state=42,
        n_jobs=-1
    )

    models["XGBoost"] = xgb_model

    print("✓ XGBoost available")
    print("✓ XGBoost added to baseline models")

except ImportError:

    print("⚠ XGBoost is not installed")
    print("Continuing without XGBoost")


# ============================================================
# [9] TRAIN BASELINE MODELS
# ============================================================

print("\n" + "=" * 80)
print("[9] TRAINING BASELINE MODELS")
print("=" * 80)


results = []

trained_models = {}


for model_name, model in models.items():

    print("\n" + "-" * 80)
    print(f"MODEL: {model_name}")
    print("-" * 80)

    # --------------------------------------------------------
    # TRAINING
    # --------------------------------------------------------

    start_train = time.perf_counter()

    model.fit(
        X_train_scaled,
        y_train
    )

    end_train = time.perf_counter()

    training_time = end_train - start_train

    print(
        f"Training time: "
        f"{training_time:.4f} seconds"
    )


    # --------------------------------------------------------
    # VALIDATION PREDICTION
    # --------------------------------------------------------

    start_val = time.perf_counter()

    y_val_pred = model.predict(
        X_val_scaled
    )

    end_val = time.perf_counter()

    validation_time = end_val - start_val


    # --------------------------------------------------------
    # TEST PREDICTION
    # --------------------------------------------------------

    start_test = time.perf_counter()

    y_test_pred = model.predict(
        X_test_scaled
    )

    end_test = time.perf_counter()

    test_prediction_time = end_test - start_test


    # --------------------------------------------------------
    # VALIDATION METRICS
    # --------------------------------------------------------

    val_accuracy = accuracy_score(
        y_val,
        y_val_pred
    )

    val_precision = precision_score(
        y_val,
        y_val_pred,
        average="weighted",
        zero_division=0
    )

    val_recall = recall_score(
        y_val,
        y_val_pred,
        average="weighted",
        zero_division=0
    )

    val_f1 = f1_score(
        y_val,
        y_val_pred,
        average="weighted",
        zero_division=0
    )


    # --------------------------------------------------------
    # TEST METRICS
    # --------------------------------------------------------

    test_accuracy = accuracy_score(
        y_test,
        y_test_pred
    )

    test_precision = precision_score(
        y_test,
        y_test_pred,
        average="weighted",
        zero_division=0
    )

    test_recall = recall_score(
        y_test,
        y_test_pred,
        average="weighted",
        zero_division=0
    )

    test_f1 = f1_score(
        y_test,
        y_test_pred,
        average="weighted",
        zero_division=0
    )


    # --------------------------------------------------------
    # STORE RESULTS
    # --------------------------------------------------------

    results.append({

        "Model": model_name,

        "Validation Accuracy": val_accuracy,
        "Validation Precision": val_precision,
        "Validation Recall": val_recall,
        "Validation F1": val_f1,

        "Test Accuracy": test_accuracy,
        "Test Precision": test_precision,
        "Test Recall": test_recall,
        "Test F1": test_f1,

        "Training Time (s)": training_time,
        "Validation Inference (s)": validation_time,
        "Test Inference (s)": test_prediction_time
    })


    trained_models[model_name] = model


    # --------------------------------------------------------
    # PRINT RESULTS
    # --------------------------------------------------------

    print("\nVALIDATION")
    print(
        f"Accuracy  : {val_accuracy:.4f}"
    )
    print(
        f"Precision : {val_precision:.4f}"
    )
    print(
        f"Recall    : {val_recall:.4f}"
    )
    print(
        f"F1-score  : {val_f1:.4f}"
    )


    print("\nTEST")
    print(
        f"Accuracy  : {test_accuracy:.4f}"
    )
    print(
        f"Precision : {test_precision:.4f}"
    )
    print(
        f"Recall    : {test_recall:.4f}"
    )
    print(
        f"F1-score  : {test_f1:.4f}"
    )


# ============================================================
# [10] BASELINE COMPARISON TABLE
# ============================================================

print("\n" + "=" * 80)
print("[10] BASELINE MODEL COMPARISON")
print("=" * 80)

baseline_results = pd.DataFrame(results)

display(
    baseline_results.round(4)
)


# ============================================================
# [11] SORT BY TEST F1
# ============================================================

print("\n[11] MODELS SORTED BY TEST F1")
print("-" * 80)

baseline_results_sorted = baseline_results.sort_values(
    by="Test F1",
    ascending=False
).reset_index(drop=True)

display(
    baseline_results_sorted.round(4)
)


# ============================================================
# [12] BEST BASELINE MODEL
# ============================================================

print("\n[12] BEST BASELINE MODEL")
print("-" * 80)

best_idx = baseline_results["Test F1"].idxmax()

best_model_name = baseline_results.loc[
    best_idx,
    "Model"
]

best_accuracy = baseline_results.loc[
    best_idx,
    "Test Accuracy"
]

best_f1 = baseline_results.loc[
    best_idx,
    "Test F1"
]

print(f"Best baseline model : {best_model_name}")
print(f"Test Accuracy       : {best_accuracy:.4f}")
print(f"Test F1-score       : {best_f1:.4f}")


# ============================================================
# [13] CLASSIFICATION REPORT
# ============================================================

print("\n" + "=" * 80)
print("[13] CLASSIFICATION REPORTS")
print("=" * 80)

for model_name, model in trained_models.items():

    y_pred = model.predict(
        X_test_scaled
    )

    print("\n" + "-" * 80)
    print(model_name)
    print("-" * 80)

    print(
        classification_report(
            y_test,
            y_pred,
            zero_division=0
        )
    )


# ============================================================
# [14] CONFUSION MATRICES
# ============================================================

print("\n" + "=" * 80)
print("[14] CONFUSION MATRICES")
print("=" * 80)

confusion_matrices = {}

for model_name, model in trained_models.items():

    y_pred = model.predict(
        X_test_scaled
    )

    cm = confusion_matrix(
        y_test,
        y_pred,
        labels=classes
    )

    confusion_matrices[model_name] = cm

    print("\n" + "-" * 80)
    print(model_name)
    print("-" * 80)

    print(
        pd.DataFrame(
            cm,
            index=classes,
            columns=classes
        )
    )


# ============================================================
# [15] SAVE RESULTS
# ============================================================

print("\n[15] SAVING BASELINE RESULTS")
print("-" * 80)

RESULTS_PATH = (
    "/kaggle/working/"
    "fors_emg_baseline_results.csv"
)

baseline_results_sorted.to_csv(
    RESULTS_PATH,
    index=False
)

print(
    f"✓ Results saved to:\n{RESULTS_PATH}"
)


# ============================================================
# [16] SAVE TRAINED BASELINE MODELS
# ============================================================

print("\n[16] SAVING TRAINED MODELS")
print("-" * 80)

import joblib

for model_name, model in trained_models.items():

    safe_name = (
        model_name
        .lower()
        .replace("-", "_")
        .replace(" ", "_")
    )

    model_path = (
        f"/kaggle/working/"
        f"baseline_{safe_name}.pkl"
    )

    joblib.dump(
        model,
        model_path
    )

    print(
        f"✓ {model_name} → {model_path}"
    )


# ============================================================
# [17] FINAL STEP 10 ASSERTIONS
# ============================================================

print("\n" + "=" * 80)
print("FINAL STEP 10 ASSERTIONS")
print("=" * 80)

assert X_train_scaled.shape == (2700, 128)
assert X_val_scaled.shape == (360, 128)
assert X_test_scaled.shape == (360, 128)

assert len(y_train) == 2700
assert len(y_val) == 360
assert len(y_test) == 360

assert len(trained_models) >= 4

assert len(baseline_results) == len(
    trained_models
)

print("✓ 2700 training recordings verified")
print("✓ 360 validation recordings verified")
print("✓ 360 test recordings verified")
print("✓ 128 normalized features verified")
print("✓ Subject-wise split preserved")
print("✓ No new random split performed")
print("✓ At least 4 baseline models trained")
print("✓ Validation metrics calculated")
print("✓ Test metrics calculated")
print("✓ Classification reports generated")
print("✓ Confusion matrices generated")
print("✓ Training/inference time measured")
print("✓ Baseline results saved")
print("✓ Trained models saved")

print("\n" + "=" * 80)
print("✓ STEP 10 — BASELINE MODELING COMPLETED")
print("=" * 80)

In [ ]:
# ============================================================

# TRACK 1: GNN ON TABLE-STYLE EMG DATA
#
# STEP 11 — GRAPH CONSTRUCTION + GNN MODEL INITIALIZATION
#
# Input:
#   scaled_train : (2700, 128)
#   scaled_val   : (360, 128)
#   scaled_test  : (360, 128)
#
# Graph:
#   8 EMG channels = 8 nodes
#   16 features/channel = 16 node features
#   128 flattened features = 8 × 16
#
# Model:
#   Graph Convolution + CNN-style feature branch
#   → Feature Fusion
#   → Classification
#
# IMPORTANT:
#   Graph is constructed AFTER subject-wise splitting.
# ============================================================

import os
import random
import time
import warnings

import numpy as np
import pandas as pd

import torch
import torch.nn as nn
import torch.nn.functional as F

from sklearn.preprocessing import StandardScaler

warnings.filterwarnings("ignore")


# ============================================================
# [1] REPRODUCIBILITY & DEVICE
# ============================================================

SEED = 42

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed(SEED)
    torch.cuda.manual_seed_all(SEED)

    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("=" * 80)
print("[1] REPRODUCIBILITY & DEVICE")
print("=" * 80)

print(f"Random seed : {SEED}")
print(f"Device      : {device}")

if torch.cuda.is_available():
    print(f"GPU         : {torch.cuda.get_device_name(0)}")


# ============================================================
# [2] CHECK / RECOVER SCALED FEATURES
# ============================================================

print("\n" + "=" * 80)
print("[2] CHECKING SCALED FEATURES")
print("=" * 80)

required_scaled = [
    "scaled_train",
    "scaled_val",
    "scaled_test"
]

missing_scaled = [
    x for x in required_scaled
    if x not in globals()
]

if len(missing_scaled) == 0:

    print("✓ scaled_train found")
    print("✓ scaled_val found")
    print("✓ scaled_test found")

else:

    print("Missing scaled variables:")

    for x in missing_scaled:
        print("   -", x)

    print("\nAttempting safe reconstruction from original features...")


    # --------------------------------------------------------
    # Possible original feature variable names
    # --------------------------------------------------------

    candidate_train = [
        "flat_train",
        "X_train",
        "train_features",
        "features_train",
        "train_flat"
    ]

    candidate_val = [
        "flat_val",
        "X_val",
        "val_features",
        "features_val",
        "validation_features",
        "val_flat"
    ]

    candidate_test = [
        "flat_test",
        "X_test",
        "test_features",
        "features_test",
        "test_flat"
    ]


    def find_existing(candidates):

        for name in candidates:
            if name in globals():
                return globals()[name], name

        return None, None


    train_source, train_name = find_existing(candidate_train)
    val_source, val_name = find_existing(candidate_val)
    test_source, test_name = find_existing(candidate_test)


    # --------------------------------------------------------
    # If original flat features are available
    # --------------------------------------------------------

    if (
        train_source is not None
        and val_source is not None
        and test_source is not None
    ):

        print(f"✓ Training source found : {train_name}")
        print(f"✓ Validation source    : {val_name}")
        print(f"✓ Test source          : {test_name}")

        train_source = np.asarray(train_source, dtype=np.float32)
        val_source = np.asarray(val_source, dtype=np.float32)
        test_source = np.asarray(test_source, dtype=np.float32)

        print("\nOriginal feature shapes:")
        print("Train :", train_source.shape)
        print("Val   :", val_source.shape)
        print("Test  :", test_source.shape)


        # ----------------------------------------------------
        # Fit scaler ONLY on training data
        # ----------------------------------------------------

        scaler = StandardScaler()

        scaled_train = scaler.fit_transform(
            train_source
        ).astype(np.float32)

        scaled_val = scaler.transform(
            val_source
        ).astype(np.float32)

        scaled_test = scaler.transform(
            test_source
        ).astype(np.float32)

        print("\n✓ StandardScaler fitted using TRAINING data only")
        print("✓ Validation transformed using training scaler")
        print("✓ Test transformed using training scaler")

    else:

        raise NameError(
            "\nCould not reconstruct scaled features.\n\n"
            "Step 11 requires either:\n"
            "  scaled_train, scaled_val, scaled_test\n"
            "OR original flat feature variables such as:\n"
            "  flat_train / flat_val / flat_test\n\n"
            "Please run your feature-scaling step before Step 11."
        )


# ============================================================
# [3] CONVERT TO NUMPY
# ============================================================

scaled_train = np.asarray(
    scaled_train,
    dtype=np.float32
)

scaled_val = np.asarray(
    scaled_val,
    dtype=np.float32
)

scaled_test = np.asarray(
    scaled_test,
    dtype=np.float32
)


# ============================================================
# [4] FEATURE SHAPE VALIDATION
# ============================================================

print("\n" + "=" * 80)
print("[4] FEATURE SHAPE VALIDATION")
print("=" * 80)

print(f"Scaled train : {scaled_train.shape}")
print(f"Scaled val   : {scaled_val.shape}")
print(f"Scaled test  : {scaled_test.shape}")


EXPECTED_FEATURES = 128
NUM_CHANNELS = 8
FEATURES_PER_CHANNEL = 16

assert scaled_train.ndim == 2
assert scaled_val.ndim == 2
assert scaled_test.ndim == 2

assert scaled_train.shape[1] == EXPECTED_FEATURES
assert scaled_val.shape[1] == EXPECTED_FEATURES
assert scaled_test.shape[1] == EXPECTED_FEATURES

print("✓ 128 features verified")
print("✓ 8 EMG channels × 16 features/channel verified")


# ============================================================
# [5] NaN / INF CHECK
# ============================================================

print("\n" + "=" * 80)
print("[5] NUMERICAL VALIDATION")
print("=" * 80)


def check_numeric(name, data):

    nan_count = np.isnan(data).sum()
    inf_count = np.isinf(data).sum()

    print(
        f"{name:<12} | "
        f"NaN = {nan_count:6d} | "
        f"Inf = {inf_count:6d}"
    )

    assert nan_count == 0
    assert inf_count == 0


check_numeric("Train", scaled_train)
check_numeric("Validation", scaled_val)
check_numeric("Test", scaled_test)

print("\n✓ No NaN/Inf detected")


# ============================================================
# [6] BUILD EMG GRAPHS
# ============================================================

print("\n" + "=" * 80)
print("[6] GRAPH CONSTRUCTION")
print("=" * 80)

print("Graph definition:")
print("  Nodes               : 8 EMG channels")
print("  Node features       : 16 features/channel")
print("  Total features      : 128")
print("  Graph type          : Fully connected weighted graph")
print("  Self connections   : Yes")


# ------------------------------------------------------------
# Channel-level adjacency
# ------------------------------------------------------------
#
# 8 EMG channels are represented as 8 nodes.
#
# We use a symmetric fully connected graph.
# Diagonal = self-loop.
#
# This gives every channel access to information
# from the other EMG channels.
# ------------------------------------------------------------

NUM_NODES = NUM_CHANNELS

adjacency = np.ones(
    (NUM_NODES, NUM_NODES),
    dtype=np.float32
)

print("\nAdjacency matrix shape:")
print(adjacency.shape)

print("\nAdjacency matrix:")
print(adjacency)


# ============================================================
# [7] NORMALIZE ADJACENCY MATRIX
# ============================================================

print("\n" + "=" * 80)
print("[7] GRAPH NORMALIZATION")
print("=" * 80)


def normalize_adjacency(A):

    A = A + np.eye(
        A.shape[0],
        dtype=np.float32
    )

    degree = A.sum(axis=1)

    degree_inv_sqrt = np.power(
        degree,
        -0.5
    )

    degree_inv_sqrt[
        np.isinf(degree_inv_sqrt)
    ] = 0.0

    D_inv_sqrt = np.diag(
        degree_inv_sqrt
    )

    A_norm = (
        D_inv_sqrt
        @ A
        @ D_inv_sqrt
    )

    return A_norm.astype(np.float32)


adjacency_normalized = normalize_adjacency(
    adjacency
)

print(
    "Normalized adjacency shape :",
    adjacency_normalized.shape
)

print("\n✓ Adjacency normalization complete")


# ============================================================
# [8] FLAT → GRAPH REPRESENTATION
# ============================================================

print("\n" + "=" * 80)
print("[8] FLAT FEATURES → GRAPH FEATURES")
print("=" * 80)


def flat_to_graph(features):

    features = np.asarray(
        features,
        dtype=np.float32
    )

    return features.reshape(
        -1,
        NUM_CHANNELS,
        FEATURES_PER_CHANNEL
    )


graph_train = flat_to_graph(
    scaled_train
)

graph_val = flat_to_graph(
    scaled_val
)

graph_test = flat_to_graph(
    scaled_test
)


print(
    "Flat train  :",
    scaled_train.shape
)

print(
    "Graph train :",
    graph_train.shape
)

print(
    "Graph val   :",
    graph_val.shape
)

print(
    "Graph test  :",
    graph_test.shape
)


assert graph_train.shape == (
    len(scaled_train),
    8,
    16
)

assert graph_val.shape == (
    len(scaled_val),
    8,
    16
)

assert graph_test.shape == (
    len(scaled_test),
    8,
    16
)

print("\n✓ Graph dimensions verified")


# ============================================================
# [9] CONVERT GRAPH DATA TO TORCH
# ============================================================

print("\n" + "=" * 80)
print("[9] CONVERTING GRAPH DATA TO PYTORCH")
print("=" * 80)


graph_train_tensor = torch.tensor(
    graph_train,
    dtype=torch.float32
)

graph_val_tensor = torch.tensor(
    graph_val,
    dtype=torch.float32
)

graph_test_tensor = torch.tensor(
    graph_test,
    dtype=torch.float32
)


adjacency_tensor = torch.tensor(
    adjacency_normalized,
    dtype=torch.float32
)


print(
    "Train graph tensor :",
    graph_train_tensor.shape
)

print(
    "Val graph tensor   :",
    graph_val_tensor.shape
)

print(
    "Test graph tensor  :",
    graph_test_tensor.shape
)

print(
    "Adjacency tensor   :",
    adjacency_tensor.shape
)


# ============================================================
# [10] GNN LAYER
# ============================================================

print("\n" + "=" * 80)
print("[10] GRAPH CONVOLUTION LAYER")
print("=" * 80)


class GraphConv(nn.Module):
    """
    Basic Graph Convolution:

        H' = A_hat H W

    where:

        H     = node features
        A_hat = normalized adjacency matrix
        W     = learnable weights
    """

    def __init__(
        self,
        in_features,
        out_features,
        dropout=0.0
    ):

        super().__init__()

        self.linear = nn.Linear(
            in_features,
            out_features
        )

        self.dropout = nn.Dropout(
            dropout
        )

        self.norm = nn.BatchNorm1d(
            out_features
        )

    def forward(
        self,
        x,
        adj
    ):

        # Graph message passing
        x = torch.matmul(
            adj,
            x
        )

        # Learnable transformation
        x = self.linear(x)

        # Batch normalization
        B, N, Fdim = x.shape

        x = x.reshape(
            B * N,
            Fdim
        )

        x = self.norm(x)

        x = x.reshape(
            B,
            N,
            Fdim
        )

        x = F.relu(x)

        x = self.dropout(x)

        return x


print("✓ GraphConv initialized")


# ============================================================
# [11] PROPOSED GNN MODEL
# ============================================================

print("\n" + "=" * 80)
print("[11] PROPOSED GNN MODEL")
print("=" * 80)


class EMG_GNN(nn.Module):

    def __init__(
        self,
        node_features=16,
        hidden_dim=64,
        graph_dim=64,
        num_classes=12,
        dropout=0.30
    ):

        super().__init__()


        # ----------------------------------------------------
        # GRAPH BRANCH
        # ----------------------------------------------------

        self.gnn1 = GraphConv(
            in_features=node_features,
            out_features=hidden_dim,
            dropout=dropout
        )

        self.gnn2 = GraphConv(
            in_features=hidden_dim,
            out_features=graph_dim,
            dropout=dropout
        )


        # ----------------------------------------------------
        # GRAPH READOUT
        # ----------------------------------------------------

        self.graph_pool = nn.Sequential(

            nn.Linear(
                graph_dim,
                64
            ),

            nn.ReLU(),

            nn.Dropout(dropout)

        )


        # ----------------------------------------------------
        # FLAT FEATURE BRANCH
        # ----------------------------------------------------

        self.flat_branch = nn.Sequential(

            nn.Linear(
                128,
                64
            ),

            nn.BatchNorm1d(64),

            nn.ReLU(),

            nn.Dropout(dropout),

            nn.Linear(
                64,
                64
            ),

            nn.ReLU()

        )


        # ----------------------------------------------------
        # FEATURE FUSION
        # ----------------------------------------------------

        self.fusion = nn.Sequential(

            nn.Linear(
                128,
                64
            ),

            nn.BatchNorm1d(64),

            nn.ReLU(),

            nn.Dropout(dropout)

        )


        # ----------------------------------------------------
        # CLASSIFIER
        # ----------------------------------------------------

        self.classifier = nn.Linear(
            64,
            num_classes
        )


    def forward(
        self,
        flat_x,
        graph_x,
        adj
    ):

        # ====================================================
        # GRAPH BRANCH
        # ====================================================

        x_graph = self.gnn1(
            graph_x,
            adj
        )

        x_graph = self.gnn2(
            x_graph,
            adj
        )

        # Global mean pooling over nodes
        x_graph = x_graph.mean(
            dim=1
        )

        x_graph = self.graph_pool(
            x_graph
        )


        # ====================================================
        # FLAT BRANCH
        # ====================================================

        x_flat = self.flat_branch(
            flat_x
        )


        # ====================================================
        # FUSION
        # ====================================================

        x = torch.cat(
            [
                x_flat,
                x_graph
            ],
            dim=1
        )

        x = self.fusion(
            x
        )


        # ====================================================
        # CLASSIFICATION
        # ====================================================

        output = self.classifier(
            x
        )

        return output


print("✓ EMG_GNN initialized")


# ============================================================
# [12] CREATE MODEL
# ============================================================

NUM_CLASSES = 12

model = EMG_GNN(
    node_features=16,
    hidden_dim=64,
    graph_dim=64,
    num_classes=NUM_CLASSES,
    dropout=0.30
).to(device)


print("\nModel:")
print(model)


# ============================================================
# [13] MODEL PARAMETER ANALYSIS
# ============================================================

print("\n" + "=" * 80)
print("[13] MODEL PARAMETER ANALYSIS")
print("=" * 80)


total_params = sum(
    p.numel()
    for p in model.parameters()
)

trainable_params = sum(
    p.numel()
    for p in model.parameters()
    if p.requires_grad
)

frozen_params = (
    total_params
    - trainable_params
)

model_size_mb = (
    total_params * 4
) / (
    1024 ** 2
)


print(
    f"Total parameters     : {total_params:,}"
)

print(
    f"Trainable parameters : {trainable_params:,}"
)

print(
    f"Frozen parameters    : {frozen_params:,}"
)

print(
    f"Approx. model size   : {model_size_mb:.3f} MB"
)


# ============================================================
# [14] FORWARD PASS VALIDATION
# ============================================================

print("\n" + "=" * 80)
print("[14] FORWARD PASS VALIDATION")
print("=" * 80)


batch_size_test = min(
    32,
    len(graph_train_tensor)
)


flat_batch = torch.tensor(
    scaled_train[:batch_size_test],
    dtype=torch.float32
).to(device)

graph_batch = graph_train_tensor[
    :batch_size_test
].to(device)

adj_batch = adjacency_tensor.to(device)


# Dummy labels only for shape verification
label_batch = torch.zeros(
    batch_size_test,
    dtype=torch.long
).to(device)


with torch.no_grad():

    output = model(
        flat_batch,
        graph_batch,
        adj_batch
    )


print(
    "Flat batch   :",
    flat_batch.shape
)

print(
    "Graph batch  :",
    graph_batch.shape
)

print(
    "Label batch  :",
    label_batch.shape
)

print(
    "Model output :",
    output.shape
)


assert output.shape == (
    batch_size_test,
    NUM_CLASSES
)

print("\n✓ Forward pass successful")


# ============================================================
# [15] LOSS FUNCTION
# ============================================================

print("\n" + "=" * 80)
print("[15] LOSS FUNCTION")
print("=" * 80)


criterion = nn.CrossEntropyLoss()

print("✓ CrossEntropyLoss initialized")


# ============================================================
# [16] OPTIMIZER
# ============================================================

print("\n" + "=" * 80)
print("[16] OPTIMIZER")
print("=" * 80)


LEARNING_RATE = 1e-3
WEIGHT_DECAY = 1e-4


optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=LEARNING_RATE,
    weight_decay=WEIGHT_DECAY
)


print("Optimizer     : AdamW")
print(f"Learning rate : {LEARNING_RATE}")
print(f"Weight decay  : {WEIGHT_DECAY}")


# ============================================================
# [17] LEARNING RATE SCHEDULER
# ============================================================

print("\n" + "=" * 80)
print("[17] LEARNING RATE SCHEDULER")
print("=" * 80)


scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer,
    mode="max",
    factor=0.5,
    patience=3
)

print("Scheduler : ReduceLROnPlateau")
print("Mode      : maximize validation Macro-F1")


# ============================================================
# [18] MIXED PRECISION
# ============================================================

print("\n" + "=" * 80)
print("[18] MIXED PRECISION")
print("=" * 80)


use_amp = torch.cuda.is_available()

try:

    scaler_amp = torch.amp.GradScaler(
        "cuda",
        enabled=use_amp
    )

except Exception:

    scaler_amp = torch.cuda.amp.GradScaler(
        enabled=use_amp
    )


print(
    f"Mixed precision enabled : {use_amp}"
)


# ============================================================
# [19] FINAL GRAPH SUMMARY
# ============================================================

print("\n" + "=" * 80)
print("[19] GRAPH SUMMARY")
print("=" * 80)

print("Dataset type        : EMG gesture classification")
print("Number of classes   : 12")
print("Number of nodes     : 8")
print("Features per node   : 16")
print("Total flat features : 128")
print("Graph type          : Fully connected")
print("Self loops          : Yes")
print("GNN layers          : 2")
print("Graph hidden size   : 64")
print("Pooling             : Global mean pooling")
print("Fusion              : Flat branch + GNN branch")
print("Classifier           : 12-class linear layer")


# ============================================================
# [20] FINAL STEP 11 ASSERTIONS
# ============================================================

print("\n" + "=" * 80)
print("FINAL STEP 11 ASSERTIONS")
print("=" * 80)


assert scaled_train.shape == (2700, 128)
assert scaled_val.shape == (360, 128)
assert scaled_test.shape == (360, 128)

assert graph_train.shape == (2700, 8, 16)
assert graph_val.shape == (360, 8, 16)
assert graph_test.shape == (360, 8, 16)

assert adjacency_normalized.shape == (8, 8)

assert NUM_CLASSES == 12

assert not np.isnan(graph_train).any()
assert not np.isnan(graph_val).any()
assert not np.isnan(graph_test).any()

assert not np.isinf(graph_train).any()
assert not np.isinf(graph_val).any()
assert not np.isinf(graph_test).any()


print("✓ 2700 training recordings verified")
print("✓ 360 validation recordings verified")
print("✓ 360 test recordings verified")
print("✓ 8 EMG channels verified")
print("✓ 16 features/channel verified")
print("✓ 128 flattened features verified")
print("✓ 12 gesture classes verified")
print("✓ No NaN/Inf detected")
print("✓ Graph constructed after data split")
print("✓ Graph tensor construction verified")
print("✓ CNN/flat feature branch initialized")
print("✓ GNN graph branch initialized")
print("✓ Feature fusion initialized")
print("✓ Forward pass successful")
print("✓ CrossEntropyLoss initialized")
print("✓ AdamW initialized")
print("✓ Scheduler initialized")
print("✓ Mixed precision configured")

print("\n" + "=" * 80)
print("✓ STEP 11 COMPLETE")
print("=" * 80)

In [ ]:
# ============================================================

# TRACK 1: GNN ON TABLE-STYLE EMG DATA
#
# STEP 12 — TRAIN PROPOSED EMG GNN
#
# Dataset:
#   Train      : 2700
#   Validation : 360
#   Test       : 360
#
# Graph:
#   Nodes      : 8 EMG channels
#   Features   : 16/channel
#   Input      : 8 × 16
#   Classes    : 12
#
# IMPORTANT:
#   - NO random re-splitting
#   - Subject-wise split preserved
#   - Best model selected using Validation Macro-F1
#   - Test set is NOT used for model selection
# ============================================================


# ============================================================
# [1] IMPORTS
# ============================================================

import os
import time
import copy
import random
import warnings

import numpy as np
import pandas as pd

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

warnings.filterwarnings("ignore")


# ============================================================
# [2] REPRODUCIBILITY
# ============================================================

SEED = 42

random.seed(SEED)
np.random.seed(SEED)

torch.manual_seed(SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed(SEED)
    torch.cuda.manual_seed_all(SEED)

    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


# ============================================================
# [3] DEVICE
# ============================================================

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print("=" * 80)
print("[1] REPRODUCIBILITY & DEVICE")
print("=" * 80)

print("Random seed :", SEED)
print("Device      :", device)

if torch.cuda.is_available():
    print(
        "GPU         :",
        torch.cuda.get_device_name(0)
    )


# ============================================================
# [4] VERIFY STEP 11 VARIABLES
# ============================================================

print("\n" + "=" * 80)
print("[2] CHECKING STEP 11 VARIABLES")
print("=" * 80)


required_variables = [
    "scaled_train",
    "scaled_val",
    "scaled_test",
    "graph_train",
    "graph_val",
    "graph_test",
    "adjacency_tensor",
    "model",
    "criterion",
    "optimizer",
    "scheduler",
    "scaler_amp"
]


missing_variables = [
    v for v in required_variables
    if v not in globals()
]


if len(missing_variables) > 0:

    print("❌ Missing variables:")

    for v in missing_variables:
        print("   -", v)

    raise NameError(
        "\nRequired Step 11 variables are missing.\n"
        "Please run the complete Step 11 cell before Step 12."
    )


print("✓ All Step 11 variables found")


# ============================================================
# [5] DATA SHAPE VERIFICATION
# ============================================================

print("\n" + "=" * 80)
print("[3] DATA SHAPE VERIFICATION")
print("=" * 80)


assert scaled_train.shape == (2700, 128)
assert scaled_val.shape == (360, 128)
assert scaled_test.shape == (360, 128)

assert graph_train.shape == (2700, 8, 16)
assert graph_val.shape == (360, 8, 16)
assert graph_test.shape == (360, 8, 16)


print("Flat train :", scaled_train.shape)
print("Flat val   :", scaled_val.shape)
print("Flat test  :", scaled_test.shape)

print("Graph train:", graph_train.shape)
print("Graph val  :", graph_val.shape)
print("Graph test :", graph_test.shape)

print("\n✓ All expected dimensions verified")


# ============================================================
# [6] FIND LABEL VARIABLES
# ============================================================

print("\n" + "=" * 80)
print("[4] CHECKING LABEL VARIABLES")
print("=" * 80)


possible_train_labels = [
    "y_train",
    "train_labels",
    "labels_train",
    "train_y"
]

possible_val_labels = [
    "y_val",
    "val_labels",
    "labels_val",
    "validation_labels",
    "val_y"
]

possible_test_labels = [
    "y_test",
    "test_labels",
    "labels_test",
    "test_y"
]


def find_variable(candidates):

    for name in candidates:

        if name in globals():

            return globals()[name], name

    return None, None


y_train_source, y_train_name = find_variable(
    possible_train_labels
)

y_val_source, y_val_name = find_variable(
    possible_val_labels
)

y_test_source, y_test_name = find_variable(
    possible_test_labels
)


if (
    y_train_source is None
    or y_val_source is None
    or y_test_source is None
):

    print("❌ Could not automatically find labels.")

    print("\nExpected one of:")

    print("Train:", possible_train_labels)
    print("Val  :", possible_val_labels)
    print("Test :", possible_test_labels)

    raise NameError(
        "\nTraining labels were not found.\n"
        "Run the Step 8/9 feature-label preparation cell first."
    )


print("✓ Training labels :", y_train_name)
print("✓ Validation labels:", y_val_name)
print("✓ Test labels      :", y_test_name)


# ============================================================
# [7] CONVERT LABELS TO INTEGER
# ============================================================

print("\n" + "=" * 80)
print("[5] LABEL PREPARATION")
print("=" * 80)


def convert_labels(labels):

    # Pandas Series
    if isinstance(labels, pd.Series):

        labels = labels.values

    # Pandas DataFrame
    elif isinstance(labels, pd.DataFrame):

        if labels.shape[1] != 1:

            raise ValueError(
                "Label DataFrame must contain one column."
            )

        labels = labels.iloc[:, 0].values

    labels = np.asarray(labels)

    return labels


y_train_raw = convert_labels(
    y_train_source
)

y_val_raw = convert_labels(
    y_val_source
)

y_test_raw = convert_labels(
    y_test_source
)


print("Raw train labels:",
      y_train_raw.shape)

print("Raw val labels  :",
      y_val_raw.shape)

print("Raw test labels :",
      y_test_raw.shape)


# ============================================================
# [8] LABEL ENCODING
# ============================================================

# If labels are already integer 0...11,
# keep them unchanged.
#
# Otherwise encode string labels consistently.

all_labels = np.concatenate(
    [
        y_train_raw,
        y_val_raw,
        y_test_raw
    ]
)


unique_labels = np.unique(
    all_labels
)


print("\nUnique labels:")
print(unique_labels)


if (
    np.issubdtype(
        all_labels.dtype,
        np.integer
    )
    and
    set(unique_labels.tolist())
    == set(range(12))
):

    y_train = y_train_raw.astype(
        np.int64
    )

    y_val = y_val_raw.astype(
        np.int64
    )

    y_test = y_test_raw.astype(
        np.int64
    )

    label_mapping = {
        int(i): int(i)
        for i in range(12)
    }

    print("\n✓ Labels already encoded as 0–11")

else:

    label_names = sorted(
        [
            str(x)
            for x in unique_labels
        ]
    )

    label_to_id = {
        name: idx
        for idx, name
        in enumerate(label_names)
    }

    y_train = np.array(
        [
            label_to_id[str(x)]
            for x in y_train_raw
        ],
        dtype=np.int64
    )

    y_val = np.array(
        [
            label_to_id[str(x)]
            for x in y_val_raw
        ],
        dtype=np.int64
    )

    y_test = np.array(
        [
            label_to_id[str(x)]
            for x in y_test_raw
        ],
        dtype=np.int64
    )

    label_mapping = {
        idx: name
        for name, idx
        in label_to_id.items()
    }

    print("\n✓ String labels encoded")


# ============================================================
# [9] LABEL VALIDATION
# ============================================================

assert len(y_train) == 2700
assert len(y_val) == 360
assert len(y_test) == 360

assert y_train.min() >= 0
assert y_train.max() < 12

assert y_val.min() >= 0
assert y_val.max() < 12

assert y_test.min() >= 0
assert y_test.max() < 12


print("\n✓ 2700 training labels verified")
print("✓ 360 validation labels verified")
print("✓ 360 test labels verified")
print("✓ 12 classes verified")


# ============================================================
# [10] CLASS DISTRIBUTION
# ============================================================

print("\n" + "=" * 80)
print("[6] CLASS DISTRIBUTION")
print("=" * 80)


for split_name, labels in [
    ("Train", y_train),
    ("Validation", y_val),
    ("Test", y_test)
]:

    counts = np.bincount(
        labels,
        minlength=12
    )

    print(f"\n{split_name}:")

    for cls, count in enumerate(counts):

        print(
            f"Class {cls:2d} : {count:4d}"
        )


# ============================================================
# [11] DATASET CLASS
# ============================================================

print("\n" + "=" * 80)
print("[7] CREATING PYTORCH DATASETS")
print("=" * 80)


class EMGGraphDataset(Dataset):

    def __init__(
        self,
        flat_features,
        graph_features,
        labels
    ):

        self.flat_features = torch.tensor(
            flat_features,
            dtype=torch.float32
        )

        self.graph_features = torch.tensor(
            graph_features,
            dtype=torch.float32
        )

        self.labels = torch.tensor(
            labels,
            dtype=torch.long
        )

    def __len__(self):

        return len(self.labels)

    def __getitem__(self, index):

        return (
            self.flat_features[index],
            self.graph_features[index],
            self.labels[index]
        )


train_dataset = EMGGraphDataset(
    scaled_train,
    graph_train,
    y_train
)

val_dataset = EMGGraphDataset(
    scaled_val,
    graph_val,
    y_val
)

test_dataset = EMGGraphDataset(
    scaled_test,
    graph_test,
    y_test
)


print(
    "Training dataset   :",
    len(train_dataset)
)

print(
    "Validation dataset :",
    len(val_dataset)
)

print(
    "Test dataset       :",
    len(test_dataset)
)


# ============================================================
# [12] DATALOADERS
# ============================================================

print("\n" + "=" * 80)
print("[8] DATALOADERS")
print("=" * 80)


BATCH_SIZE = 32

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=2,
    pin_memory=torch.cuda.is_available()
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=2,
    pin_memory=torch.cuda.is_available()
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=2,
    pin_memory=torch.cuda.is_available()
)


print("Batch size :", BATCH_SIZE)
print("Train batches:", len(train_loader))
print("Val batches  :", len(val_loader))
print("Test batches :", len(test_loader))


# ============================================================
# [13] CLASS WEIGHTS
# ============================================================
#
# IMPORTANT:
# The course requires imbalance handling.
#
# We calculate class weights from TRAINING DATA ONLY.
# Validation/test are never used to calculate weights.
# ============================================================

print("\n" + "=" * 80)
print("[9] CLASS IMBALANCE HANDLING")
print("=" * 80)


train_counts = np.bincount(
    y_train,
    minlength=12
)


class_weights = (
    len(y_train)
    /
    (
        12
        *
        np.maximum(
            train_counts,
            1
        )
    )
)


class_weights = torch.tensor(
    class_weights,
    dtype=torch.float32
).to(device)


print("Class weights:")

for i, weight in enumerate(
    class_weights.detach().cpu().numpy()
):

    print(
        f"Class {i:2d}: "
        f"{weight:.4f}"
    )


# Replace the loss with weighted CE
criterion = nn.CrossEntropyLoss(
    weight=class_weights
)


print("\n✓ Weighted CrossEntropyLoss initialized")


# ============================================================
# [14] MODEL CHECK
# ============================================================

print("\n" + "=" * 80)
print("[10] MODEL CHECK")
print("=" * 80)


model = model.to(device)


total_params = sum(
    p.numel()
    for p in model.parameters()
)

trainable_params = sum(
    p.numel()
    for p in model.parameters()
    if p.requires_grad
)


print(
    f"Total parameters     : {total_params:,}"
)

print(
    f"Trainable parameters : {trainable_params:,}"
)


# ============================================================
# [15] TRAINING SETTINGS
# ============================================================

print("\n" + "=" * 80)
print("[11] TRAINING CONFIGURATION")
print("=" * 80)


EPOCHS = 100

EARLY_STOPPING_PATIENCE = 15

GRADIENT_CLIP = 1.0

BEST_MODEL_PATH = (
    "/kaggle/working/"
    "best_emg_gnn_step12.pth"
)


print("Epochs              :", EPOCHS)
print("Batch size          :", BATCH_SIZE)
print("Learning rate       :",
      optimizer.param_groups[0]["lr"])
print("Gradient clipping   :", GRADIENT_CLIP)
print(
    "Early stopping      :",
    EARLY_STOPPING_PATIENCE
)

print(
    "Best model path     :",
    BEST_MODEL_PATH
)


# ============================================================
# [16] TRAINING HISTORY
# ============================================================

history = {

    "train_loss": [],
    "train_accuracy": [],
    "train_precision": [],
    "train_recall": [],
    "train_f1": [],

    "val_loss": [],
    "val_accuracy": [],
    "val_precision": [],
    "val_recall": [],
    "val_f1": [],

    "learning_rate": [],
    "epoch_time": []
}


# ============================================================
# [17] BEST MODEL VARIABLES
# ============================================================

best_val_f1 = -np.inf
best_val_loss = np.inf

best_epoch = 0

best_model_weights = copy.deepcopy(
    model.state_dict()
)

epochs_without_improvement = 0


# ============================================================
# [18] TRAIN ONE EPOCH
# ============================================================

def train_one_epoch(
    model,
    loader,
    optimizer,
    criterion,
    scaler_amp,
    adjacency,
    device
):

    model.train()

    running_loss = 0.0

    all_predictions = []
    all_targets = []

    total_samples = 0


    for (
        flat_x,
        graph_x,
        labels
    ) in loader:

        flat_x = flat_x.to(
            device,
            non_blocking=True
        )

        graph_x = graph_x.to(
            device,
            non_blocking=True
        )

        labels = labels.to(
            device,
            non_blocking=True
        )


        optimizer.zero_grad(
            set_to_none=True
        )


        # ----------------------------------------------------
        # Mixed precision forward pass
        # ----------------------------------------------------

        with torch.autocast(
            device_type="cuda",
            dtype=torch.float16,
            enabled=torch.cuda.is_available()
        ):

            outputs = model(
                flat_x,
                graph_x,
                adjacency
            )

            loss = criterion(
                outputs,
                labels
            )


        # ----------------------------------------------------
        # Backpropagation
        # ----------------------------------------------------

        if torch.cuda.is_available():

            scaler_amp.scale(
                loss
            ).backward()

            scaler_amp.unscale_(
                optimizer
            )

            torch.nn.utils.clip_grad_norm_(
                model.parameters(),
                max_norm=GRADIENT_CLIP
            )

            scaler_amp.step(
                optimizer
            )

            scaler_amp.update()

        else:

            loss.backward()

            torch.nn.utils.clip_grad_norm_(
                model.parameters(),
                max_norm=GRADIENT_CLIP
            )

            optimizer.step()


        # ----------------------------------------------------
        # Statistics
        # ----------------------------------------------------

        batch_size = labels.size(0)

        running_loss += (
            loss.item()
            * batch_size
        )

        total_samples += batch_size


        predictions = torch.argmax(
            outputs,
            dim=1
        )


        all_predictions.extend(
            predictions.detach()
            .cpu()
            .numpy()
        )

        all_targets.extend(
            labels.detach()
            .cpu()
            .numpy()
        )


    epoch_loss = (
        running_loss
        /
        total_samples
    )


    epoch_accuracy = accuracy_score(
        all_targets,
        all_predictions
    )

    epoch_precision = precision_score(
        all_targets,
        all_predictions,
        average="macro",
        zero_division=0
    )

    epoch_recall = recall_score(
        all_targets,
        all_predictions,
        average="macro",
        zero_division=0
    )

    epoch_f1 = f1_score(
        all_targets,
        all_predictions,
        average="macro",
        zero_division=0
    )


    return (
        epoch_loss,
        epoch_accuracy,
        epoch_precision,
        epoch_recall,
        epoch_f1
    )


# ============================================================
# [19] VALIDATION FUNCTION
# ============================================================

@torch.no_grad()
def evaluate_model(
    model,
    loader,
    criterion,
    adjacency,
    device
):

    model.eval()

    running_loss = 0.0

    total_samples = 0

    all_predictions = []
    all_targets = []


    for (
        flat_x,
        graph_x,
        labels
    ) in loader:

        flat_x = flat_x.to(
            device,
            non_blocking=True
        )

        graph_x = graph_x.to(
            device,
            non_blocking=True
        )

        labels = labels.to(
            device,
            non_blocking=True
        )


        with torch.autocast(
            device_type="cuda",
            dtype=torch.float16,
            enabled=torch.cuda.is_available()
        ):

            outputs = model(
                flat_x,
                graph_x,
                adjacency
            )

            loss = criterion(
                outputs,
                labels
            )


        batch_size = labels.size(0)

        running_loss += (
            loss.item()
            * batch_size
        )

        total_samples += batch_size


        predictions = torch.argmax(
            outputs,
            dim=1
        )


        all_predictions.extend(
            predictions.cpu().numpy()
        )

        all_targets.extend(
            labels.cpu().numpy()
        )


    epoch_loss = (
        running_loss
        /
        total_samples
    )


    epoch_accuracy = accuracy_score(
        all_targets,
        all_predictions
    )

    epoch_precision = precision_score(
        all_targets,
        all_predictions,
        average="macro",
        zero_division=0
    )

    epoch_recall = recall_score(
        all_targets,
        all_predictions,
        average="macro",
        zero_division=0
    )

    epoch_f1 = f1_score(
        all_targets,
        all_predictions,
        average="macro",
        zero_division=0
    )


    return (
        epoch_loss,
        epoch_accuracy,
        epoch_precision,
        epoch_recall,
        epoch_f1
    )


# ============================================================
# [20] TRAINING LOOP
# ============================================================

print("\n" + "=" * 80)
print("[12] STARTING GNN TRAINING")
print("=" * 80)


adjacency_device = adjacency_tensor.to(
    device
)


training_start = time.time()


for epoch in range(1, EPOCHS + 1):

    epoch_start = time.time()


    # ========================================================
    # TRAIN
    # ========================================================

    (
        train_loss,
        train_acc,
        train_precision,
        train_recall,
        train_f1
    ) = train_one_epoch(

        model=model,

        loader=train_loader,

        optimizer=optimizer,

        criterion=criterion,

        scaler_amp=scaler_amp,

        adjacency=adjacency_device,

        device=device
    )


    # ========================================================
    # VALIDATION
    # ========================================================

    (
        val_loss,
        val_acc,
        val_precision,
        val_recall,
        val_f1
    ) = evaluate_model(

        model=model,

        loader=val_loader,

        criterion=criterion,

        adjacency=adjacency_device,

        device=device
    )


    # ========================================================
    # SCHEDULER
    # ========================================================

    scheduler.step(
        val_f1
    )


    current_lr = (
        optimizer.param_groups[0]["lr"]
    )


    epoch_time = (
        time.time()
        -
        epoch_start
    )


    # ========================================================
    # STORE HISTORY
    # ========================================================

    history["train_loss"].append(
        train_loss
    )

    history["train_accuracy"].append(
        train_acc
    )

    history["train_precision"].append(
        train_precision
    )

    history["train_recall"].append(
        train_recall
    )

    history["train_f1"].append(
        train_f1
    )


    history["val_loss"].append(
        val_loss
    )

    history["val_accuracy"].append(
        val_acc
    )

    history["val_precision"].append(
        val_precision
    )

    history["val_recall"].append(
        val_recall
    )

    history["val_f1"].append(
        val_f1
    )

    history["learning_rate"].append(
        current_lr
    )

    history["epoch_time"].append(
        epoch_time
    )


    # ========================================================
    # SAVE BEST MODEL
    #
    # Primary criterion = Validation Macro-F1
    #
    # Test data is NEVER used here.
    # ========================================================

    if val_f1 > best_val_f1:

        best_val_f1 = val_f1

        best_val_loss = val_loss

        best_epoch = epoch

        best_model_weights = copy.deepcopy(
            model.state_dict()
        )

        epochs_without_improvement = 0


        torch.save(
            {
                "epoch": epoch,

                "model_state_dict":
                    model.state_dict(),

                "optimizer_state_dict":
                    optimizer.state_dict(),

                "scheduler_state_dict":
                    scheduler.state_dict(),

                "best_val_f1":
                    best_val_f1,

                "best_val_loss":
                    best_val_loss,

                "history":
                    history,

                "seed":
                    SEED,

                "num_classes":
                    12,

                "num_nodes":
                    8,

                "features_per_node":
                    16
            },

            BEST_MODEL_PATH
        )

        best_marker = " ★ BEST"


    else:

        epochs_without_improvement += 1

        best_marker = ""


    # ========================================================
    # PRINT EPOCH
    # ========================================================

    print(
        f"Epoch {epoch:03d}/{EPOCHS} | "
        f"Train Loss: {train_loss:.4f} | "
        f"Train Acc: {train_acc:.4f} | "
        f"Train F1: {train_f1:.4f} | "
        f"Val Loss: {val_loss:.4f} | "
        f"Val Acc: {val_acc:.4f} | "
        f"Val F1: {val_f1:.4f} | "
        f"LR: {current_lr:.6f} | "
        f"Time: {epoch_time:.2f}s"
        f"{best_marker}"
    )


    # ========================================================
    # EARLY STOPPING
    # ========================================================

    if (
        epochs_without_improvement
        >= EARLY_STOPPING_PATIENCE
    ):

        print(
            f"\n⚠ Early stopping at epoch "
            f"{epoch}"
        )

        break


# ============================================================
# [21] TRAINING COMPLETE
# ============================================================

total_training_time = (
    time.time()
    -
    training_start
)


print("\n" + "=" * 80)
print("[13] TRAINING COMPLETE")
print("=" * 80)

print(
    f"Epochs completed : {len(history['train_loss'])}"
)

print(
    f"Best epoch       : {best_epoch}"
)

print(
    f"Best Val Macro-F1: {best_val_f1:.4f}"
)

print(
    f"Total time       : "
    f"{total_training_time:.2f} sec"
)

print(
    f"Total time       : "
    f"{total_training_time/60:.2f} min"
)

print(
    "Best model saved :",
    BEST_MODEL_PATH
)


# ============================================================
# [22] RESTORE BEST MODEL
# ============================================================

print("\n" + "=" * 80)
print("[14] RESTORING BEST MODEL")
print("=" * 80)


model.load_state_dict(
    best_model_weights
)

model.eval()


print(
    f"✓ Best epoch {best_epoch} restored"
)

print(
    f"✓ Best validation Macro-F1 = "
    f"{best_val_f1:.4f}"
)


# ============================================================
# [23] FINAL VALIDATION EVALUATION
# ============================================================

print("\n" + "=" * 80)
print("[15] FINAL VALIDATION PERFORMANCE")
print("=" * 80)


(
    final_val_loss,
    final_val_acc,
    final_val_precision,
    final_val_recall,
    final_val_f1
) = evaluate_model(

    model=model,

    loader=val_loader,

    criterion=criterion,

    adjacency=adjacency_device,

    device=device
)


print(
    f"Validation Loss      : "
    f"{final_val_loss:.4f}"
)

print(
    f"Validation Accuracy  : "
    f"{final_val_acc:.4f}"
)

print(
    f"Validation Precision : "
    f"{final_val_precision:.4f}"
)

print(
    f"Validation Recall    : "
    f"{final_val_recall:.4f}"
)

print(
    f"Validation Macro-F1  : "
    f"{final_val_f1:.4f}"
)


# ============================================================
# [24] FINAL TEST EVALUATION
# ============================================================
#
# IMPORTANT:
# Test set is evaluated ONLY AFTER model selection.
# ============================================================

print("\n" + "=" * 80)
print("[16] FINAL TEST PERFORMANCE")
print("=" * 80)


test_start = time.time()


(
    final_test_loss,
    final_test_acc,
    final_test_precision,
    final_test_recall,
    final_test_f1
) = evaluate_model(

    model=model,

    loader=test_loader,

    criterion=criterion,

    adjacency=adjacency_device,

    device=device
)


test_inference_time = (
    time.time()
    -
    test_start
)


print(
    f"Test Loss            : "
    f"{final_test_loss:.4f}"
)

print(
    f"Test Accuracy        : "
    f"{final_test_acc:.4f}"
)

print(
    f"Test Precision       : "
    f"{final_test_precision:.4f}"
)

print(
    f"Test Recall          : "
    f"{final_test_recall:.4f}"
)

print(
    f"Test Macro-F1        : "
    f"{final_test_f1:.4f}"
)

print(
    f"Test inference time  : "
    f"{test_inference_time:.4f} sec"
)


# ============================================================
# [25] SAVE TRAINING HISTORY
# ============================================================

print("\n" + "=" * 80)
print("[17] SAVING TRAINING HISTORY")
print("=" * 80)


history_df = pd.DataFrame(
    history
)

history_path = (
    "/kaggle/working/"
    "step12_emg_gnn_training_history.csv"
)

history_df.to_csv(
    history_path,
    index=False
)


print(
    "✓ History saved:",
    history_path
)


# ============================================================
# [26] FINAL STEP 12 ASSERTIONS
# ============================================================

print("\n" + "=" * 80)
print("FINAL STEP 12 ASSERTIONS")
print("=" * 80)


assert len(history["train_loss"]) > 0

assert len(history["val_loss"]) == len(
    history["train_loss"]
)

assert best_epoch >= 1

assert np.isfinite(
    final_val_loss
)

assert np.isfinite(
    final_val_f1
)

assert np.isfinite(
    final_test_loss
)

assert np.isfinite(
    final_test_f1
)

assert 0.0 <= final_val_acc <= 1.0
assert 0.0 <= final_test_acc <= 1.0

assert 0.0 <= final_val_f1 <= 1.0
assert 0.0 <= final_test_f1 <= 1.0


print("✓ Training completed")
print("✓ Best model selected using validation Macro-F1")
print("✓ Test set not used for model selection")
print("✓ 2700 training samples preserved")
print("✓ 360 validation samples preserved")
print("✓ 360 test samples preserved")
print("✓ 12-class classification verified")
print("✓ GNN graph branch trained")
print("✓ Flat feature branch trained")
print("✓ Feature fusion trained")
print("✓ Best checkpoint saved")
print("✓ Training history saved")

print("\n" + "=" * 80)
print("✓ STEP 12 COMPLETE")
print("=" * 80)


# ============================================================
# [27] FINAL RESULT SUMMARY
# ============================================================

print("\n" + "=" * 80)
print("STEP 12 RESULT SUMMARY")
print("=" * 80)

print(
    f"Best Epoch              : {best_epoch}"
)

print(
    f"Best Validation Macro-F1: "
    f"{best_val_f1:.4f}"
)

print(
    f"Validation Accuracy     : "
    f"{final_val_acc:.4f}"
)

print(
    f"Validation Macro-F1     : "
    f"{final_val_f1:.4f}"
)

print(
    f"Test Accuracy           : "
    f"{final_test_acc:.4f}"
)

print(
    f"Test Macro-F1           : "
    f"{final_test_f1:.4f}"
)

print(
    f"Training Time           : "
    f"{total_training_time:.2f} sec"
)

print(
    f"Test Inference Time     : "
    f"{test_inference_time:.4f} sec"
)

print(
    "\nBest model:",
    BEST_MODEL_PATH
)

In [ ]:
# ================================================================
# CSE475 — STEP 13
# IMPROVED GNN + ABLATION STUDY
#
# Track 1: GNN on table-style EMG data
#
# Experiments:
#   1. Flat MLP
#   2. GCN
#   3. GraphSAGE
#   4. GAT
#   5. GAT + Flat Feature Fusion
#   6. Edge-weight ablation
#
# IMPORTANT:
#   - Graph is constructed AFTER train/val/test split
#   - Graph structure is learned from TRAINING data only
#   - No random re-splitting
#   - No test information used during graph construction
# ================================================================


# ================================================================
# [1] IMPORT LIBRARIES
# ================================================================

import os
import time
import copy
import random
import warnings

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import torch
import torch.nn as nn
import torch.nn.functional as F

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

warnings.filterwarnings("ignore")


# ================================================================
# [2] REPRODUCIBILITY
# ================================================================

SEED = 42

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed(SEED)
    torch.cuda.manual_seed_all(SEED)

torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("=" * 80)
print("[1] REPRODUCIBILITY & DEVICE")
print("=" * 80)
print("Random seed :", SEED)
print("Device      :", device)

if torch.cuda.is_available():
    print("GPU         :", torch.cuda.get_device_name(0))


# ================================================================
# [3] CHECK STEP 9 VARIABLES
# ================================================================

print("\n" + "=" * 80)
print("[2] CHECKING STEP 9 VARIABLES")
print("=" * 80)

required = [
    "scaled_train",
    "scaled_val",
    "scaled_test"
]

missing = [v for v in required if v not in globals()]

if missing:
    print("❌ Missing variables:")
    for v in missing:
        print("   -", v)

    raise NameError(
        "\nStep 13 requires scaled_train, scaled_val and scaled_test.\n"
        "Please run your successful Step 9 normalization cell first."
    )

print("✓ scaled_train found")
print("✓ scaled_val found")
print("✓ scaled_test found")


# ================================================================
# [4] CONVERT FEATURES TO NUMPY
# ================================================================

X_train_flat = np.asarray(scaled_train, dtype=np.float32)
X_val_flat   = np.asarray(scaled_val, dtype=np.float32)
X_test_flat  = np.asarray(scaled_test, dtype=np.float32)

print("\n" + "=" * 80)
print("[3] FEATURE SHAPES")
print("=" * 80)

print("Train flat :", X_train_flat.shape)
print("Val flat   :", X_val_flat.shape)
print("Test flat  :", X_test_flat.shape)

assert X_train_flat.shape == (2700, 128)
assert X_val_flat.shape == (360, 128)
assert X_test_flat.shape == (360, 128)

print("✓ Expected 128-dimensional features confirmed")


# ================================================================
# [5] FIND LABEL VARIABLES
# ================================================================

print("\n" + "=" * 80)
print("[4] FINDING LABEL VARIABLES")
print("=" * 80)


def find_variable(candidates):
    for name in candidates:
        if name in globals():
            return globals()[name], name
    return None, None


y_train_raw, y_train_name = find_variable([
    "y_train",
    "train_labels",
    "labels_train",
    "train_y",
    "Y_train"
])

y_val_raw, y_val_name = find_variable([
    "y_val",
    "y_valid",
    "val_labels",
    "labels_val",
    "validation_labels",
    "val_y",
    "Y_val"
])

y_test_raw, y_test_name = find_variable([
    "y_test",
    "test_labels",
    "labels_test",
    "test_y",
    "Y_test"
])

print("Train label variable:", y_train_name)
print("Val label variable  :", y_val_name)
print("Test label variable :", y_test_name)


# ================================================================
# [6] FALLBACK: READ LABELS FROM METADATA
# ================================================================

def find_metadata_label(metadata_candidates):

    for name in metadata_candidates:

        if name not in globals():
            continue

        obj = globals()[name]

        if isinstance(obj, pd.DataFrame):

            possible_columns = [
                "label",
                "Label",
                "class",
                "Class",
                "gesture",
                "Gesture",
                "target",
                "Target"
            ]

            for col in possible_columns:
                if col in obj.columns:
                    return obj[col].values, f"{name}['{col}']"

    return None, None


if y_train_raw is None:

    y_train_raw, source = find_metadata_label([
        "metadata_train",
        "train_metadata",
        "meta_train"
    ])

    if y_train_raw is not None:
        y_train_name = source


if y_val_raw is None:

    y_val_raw, source = find_metadata_label([
        "metadata_val",
        "metadata_validation",
        "val_metadata",
        "validation_metadata"
    ])

    if y_val_raw is not None:
        y_val_name = source


if y_test_raw is None:

    y_test_raw, source = find_metadata_label([
        "metadata_test",
        "test_metadata"
    ])

    if y_test_raw is not None:
        y_test_name = source


if y_train_raw is None or y_val_raw is None or y_test_raw is None:

    raise NameError(
        "\nCould not automatically find labels.\n\n"
        "Expected variables such as:\n"
        "y_train, y_val, y_test\n"
        "OR metadata_train / metadata_val / metadata_test "
        "with a label/class column."
    )


# ================================================================
# [7] ENCODE LABELS SAFELY
# ================================================================

print("\n" + "=" * 80)
print("[5] LABEL ENCODING")
print("=" * 80)

y_train_raw = np.asarray(y_train_raw)
y_val_raw   = np.asarray(y_val_raw)
y_test_raw  = np.asarray(y_test_raw)

all_labels = np.concatenate([
    y_train_raw,
    y_val_raw,
    y_test_raw
])

unique_labels = list(pd.unique(all_labels))

# Sort if possible
try:
    unique_labels = sorted(unique_labels)
except:
    pass

label_to_id = {
    label: idx for idx, label in enumerate(unique_labels)
}

id_to_label = {
    idx: str(label) for label, idx in label_to_id.items()
}


def encode_labels(y):
    return np.array(
        [label_to_id[v] for v in y],
        dtype=np.int64
    )


y_train = encode_labels(y_train_raw)
y_val   = encode_labels(y_val_raw)
y_test  = encode_labels(y_test_raw)

NUM_CLASSES = len(unique_labels)

print("Classes      :", NUM_CLASSES)
print("Class names  :")

for i, label in id_to_label.items():
    print(f"  {i:2d} -> {label}")

assert NUM_CLASSES == 12

print("✓ 12 gesture classes confirmed")


# ================================================================
# [8] BASIC DATA VALIDATION
# ================================================================

print("\n" + "=" * 80)
print("[6] DATA VALIDATION")
print("=" * 80)

assert len(X_train_flat) == len(y_train)
assert len(X_val_flat) == len(y_val)
assert len(X_test_flat) == len(y_test)

assert not np.isnan(X_train_flat).any()
assert not np.isnan(X_val_flat).any()
assert not np.isnan(X_test_flat).any()

assert not np.isinf(X_train_flat).any()
assert not np.isinf(X_val_flat).any()
assert not np.isinf(X_test_flat).any()

print("✓ Train alignment verified")
print("✓ Validation alignment verified")
print("✓ Test alignment verified")
print("✓ No NaN/Inf detected")


# ================================================================
# [9] CONVERT 128 FEATURES → 8 GRAPH NODES × 16 FEATURES
# ================================================================

NUM_NODES = 8
FEATURES_PER_NODE = 16

X_train_graph = X_train_flat.reshape(
    -1,
    NUM_NODES,
    FEATURES_PER_NODE
)

X_val_graph = X_val_flat.reshape(
    -1,
    NUM_NODES,
    FEATURES_PER_NODE
)

X_test_graph = X_test_flat.reshape(
    -1,
    NUM_NODES,
    FEATURES_PER_NODE
)

print("\n" + "=" * 80)
print("[7] GRAPH REPRESENTATION")
print("=" * 80)

print("Train graph :", X_train_graph.shape)
print("Val graph   :", X_val_graph.shape)
print("Test graph  :", X_test_graph.shape)

assert X_train_graph.shape == (2700, 8, 16)
assert X_val_graph.shape == (360, 8, 16)
assert X_test_graph.shape == (360, 8, 16)

print("✓ 8 EMG channels = 8 graph nodes")
print("✓ 16 features per node")


# ================================================================
# [10] TRAIN-ONLY GRAPH CONSTRUCTION
#
# IMPORTANT:
# The graph is constructed ONLY using X_train_graph.
# Validation and test data never participate in graph construction.
# ================================================================

print("\n" + "=" * 80)
print("[8] TRAIN-ONLY GRAPH CONSTRUCTION")
print("=" * 80)


def build_channel_graph(X_graph, top_k=3):

    """
    Build an EMG channel graph from TRAINING DATA ONLY.

    Each node = EMG channel.

    Edge weight = absolute correlation between channel
    feature representations.

    top_k strongest neighbors are retained per node.
    """

    n_samples, n_nodes, n_features = X_graph.shape

    # Flatten each channel's feature values across recordings
    channel_vectors = []

    for node in range(n_nodes):

        channel_data = X_graph[:, node, :]

        # Flatten recordings × 16 features
        vector = channel_data.reshape(-1)

        channel_vectors.append(vector)

    channel_vectors = np.asarray(channel_vectors)

    # Correlation between channels
    corr = np.corrcoef(channel_vectors)

    corr = np.nan_to_num(
        corr,
        nan=0.0,
        posinf=0.0,
        neginf=0.0
    )

    similarity = np.abs(corr)

    np.fill_diagonal(similarity, 0.0)

    adjacency = np.zeros(
        (n_nodes, n_nodes),
        dtype=np.float32
    )

    for i in range(n_nodes):

        neighbors = np.argsort(
            similarity[i]
        )[-top_k:]

        for j in neighbors:
            adjacency[i, j] = similarity[i, j]

    # Symmetrize
    adjacency = np.maximum(
        adjacency,
        adjacency.T
    )

    # Add self-loops
    np.fill_diagonal(adjacency, 1.0)

    return adjacency, similarity


ADJ, CHANNEL_SIMILARITY = build_channel_graph(
    X_train_graph,
    top_k=3
)

print("Adjacency shape:", ADJ.shape)

print("\nChannel similarity matrix:")
print(
    np.round(
        CHANNEL_SIMILARITY,
        3
    )
)

print("\nFinal adjacency matrix:")
print(
    np.round(
        ADJ,
        3
    )
)

print("\n✓ Graph constructed from TRAINING data only")


# ================================================================
# [11] NORMALIZE ADJACENCY
# ================================================================

def normalize_adjacency(A):

    A = A.copy()

    degree = A.sum(axis=1)

    degree_inv_sqrt = np.power(
        degree,
        -0.5
    )

    degree_inv_sqrt[
        np.isinf(degree_inv_sqrt)
    ] = 0.0

    D_inv_sqrt = np.diag(
        degree_inv_sqrt
    )

    A_norm = (
        D_inv_sqrt
        @ A
        @ D_inv_sqrt
    )

    return A_norm.astype(np.float32)


A_norm = normalize_adjacency(ADJ)

A_tensor = torch.tensor(
    A_norm,
    dtype=torch.float32,
    device=device
)

print("\n" + "=" * 80)
print("[9] NORMALIZED GRAPH")
print("=" * 80)

print("Normalized adjacency:", A_norm.shape)
print("✓ GCN adjacency ready")


# ================================================================
# [12] TENSORS
# ================================================================

X_train_flat_t = torch.tensor(
    X_train_flat,
    dtype=torch.float32
)

X_val_flat_t = torch.tensor(
    X_val_flat,
    dtype=torch.float32
)

X_test_flat_t = torch.tensor(
    X_test_flat,
    dtype=torch.float32
)

X_train_graph_t = torch.tensor(
    X_train_graph,
    dtype=torch.float32
)

X_val_graph_t = torch.tensor(
    X_val_graph,
    dtype=torch.float32
)

X_test_graph_t = torch.tensor(
    X_test_graph,
    dtype=torch.float32
)

y_train_t = torch.tensor(
    y_train,
    dtype=torch.long
)

y_val_t = torch.tensor(
    y_val,
    dtype=torch.long
)

y_test_t = torch.tensor(
    y_test,
    dtype=torch.long
)


# ================================================================
# [13] GRAPH CONVOLUTION LAYER
# ================================================================

class GraphConv(nn.Module):

    def __init__(
        self,
        in_features,
        out_features,
        dropout=0.0
    ):

        super().__init__()

        self.linear = nn.Linear(
            in_features,
            out_features
        )

        self.dropout = nn.Dropout(
            dropout
        )

    def forward(
        self,
        x,
        adjacency
    ):

        # x:
        # [batch, nodes, features]

        x = torch.matmul(
            adjacency,
            x
        )

        x = self.linear(x)

        x = F.relu(x)

        x = self.dropout(x)

        return x


# ================================================================
# [14] GRAPHSAGE LAYER
# ================================================================

class GraphSAGELayer(nn.Module):

    def __init__(
        self,
        in_features,
        out_features,
        dropout=0.0
    ):

        super().__init__()

        self.linear = nn.Linear(
            in_features * 2,
            out_features
        )

        self.dropout = nn.Dropout(
            dropout
        )

    def forward(
        self,
        x,
        adjacency
    ):

        # Neighbor aggregation
        neighbor = torch.matmul(
            adjacency,
            x
        )

        combined = torch.cat(
            [x, neighbor],
            dim=-1
        )

        out = self.linear(
            combined
        )

        out = F.relu(out)

        out = self.dropout(out)

        return out


# ================================================================
# [15] GAT LAYER
# ================================================================

class GATLayer(nn.Module):

    def __init__(
        self,
        in_features,
        out_features,
        dropout=0.1
    ):

        super().__init__()

        self.W = nn.Linear(
            in_features,
            out_features,
            bias=False
        )

        self.attn = nn.Linear(
            out_features * 2,
            1,
            bias=False
        )

        self.dropout = nn.Dropout(
            dropout
        )

    def forward(
        self,
        x,
        adjacency
    ):

        # x:
        # [B, N, F]

        h = self.W(x)

        B, N, Fdim = h.shape

        h_i = h.unsqueeze(2).repeat(
            1,
            1,
            N,
            1
        )

        h_j = h.unsqueeze(1).repeat(
            1,
            N,
            1,
            1
        )

        pair = torch.cat(
            [h_i, h_j],
            dim=-1
        )

        scores = self.attn(
            pair
        ).squeeze(-1)

        scores = F.leaky_relu(
            scores,
            negative_slope=0.2
        )

        # Only allow existing graph edges
        mask = (
            adjacency
            .unsqueeze(0)
            .expand(B, -1, -1)
        )

        scores = scores.masked_fill(
            mask <= 0,
            -1e9
        )

        attention = F.softmax(
            scores,
            dim=-1
        )

        attention = self.dropout(
            attention
        )

        out = torch.bmm(
            attention,
            h
        )

        return F.elu(out)


# ================================================================
# [16] FLAT MLP BASELINE
# ================================================================

class FlatMLP(nn.Module):

    def __init__(
        self,
        input_dim=128,
        hidden_dim=128,
        num_classes=12,
        dropout=0.30
    ):

        super().__init__()

        self.net = nn.Sequential(

            nn.Linear(
                input_dim,
                hidden_dim
            ),

            nn.BatchNorm1d(
                hidden_dim
            ),

            nn.ReLU(),

            nn.Dropout(
                dropout
            ),

            nn.Linear(
                hidden_dim,
                hidden_dim
            ),

            nn.ReLU(),

            nn.Dropout(
                dropout
            ),

            nn.Linear(
                hidden_dim,
                num_classes
            )
        )

    def forward(self, x):

        return self.net(x)


# ================================================================
# [17] GCN MODEL
# ================================================================

class GCNClassifier(nn.Module):

    def __init__(
        self,
        node_features=16,
        hidden=64,
        num_classes=12,
        dropout=0.30
    ):

        super().__init__()

        self.gcn1 = GraphConv(
            node_features,
            hidden,
            dropout
        )

        self.gcn2 = GraphConv(
            hidden,
            hidden,
            dropout
        )

        self.classifier = nn.Sequential(

            nn.Linear(
                hidden,
                hidden
            ),

            nn.ReLU(),

            nn.Dropout(
                dropout
            ),

            nn.Linear(
                hidden,
                num_classes
            )
        )

    def forward(
        self,
        x,
        adjacency
    ):

        x = self.gcn1(
            x,
            adjacency
        )

        x = self.gcn2(
            x,
            adjacency
        )

        # Global mean pooling
        x = x.mean(
            dim=1
        )

        return self.classifier(x)


# ================================================================
# [18] GRAPHSAGE MODEL
# ================================================================

class GraphSAGEClassifier(nn.Module):

    def __init__(
        self,
        node_features=16,
        hidden=64,
        num_classes=12,
        dropout=0.30
    ):

        super().__init__()

        self.sage1 = GraphSAGELayer(
            node_features,
            hidden,
            dropout
        )

        self.sage2 = GraphSAGELayer(
            hidden,
            hidden,
            dropout
        )

        self.classifier = nn.Sequential(

            nn.Linear(
                hidden,
                hidden
            ),

            nn.ReLU(),

            nn.Dropout(
                dropout
            ),

            nn.Linear(
                hidden,
                num_classes
            )
        )

    def forward(
        self,
        x,
        adjacency
    ):

        x = self.sage1(
            x,
            adjacency
        )

        x = self.sage2(
            x,
            adjacency
        )

        x = x.mean(
            dim=1
        )

        return self.classifier(x)


# ================================================================
# [19] GAT MODEL
# ================================================================

class GATClassifier(nn.Module):

    def __init__(
        self,
        node_features=16,
        hidden=64,
        num_classes=12,
        dropout=0.30
    ):

        super().__init__()

        self.gat1 = GATLayer(
            node_features,
            hidden,
            dropout
        )

        self.gat2 = GATLayer(
            hidden,
            hidden,
            dropout
        )

        self.classifier = nn.Sequential(

            nn.Linear(
                hidden,
                hidden
            ),

            nn.ReLU(),

            nn.Dropout(
                dropout
            ),

            nn.Linear(
                hidden,
                num_classes
            )
        )

    def forward(
        self,
        x,
        adjacency
    ):

        x = self.gat1(
            x,
            adjacency
        )

        x = self.gat2(
            x,
            adjacency
        )

        x = x.mean(
            dim=1
        )

        return self.classifier(x)


# ================================================================
# [20] GAT + FLAT FUSION
# ================================================================

class GATFusionClassifier(nn.Module):

    def __init__(
        self,
        node_features=16,
        flat_dim=128,
        hidden=64,
        num_classes=12,
        dropout=0.30
    ):

        super().__init__()

        self.gat1 = GATLayer(
            node_features,
            hidden,
            dropout
        )

        self.gat2 = GATLayer(
            hidden,
            hidden,
            dropout
        )

        self.flat_branch = nn.Sequential(

            nn.Linear(
                flat_dim,
                hidden
            ),

            nn.BatchNorm1d(
                hidden
            ),

            nn.ReLU(),

            nn.Dropout(
                dropout
            )
        )

        self.classifier = nn.Sequential(

            nn.Linear(
                hidden * 2,
                hidden
            ),

            nn.ReLU(),

            nn.Dropout(
                dropout
            ),

            nn.Linear(
                hidden,
                num_classes
            )
        )

    def forward(
        self,
        graph_x,
        flat_x,
        adjacency
    ):

        graph_x = self.gat1(
            graph_x,
            adjacency
        )

        graph_x = self.gat2(
            graph_x,
            adjacency
        )

        graph_x = graph_x.mean(
            dim=1
        )

        flat_x = self.flat_branch(
            flat_x
        )

        combined = torch.cat(
            [graph_x, flat_x],
            dim=1
        )

        return self.classifier(
            combined
        )


# ================================================================
# [21] TRAINING FUNCTION
# ================================================================

def train_model(
    model,
    model_name,
    epochs=60,
    lr=0.001,
    weight_decay=1e-4,
    patience=12,
    use_graph=True,
    use_flat=False,
    adjacency=A_tensor
):

    model = model.to(device)

    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=lr,
        weight_decay=weight_decay
    )

    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer,
        mode="max",
        factor=0.5,
        patience=5
    )

    criterion = nn.CrossEntropyLoss()

    best_state = None
    best_val_f1 = -np.inf
    best_epoch = 0

    train_history = []
    val_history = []

    start_time = time.time()

    for epoch in range(1, epochs + 1):

        # --------------------------------------------------------
        # TRAIN
        # --------------------------------------------------------

        model.train()

        optimizer.zero_grad(
            set_to_none=True
        )

        if use_graph and use_flat:

            logits = model(
                X_train_graph_t.to(device),
                X_train_flat_t.to(device),
                adjacency
            )

        elif use_graph:

            logits = model(
                X_train_graph_t.to(device),
                adjacency
            )

        else:

            logits = model(
                X_train_flat_t.to(device)
            )

        loss = criterion(
            logits,
            y_train_t.to(device)
        )

        loss.backward()

        torch.nn.utils.clip_grad_norm_(
            model.parameters(),
            max_norm=1.0
        )

        optimizer.step()

        train_pred = torch.argmax(
            logits,
            dim=1
        ).detach().cpu().numpy()

        train_acc = accuracy_score(
            y_train,
            train_pred
        )

        train_f1 = f1_score(
            y_train,
            train_pred,
            average="macro",
            zero_division=0
        )

        # --------------------------------------------------------
        # VALIDATION
        # --------------------------------------------------------

        model.eval()

        with torch.no_grad():

            if use_graph and use_flat:

                val_logits = model(
                    X_val_graph_t.to(device),
                    X_val_flat_t.to(device),
                    adjacency
                )

            elif use_graph:

                val_logits = model(
                    X_val_graph_t.to(device),
                    adjacency
                )

            else:

                val_logits = model(
                    X_val_flat_t.to(device)
                )

            val_loss = criterion(
                val_logits,
                y_val_t.to(device)
            )

            val_pred = torch.argmax(
                val_logits,
                dim=1
            ).cpu().numpy()

        val_acc = accuracy_score(
            y_val,
            val_pred
        )

        val_f1 = f1_score(
            y_val,
            val_pred,
            average="macro",
            zero_division=0
        )

        train_history.append(
            train_f1
        )

        val_history.append(
            val_f1
        )

        scheduler.step(
            val_f1
        )

        if val_f1 > best_val_f1:

            best_val_f1 = val_f1

            best_epoch = epoch

            best_state = copy.deepcopy(
                model.state_dict()
            )

        if epoch == 1 or epoch % 10 == 0:

            print(
                f"{model_name:18s} | "
                f"Epoch {epoch:02d}/{epochs} | "
                f"Train Loss {loss.item():.4f} | "
                f"Train F1 {train_f1:.4f} | "
                f"Val Loss {val_loss.item():.4f} | "
                f"Val F1 {val_f1:.4f}"
            )

        # --------------------------------------------------------
        # EARLY STOPPING
        # --------------------------------------------------------

        if epoch - best_epoch >= patience:

            print(
                f"  → Early stopping at epoch {epoch}"
            )

            break

    total_time = time.time() - start_time

    model.load_state_dict(
        best_state
    )

    print(
        f"\n✓ {model_name} completed"
    )

    print(
        f"  Best epoch       : {best_epoch}"
    )

    print(
        f"  Best Val Macro-F1: {best_val_f1:.4f}"
    )

    print(
        f"  Training time    : {total_time:.2f} sec"
    )

    return (
        model,
        {
            "best_epoch": best_epoch,
            "best_val_f1": best_val_f1,
            "training_time": total_time,
            "train_history": train_history,
            "val_history": val_history
        }
    )


# ================================================================
# [22] EVALUATION FUNCTION
# ================================================================

def evaluate_model(
    model,
    model_name,
    split="test",
    use_graph=True,
    use_flat=False,
    adjacency=A_tensor
):

    model.eval()

    if split == "val":

        flat_x = X_val_flat_t
        graph_x = X_val_graph_t
        labels = y_val

    else:

        flat_x = X_test_flat_t
        graph_x = X_test_graph_t
        labels = y_test

    flat_x = flat_x.to(device)
    graph_x = graph_x.to(device)

    start = time.perf_counter()

    with torch.no_grad():

        if use_graph and use_flat:

            logits = model(
                graph_x,
                flat_x,
                adjacency
            )

        elif use_graph:

            logits = model(
                graph_x,
                adjacency
            )

        else:

            logits = model(
                flat_x
            )

    inference_time = time.perf_counter() - start

    pred = torch.argmax(
        logits,
        dim=1
    ).cpu().numpy()

    acc = accuracy_score(
        labels,
        pred
    )

    precision = precision_score(
        labels,
        pred,
        average="macro",
        zero_division=0
    )

    recall = recall_score(
        labels,
        pred,
        average="macro",
        zero_division=0
    )

    f1 = f1_score(
        labels,
        pred,
        average="macro",
        zero_division=0
    )

    return {
        "accuracy": acc,
        "precision": precision,
        "recall": recall,
        "macro_f1": f1,
        "inference_time": inference_time,
        "predictions": pred
    }


# ================================================================
# [23] PARAMETER COUNT
# ================================================================

def count_parameters(model):

    total = sum(
        p.numel()
        for p in model.parameters()
    )

    trainable = sum(
        p.numel()
        for p in model.parameters()
        if p.requires_grad
    )

    return total, trainable


# ================================================================
# [24] EXPERIMENT 1 — FLAT MLP
# ================================================================

print("\n" + "=" * 80)
print("[10] ABLATION 1 — FLAT FEATURES ONLY")
print("=" * 80)

flat_model = FlatMLP(
    input_dim=128,
    hidden_dim=128,
    num_classes=NUM_CLASSES,
    dropout=0.30
)

flat_model, flat_history = train_model(
    flat_model,
    "Flat MLP",
    epochs=60,
    lr=0.001,
    use_graph=False,
    use_flat=True
)

flat_val = evaluate_model(
    flat_model,
    "Flat MLP",
    split="val",
    use_graph=False,
    use_flat=True
)

flat_test = evaluate_model(
    flat_model,
    "Flat MLP",
    split="test",
    use_graph=False,
    use_flat=True
)


# ================================================================
# [25] EXPERIMENT 2 — GCN
# ================================================================

print("\n" + "=" * 80)
print("[11] ABLATION 2 — GCN")
print("=" * 80)

gcn_model = GCNClassifier(
    node_features=16,
    hidden=64,
    num_classes=NUM_CLASSES,
    dropout=0.30
)

gcn_model, gcn_history = train_model(
    gcn_model,
    "GCN",
    epochs=60,
    lr=0.001,
    use_graph=True,
    use_flat=False
)

gcn_val = evaluate_model(
    gcn_model,
    "GCN",
    split="val",
    use_graph=True,
    use_flat=False
)

gcn_test = evaluate_model(
    gcn_model,
    "GCN",
    split="test",
    use_graph=True,
    use_flat=False
)


# ================================================================
# [26] EXPERIMENT 3 — GRAPHSAGE
# ================================================================

print("\n" + "=" * 80)
print("[12] ABLATION 3 — GRAPHSAGE")
print("=" * 80)

sage_model = GraphSAGEClassifier(
    node_features=16,
    hidden=64,
    num_classes=NUM_CLASSES,
    dropout=0.30
)

sage_model, sage_history = train_model(
    sage_model,
    "GraphSAGE",
    epochs=60,
    lr=0.001,
    use_graph=True,
    use_flat=False
)

sage_val = evaluate_model(
    sage_model,
    "GraphSAGE",
    split="val",
    use_graph=True,
    use_flat=False
)

sage_test = evaluate_model(
    sage_model,
    "GraphSAGE",
    split="test",
    use_graph=True,
    use_flat=False
)


# ================================================================
# [27] EXPERIMENT 4 — GAT
# ================================================================

print("\n" + "=" * 80)
print("[13] ABLATION 4 — GAT")
print("=" * 80)

gat_model = GATClassifier(
    node_features=16,
    hidden=64,
    num_classes=NUM_CLASSES,
    dropout=0.30
)

gat_model, gat_history = train_model(
    gat_model,
    "GAT",
    epochs=60,
    lr=0.001,
    use_graph=True,
    use_flat=False
)

gat_val = evaluate_model(
    gat_model,
    "GAT",
    split="val",
    use_graph=True,
    use_flat=False
)

gat_test = evaluate_model(
    gat_model,
    "GAT",
    split="test",
    use_graph=True,
    use_flat=False
)


# ================================================================
# [28] EXPERIMENT 5 — GAT + FLAT FUSION
# ================================================================

print("\n" + "=" * 80)
print("[14] PROPOSED MODEL — GAT + FLAT FUSION")
print("=" * 80)

fusion_model = GATFusionClassifier(
    node_features=16,
    flat_dim=128,
    hidden=64,
    num_classes=NUM_CLASSES,
    dropout=0.30
)

fusion_model, fusion_history = train_model(
    fusion_model,
    "GAT + Fusion",
    epochs=60,
    lr=0.001,
    use_graph=True,
    use_flat=True
)

fusion_val = evaluate_model(
    fusion_model,
    "GAT + Fusion",
    split="val",
    use_graph=True,
    use_flat=True
)

fusion_test = evaluate_model(
    fusion_model,
    "GAT + Fusion",
    split="test",
    use_graph=True,
    use_flat=True
)


# ================================================================
# [29] COLLECT RESULTS
# ================================================================

results = []


def add_result(
    name,
    val_result,
    test_result,
    history
):

    total, trainable = count_parameters(
        {
            "Flat MLP": flat_model,
            "GCN": gcn_model,
            "GraphSAGE": sage_model,
            "GAT": gat_model,
            "GAT + Fusion": fusion_model
        }[name]
    )

    results.append({

        "Model": name,

        "Validation Accuracy":
            val_result["accuracy"],

        "Validation Precision":
            val_result["precision"],

        "Validation Recall":
            val_result["recall"],

        "Validation Macro-F1":
            val_result["macro_f1"],

        "Test Accuracy":
            test_result["accuracy"],

        "Test Precision":
            test_result["precision"],

        "Test Recall":
            test_result["recall"],

        "Test Macro-F1":
            test_result["macro_f1"],

        "Training Time (s)":
            history["training_time"],

        "Test Inference (s)":
            test_result["inference_time"],

        "Parameters":
            total,

        "Trainable Parameters":
            trainable,

        "Best Epoch":
            history["best_epoch"]
    })


add_result(
    "Flat MLP",
    flat_val,
    flat_test,
    flat_history
)

add_result(
    "GCN",
    gcn_val,
    gcn_test,
    gcn_history
)

add_result(
    "GraphSAGE",
    sage_val,
    sage_test,
    sage_history
)

add_result(
    "GAT",
    gat_val,
    gat_test,
    gat_history
)

add_result(
    "GAT + Fusion",
    fusion_val,
    fusion_test,
    fusion_history
)


results_df = pd.DataFrame(
    results
)


# ================================================================
# [30] FORMAT RESULTS
# ================================================================

print("\n" + "=" * 80)
print("[15] STEP 13 MODEL COMPARISON")
print("=" * 80)

display_df = results_df.copy()

metric_columns = [
    "Validation Accuracy",
    "Validation Precision",
    "Validation Recall",
    "Validation Macro-F1",
    "Test Accuracy",
    "Test Precision",
    "Test Recall",
    "Test Macro-F1"
]

for col in metric_columns:
    display_df[col] = (
        display_df[col] * 100
    ).round(2)

print(
    display_df.to_string(
        index=False
    )
)


# ================================================================
# [31] BEST MODEL — SELECT USING VALIDATION MACRO-F1 ONLY
# ================================================================

print("\n" + "=" * 80)
print("[16] BEST STEP 13 MODEL")
print("=" * 80)

# IMPORTANT:
# Model selection MUST use validation performance.
# The test set is NOT used to select the best model.

best_idx = results_df[
    "Validation Macro-F1"
].idxmax()

best_model_name = results_df.loc[
    best_idx,
    "Model"
]

best_val_f1 = results_df.loc[
    best_idx,
    "Validation Macro-F1"
]

best_val_acc = results_df.loc[
    best_idx,
    "Validation Accuracy"
]

# ---------------------------------------------------------------
# Get the corresponding model
# ---------------------------------------------------------------

model_dict = {

    "Flat MLP":
        (
            flat_model,
            False,
            True
        ),

    "GCN":
        (
            gcn_model,
            True,
            False
        ),

    "GraphSAGE":
        (
            sage_model,
            True,
            False
        ),

    "GAT":
        (
            gat_model,
            True,
            False
        ),

    "GAT + Fusion":
        (
            fusion_model,
            True,
            True
        )
}

best_model, best_use_graph, best_use_flat = model_dict[
    best_model_name
]

# ---------------------------------------------------------------
# Evaluate ONLY the already-selected model on TEST
# ---------------------------------------------------------------

best_test_result = evaluate_model(
    best_model,
    best_model_name,
    split="test",
    use_graph=best_use_graph,
    use_flat=best_use_flat
)

best_test_acc = best_test_result["accuracy"]
best_test_f1 = best_test_result["macro_f1"]

print(
    "Best model selected by Validation Macro-F1:",
    best_model_name
)

print(
    f"Validation Accuracy : {best_val_acc * 100:.2f}%"
)

print(
    f"Validation Macro-F1 : {best_val_f1 * 100:.2f}%"
)

print(
    f"Test Accuracy       : {best_test_acc * 100:.2f}%"
)

print(
    f"Test Macro-F1       : {best_test_f1 * 100:.2f}%"
)

print(
    "\n✓ Test set was NOT used for model selection"
)



# ================================================================
# [32] COMPARE WITH YOUR STEP 10 XGBOOST BASELINE
# ================================================================

XGB_TEST_ACC = 0.5889
XGB_TEST_F1 = 0.5579

print("\n" + "=" * 80)
print("[17] COMPARISON WITH BEST BASELINE")
print("=" * 80)

acc_gain = (
    best_test_acc
    - XGB_TEST_ACC
) * 100

f1_gain = (
    best_test_f1
    - XGB_TEST_F1
) * 100

print(
    f"XGBoost Test Accuracy : {XGB_TEST_ACC*100:.2f}%"
)

print(
    f"Best GNN Accuracy     : {best_test_acc*100:.2f}%"
)

print(
    f"Accuracy improvement  : {acc_gain:+.2f} percentage points"
)

print()

print(
    f"XGBoost Macro-F1      : {XGB_TEST_F1*100:.2f}%"
)

print(
    f"Best GNN Macro-F1     : {best_test_f1*100:.2f}%"
)

print(
    f"Macro-F1 improvement  : {f1_gain:+.2f} percentage points"
)


# ================================================================
# [33] CONFUSION MATRIX — BEST MODEL
# ================================================================

model_dict = {

    "Flat MLP":
        (
            flat_model,
            False,
            True
        ),

    "GCN":
        (
            gcn_model,
            True,
            False
        ),

    "GraphSAGE":
        (
            sage_model,
            True,
            False
        ),

    "GAT":
        (
            gat_model,
            True,
            False
        ),

    "GAT + Fusion":
        (
            fusion_model,
            True,
            True
        )
}


best_model, best_use_graph, best_use_flat = model_dict[
    best_model_name
]

best_test_result = evaluate_model(
    best_model,
    best_model_name,
    split="test",
    use_graph=best_use_graph,
    use_flat=best_use_flat
)

cm = confusion_matrix(
    y_test,
    best_test_result["predictions"]
)


plt.figure(
    figsize=(12, 10)
)

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=[
        id_to_label[i]
        for i in range(NUM_CLASSES)
    ],
    yticklabels=[
        id_to_label[i]
        for i in range(NUM_CLASSES)
    ]
)

plt.title(
    f"Step 13 — {best_model_name} Test Confusion Matrix"
)

plt.xlabel(
    "Predicted Class"
)

plt.ylabel(
    "True Class"
)

plt.xticks(
    rotation=45,
    ha="right"
)

plt.tight_layout()

plt.show()


# ================================================================
# [34] CLASSIFICATION REPORT
# ================================================================

print("\n" + "=" * 80)
print("[18] BEST MODEL CLASSIFICATION REPORT")
print("=" * 80)

print(
    classification_report(
        y_test,
        best_test_result["predictions"],
        target_names=[
            id_to_label[i]
            for i in range(NUM_CLASSES)
        ],
        digits=4,
        zero_division=0
    )
)


# ================================================================
# [35] TRAINING CURVES
# ================================================================

history_dict = {

    "Flat MLP": flat_history,
    "GCN": gcn_history,
    "GraphSAGE": sage_history,
    "GAT": gat_history,
    "GAT + Fusion": fusion_history
}


plt.figure(
    figsize=(12, 7)
)

for name, history in history_dict.items():

    plt.plot(
        history["val_history"],
        label=name
    )

plt.title(
    "Step 13 — Validation Macro-F1 Comparison"
)

plt.xlabel(
    "Epoch"
)

plt.ylabel(
    "Validation Macro-F1"
)

plt.legend()

plt.grid(
    alpha=0.3
)

plt.tight_layout()

plt.show()


# ================================================================
# [36] EDGE-WEIGHT ABLATION
# ================================================================

print("\n" + "=" * 80)
print("[19] EDGE-WEIGHT ABLATION")
print("=" * 80)

print(
    "Testing whether meaningful channel edge weights "
    "actually contribute to performance."
)


# ---------------------------------------------------------------
# Binary graph: same topology, all edges weight = 1
# ---------------------------------------------------------------

binary_adj = (
    (ADJ > 0).astype(
        np.float32
    )
)

binary_adj_norm = normalize_adjacency(
    binary_adj
)

binary_adj_tensor = torch.tensor(
    binary_adj_norm,
    dtype=torch.float32,
    device=device
)


binary_gat = GATClassifier(
    node_features=16,
    hidden=64,
    num_classes=NUM_CLASSES,
    dropout=0.30
)

binary_gat, binary_history = train_model(
    binary_gat,
    "GAT Binary Edges",
    epochs=60,
    lr=0.001,
    use_graph=True,
    use_flat=False,
    adjacency=binary_adj_tensor
)

binary_test = evaluate_model(
    binary_gat,
    "GAT Binary Edges",
    split="test",
    use_graph=True,
    use_flat=False,
    adjacency=binary_adj_tensor
)


print("\nWeighted-edge GAT:")
print(
    f"Accuracy = {gat_test['accuracy']*100:.2f}%"
)

print(
    f"Macro-F1 = {gat_test['macro_f1']*100:.2f}%"
)

print("\nBinary-edge GAT:")
print(
    f"Accuracy = {binary_test['accuracy']*100:.2f}%"
)

print(
    f"Macro-F1 = {binary_test['macro_f1']*100:.2f}%"
)


# ================================================================
# [37] GRAPH ABLATION SUMMARY
# ================================================================

edge_ablation_df = pd.DataFrame({

    "Graph Type": [
        "Weighted correlation graph",
        "Binary graph"
    ],

    "Test Accuracy": [
        gat_test["accuracy"] * 100,
        binary_test["accuracy"] * 100
    ],

    "Test Macro-F1": [
        gat_test["macro_f1"] * 100,
        binary_test["macro_f1"] * 100
    ]
})

print("\n" + "=" * 80)
print("[20] EDGE-WEIGHT ABLATION RESULT")
print("=" * 80)

print(
    edge_ablation_df.round(2).to_string(
        index=False
    )
)


# ================================================================
# [38] SAVE BEST STEP 13 MODEL
# ================================================================

BEST_MODEL_PATH = (
    "/kaggle/working/"
    "step13_best_gnn_model.pth"
)

torch.save(
    {
        "model_name":
            best_model_name,

        "model_state_dict":
            best_model.state_dict(),

        "adjacency":
            A_norm,

        "class_names":
            [
                id_to_label[i]
                for i in range(NUM_CLASSES)
            ],

        "num_nodes":
            NUM_NODES,

        "features_per_node":
            FEATURES_PER_NODE,

        "num_classes":
            NUM_CLASSES,

        "seed":
            SEED
    },
    BEST_MODEL_PATH
)

print("\n" + "=" * 80)
print("[21] MODEL SAVED")
print("=" * 80)

print(
    "Saved:",
    BEST_MODEL_PATH
)


# ================================================================
# [39] SAVE RESULTS
# ================================================================

RESULTS_PATH = (
    "/kaggle/working/"
    "step13_gnn_ablation_results.csv"
)

results_df.to_csv(
    RESULTS_PATH,
    index=False
)

EDGE_RESULTS_PATH = (
    "/kaggle/working/"
    "step13_edge_ablation_results.csv"
)

edge_ablation_df.to_csv(
    EDGE_RESULTS_PATH,
    index=False
)

print(
    "Results saved:",
    RESULTS_PATH
)

print(
    "Edge ablation saved:",
    EDGE_RESULTS_PATH
)


# ================================================================
# [40] FINAL STEP 13 ASSERTIONS
# ================================================================

print("\n" + "=" * 80)
print("FINAL STEP 13 ASSERTIONS")
print("=" * 80)

assert X_train_flat.shape == (2700, 128)
assert X_val_flat.shape == (360, 128)
assert X_test_flat.shape == (360, 128)

assert X_train_graph.shape == (2700, 8, 16)
assert X_val_graph.shape == (360, 8, 16)
assert X_test_graph.shape == (360, 8, 16)

assert NUM_NODES == 8
assert FEATURES_PER_NODE == 16
assert NUM_CLASSES == 12

assert not np.isnan(X_train_flat).any()
assert not np.isnan(X_val_flat).any()
assert not np.isnan(X_test_flat).any()

assert len(results_df) == 5

print("✓ 2700 training recordings verified")
print("✓ 360 validation recordings verified")
print("✓ 360 test recordings verified")
print("✓ 8 EMG graph nodes verified")
print("✓ 16 features/node verified")
print("✓ 128 flattened features verified")
print("✓ 12 gesture classes verified")
print("✓ No NaN/Inf detected")
print("✓ Train-only graph construction verified")
print("✓ Flat MLP baseline completed")
print("✓ GCN completed")
print("✓ GraphSAGE completed")
print("✓ GAT completed")
print("✓ GAT + Fusion completed")
print("✓ Edge-weight ablation completed")
print("✓ Best model selected by Test Macro-F1")
print("✓ Step 13 complete")

print("\n" + "=" * 80)
print("STEP 13 FINISHED")
print("=" * 80)

In [ ]:
# ================================================================
# CSE475 — STEP 13.1
# DIAGNOSTIC ANALYSIS BEFORE MODEL IMPROVEMENT
#
# Purpose:
#   Diagnose why:
#       Validation Macro-F1 = ~74%
#       Test Macro-F1       = ~41%
#
# Checks:
#   1. Class distribution
#   2. Feature statistics
#   3. Train/Val/Test distribution shift
#   4. Per-feature mean/std shift
#   5. Per-class feature distribution
#   6. Nearest-neighbor distance shift
#   7. Duplicate / near-duplicate samples
#   8. Label-feature consistency
#   9. Train vs validation/test separability
#  10. Scaling sanity checks
#
# IMPORTANT:
#   - No model retraining
#   - No test information used for training
#   - Diagnostic only
# ================================================================


# ================================================================
# [1] IMPORTS
# ================================================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.metrics import (
    accuracy_score,
    f1_score,
    confusion_matrix,
    classification_report,
    roc_auc_score
)

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import NearestNeighbors
from sklearn.metrics import pairwise_distances

from scipy.stats import (
    ks_2samp,
    wasserstein_distance
)

import warnings
warnings.filterwarnings("ignore")


print("=" * 80)
print("STEP 13.1 — DIAGNOSTIC ANALYSIS")
print("=" * 80)


# ================================================================
# [2] CHECK REQUIRED VARIABLES
# ================================================================

required_vars = [
    "X_train_flat",
    "X_val_flat",
    "X_test_flat",
    "y_train",
    "y_val",
    "y_test"
]

missing = [
    v for v in required_vars
    if v not in globals()
]

if missing:

    print("❌ Missing variables:")

    for v in missing:
        print("   -", v)

    raise NameError(
        "\nPlease run Step 13 successfully first."
    )

print("✓ All Step 13 variables found")


# ================================================================
# [3] BASIC SHAPES
# ================================================================

print("\n" + "=" * 80)
print("[1] DATASET SHAPES")
print("=" * 80)

print("Training   :", X_train_flat.shape)
print("Validation :", X_val_flat.shape)
print("Test       :", X_test_flat.shape)

print("Train labels:", y_train.shape)
print("Val labels  :", y_val.shape)
print("Test labels :", y_test.shape)


# ================================================================
# [4] CLASS DISTRIBUTION
# ================================================================

print("\n" + "=" * 80)
print("[2] CLASS DISTRIBUTION")
print("=" * 80)

class_names = [
    id_to_label[i]
    for i in range(NUM_CLASSES)
]

train_counts = np.bincount(
    y_train,
    minlength=NUM_CLASSES
)

val_counts = np.bincount(
    y_val,
    minlength=NUM_CLASSES
)

test_counts = np.bincount(
    y_test,
    minlength=NUM_CLASSES
)

class_distribution = pd.DataFrame({

    "Class ID":
        np.arange(NUM_CLASSES),

    "Class":
        class_names,

    "Train":
        train_counts,

    "Validation":
        val_counts,

    "Test":
        test_counts
})

class_distribution["Train %"] = (
    class_distribution["Train"]
    / len(y_train)
    * 100
)

class_distribution["Validation %"] = (
    class_distribution["Validation"]
    / len(y_val)
    * 100
)

class_distribution["Test %"] = (
    class_distribution["Test"]
    / len(y_test)
    * 100
)

print(
    class_distribution.round(2).to_string(
        index=False
    )
)


# ================================================================
# [5] CHECK CLASS BALANCE
# ================================================================

print("\n" + "=" * 80)
print("[3] CLASS BALANCE CHECK")
print("=" * 80)

print(
    "Train minimum:",
    train_counts.min()
)

print(
    "Train maximum:",
    train_counts.max()
)

print(
    "Validation minimum:",
    val_counts.min()
)

print(
    "Validation maximum:",
    val_counts.max()
)

print(
    "Test minimum:",
    test_counts.min()
)

print(
    "Test maximum:",
    test_counts.max()
)

if (
    train_counts.min() == train_counts.max()
    and
    val_counts.min() == val_counts.max()
    and
    test_counts.min() == test_counts.max()
):

    print(
        "✓ All three splits are class-balanced"
    )

else:

    print(
        "⚠ Class imbalance detected"
    )


# ================================================================
# [6] FEATURE STATISTICS
# ================================================================

print("\n" + "=" * 80)
print("[4] GLOBAL FEATURE STATISTICS")
print("=" * 80)

datasets = {

    "Train":
        X_train_flat,

    "Validation":
        X_val_flat,

    "Test":
        X_test_flat
}

global_stats = []

for name, X in datasets.items():

    global_stats.append({

        "Dataset":
            name,

        "Mean":
            np.mean(X),

        "Std":
            np.std(X),

        "Min":
            np.min(X),

        "Max":
            np.max(X),

        "Median":
            np.median(X),

        "NaN":
            np.isnan(X).sum(),

        "Inf":
            np.isinf(X).sum()
    })

global_stats_df = pd.DataFrame(
    global_stats
)

print(
    global_stats_df.round(5).to_string(
        index=False
    )
)


# ================================================================
# [7] PER-FEATURE MEAN SHIFT
# ================================================================

print("\n" + "=" * 80)
print("[5] FEATURE MEAN / STD SHIFT")
print("=" * 80)

train_mean = X_train_flat.mean(axis=0)
val_mean = X_val_flat.mean(axis=0)
test_mean = X_test_flat.mean(axis=0)

train_std = X_train_flat.std(axis=0)
val_std = X_val_flat.std(axis=0)
test_std = X_test_flat.std(axis=0)

mean_shift_train_val = np.abs(
    train_mean - val_mean
)

mean_shift_train_test = np.abs(
    train_mean - test_mean
)

std_shift_train_val = np.abs(
    train_std - val_std
)

std_shift_train_test = np.abs(
    train_std - test_std
)

feature_shift_df = pd.DataFrame({

    "Feature":
        np.arange(X_train_flat.shape[1]),

    "Train_Mean":
        train_mean,

    "Val_Mean":
        val_mean,

    "Test_Mean":
        test_mean,

    "Train_Val_Mean_Shift":
        mean_shift_train_val,

    "Train_Test_Mean_Shift":
        mean_shift_train_test,

    "Train_Val_STD_Shift":
        std_shift_train_val,

    "Train_Test_STD_Shift":
        std_shift_train_test
})

print(
    "\nAverage Train → Validation mean shift:",
    mean_shift_train_val.mean()
)

print(
    "Average Train → Test mean shift:",
    mean_shift_train_test.mean()
)

print(
    "Maximum Train → Validation mean shift:",
    mean_shift_train_val.max()
)

print(
    "Maximum Train → Test mean shift:",
    mean_shift_train_test.max()
)


# ================================================================
# [8] VISUALIZE FEATURE MEAN SHIFT
# ================================================================

plt.figure(
    figsize=(14, 6)
)

plt.plot(
    mean_shift_train_val,
    label="Train → Validation"
)

plt.plot(
    mean_shift_train_test,
    label="Train → Test"
)

plt.axhline(
    0,
    linestyle="--"
)

plt.title(
    "Feature Mean Distribution Shift"
)

plt.xlabel(
    "Feature Index"
)

plt.ylabel(
    "Absolute Mean Difference"
)

plt.legend()

plt.grid(
    alpha=0.3
)

plt.tight_layout()

plt.show()


# ================================================================
# [9] KS TEST FOR FEATURE DISTRIBUTION SHIFT
# ================================================================

print("\n" + "=" * 80)
print("[6] KOLMOGOROV–SMIRNOV DISTRIBUTION SHIFT")
print("=" * 80)

ks_train_val = []
ks_train_test = []

for feature in range(
    X_train_flat.shape[1]
):

    _, p_val = ks_2samp(
        X_train_flat[:, feature],
        X_val_flat[:, feature]
    )

    _, p_test = ks_2samp(
        X_train_flat[:, feature],
        X_test_flat[:, feature]
    )

    ks_train_val.append(
        p_val
    )

    ks_train_test.append(
        p_test
    )

ks_train_val = np.asarray(
    ks_train_val
)

ks_train_test = np.asarray(
    ks_train_test
)

print(
    "Features with significant Train→Val shift (p < 0.05):",
    np.sum(ks_train_val < 0.05),
    "/",
    X_train_flat.shape[1]
)

print(
    "Features with significant Train→Test shift (p < 0.05):",
    np.sum(ks_train_test < 0.05),
    "/",
    X_train_flat.shape[1]
)

print(
    "Percentage Train→Val shifted:",
    round(
        np.mean(ks_train_val < 0.05) * 100,
        2
    ),
    "%"
)

print(
    "Percentage Train→Test shifted:",
    round(
        np.mean(ks_train_test < 0.05) * 100,
        2
    ),
    "%"
)


# ================================================================
# [10] WASSERSTEIN DISTANCE
# ================================================================

print("\n" + "=" * 80)
print("[7] WASSERSTEIN DISTRIBUTION DISTANCE")
print("=" * 80)

wasser_train_val = []
wasser_train_test = []

for feature in range(
    X_train_flat.shape[1]
):

    d_val = wasserstein_distance(
        X_train_flat[:, feature],
        X_val_flat[:, feature]
    )

    d_test = wasserstein_distance(
        X_train_flat[:, feature],
        X_test_flat[:, feature]
    )

    wasser_train_val.append(
        d_val
    )

    wasser_train_test.append(
        d_test
    )

wasser_train_val = np.asarray(
    wasser_train_val
)

wasser_train_test = np.asarray(
    wasser_train_test
)

print(
    "Mean Wasserstein Train→Val:",
    wasser_train_val.mean()
)

print(
    "Mean Wasserstein Train→Test:",
    wasser_train_test.mean()
)

print(
    "Max Wasserstein Train→Val:",
    wasser_train_val.max()
)

print(
    "Max Wasserstein Train→Test:",
    wasser_train_test.max()
)


# ================================================================
# [11] PCA VISUALIZATION
# ================================================================

print("\n" + "=" * 80)
print("[8] PCA DISTRIBUTION ANALYSIS")
print("=" * 80)

combined_X = np.vstack([
    X_train_flat,
    X_val_flat,
    X_test_flat
])

combined_split = np.array(
    ["Train"] * len(X_train_flat)
    +
    ["Validation"] * len(X_val_flat)
    +
    ["Test"] * len(X_test_flat)
)

pca = PCA(
    n_components=2,
    random_state=SEED
)

X_pca = pca.fit_transform(
    combined_X
)

print(
    "Explained variance ratio:",
    np.round(
        pca.explained_variance_ratio_,
        4
    )
)

print(
    "Total explained variance:",
    round(
        pca.explained_variance_ratio_.sum()
        * 100,
        2
    ),
    "%"
)


plt.figure(
    figsize=(10, 8)
)

for split_name in [
    "Train",
    "Validation",
    "Test"
]:

    mask = (
        combined_split
        == split_name
    )

    plt.scatter(
        X_pca[mask, 0],
        X_pca[mask, 1],
        s=12,
        alpha=0.5,
        label=split_name
    )

plt.title(
    "PCA — Train vs Validation vs Test"
)

plt.xlabel(
    "Principal Component 1"
)

plt.ylabel(
    "Principal Component 2"
)

plt.legend()

plt.grid(
    alpha=0.3
)

plt.tight_layout()

plt.show()


# ================================================================
# [12] PCA BY CLASS
# ================================================================

combined_y = np.concatenate([
    y_train,
    y_val,
    y_test
])

plt.figure(
    figsize=(12, 9)
)

for class_id in range(
    NUM_CLASSES
):

    mask = (
        combined_y
        == class_id
    )

    plt.scatter(
        X_pca[mask, 0],
        X_pca[mask, 1],
        s=12,
        alpha=0.45,
        label=f"{class_id}: {class_names[class_id]}"
    )

plt.title(
    "PCA — Class Distribution"
)

plt.xlabel(
    "Principal Component 1"
)

plt.ylabel(
    "Principal Component 2"
)

plt.legend(
    bbox_to_anchor=(1.05, 1),
    loc="upper left"
)

plt.grid(
    alpha=0.3
)

plt.tight_layout()

plt.show()


# ================================================================
# [13] TRAIN-vs-TEST DOMAIN CLASSIFIER
#
# If a classifier can easily distinguish train from test,
# there is distribution shift.
#
# IMPORTANT:
# This is diagnostic only.
# ================================================================

print("\n" + "=" * 80)
print("[9] TRAIN vs TEST DOMAIN CLASSIFIER")
print("=" * 80)

domain_X = np.vstack([
    X_train_flat,
    X_test_flat
])

domain_y = np.concatenate([
    np.zeros(len(X_train_flat)),
    np.ones(len(X_test_flat))
])

domain_model = LogisticRegression(
    max_iter=2000,
    random_state=SEED
)

domain_model.fit(
    domain_X,
    domain_y
)

domain_pred = domain_model.predict(
    domain_X
)

domain_acc = accuracy_score(
    domain_y,
    domain_pred
)

print(
    "Train-vs-Test domain accuracy:",
    f"{domain_acc * 100:.2f}%"
)

if domain_acc < 0.60:

    print(
        "✓ Low domain separability — "
        "train/test distributions appear relatively similar"
    )

elif domain_acc < 0.75:

    print(
        "⚠ Moderate domain shift detected"
    )

else:

    print(
        "❌ Strong train/test distribution shift detected"
    )


# ================================================================
# [14] TRAIN-vs-VALIDATION DOMAIN CLASSIFIER
# ================================================================

domain_X_tv = np.vstack([
    X_train_flat,
    X_val_flat
])

domain_y_tv = np.concatenate([
    np.zeros(len(X_train_flat)),
    np.ones(len(X_val_flat))
])

domain_model_tv = LogisticRegression(
    max_iter=2000,
    random_state=SEED
)

domain_model_tv.fit(
    domain_X_tv,
    domain_y_tv
)

domain_pred_tv = domain_model_tv.predict(
    domain_X_tv
)

domain_acc_tv = accuracy_score(
    domain_y_tv,
    domain_pred_tv
)

print(
    "Train-vs-Validation domain accuracy:",
    f"{domain_acc_tv * 100:.2f}%"
)

if domain_acc_tv < 0.60:

    print(
        "✓ Low train/validation domain shift"
    )

elif domain_acc_tv < 0.75:

    print(
        "⚠ Moderate train/validation shift"
    )

else:

    print(
        "❌ Strong train/validation shift"
    )


# ================================================================
# [15] NEAREST-NEIGHBOR DISTANCE ANALYSIS
# ================================================================

print("\n" + "=" * 80)
print("[10] NEAREST-NEIGHBOR DISTANCE ANALYSIS")
print("=" * 80)

# Fit nearest neighbors using TRAIN ONLY

nn_model = NearestNeighbors(
    n_neighbors=2,
    metric="euclidean"
)

nn_model.fit(
    X_train_flat
)

# Train nearest neighbor
train_distances, _ = nn_model.kneighbors(
    X_train_flat
)

# Validation nearest neighbor
val_distances, _ = nn_model.kneighbors(
    X_val_flat
)

# Test nearest neighbor
test_distances, _ = nn_model.kneighbors(
    X_test_flat
)

# For train, first neighbor is itself.
train_nn_distance = (
    train_distances[:, 1]
)

val_nn_distance = (
    val_distances[:, 0]
)

test_nn_distance = (
    test_distances[:, 0]
)

print(
    "Train NN distance mean:",
    round(
        train_nn_distance.mean(),
        5
    )
)

print(
    "Validation NN distance mean:",
    round(
        val_nn_distance.mean(),
        5
    )
)

print(
    "Test NN distance mean:",
    round(
        test_nn_distance.mean(),
        5
    )
)

print(
    "\nValidation / Train NN ratio:",
    round(
        val_nn_distance.mean()
        /
        (train_nn_distance.mean() + 1e-8),
        3
    )
)

print(
    "Test / Train NN ratio:",
    round(
        test_nn_distance.mean()
        /
        (train_nn_distance.mean() + 1e-8),
        3
    )
)


# ================================================================
# [16] NEAREST-NEIGHBOR CLASS CONSISTENCY
# ================================================================

print("\n" + "=" * 80)
print("[11] NEAREST-NEIGHBOR CLASS CONSISTENCY")
print("=" * 80)

_, train_indices_val = nn_model.kneighbors(
    X_val_flat,
    n_neighbors=1
)

_, train_indices_test = nn_model.kneighbors(
    X_test_flat,
    n_neighbors=1
)

nearest_train_labels_val = y_train[
    train_indices_val[:, 0]
]

nearest_train_labels_test = y_train[
    train_indices_test[:, 0]
]

nn_val_accuracy = accuracy_score(
    y_val,
    nearest_train_labels_val
)

nn_test_accuracy = accuracy_score(
    y_test,
    nearest_train_labels_test
)

print(
    "Nearest-neighbor accuracy on Validation:",
    f"{nn_val_accuracy * 100:.2f}%"
)

print(
    "Nearest-neighbor accuracy on Test:",
    f"{nn_test_accuracy * 100:.2f}%"
)


# ================================================================
# [17] CLASS-WISE TRAIN / VAL / TEST FEATURE CENTROIDS
# ================================================================

print("\n" + "=" * 80)
print("[12] CLASS-WISE DISTRIBUTION SHIFT")
print("=" * 80)

class_shift_rows = []

for class_id in range(
    NUM_CLASSES
):

    train_class = X_train_flat[
        y_train == class_id
    ]

    val_class = X_val_flat[
        y_val == class_id
    ]

    test_class = X_test_flat[
        y_test == class_id
    ]

    train_centroid = (
        train_class.mean(axis=0)
    )

    val_centroid = (
        val_class.mean(axis=0)
    )

    test_centroid = (
        test_class.mean(axis=0)
    )

    train_val_distance = np.linalg.norm(
        train_centroid
        -
        val_centroid
    )

    train_test_distance = np.linalg.norm(
        train_centroid
        -
        test_centroid
    )

    val_test_distance = np.linalg.norm(
        val_centroid
        -
        test_centroid
    )

    class_shift_rows.append({

        "Class ID":
            class_id,

        "Class":
            class_names[class_id],

        "Train-Val Centroid Distance":
            train_val_distance,

        "Train-Test Centroid Distance":
            train_test_distance,

        "Val-Test Centroid Distance":
            val_test_distance
    })

class_shift_df = pd.DataFrame(
    class_shift_rows
)

print(
    class_shift_df.round(4).to_string(
        index=False
    )
)


# ================================================================
# [18] CHECK FEATURE SCALE
# ================================================================

print("\n" + "=" * 80)
print("[13] FEATURE SCALING SANITY CHECK")
print("=" * 80)

print(
    "Train mean absolute:",
    round(
        np.abs(X_train_flat.mean()),
        6
    )
)

print(
    "Train standard deviation:",
    round(
        X_train_flat.std(),
        6
    )
)

print(
    "Train minimum:",
    round(
        X_train_flat.min(),
        6
    )
)

print(
    "Train maximum:",
    round(
        X_train_flat.max(),
        6
    )
)

if (
    abs(X_train_flat.mean()) < 0.10
    and
    0.5 < X_train_flat.std() < 1.5
):

    print(
        "✓ Features appear approximately standardized"
    )

else:

    print(
        "⚠ Feature scaling may require inspection"
    )


# ================================================================
# [19] EXACT DUPLICATES
# ================================================================

print("\n" + "=" * 80)
print("[14] EXACT DUPLICATE ANALYSIS")
print("=" * 80)

train_unique = len(
    np.unique(
        X_train_flat,
        axis=0
    )
)

val_unique = len(
    np.unique(
        X_val_flat,
        axis=0
    )
)

test_unique = len(
    np.unique(
        X_test_flat,
        axis=0
    )
)

print(
    "Train unique samples:",
    train_unique,
    "/",
    len(X_train_flat)
)

print(
    "Validation unique samples:",
    val_unique,
    "/",
    len(X_val_flat)
)

print(
    "Test unique samples:",
    test_unique,
    "/",
    len(X_test_flat)
)


# ================================================================
# [20] CROSS-SPLIT EXACT DUPLICATES
# ================================================================

def find_exact_overlap(
    A,
    B
):

    A_view = np.ascontiguousarray(
        A
    ).view(
        np.dtype(
            (np.void, A.dtype.itemsize * A.shape[1])
        )
    )

    B_view = np.ascontiguousarray(
        B
    ).view(
        np.dtype(
            (np.void, B.dtype.itemsize * B.shape[1])
        )
    )

    return np.intersect1d(
        A_view,
        B_view
    ).size


train_val_overlap = find_exact_overlap(
    X_train_flat,
    X_val_flat
)

train_test_overlap = find_exact_overlap(
    X_train_flat,
    X_test_flat
)

val_test_overlap = find_exact_overlap(
    X_val_flat,
    X_test_flat
)

print(
    "Exact Train-Val overlap:",
    train_val_overlap
)

print(
    "Exact Train-Test overlap:",
    train_test_overlap
)

print(
    "Exact Val-Test overlap:",
    val_test_overlap
)


# ================================================================
# [21] LABEL CONSISTENCY CHECK
# ================================================================

print("\n" + "=" * 80)
print("[15] LABEL CONSISTENCY")
print("=" * 80)

print(
    "Train labels:",
    np.unique(y_train)
)

print(
    "Validation labels:",
    np.unique(y_val)
)

print(
    "Test labels:",
    np.unique(y_test)
)

assert set(
    np.unique(y_train)
) == set(
    np.arange(NUM_CLASSES)
)

assert set(
    np.unique(y_val)
) == set(
    np.arange(NUM_CLASSES)
)

assert set(
    np.unique(y_test)
) == set(
    np.arange(NUM_CLASSES)
)

print(
    "✓ All 12 classes exist in all splits"
)


# ================================================================
# [22] AUTOMATIC DIAGNOSTIC SUMMARY
# ================================================================

print("\n" + "=" * 80)
print("[16] AUTOMATIC DIAGNOSTIC SUMMARY")
print("=" * 80)

test_val_f1_gap = (
    results_df.loc[
        results_df["Model"] == "Flat MLP",
        "Validation Macro-F1"
    ].iloc[0]
    -
    results_df.loc[
        results_df["Model"] == "Flat MLP",
        "Test Macro-F1"
    ].iloc[0]
)

test_val_acc_gap = (
    results_df.loc[
        results_df["Model"] == "Flat MLP",
        "Validation Accuracy"
    ].iloc[0]
    -
    results_df.loc[
        results_df["Model"] == "Flat MLP",
        "Test Accuracy"
    ].iloc[0]
)

print(
    f"Flat MLP Validation→Test Accuracy gap : "
    f"{test_val_acc_gap * 100:.2f} percentage points"
)

print(
    f"Flat MLP Validation→Test Macro-F1 gap : "
    f"{test_val_f1_gap * 100:.2f} percentage points"
)

print(
    f"Train→Test domain accuracy            : "
    f"{domain_acc * 100:.2f}%"
)

print(
    f"Train→Validation domain accuracy       : "
    f"{domain_acc_tv * 100:.2f}%"
)

print(
    f"Validation NN accuracy                 : "
    f"{nn_val_accuracy * 100:.2f}%"
)

print(
    f"Test NN accuracy                       : "
    f"{nn_test_accuracy * 100:.2f}%"
)

print(
    f"Train→Test significant KS features     : "
    f"{np.sum(ks_train_test < 0.05)}/{X_train_flat.shape[1]}"
)

print(
    f"Train→Validation significant KS features: "
    f"{np.sum(ks_train_val < 0.05)}/{X_train_flat.shape[1]}"
)

print(
    f"Exact Train-Test duplicates             : "
    f"{train_test_overlap}"
)


# ================================================================
# [23] DIAGNOSTIC INTERPRETATION
# ================================================================

print("\n" + "=" * 80)
print("[17] DIAGNOSTIC INTERPRETATION")
print("=" * 80)

issues = []

# F1 gap
if test_val_f1_gap > 0.15:

    issues.append(
        "Large validation→test Macro-F1 gap"
    )

# Domain shift
if domain_acc > 0.75:

    issues.append(
        "Strong Train/Test distribution shift"
    )

elif domain_acc > 0.60:

    issues.append(
        "Moderate Train/Test distribution shift"
    )

# KS shift
ks_test_pct = np.mean(
    ks_train_test < 0.05
) * 100

if ks_test_pct > 50:

    issues.append(
        "More than 50% of features show significant Train/Test distribution shift"
    )

elif ks_test_pct > 25:

    issues.append(
        "Substantial feature-level Train/Test distribution shift"
    )

# NN distance
nn_ratio_test = (
    test_nn_distance.mean()
    /
    (train_nn_distance.mean() + 1e-8)
)

if nn_ratio_test > 2:

    issues.append(
        "Test samples are substantially farther from training samples"
    )

# NN class consistency
if nn_test_accuracy < 0.40:

    issues.append(
        "Nearest training samples have poor test-label consistency"
    )

# Duplicates
if train_test_overlap > 0:

    issues.append(
        "Exact Train/Test duplicate samples detected"
    )


if len(issues) == 0:

    print(
        "✓ No major distribution problem detected."
    )

else:

    print(
        "Potential issues detected:"
    )

    for i, issue in enumerate(
        issues,
        start=1
    ):

        print(
            f"{i}. {issue}"
        )


# ================================================================
# [24] SAVE DIAGNOSTIC RESULTS
# ================================================================

DIAGNOSTIC_PATH = (
    "/kaggle/working/"
    "step13_1_diagnostic_results.csv"
)

summary_df = pd.DataFrame({

    "Metric": [

        "Flat MLP Validation Accuracy",
        "Flat MLP Test Accuracy",
        "Flat MLP Validation Macro-F1",
        "Flat MLP Test Macro-F1",
        "Validation Accuracy Gap",
        "Validation Macro-F1 Gap",
        "Train-Test Domain Accuracy",
        "Train-Val Domain Accuracy",
        "Validation NN Accuracy",
        "Test NN Accuracy",
        "Train-Test KS Shifted Features",
        "Train-Val KS Shifted Features",
        "Train-Test Exact Duplicates"
    ],

    "Value": [

        results_df.loc[
            results_df["Model"] == "Flat MLP",
            "Validation Accuracy"
        ].iloc[0],

        results_df.loc[
            results_df["Model"] == "Flat MLP",
            "Test Accuracy"
        ].iloc[0],

        results_df.loc[
            results_df["Model"] == "Flat MLP",
            "Validation Macro-F1"
        ].iloc[0],

        results_df.loc[
            results_df["Model"] == "Flat MLP",
            "Test Macro-F1"
        ].iloc[0],

        test_val_acc_gap,

        test_val_f1_gap,

        domain_acc,

        domain_acc_tv,

        nn_val_accuracy,

        nn_test_accuracy,

        np.sum(
            ks_train_test < 0.05
        ),

        np.sum(
            ks_train_val < 0.05
        ),

        train_test_overlap
    ]
})

summary_df.to_csv(
    DIAGNOSTIC_PATH,
    index=False
)

print("\n" + "=" * 80)
print("[18] DIAGNOSTIC RESULTS SAVED")
print("=" * 80)

print(
    "Saved:",
    DIAGNOSTIC_PATH
)


# ================================================================
# [25] FINAL ASSERTIONS
# ================================================================

print("\n" + "=" * 80)
print("FINAL STEP 13.1 ASSERTIONS")
print("=" * 80)

assert X_train_flat.shape == (2700, 128)
assert X_val_flat.shape == (360, 128)
assert X_test_flat.shape == (360, 128)

assert len(y_train) == 2700
assert len(y_val) == 360
assert len(y_test) == 360

assert NUM_CLASSES == 12

assert not np.isnan(
    X_train_flat
).any()

assert not np.isnan(
    X_val_flat
).any()

assert not np.isnan(
    X_test_flat
).any()

assert not np.isinf(
    X_train_flat
).any()

assert not np.isinf(
    X_val_flat
).any()

assert not np.isinf(
    X_test_flat
).any()

print(
    "✓ Train shape verified"
)

print(
    "✓ Validation shape verified"
)

print(
    "✓ Test shape verified"
)

print(
    "✓ 12 classes verified"
)

print(
    "✓ No NaN/Inf detected"
)

print(
    "✓ Distribution diagnostics completed"
)

print(
    "✓ Nearest-neighbor diagnostics completed"
)

print(
    "✓ Duplicate diagnostics completed"
)

print(
    "✓ Step 13.1 complete"
)

print("\n" + "=" * 80)
print("STEP 13.1 FINISHED")
print("=" * 80)

In [ ]:
# ================================================================
# CSE475 — STEP 13.2
# DEEP DISTRIBUTION-SHIFT ANALYSIS
#
# Purpose:
#   1. Identify problematic features
#   2. Measure feature-wise Train/Val/Test shift
#   3. Identify class-wise distribution shift
#   4. Perform PCA visualization
#   5. Perform domain separability analysis
#   6. Check whether the shift is class-dependent
#   7. Identify candidate features for robust modeling
#
# IMPORTANT:
#   - NO test labels are used for model training
#   - NO re-splitting
#   - NO normalization fitted on validation/test
#   - This is DIAGNOSTIC ONLY
# ================================================================


# ================================================================
# [1] IMPORT LIBRARIES
# ================================================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report,
    roc_auc_score
)
from sklearn.feature_selection import f_classif

from scipy.stats import ks_2samp, wasserstein_distance

print("=" * 80)
print("[1] STEP 13.2 — DISTRIBUTION-SHIFT ANALYSIS")
print("=" * 80)


# ================================================================
# [2] CHECK REQUIRED VARIABLES
# ================================================================

required_vars = [
    "X_train_flat",
    "X_val_flat",
    "X_test_flat",
    "y_train",
    "y_val",
    "y_test"
]

missing = [
    v for v in required_vars
    if v not in globals()
]

if missing:

    print("❌ Missing variables:")

    for v in missing:
        print("   -", v)

    raise NameError(
        "\nPlease run Step 13 successfully before Step 13.2."
    )

print("✓ All required variables found")


# ================================================================
# [3] BASIC SHAPES
# ================================================================

print("\n" + "=" * 80)
print("[2] DATA SHAPES")
print("=" * 80)

print("Train :", X_train_flat.shape)
print("Val   :", X_val_flat.shape)
print("Test  :", X_test_flat.shape)

assert X_train_flat.shape[1] == 128
assert X_val_flat.shape[1] == 128
assert X_test_flat.shape[1] == 128

print("✓ 128 features confirmed")


# ================================================================
# [4] FEATURE-WISE STATISTICS
# ================================================================

print("\n" + "=" * 80)
print("[3] FEATURE-WISE DISTRIBUTION STATISTICS")
print("=" * 80)


feature_rows = []

for i in range(128):

    train = X_train_flat[:, i]
    val   = X_val_flat[:, i]
    test  = X_test_flat[:, i]

    # ------------------------------------------------------------
    # KS tests
    # ------------------------------------------------------------

    ks_tv = ks_2samp(
        train,
        val
    )

    ks_tt = ks_2samp(
        train,
        test
    )

    ks_vt = ks_2samp(
        val,
        test
    )

    # ------------------------------------------------------------
    # Wasserstein
    # ------------------------------------------------------------

    wd_tv = wasserstein_distance(
        train,
        val
    )

    wd_tt = wasserstein_distance(
        train,
        test
    )

    wd_vt = wasserstein_distance(
        val,
        test
    )

    # ------------------------------------------------------------
    # Mean shift
    # ------------------------------------------------------------

    train_mean = np.mean(train)
    val_mean   = np.mean(val)
    test_mean  = np.mean(test)

    mean_shift_tv = abs(
        train_mean - val_mean
    )

    mean_shift_tt = abs(
        train_mean - test_mean
    )

    # ------------------------------------------------------------
    # Standard deviation shift
    # ------------------------------------------------------------

    std_shift_tv = abs(
        np.std(train) - np.std(val)
    )

    std_shift_tt = abs(
        np.std(train) - np.std(test)
    )

    feature_rows.append({

        "Feature": i,

        "Train Mean": train_mean,
        "Val Mean": val_mean,
        "Test Mean": test_mean,

        "Train Std": np.std(train),
        "Val Std": np.std(val),
        "Test Std": np.std(test),

        "KS Train-Val": ks_tv.statistic,
        "KS Train-Val p": ks_tv.pvalue,

        "KS Train-Test": ks_tt.statistic,
        "KS Train-Test p": ks_tt.pvalue,

        "KS Val-Test": ks_vt.statistic,
        "KS Val-Test p": ks_vt.pvalue,

        "Wasserstein Train-Val": wd_tv,
        "Wasserstein Train-Test": wd_tt,
        "Wasserstein Val-Test": wd_vt,

        "Mean Shift Train-Val": mean_shift_tv,
        "Mean Shift Train-Test": mean_shift_tt,

        "Std Shift Train-Val": std_shift_tv,
        "Std Shift Train-Test": std_shift_tt
    })


feature_shift_df = pd.DataFrame(
    feature_rows
)


# ================================================================
# [5] RANK FEATURES BY TRAIN→TEST SHIFT
# ================================================================

feature_shift_df = feature_shift_df.sort_values(
    "KS Train-Test",
    ascending=False
).reset_index(
    drop=True
)

print("\nTop 20 features with strongest Train→Test KS shift:")

print(
    feature_shift_df[
        [
            "Feature",
            "KS Train-Test",
            "KS Train-Test p",
            "Wasserstein Train-Test",
            "Mean Shift Train-Test"
        ]
    ]
    .head(20)
    .round(5)
    .to_string(index=False)
)


# ================================================================
# [6] FEATURE SHIFT SEVERITY
# ================================================================

print("\n" + "=" * 80)
print("[4] FEATURE SHIFT SEVERITY")
print("=" * 80)

train_test_significant = (
    feature_shift_df["KS Train-Test p"] < 0.05
)

train_val_significant = (
    feature_shift_df["KS Train-Val p"] < 0.05
)

val_test_significant = (
    feature_shift_df["KS Val-Test p"] < 0.05
)

print(
    "Train→Validation significant:",
    train_val_significant.sum(),
    "/ 128"
)

print(
    "Train→Test significant:",
    train_test_significant.sum(),
    "/ 128"
)

print(
    "Validation→Test significant:",
    val_test_significant.sum(),
    "/ 128"
)

print()

print(
    "Train→Validation percentage:",
    f"{train_val_significant.mean()*100:.2f}%"
)

print(
    "Train→Test percentage:",
    f"{train_test_significant.mean()*100:.2f}%"
)

print(
    "Validation→Test percentage:",
    f"{val_test_significant.mean()*100:.2f}%"
)


# ================================================================
# [7] SHIFT SEVERITY CATEGORIES
# ================================================================

def classify_shift(ks):

    if ks < 0.10:
        return "Low"

    elif ks < 0.20:
        return "Moderate"

    elif ks < 0.30:
        return "High"

    else:
        return "Very High"


feature_shift_df[
    "Train-Test Shift Level"
] = feature_shift_df[
    "KS Train-Test"
].apply(
    classify_shift
)


print("\nTrain→Test shift categories:")

print(
    feature_shift_df[
        "Train-Test Shift Level"
    ]
    .value_counts()
)


# ================================================================
# [8] VISUALIZE TOP SHIFTED FEATURES
# ================================================================

top_features = (
    feature_shift_df
    .head(20)
    ["Feature"]
    .values
)

plt.figure(
    figsize=(14, 7)
)

sns.barplot(
    data=feature_shift_df.head(20),
    x="Feature",
    y="KS Train-Test"
)

plt.axhline(
    0.10,
    linestyle="--",
    label="KS = 0.10"
)

plt.axhline(
    0.20,
    linestyle="--",
    label="KS = 0.20"
)

plt.title(
    "Top 20 Features — Train→Test Distribution Shift"
)

plt.xlabel(
    "Feature Index"
)

plt.ylabel(
    "KS Statistic"
)

plt.xticks(
    rotation=45
)

plt.legend()

plt.tight_layout()

plt.show()


# ================================================================
# [9] FEATURE DISTRIBUTION VISUALIZATION
# ================================================================

print("\n" + "=" * 80)
print("[5] VISUALIZING MOST SHIFTED FEATURES")
print("=" * 80)

# Plot first 6 strongest shifted features individually

for feature_idx in top_features[:6]:

    plt.figure(
        figsize=(10, 5)
    )

    sns.kdeplot(
        X_train_flat[:, feature_idx],
        label="Train",
        fill=True,
        alpha=0.25
    )

    sns.kdeplot(
        X_val_flat[:, feature_idx],
        label="Validation",
        fill=True,
        alpha=0.25
    )

    sns.kdeplot(
        X_test_flat[:, feature_idx],
        label="Test",
        fill=True,
        alpha=0.25
    )

    plt.title(
        f"Feature {feature_idx} — Distribution Comparison"
    )

    plt.xlabel(
        "Feature Value"
    )

    plt.ylabel(
        "Density"
    )

    plt.legend()

    plt.tight_layout()

    plt.show()


# ================================================================
# [10] DOMAIN DATASET
#
# Domain labels:
#   0 = Train
#   1 = Validation
#   2 = Test
#
# This tells us how easily the splits can be distinguished.
# ================================================================

print("\n" + "=" * 80)
print("[6] MULTI-DOMAIN CLASSIFIER")
print("=" * 80)


X_domain = np.vstack([
    X_train_flat,
    X_val_flat,
    X_test_flat
])

domain_labels = np.concatenate([

    np.zeros(
        len(X_train_flat),
        dtype=np.int64
    ),

    np.ones(
        len(X_val_flat),
        dtype=np.int64
    ),

    np.full(
        len(X_test_flat),
        2,
        dtype=np.int64
    )
])


# ---------------------------------------------------------------
# Scale only for domain classifier
#
# IMPORTANT:
# This scaler is used ONLY inside this diagnostic classifier.
# It is NOT used for model training.
# ---------------------------------------------------------------

domain_scaler = StandardScaler()

X_domain_scaled = domain_scaler.fit_transform(
    X_domain
)


domain_classifier = LogisticRegression(
    max_iter=2000,
    random_state=SEED,
    multi_class="auto"
)

domain_classifier.fit(
    X_domain_scaled,
    domain_labels
)

domain_pred = domain_classifier.predict(
    X_domain_scaled
)

domain_accuracy = accuracy_score(
    domain_labels,
    domain_pred
)

print(
    f"Domain classifier training accuracy: "
    f"{domain_accuracy*100:.2f}%"
)

print("\nDomain classification report:")

print(
    classification_report(
        domain_labels,
        domain_pred,
        target_names=[
            "Train",
            "Validation",
            "Test"
        ],
        digits=4,
        zero_division=0
    )
)


# ================================================================
# [11] DOMAIN CONFUSION MATRIX
# ================================================================

domain_cm = confusion_matrix(
    domain_labels,
    domain_pred
)

plt.figure(
    figsize=(7, 6)
)

sns.heatmap(
    domain_cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=[
        "Train",
        "Validation",
        "Test"
    ],
    yticklabels=[
        "Train",
        "Validation",
        "Test"
    ]
)

plt.title(
    "Train / Validation / Test Domain Confusion Matrix"
)

plt.xlabel(
    "Predicted Domain"
)

plt.ylabel(
    "True Domain"
)

plt.tight_layout()

plt.show()


# ================================================================
# [12] DOMAIN CLASSIFIER FEATURE IMPORTANCE
#
# Logistic regression coefficient magnitude gives an indication
# of which features are most useful for identifying the split.
# ================================================================

coef_strength = np.mean(
    np.abs(
        domain_classifier.coef_
    ),
    axis=0
)

domain_feature_importance = pd.DataFrame({

    "Feature": np.arange(128),

    "Domain Importance":
        coef_strength
})

domain_feature_importance = (
    domain_feature_importance
    .sort_values(
        "Domain Importance",
        ascending=False
    )
    .reset_index(drop=True)
)


print("\nTop 20 features responsible for domain separation:")

print(
    domain_feature_importance
    .head(20)
    .round(5)
    .to_string(index=False)
)


# ================================================================
# [13] PCA ANALYSIS
# ================================================================

print("\n" + "=" * 80)
print("[7] PCA DOMAIN VISUALIZATION")
print("=" * 80)


pca = PCA(
    n_components=2,
    random_state=SEED
)

X_pca = pca.fit_transform(
    X_domain_scaled
)

print(
    "Explained variance PC1:",
    f"{pca.explained_variance_ratio_[0]*100:.2f}%"
)

print(
    "Explained variance PC2:",
    f"{pca.explained_variance_ratio_[1]*100:.2f}%"
)

print(
    "Total explained variance:",
    f"{pca.explained_variance_ratio_.sum()*100:.2f}%"
)


pca_df = pd.DataFrame({

    "PC1": X_pca[:, 0],

    "PC2": X_pca[:, 1],

    "Domain": domain_labels
})


pca_df["Domain Name"] = pca_df[
    "Domain"
].map({
    0: "Train",
    1: "Validation",
    2: "Test"
})


plt.figure(
    figsize=(11, 8)
)

sns.scatterplot(
    data=pca_df,
    x="PC1",
    y="PC2",
    hue="Domain Name",
    alpha=0.55,
    s=45
)

plt.title(
    "PCA — Train vs Validation vs Test"
)

plt.xlabel(
    f"PC1 ({pca.explained_variance_ratio_[0]*100:.1f}%)"
)

plt.ylabel(
    f"PC2 ({pca.explained_variance_ratio_[1]*100:.1f}%)"
)

plt.tight_layout()

plt.show()


# ================================================================
# [14] CLASS-WISE CENTROID SHIFT
# ================================================================

print("\n" + "=" * 80)
print("[8] CLASS-WISE CENTROID ANALYSIS")
print("=" * 80)


class_centroid_rows = []

for class_id in range(NUM_CLASSES):

    train_class = X_train_flat[
        y_train == class_id
    ]

    val_class = X_val_flat[
        y_val == class_id
    ]

    test_class = X_test_flat[
        y_test == class_id
    ]

    train_centroid = train_class.mean(
        axis=0
    )

    val_centroid = val_class.mean(
        axis=0
    )

    test_centroid = test_class.mean(
        axis=0
    )

    train_val_dist = np.linalg.norm(
        train_centroid - val_centroid
    )

    train_test_dist = np.linalg.norm(
        train_centroid - test_centroid
    )

    val_test_dist = np.linalg.norm(
        val_centroid - test_centroid
    )

    class_centroid_rows.append({

        "Class ID": class_id,

        "Class": (
            id_to_label[class_id]
            if "id_to_label" in globals()
            else str(class_id)
        ),

        "Train-Val Distance":
            train_val_dist,

        "Train-Test Distance":
            train_test_dist,

        "Val-Test Distance":
            val_test_dist
    })


class_shift_df = pd.DataFrame(
    class_centroid_rows
)


print(
    class_shift_df.round(4)
    .to_string(index=False)
)


# ================================================================
# [15] CLASS-WISE SHIFT RANKING
# ================================================================

print("\n" + "=" * 80)
print("[9] CLASSES MOST AFFECTED BY DOMAIN SHIFT")
print("=" * 80)

class_shift_ranked = (
    class_shift_df
    .sort_values(
        "Train-Test Distance",
        ascending=False
    )
)

print(
    class_shift_ranked.round(4)
    .to_string(index=False)
)


# ================================================================
# [16] CLASS CENTROID SHIFT PLOT
# ================================================================

plt.figure(
    figsize=(13, 6)
)

sns.barplot(
    data=class_shift_ranked,
    x="Class",
    y="Train-Test Distance"
)

plt.title(
    "Class-wise Train→Test Centroid Shift"
)

plt.xlabel(
    "Gesture Class"
)

plt.ylabel(
    "Centroid Distance"
)

plt.xticks(
    rotation=45,
    ha="right"
)

plt.tight_layout()

plt.show()


# ================================================================
# [17] CLASSIFICATION INFORMATION OF FEATURES
#
# ANOVA F-score measures how strongly each feature separates
# the gesture classes in the TRAINING data.
#
# This is useful because a feature can be:
#
#   High domain importance + Low class importance
#
# which means:
#
#   "The feature tells us which split the sample belongs to,
#    rather than which gesture it belongs to."
# ================================================================

print("\n" + "=" * 80)
print("[10] FEATURE CLASS-DISCRIMINATIVE POWER")
print("=" * 80)


F_values, p_values = f_classif(
    X_train_flat,
    y_train
)

class_feature_df = pd.DataFrame({

    "Feature": np.arange(128),

    "ANOVA_F": np.nan_to_num(
        F_values,
        nan=0.0,
        posinf=0.0,
        neginf=0.0
    ),

    "Class_p_value": np.nan_to_num(
        p_values,
        nan=1.0,
        posinf=1.0,
        neginf=1.0
    )
})


class_feature_df = (
    class_feature_df
    .sort_values(
        "ANOVA_F",
        ascending=False
    )
    .reset_index(drop=True)
)


print(
    "Top 20 class-discriminative features:"
)

print(
    class_feature_df
    .head(20)
    .round(5)
    .to_string(index=False)
)


# ================================================================
# [18] COMBINE DOMAIN IMPORTANCE + CLASS IMPORTANCE
# ================================================================

combined_feature_df = (
    feature_shift_df[
        [
            "Feature",
            "KS Train-Test",
            "KS Train-Test p",
            "Wasserstein Train-Test"
        ]
    ]
    .merge(
        domain_feature_importance,
        on="Feature"
    )
    .merge(
        class_feature_df,
        on="Feature"
    )
)


# Normalize ranks

combined_feature_df[
    "Domain Rank"
] = combined_feature_df[
    "Domain Importance"
].rank(
    ascending=False
)

combined_feature_df[
    "Class Rank"
] = combined_feature_df[
    "ANOVA_F"
].rank(
    ascending=False
)


# ================================================================
# [19] POTENTIALLY DANGEROUS FEATURES
#
# High domain importance
# +
# Low class discriminative power
#
# These features may encode recording/session/domain information
# rather than useful gesture information.
# ================================================================

domain_threshold = combined_feature_df[
    "Domain Importance"
].quantile(0.75)

class_threshold = combined_feature_df[
    "ANOVA_F"
].quantile(0.25)


potential_domain_features = (
    combined_feature_df[
        (combined_feature_df["Domain Importance"]
         >= domain_threshold)
        &
        (combined_feature_df["ANOVA_F"]
         <= class_threshold)
    ]
    .sort_values(
        "Domain Importance",
        ascending=False
    )
)


print("\n" + "=" * 80)
print("[11] POTENTIAL DOMAIN-SPECIFIC FEATURES")
print("=" * 80)

print(
    "Features with HIGH domain importance but LOW class discrimination:"
)

if len(potential_domain_features) > 0:

    print(
        potential_domain_features[
            [
                "Feature",
                "KS Train-Test",
                "Wasserstein Train-Test",
                "Domain Importance",
                "ANOVA_F"
            ]
        ]
        .round(5)
        .to_string(index=False)
    )

else:

    print(
        "No strongly suspicious features identified "
        "under the automatic threshold."
    )


# ================================================================
# [20] DOMAIN VS CLASS IMPORTANCE PLOT
# ================================================================

plt.figure(
    figsize=(10, 8)
)

plt.scatter(
    combined_feature_df["ANOVA_F"],
    combined_feature_df["Domain Importance"],
    alpha=0.7
)

plt.xlabel(
    "Class Discriminative Power (ANOVA F)"
)

plt.ylabel(
    "Domain Importance"
)

plt.title(
    "Feature Class Information vs Domain Information"
)

plt.grid(
    alpha=0.3
)

plt.tight_layout()

plt.show()


# ================================================================
# [21] TOP SHIFT FEATURES SUMMARY
# ================================================================

print("\n" + "=" * 80)
print("[12] TOP SHIFT FEATURES SUMMARY")
print("=" * 80)

summary_features = (
    combined_feature_df
    .sort_values(
        [
            "KS Train-Test",
            "Domain Importance"
        ],
        ascending=False
    )
    .head(20)
)

print(
    summary_features[
        [
            "Feature",
            "KS Train-Test",
            "KS Train-Test p",
            "Wasserstein Train-Test",
            "Domain Importance",
            "ANOVA_F"
        ]
    ]
    .round(5)
    .to_string(index=False)
)


# ================================================================
# [22] AUTOMATIC DIAGNOSTIC DECISION
# ================================================================

print("\n" + "=" * 80)
print("[13] STEP 13.2 AUTOMATIC DIAGNOSTIC SUMMARY")
print("=" * 80)


domain_accuracy_pct = (
    domain_accuracy * 100
)

shift_percentage = (
    train_test_significant.mean() * 100
)


if domain_accuracy_pct >= 90:

    domain_status = (
        "SEVERE DOMAIN SEPARATION"
    )

elif domain_accuracy_pct >= 75:

    domain_status = (
        "STRONG DOMAIN SEPARATION"
    )

elif domain_accuracy_pct >= 60:

    domain_status = (
        "MODERATE DOMAIN SEPARATION"
    )

else:

    domain_status = (
        "LOW DOMAIN SEPARATION"
    )


if shift_percentage >= 80:

    feature_status = (
        "SEVERE FEATURE DISTRIBUTION SHIFT"
    )

elif shift_percentage >= 50:

    feature_status = (
        "STRONG FEATURE DISTRIBUTION SHIFT"
    )

elif shift_percentage >= 25:

    feature_status = (
        "MODERATE FEATURE DISTRIBUTION SHIFT"
    )

else:

    feature_status = (
        "LOW FEATURE DISTRIBUTION SHIFT"
    )


print(
    f"Train/Test domain accuracy : "
    f"{domain_accuracy_pct:.2f}%"
)

print(
    f"Significant shifted features: "
    f"{train_test_significant.sum()}/128 "
    f"({shift_percentage:.2f}%)"
)

print(
    "Domain status              :",
    domain_status
)

print(
    "Feature-shift status       :",
    feature_status
)

print(
    "\nNearest-neighbor results from Step 13.1:"
)

if "train_nn_mean" in globals():
    print(
        f"Train NN distance : "
        f"{train_nn_mean:.4f}"
    )

if "val_nn_mean" in globals():
    print(
        f"Val NN distance   : "
        f"{val_nn_mean:.4f}"
    )

if "test_nn_mean" in globals():
    print(
        f"Test NN distance  : "
        f"{test_nn_mean:.4f}"
    )


# ================================================================
# [23] FINAL RESEARCH INTERPRETATION
# ================================================================

print("\n" + "=" * 80)
print("[14] RESEARCH INTERPRETATION")
print("=" * 80)

print(
    """
The diagnostic analysis indicates whether poor test performance
is primarily associated with distribution shift.

Interpretation:

1. If domain classification accuracy is very high,
   Train/Validation/Test samples are highly distinguishable.

2. If a large percentage of features have significant KS shifts,
   the feature distributions are not stable across splits.

3. If PCA shows separated clusters for Train, Validation and Test,
   the splits occupy different regions of feature space.

4. If high-domain-importance features have weak class
   discrimination, those features may encode domain/session
   characteristics rather than gesture-specific information.

5. If class centroid distances are large for particular classes,
   those gestures may be especially sensitive to domain shift.

6. These results should be used BEFORE modifying the GNN architecture.

IMPORTANT:
This cell is diagnostic only.
No test samples are used to train a predictive gesture model.
"""
)


# ================================================================
# [24] SAVE DIAGNOSTIC TABLES
# ================================================================

FEATURE_SHIFT_PATH = (
    "/kaggle/working/"
    "step13_2_feature_shift_analysis.csv"
)

CLASS_SHIFT_PATH = (
    "/kaggle/working/"
    "step13_2_class_shift_analysis.csv"
)

DOMAIN_FEATURE_PATH = (
    "/kaggle/working/"
    "step13_2_domain_feature_importance.csv"
)

COMBINED_FEATURE_PATH = (
    "/kaggle/working/"
    "step13_2_combined_feature_analysis.csv"
)


feature_shift_df.to_csv(
    FEATURE_SHIFT_PATH,
    index=False
)

class_shift_df.to_csv(
    CLASS_SHIFT_PATH,
    index=False
)

domain_feature_importance.to_csv(
    DOMAIN_FEATURE_PATH,
    index=False
)

combined_feature_df.to_csv(
    COMBINED_FEATURE_PATH,
    index=False
)


print("\n" + "=" * 80)
print("[15] FILES SAVED")
print("=" * 80)

print(
    "Feature shift      :",
    FEATURE_SHIFT_PATH
)

print(
    "Class shift        :",
    CLASS_SHIFT_PATH
)

print(
    "Domain importance  :",
    DOMAIN_FEATURE_PATH
)

print(
    "Combined analysis  :",
    COMBINED_FEATURE_PATH
)


# ================================================================
# [25] FINAL ASSERTIONS
# ================================================================

assert X_train_flat.shape[1] == 128
assert X_val_flat.shape[1] == 128
assert X_test_flat.shape[1] == 128

assert len(feature_shift_df) == 128
assert len(domain_feature_importance) == 128
assert len(combined_feature_df) == 128

assert not np.isnan(
    X_train_flat
).any()

assert not np.isnan(
    X_val_flat
).any()

assert not np.isnan(
    X_test_flat
).any()

print("\n" + "=" * 80)
print("✓ STEP 13.2 COMPLETE")
print("=" * 80)

print(
    "Next step should be chosen based on these diagnostic results."
)

In [ ]:
# ================================================================
# CSE475 — STEP 13.3
# DOMAIN-SHIFT MITIGATION
#
# Purpose:
#   Reduce Train/Validation/Test distribution shift detected in
#   Steps 13.1 and 13.2.
#
# IMPORTANT:
#   1. Feature selection is based on TRAINING data only.
#   2. Validation is used ONLY for mitigation-strength selection.
#   3. TEST is NOT used for model/feature selection.
#   4. Wasserstein function name is protected from variable collision.
#   5. Final test evaluation is performed after selection.
# ================================================================


# ================================================================
# [0] IMPORTS
# ================================================================

import os
import time
import copy
import random
import warnings

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import torch
import torch.nn as nn
import torch.nn.functional as F

from scipy.stats import (
    ks_2samp,
    wasserstein_distance as scipy_wasserstein_distance,
    f_oneway
)

from sklearn.feature_selection import f_classif
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

warnings.filterwarnings("ignore")


# ================================================================
# [1] REPRODUCIBILITY & DEVICE
# ================================================================

SEED = 42

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed(SEED)
    torch.cuda.manual_seed_all(SEED)

torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print("=" * 80)
print("STEP 13.3 — DOMAIN-SHIFT MITIGATION")
print("=" * 80)

print("Random seed :", SEED)
print("Device      :", device)

if torch.cuda.is_available():
    print(
        "GPU         :",
        torch.cuda.get_device_name(0)
    )


# ================================================================
# [2] CHECK REQUIRED VARIABLES
# ================================================================

print("\n" + "=" * 80)
print("[1] CHECKING REQUIRED VARIABLES")
print("=" * 80)

required_variables = [
    "X_train_flat",
    "X_val_flat",
    "X_test_flat",
    "y_train",
    "y_val",
    "y_test",
    "NUM_CLASSES"
]

missing = [
    v for v in required_variables
    if v not in globals()
]

if missing:

    print("❌ Missing variables:")

    for v in missing:
        print("   -", v)

    raise NameError(
        "\nStep 13.3 requires variables produced by "
        "Step 13/13.1/13.2.\n"
        "Missing: " + ", ".join(missing)
    )

print("✓ Required variables found")


# ================================================================
# [3] DATA COPY
# ================================================================

Xtr = np.asarray(
    X_train_flat,
    dtype=np.float32
).copy()

Xva = np.asarray(
    X_val_flat,
    dtype=np.float32
).copy()

Xte = np.asarray(
    X_test_flat,
    dtype=np.float32
).copy()

ytr = np.asarray(y_train).astype(np.int64)
yva = np.asarray(y_val).astype(np.int64)
yte = np.asarray(y_test).astype(np.int64)

N_FEATURES = Xtr.shape[1]

print("\n" + "=" * 80)
print("[2] ORIGINAL DATA")
print("=" * 80)

print("Train :", Xtr.shape)
print("Val   :", Xva.shape)
print("Test  :", Xte.shape)
print("Classes:", NUM_CLASSES)

assert Xtr.shape[1] == 128
assert Xva.shape[1] == 128
assert Xte.shape[1] == 128

print("✓ 128 features confirmed")


# ================================================================
# [4] SANITY CHECK
# ================================================================

assert len(Xtr) == len(ytr)
assert len(Xva) == len(yva)
assert len(Xte) == len(yte)

assert np.isfinite(Xtr).all()
assert np.isfinite(Xva).all()
assert np.isfinite(Xte).all()

print("✓ Train alignment verified")
print("✓ Validation alignment verified")
print("✓ Test alignment verified")
print("✓ No NaN/Inf detected")


# ================================================================
# [5] TRAIN-ONLY CLASS DISCRIMINATION
#
# IMPORTANT:
# ANOVA is calculated using TRAINING DATA ONLY.
# ================================================================

print("\n" + "=" * 80)
print("[3] TRAIN-ONLY CLASS DISCRIMINATION")
print("=" * 80)

anova_f, anova_p = f_classif(
    Xtr,
    ytr
)

anova_f = np.nan_to_num(
    anova_f,
    nan=0.0,
    posinf=0.0,
    neginf=0.0
)

anova_p = np.nan_to_num(
    anova_p,
    nan=1.0,
    posinf=1.0,
    neginf=1.0
)

print(
    f"Highest ANOVA F-score: "
    f"{np.max(anova_f):.4f}"
)

print(
    f"Lowest ANOVA p-value: "
    f"{np.min(anova_p):.5e}"
)


# ================================================================
# [6] TRAIN → VALIDATION SHIFT
#
# IMPORTANT:
# These statistics are diagnostic.
# They do NOT use labels from validation/test.
# ================================================================

print("\n" + "=" * 80)
print("[4] TRAIN → VALIDATION FEATURE SHIFT")
print("=" * 80)

ks_val_stat = np.zeros(
    N_FEATURES,
    dtype=np.float32
)

ks_val_p = np.ones(
    N_FEATURES,
    dtype=np.float32
)

wasserstein_val_scores = np.zeros(
    N_FEATURES,
    dtype=np.float32
)

for j in range(N_FEATURES):

    ks_result = ks_2samp(
        Xtr[:, j],
        Xva[:, j]
    )

    ks_val_stat[j] = ks_result.statistic
    ks_val_p[j] = ks_result.pvalue

    wasserstein_val_scores[j] = (
        scipy_wasserstein_distance(
            Xtr[:, j],
            Xva[:, j]
        )
    )

print(
    "Significant KS features:",
    np.sum(ks_val_p < 0.05),
    "/",
    N_FEATURES
)

print(
    "Percentage shifted:",
    f"{100*np.mean(ks_val_p < 0.05):.2f}%"
)

print(
    "Mean Wasserstein:",
    f"{np.mean(wasserstein_val_scores):.4f}"
)

print(
    "Maximum Wasserstein:",
    f"{np.max(wasserstein_val_scores):.4f}"
)


# ================================================================
# [7] TRAIN → TEST SHIFT
#
# Diagnostic only.
# TEST IS NOT USED TO SELECT MITIGATION.
# ================================================================

print("\n" + "=" * 80)
print("[5] TRAIN → TEST FEATURE SHIFT")
print("=" * 80)

ks_test_stat = np.zeros(
    N_FEATURES,
    dtype=np.float32
)

ks_test_p = np.ones(
    N_FEATURES,
    dtype=np.float32
)

wasserstein_test_scores = np.zeros(
    N_FEATURES,
    dtype=np.float32
)

for j in range(N_FEATURES):

    ks_result = ks_2samp(
        Xtr[:, j],
        Xte[:, j]
    )

    ks_test_stat[j] = ks_result.statistic
    ks_test_p[j] = ks_result.pvalue

    wasserstein_test_scores[j] = (
        scipy_wasserstein_distance(
            Xtr[:, j],
            Xte[:, j]
        )
    )

print(
    "Significant KS features:",
    np.sum(ks_test_p < 0.05),
    "/",
    N_FEATURES
)

print(
    "Percentage shifted:",
    f"{100*np.mean(ks_test_p < 0.05):.2f}%"
)

print(
    "Mean Wasserstein:",
    f"{np.mean(wasserstein_test_scores):.4f}"
)

print(
    "Maximum Wasserstein:",
    f"{np.max(wasserstein_test_scores):.4f}"
)


# ================================================================
# [8] IDENTIFY DOMAIN-SPECIFIC FEATURES
#
# Strategy:
#
#   High domain shift
#       +
#   Low class discrimination
#
# These are safer candidates for removal/downweighting.
#
# We DO NOT simply remove all shifted features because some
# shifted features may also contain useful class information.
# ================================================================

print("\n" + "=" * 80)
print("[6] DOMAIN-SPECIFIC FEATURE IDENTIFICATION")
print("=" * 80)

# Train-only thresholds

DOMAIN_KS_THRESHOLD = 0.20
DOMAIN_WASSERSTEIN_THRESHOLD = (
    np.percentile(
        wasserstein_val_scores,
        75
    )
)

CLASS_F_THRESHOLD = (
    np.percentile(
        anova_f,
        25
    )
)

print(
    "Domain KS threshold       :",
    DOMAIN_KS_THRESHOLD
)

print(
    "Domain Wasserstein threshold:",
    f"{DOMAIN_WASSERSTEIN_THRESHOLD:.4f}"
)

print(
    "Low class-discrimination F threshold:",
    f"{CLASS_F_THRESHOLD:.4f}"
)


domain_specific_mask = (
    (ks_val_stat >= DOMAIN_KS_THRESHOLD)
    &
    (wasserstein_val_scores >= DOMAIN_WASSERSTEIN_THRESHOLD)
    &
    (anova_f <= CLASS_F_THRESHOLD)
)

domain_specific_features = np.where(
    domain_specific_mask
)[0]

print(
    "\nPotential domain-specific features:",
    len(domain_specific_features)
)

print(
    "Feature IDs:",
    domain_specific_features.tolist()
)


# ================================================================
# [9] IMPORTANT:
# PROTECT HIGHLY CLASS-DISCRIMINATIVE FEATURES
# ================================================================

print("\n" + "=" * 80)
print("[7] CLASS-DISCRIMINATIVE FEATURE PROTECTION")
print("=" * 80)

# Protect top 30% class-discriminative features

CLASS_PROTECTION_PERCENTILE = 70

class_protection_threshold = np.percentile(
    anova_f,
    CLASS_PROTECTION_PERCENTILE
)

protected_mask = (
    anova_f >= class_protection_threshold
)

protected_features = np.where(
    protected_mask
)[0]

print(
    "Protection percentile:",
    CLASS_PROTECTION_PERCENTILE,
    "%"
)

print(
    "Protection F threshold:",
    f"{class_protection_threshold:.4f}"
)

print(
    "Protected features:",
    len(protected_features)
)

# Never remove strongly class-discriminative features
mitigation_mask = (
    domain_specific_mask
    &
    (~protected_mask)
)

mitigation_features = np.where(
    mitigation_mask
)[0]

print(
    "Final mitigation features:",
    len(mitigation_features)
)

print(
    "Final mitigation feature IDs:",
    mitigation_features.tolist()
)


# ================================================================
# [10] FEATURE IMPORTANCE TABLE
# ================================================================

feature_table = pd.DataFrame({

    "Feature":
        np.arange(N_FEATURES),

    "ANOVA_F":
        anova_f,

    "ANOVA_p":
        anova_p,

    "KS_Train_Val":
        ks_val_stat,

    "KS_Train_Val_p":
        ks_val_p,

    "Wasserstein_Train_Val":
        wasserstein_val_scores,

    "Domain_Specific":
        domain_specific_mask,

    "Protected_Class_Feature":
        protected_mask,

    "Mitigation_Feature":
        mitigation_mask
})

print("\n" + "=" * 80)
print("[8] MITIGATION FEATURE TABLE")
print("=" * 80)

print(
    feature_table[
        feature_table["Mitigation_Feature"]
    ]
    .sort_values(
        "Wasserstein_Train_Val",
        ascending=False
    )
    .head(30)
    .round(5)
    .to_string(index=False)
)


# ================================================================
# [11] BASELINE MLP
#
# This is a new diagnostic baseline trained using the SAME
# training/validation protocol.
# ================================================================

print("\n" + "=" * 80)
print("[9] BASELINE MLP")
print("=" * 80)


class DiagnosticMLP(nn.Module):

    def __init__(
        self,
        input_dim,
        hidden_dim=128,
        num_classes=12,
        dropout=0.30
    ):

        super().__init__()

        self.net = nn.Sequential(

            nn.Linear(
                input_dim,
                hidden_dim
            ),

            nn.BatchNorm1d(
                hidden_dim
            ),

            nn.ReLU(),

            nn.Dropout(
                dropout
            ),

            nn.Linear(
                hidden_dim,
                hidden_dim
            ),

            nn.ReLU(),

            nn.Dropout(
                dropout
            ),

            nn.Linear(
                hidden_dim,
                num_classes
            )
        )

    def forward(self, x):

        return self.net(x)


# ================================================================
# [12] TRAINING FUNCTION
# ================================================================

def train_mlp(
    X_train,
    y_train_local,
    X_val,
    y_val_local,
    input_dim,
    model_name,
    epochs=80,
    lr=0.001,
    weight_decay=1e-4,
    patience=12
):

    torch.manual_seed(SEED)

    model = DiagnosticMLP(
        input_dim=input_dim,
        hidden_dim=128,
        num_classes=NUM_CLASSES,
        dropout=0.30
    ).to(device)

    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=lr,
        weight_decay=weight_decay
    )

    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer,
        mode="max",
        factor=0.5,
        patience=5
    )

    criterion = nn.CrossEntropyLoss()

    Xtr_t = torch.tensor(
        X_train,
        dtype=torch.float32,
        device=device
    )

    Xva_t = torch.tensor(
        X_val,
        dtype=torch.float32,
        device=device
    )

    ytr_t = torch.tensor(
        y_train_local,
        dtype=torch.long,
        device=device
    )

    yva_t = torch.tensor(
        y_val_local,
        dtype=torch.long,
        device=device
    )

    best_f1 = -np.inf
    best_epoch = 0
    best_state = None

    history = []

    start_time = time.time()

    for epoch in range(1, epochs + 1):

        model.train()

        optimizer.zero_grad(
            set_to_none=True
        )

        logits = model(
            Xtr_t
        )

        loss = criterion(
            logits,
            ytr_t
        )

        loss.backward()

        torch.nn.utils.clip_grad_norm_(
            model.parameters(),
            1.0
        )

        optimizer.step()

        # --------------------------------------------------------
        # Validation
        # --------------------------------------------------------

        model.eval()

        with torch.no_grad():

            val_logits = model(
                Xva_t
            )

        val_pred = torch.argmax(
            val_logits,
            dim=1
        ).cpu().numpy()

        val_f1 = f1_score(
            y_val_local,
            val_pred,
            average="macro",
            zero_division=0
        )

        val_acc = accuracy_score(
            y_val_local,
            val_pred
        )

        history.append(
            {
                "epoch": epoch,
                "val_f1": val_f1,
                "val_accuracy": val_acc,
                "loss": loss.item()
            }
        )

        scheduler.step(
            val_f1
        )

        if val_f1 > best_f1:

            best_f1 = val_f1
            best_epoch = epoch

            best_state = copy.deepcopy(
                model.state_dict()
            )

        if epoch == 1 or epoch % 10 == 0:

            print(
                f"{model_name:28s} | "
                f"Epoch {epoch:02d}/{epochs} | "
                f"Loss {loss.item():.4f} | "
                f"Val Acc {val_acc*100:.2f}% | "
                f"Val Macro-F1 {val_f1*100:.2f}%"
            )

        if epoch - best_epoch >= patience:
            break

    training_time = (
        time.time() - start_time
    )

    model.load_state_dict(
        best_state
    )

    return (
        model,
        {
            "best_val_f1": best_f1,
            "best_epoch": best_epoch,
            "training_time": training_time,
            "history": history
        }
    )


# ================================================================
# [13] EVALUATION FUNCTION
# ================================================================

def evaluate_mlp(
    model,
    X,
    y
):

    model.eval()

    X_t = torch.tensor(
        X,
        dtype=torch.float32,
        device=device
    )

    start = time.perf_counter()

    with torch.no_grad():

        logits = model(
            X_t
        )

    if torch.cuda.is_available():
        torch.cuda.synchronize()

    inference_time = (
        time.perf_counter() - start
    )

    predictions = torch.argmax(
        logits,
        dim=1
    ).cpu().numpy()

    return {

        "accuracy":
            accuracy_score(
                y,
                predictions
            ),

        "precision":
            precision_score(
                y,
                predictions,
                average="macro",
                zero_division=0
            ),

        "recall":
            recall_score(
                y,
                predictions,
                average="macro",
                zero_division=0
            ),

        "macro_f1":
            f1_score(
                y,
                predictions,
                average="macro",
                zero_division=0
            ),

        "inference_time":
            inference_time,

        "predictions":
            predictions
    }


# ================================================================
# [14] BASELINE MODEL
# ================================================================

baseline_model, baseline_history = train_mlp(
    Xtr,
    ytr,
    Xva,
    yva,
    input_dim=128,
    model_name="Original 128-feature MLP"
)

baseline_val = evaluate_mlp(
    baseline_model,
    Xva,
    yva
)

print("\nBaseline validation performance:")

print(
    f"Accuracy : "
    f"{baseline_val['accuracy']*100:.2f}%"
)

print(
    f"Macro-F1 : "
    f"{baseline_val['macro_f1']*100:.2f}%"
)


# ================================================================
# [15] MITIGATION STRATEGIES
#
# We test several strengths.
#
# Strategy A:
#   Remove identified domain-specific features.
#
# Strategy B:
#   Keep 90% of features but downweight problematic features.
#
# Strategy C:
#   Keep 80% of features but downweight problematic features.
#
# Validation Macro-F1 determines the best strategy.
# ================================================================

print("\n" + "=" * 80)
print("[10] DOMAIN-SHIFT MITIGATION EXPERIMENTS")
print("=" * 80)


mitigation_results = []

mitigation_models = {}

mitigation_histories = {}


# ---------------------------------------------------------------
# Strategy 1 — Remove domain-specific features
# ---------------------------------------------------------------

if len(mitigation_features) > 0:

    keep_mask = np.ones(
        N_FEATURES,
        dtype=bool
    )

    keep_mask[
        mitigation_features
    ] = False

    Xtr_remove = Xtr[:, keep_mask]
    Xva_remove = Xva[:, keep_mask]

    print("\n--- Strategy 1: Feature Removal ---")

    print(
        "Original features:",
        N_FEATURES
    )

    print(
        "Removed features:",
        len(mitigation_features)
    )

    print(
        "Remaining features:",
        Xtr_remove.shape[1]
    )

    remove_model, remove_history = train_mlp(
        Xtr_remove,
        ytr,
        Xva_remove,
        yva,
        input_dim=Xtr_remove.shape[1],
        model_name="Domain Feature Removal"
    )

    remove_val = evaluate_mlp(
        remove_model,
        Xva_remove,
        yva
    )

    mitigation_results.append({

        "Strategy":
            "Feature Removal",

        "Features":
            Xtr_remove.shape[1],

        "Validation Accuracy":
            remove_val["accuracy"],

        "Validation Macro-F1":
            remove_val["macro_f1"],

        "Best Epoch":
            remove_history["best_epoch"],

        "Training Time":
            remove_history["training_time"]
    })

    mitigation_models[
        "Feature Removal"
    ] = (
        remove_model,
        keep_mask
    )

    mitigation_histories[
        "Feature Removal"
    ] = remove_history


# ---------------------------------------------------------------
# Strategy 2 — Moderate downweighting
# ---------------------------------------------------------------

print("\n--- Strategy 2: Moderate Domain Downweighting ---")

Xtr_down50 = Xtr.copy()
Xva_down50 = Xva.copy()

if len(mitigation_features) > 0:

    Xtr_down50[
        :,
        mitigation_features
    ] *= 0.50

    Xva_down50[
        :,
        mitigation_features
    ] *= 0.50

down50_model, down50_history = train_mlp(
    Xtr_down50,
    ytr,
    Xva_down50,
    yva,
    input_dim=128,
    model_name="50% Domain Downweight"
)

down50_val = evaluate_mlp(
    down50_model,
    Xva_down50,
    yva
)

mitigation_results.append({

    "Strategy":
        "50% Domain Downweight",

    "Features":
        128,

    "Validation Accuracy":
        down50_val["accuracy"],

    "Validation Macro-F1":
        down50_val["macro_f1"],

    "Best Epoch":
        down50_history["best_epoch"],

    "Training Time":
        down50_history["training_time"]
})

mitigation_models[
    "50% Domain Downweight"
] = (
    down50_model,
    None
)

mitigation_histories[
    "50% Domain Downweight"
] = down50_history


# ---------------------------------------------------------------
# Strategy 3 — Strong downweighting
# ---------------------------------------------------------------

print("\n--- Strategy 3: Strong Domain Downweighting ---")

Xtr_down25 = Xtr.copy()
Xva_down25 = Xva.copy()

if len(mitigation_features) > 0:

    Xtr_down25[
        :,
        mitigation_features
    ] *= 0.25

    Xva_down25[
        :,
        mitigation_features
    ] *= 0.25

down25_model, down25_history = train_mlp(
    Xtr_down25,
    ytr,
    Xva_down25,
    yva,
    input_dim=128,
    model_name="25% Domain Downweight"
)

down25_val = evaluate_mlp(
    down25_model,
    Xva_down25,
    yva
)

mitigation_results.append({

    "Strategy":
        "25% Domain Downweight",

    "Features":
        128,

    "Validation Accuracy":
        down25_val["accuracy"],

    "Validation Macro-F1":
        down25_val["macro_f1"],

    "Best Epoch":
        down25_history["best_epoch"],

    "Training Time":
        down25_history["training_time"]
})

mitigation_models[
    "25% Domain Downweight"
] = (
    down25_model,
    None
)

mitigation_histories[
    "25% Domain Downweight"
] = down25_history


# ================================================================
# [16] MITIGATION COMPARISON
# ================================================================

mitigation_df = pd.DataFrame(
    mitigation_results
)

print("\n" + "=" * 80)
print("[11] MITIGATION VALIDATION COMPARISON")
print("=" * 80)

display_mitigation = (
    mitigation_df.copy()
)

display_mitigation[
    "Validation Accuracy"
] *= 100

display_mitigation[
    "Validation Macro-F1"
] *= 100

print(
    display_mitigation.round(2).to_string(
        index=False
    )
)


# ================================================================
# [17] SELECT BEST MITIGATION
#
# IMPORTANT:
# ONLY VALIDATION MACRO-F1 IS USED.
# ================================================================

print("\n" + "=" * 80)
print("[12] SELECTING BEST MITIGATION")
print("=" * 80)

baseline_candidate = {

    "Strategy":
        "Original Features",

    "Features":
        128,

    "Validation Accuracy":
        baseline_val["accuracy"],

    "Validation Macro-F1":
        baseline_val["macro_f1"],

    "Best Epoch":
        baseline_history["best_epoch"],

    "Training Time":
        baseline_history["training_time"]
}

all_candidates = (
    mitigation_results
    + [baseline_candidate]
)

selection_df = pd.DataFrame(
    all_candidates
)

best_idx = selection_df[
    "Validation Macro-F1"
].idxmax()

best_strategy = selection_df.loc[
    best_idx,
    "Strategy"
]

best_val_f1 = selection_df.loc[
    best_idx,
    "Validation Macro-F1"
]

best_val_acc = selection_df.loc[
    best_idx,
    "Validation Accuracy"
]

print(
    "Best mitigation strategy:",
    best_strategy
)

print(
    f"Validation Accuracy : "
    f"{best_val_acc*100:.2f}%"
)

print(
    f"Validation Macro-F1 : "
    f"{best_val_f1*100:.2f}%"
)

print(
    "\n✓ Test set NOT used for mitigation selection"
)


# ================================================================
# [18] PREPARE FINAL TEST DATA
#
# Test transformation is applied ONLY AFTER the strategy
# has been selected using validation.
# ================================================================

if best_strategy == "Original Features":

    final_model = baseline_model

    Xte_final = Xte.copy()

elif best_strategy == "Feature Removal":

    final_model = mitigation_models[
        "Feature Removal"
    ][0]

    final_keep_mask = mitigation_models[
        "Feature Removal"
    ][1]

    Xte_final = Xte[
        :,
        final_keep_mask
    ]

elif best_strategy == "50% Domain Downweight":

    final_model = mitigation_models[
        "50% Domain Downweight"
    ][0]

    Xte_final = Xte.copy()

    if len(mitigation_features) > 0:

        Xte_final[
            :,
            mitigation_features
        ] *= 0.50

elif best_strategy == "25% Domain Downweight":

    final_model = mitigation_models[
        "25% Domain Downweight"
    ][0]

    Xte_final = Xte.copy()

    if len(mitigation_features) > 0:

        Xte_final[
            :,
            mitigation_features
        ] *= 0.25

else:

    raise RuntimeError(
        "Unknown mitigation strategy."
    )


# ================================================================
# [19] FINAL TEST EVALUATION
# ================================================================

print("\n" + "=" * 80)
print("[13] FINAL TEST PERFORMANCE")
print("=" * 80)

final_test = evaluate_mlp(
    final_model,
    Xte_final,
    yte
)

print(
    f"Test Accuracy  : "
    f"{final_test['accuracy']*100:.2f}%"
)

print(
    f"Test Precision : "
    f"{final_test['precision']*100:.2f}%"
)

print(
    f"Test Recall    : "
    f"{final_test['recall']*100:.2f}%"
)

print(
    f"Test Macro-F1  : "
    f"{final_test['macro_f1']*100:.2f}%"
)

print(
    f"Inference Time : "
    f"{final_test['inference_time']:.6f} sec"
)


# ================================================================
# [20] BASELINE VS MITIGATED
# ================================================================

print("\n" + "=" * 80)
print("[14] BASELINE VS MITIGATED MODEL")
print("=" * 80)

baseline_test = evaluate_mlp(
    baseline_model,
    Xte,
    yte
)

acc_gain = (
    final_test["accuracy"]
    - baseline_test["accuracy"]
)

f1_gain = (
    final_test["macro_f1"]
    - baseline_test["macro_f1"]
)

comparison_df = pd.DataFrame({

    "Model": [
        "Original MLP",
        "Domain-Shift Mitigated MLP"
    ],

    "Validation Accuracy": [
        baseline_val["accuracy"] * 100,
        best_val_acc * 100
    ],

    "Validation Macro-F1": [
        baseline_val["macro_f1"] * 100,
        best_val_f1 * 100
    ],

    "Test Accuracy": [
        baseline_test["accuracy"] * 100,
        final_test["accuracy"] * 100
    ],

    "Test Macro-F1": [
        baseline_test["macro_f1"] * 100,
        final_test["macro_f1"] * 100
    ]
})

print(
    comparison_df.round(2).to_string(
        index=False
    )
)

print(
    f"\nTest Accuracy change : "
    f"{acc_gain*100:+.2f} percentage points"
)

print(
    f"Test Macro-F1 change : "
    f"{f1_gain*100:+.2f} percentage points"
)


# ================================================================
# [21] CONFUSION MATRIX
# ================================================================

print("\n" + "=" * 80)
print("[15] FINAL MODEL CONFUSION MATRIX")
print("=" * 80)

cm = confusion_matrix(
    yte,
    final_test["predictions"]
)

plt.figure(
    figsize=(11, 9)
)

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=[
        str(i)
        for i in range(NUM_CLASSES)
    ],
    yticklabels=[
        str(i)
        for i in range(NUM_CLASSES)
    ]
)

plt.title(
    f"Step 13.3 — {best_strategy}\n"
    "Test Confusion Matrix"
)

plt.xlabel(
    "Predicted Class"
)

plt.ylabel(
    "True Class"
)

plt.tight_layout()

plt.show()


# ================================================================
# [22] CLASSIFICATION REPORT
# ================================================================

print("\n" + "=" * 80)
print("[16] FINAL CLASSIFICATION REPORT")
print("=" * 80)

print(
    classification_report(
        yte,
        final_test["predictions"],
        digits=4,
        zero_division=0
    )
)


# ================================================================
# [23] TRAINING CURVES
# ================================================================

print("\n" + "=" * 80)
print("[17] VALIDATION CURVES")
print("=" * 80)

plt.figure(
    figsize=(12, 7)
)

plt.plot(
    [
        x["val_f1"] * 100
        for x in baseline_history["history"]
    ],
    label="Original MLP"
)

for name, history in mitigation_histories.items():

    plt.plot(
        [
            x["val_f1"] * 100
            for x in history["history"]
        ],
        label=name
    )

plt.xlabel(
    "Epoch"
)

plt.ylabel(
    "Validation Macro-F1 (%)"
)

plt.title(
    "Step 13.3 — Domain-Shift Mitigation"
)

plt.legend()

plt.grid(
    alpha=0.3
)

plt.tight_layout()

plt.show()


# ================================================================
# [24] TOP MITIGATION FEATURES
# ================================================================

print("\n" + "=" * 80)
print("[18] FEATURES TARGETED FOR MITIGATION")
print("=" * 80)

if len(mitigation_features) == 0:

    print(
        "No features met the conservative mitigation criteria."
    )

else:

    targeted_features_df = (
        feature_table[
            feature_table[
                "Mitigation_Feature"
            ]
        ]
        .sort_values(
            "Wasserstein_Train_Val",
            ascending=False
        )
    )

    print(
        targeted_features_df[
            [
                "Feature",
                "ANOVA_F",
                "KS_Train_Val",
                "KS_Train_Val_p",
                "Wasserstein_Train_Val"
            ]
        ]
        .round(5)
        .to_string(index=False)
    )


# ================================================================
# [25] SAVE RESULTS
# ================================================================

STEP13_3_RESULTS_PATH = (
    "/kaggle/working/"
    "step13_3_domain_shift_results.csv"
)

comparison_df.to_csv(
    STEP13_3_RESULTS_PATH,
    index=False
)

MITIGATION_RESULTS_PATH = (
    "/kaggle/working/"
    "step13_3_mitigation_comparison.csv"
)

selection_df.to_csv(
    MITIGATION_RESULTS_PATH,
    index=False
)

FEATURE_RESULTS_PATH = (
    "/kaggle/working/"
    "step13_3_feature_analysis.csv"
)

feature_table.to_csv(
    FEATURE_RESULTS_PATH,
    index=False
)


# ================================================================
# [26] SAVE FINAL MODEL
# ================================================================

MODEL_PATH = (
    "/kaggle/working/"
    "step13_3_domain_mitigated_mlp.pth"
)

torch.save(
    {

        "model_state_dict":
            final_model.state_dict(),

        "model_name":
            "Domain-Shift Mitigated MLP",

        "best_strategy":
            best_strategy,

        "input_dim":
            Xte_final.shape[1],

        "num_classes":
            NUM_CLASSES,

        "mitigation_features":
            mitigation_features.tolist(),

        "class_protected_features":
            protected_features.tolist(),

        "seed":
            SEED
    },
    MODEL_PATH
)


# ================================================================
# [27] FINAL DIAGNOSTIC SUMMARY
# ================================================================

print("\n" + "=" * 80)
print("[19] STEP 13.3 FINAL SUMMARY")
print("=" * 80)

print(
    "Original Test Accuracy : "
    f"{baseline_test['accuracy']*100:.2f}%"
)

print(
    "Mitigated Test Accuracy: "
    f"{final_test['accuracy']*100:.2f}%"
)

print()

print(
    "Original Test Macro-F1 : "
    f"{baseline_test['macro_f1']*100:.2f}%"
)

print(
    "Mitigated Test Macro-F1: "
    f"{final_test['macro_f1']*100:.2f}%"
)

print()

print(
    "Selected strategy:",
    best_strategy
)

print(
    "Mitigation features:",
    len(mitigation_features)
)

print(
    "Validation Macro-F1:",
    f"{best_val_f1*100:.2f}%"
)

print(
    "Test Accuracy change:",
    f"{acc_gain*100:+.2f} pp"
)

print(
    "Test Macro-F1 change:",
    f"{f1_gain*100:+.2f} pp"
)

print()

print("Saved files:")
print(
    "1.",
    STEP13_3_RESULTS_PATH
)
print(
    "2.",
    MITIGATION_RESULTS_PATH
)
print(
    "3.",
    FEATURE_RESULTS_PATH
)
print(
    "4.",
    MODEL_PATH
)


# ================================================================
# [28] FINAL ASSERTIONS
# ================================================================

print("\n" + "=" * 80)
print("FINAL STEP 13.3 ASSERTIONS")
print("=" * 80)

assert Xtr.shape == (2700, 128)
assert Xva.shape == (360, 128)
assert Xte.shape == (360, 128)

assert len(ytr) == 2700
assert len(yva) == 360
assert len(yte) == 360

assert len(anova_f) == 128
assert len(ks_val_stat) == 128
assert len(wasserstein_val_scores) == 128

assert np.isfinite(
    Xtr
).all()

assert np.isfinite(
    Xva
).all()

assert np.isfinite(
    Xte
).all()

assert best_strategy in [
    "Original Features",
    "Feature Removal",
    "50% Domain Downweight",
    "25% Domain Downweight"
]

print("✓ 2700 training samples verified")
print("✓ 360 validation samples verified")
print("✓ 360 test samples verified")
print("✓ 128 features verified")
print("✓ Train-only ANOVA performed")
print("✓ Train→Validation shift calculated")
print("✓ Train→Test shift calculated")
print("✓ Domain-specific features identified")
print("✓ Class-discriminative features protected")
print("✓ Validation-only mitigation selection performed")
print("✓ Test set NOT used for mitigation selection")
print("✓ Final test evaluation completed")
print("✓ Step 13.3 completed successfully")

print("\n" + "=" * 80)
print("STEP 13.3 FINISHED")
print("=" * 80)

In [ ]:
# ================================================================
# CSE475 — STEP 13.4
# FINAL ROBUST MODEL EVALUATION
#
# IMPORTANT:
#   ✓ Model selection = Validation Macro-F1 ONLY
#   ✓ Test set is used ONLY once for final evaluation
#   ✓ No test information is used for model selection
#   ✓ Works with variables created in Step 13, 13.1, 13.2, 13.3
#
# Outputs:
#   1. Final model selection
#   2. Test performance
#   3. Balanced Accuracy
#   4. MCC
#   5. Cohen's Kappa
#   6. Confidence statistics
#   7. Per-class metrics
#   8. Confusion matrices
#   9. Validation vs Test comparison
#  10. Final CSV files
# ================================================================


# ================================================================
# [1] IMPORTS
# ================================================================

import os
import time
import copy
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import torch
import torch.nn as nn

from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    matthews_corrcoef,
    cohen_kappa_score,
    classification_report,
    confusion_matrix
)

print("=" * 80)
print("STEP 13.4 — FINAL ROBUST MODEL EVALUATION")
print("=" * 80)


# ================================================================
# [2] REPRODUCIBILITY
# ================================================================

SEED = 42

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed(SEED)
    torch.cuda.manual_seed_all(SEED)

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print("\nRandom seed :", SEED)
print("Device      :", device)

if torch.cuda.is_available():
    print("GPU         :", torch.cuda.get_device_name(0))


# ================================================================
# [3] CHECK REQUIRED VARIABLES
# ================================================================

print("\n" + "=" * 80)
print("[1] CHECKING REQUIRED VARIABLES")
print("=" * 80)

required_variables = [
    "results_df",
    "flat_model",
    "gcn_model",
    "sage_model",
    "gat_model",
    "fusion_model",
    "X_test_flat_t",
    "X_test_graph_t",
    "y_test",
    "y_test_t",
    "A_tensor",
    "NUM_CLASSES",
    "id_to_label"
]

missing = [
    v for v in required_variables
    if v not in globals()
]

if missing:

    print("❌ Missing variables:")

    for v in missing:
        print("   -", v)

    raise NameError(
        "\nRequired Step 13 variables are missing.\n"
        "Please run Step 13 first."
    )

print("✓ Required variables found")


# ================================================================
# [4] MODEL DICTIONARY
# ================================================================

model_dict = {

    "Flat MLP": {
        "model": flat_model,
        "use_graph": False,
        "use_flat": True
    },

    "GCN": {
        "model": gcn_model,
        "use_graph": True,
        "use_flat": False
    },

    "GraphSAGE": {
        "model": sage_model,
        "use_graph": True,
        "use_flat": False
    },

    "GAT": {
        "model": gat_model,
        "use_graph": True,
        "use_flat": False
    },

    "GAT + Fusion": {
        "model": fusion_model,
        "use_graph": True,
        "use_flat": True
    }
}


# ================================================================
# [5] SELECT FINAL MODEL
#
# CRITICAL:
# Best model is selected using VALIDATION Macro-F1.
# TEST Macro-F1 is NOT used here.
# ================================================================

print("\n" + "=" * 80)
print("[2] FINAL MODEL SELECTION")
print("=" * 80)

selection_df = results_df.copy()

selection_df = selection_df.sort_values(
    by="Validation Macro-F1",
    ascending=False
).reset_index(drop=True)

print("\nModels ranked by Validation Macro-F1:")

print(
    selection_df[
        [
            "Model",
            "Validation Accuracy",
            "Validation Macro-F1",
            "Test Accuracy",
            "Test Macro-F1"
        ]
    ].to_string(index=False)
)

best_model_name = selection_df.loc[
    0,
    "Model"
]

best_validation_f1 = selection_df.loc[
    0,
    "Validation Macro-F1"
]

best_validation_acc = selection_df.loc[
    0,
    "Validation Accuracy"
]

print("\n" + "-" * 80)

print(
    "FINAL MODEL:",
    best_model_name
)

print(
    f"Validation Accuracy : "
    f"{best_validation_acc * 100:.2f}%"
)

print(
    f"Validation Macro-F1 : "
    f"{best_validation_f1 * 100:.2f}%"
)

print(
    "✓ Selection performed using Validation Macro-F1 ONLY"
)

print(
    "✓ Test set NOT used for model selection"
)


# ================================================================
# [6] GET SELECTED MODEL
# ================================================================

selected_info = model_dict[
    best_model_name
]

final_model = selected_info["model"]

use_graph = selected_info["use_graph"]
use_flat = selected_info["use_flat"]

final_model = final_model.to(device)

final_model.eval()


# ================================================================
# [7] PREPARE TEST DATA
# ================================================================

test_flat = X_test_flat_t.to(device)
test_graph = X_test_graph_t.to(device)
test_labels = y_test

if use_graph:
    print("\nFinal model input: GRAPH")

else:
    print("\nFinal model input: FLAT FEATURES")


# ================================================================
# [8] FINAL TEST INFERENCE
# ================================================================

print("\n" + "=" * 80)
print("[3] FINAL TEST EVALUATION")
print("=" * 80)

# Warm-up
with torch.no_grad():

    if use_graph and use_flat:

        _ = final_model(
            test_graph,
            test_flat,
            A_tensor
        )

    elif use_graph:

        _ = final_model(
            test_graph,
            A_tensor
        )

    else:

        _ = final_model(
            test_flat
        )


# Actual inference
if torch.cuda.is_available():
    torch.cuda.synchronize()

start_time = time.perf_counter()

with torch.no_grad():

    if use_graph and use_flat:

        logits = final_model(
            test_graph,
            test_flat,
            A_tensor
        )

    elif use_graph:

        logits = final_model(
            test_graph,
            A_tensor
        )

    else:

        logits = final_model(
            test_flat
        )

if torch.cuda.is_available():
    torch.cuda.synchronize()

inference_time = (
    time.perf_counter()
    - start_time
)


# ================================================================
# [9] PROBABILITIES + PREDICTIONS
# ================================================================

probabilities = torch.softmax(
    logits,
    dim=1
)

predictions = torch.argmax(
    probabilities,
    dim=1
).cpu().numpy()

confidence = torch.max(
    probabilities,
    dim=1
).values.cpu().numpy()


# ================================================================
# [10] FINAL METRICS
# ================================================================

test_accuracy = accuracy_score(
    test_labels,
    predictions
)

test_balanced_accuracy = balanced_accuracy_score(
    test_labels,
    predictions
)

test_precision = precision_score(
    test_labels,
    predictions,
    average="macro",
    zero_division=0
)

test_recall = recall_score(
    test_labels,
    predictions,
    average="macro",
    zero_division=0
)

test_macro_f1 = f1_score(
    test_labels,
    predictions,
    average="macro",
    zero_division=0
)

test_weighted_f1 = f1_score(
    test_labels,
    predictions,
    average="weighted",
    zero_division=0
)

test_mcc = matthews_corrcoef(
    test_labels,
    predictions
)

test_kappa = cohen_kappa_score(
    test_labels,
    predictions
)


# ================================================================
# [11] CONFIDENCE STATISTICS
# ================================================================

mean_confidence = np.mean(
    confidence
)

std_confidence = np.std(
    confidence
)

median_confidence = np.median(
    confidence
)

min_confidence = np.min(
    confidence
)

max_confidence = np.max(
    confidence
)


# ================================================================
# [12] PRINT FINAL TEST RESULTS
# ================================================================

print("\n" + "=" * 80)
print("[4] FINAL TEST PERFORMANCE")
print("=" * 80)

print(
    f"Model                  : {best_model_name}"
)

print(
    f"Test Accuracy          : "
    f"{test_accuracy * 100:.2f}%"
)

print(
    f"Balanced Accuracy      : "
    f"{test_balanced_accuracy * 100:.2f}%"
)

print(
    f"Macro Precision        : "
    f"{test_precision * 100:.2f}%"
)

print(
    f"Macro Recall           : "
    f"{test_recall * 100:.2f}%"
)

print(
    f"Macro-F1               : "
    f"{test_macro_f1 * 100:.2f}%"
)

print(
    f"Weighted-F1            : "
    f"{test_weighted_f1 * 100:.2f}%"
)

print(
    f"MCC                    : "
    f"{test_mcc:.4f}"
)

print(
    f"Cohen's Kappa         : "
    f"{test_kappa:.4f}"
)

print(
    f"Inference Time         : "
    f"{inference_time:.6f} sec"
)

print(
    f"Mean Confidence        : "
    f"{mean_confidence * 100:.2f}%"
)

print(
    f"Median Confidence      : "
    f"{median_confidence * 100:.2f}%"
)

print(
    f"Confidence Std         : "
    f"{std_confidence * 100:.2f}%"
)

print(
    f"Minimum Confidence     : "
    f"{min_confidence * 100:.2f}%"
)

print(
    f"Maximum Confidence     : "
    f"{max_confidence * 100:.2f}%"
)


# ================================================================
# [13] VALIDATION → TEST GENERALIZATION GAP
# ================================================================

print("\n" + "=" * 80)
print("[5] GENERALIZATION GAP")
print("=" * 80)

accuracy_gap = (
    best_validation_acc
    - test_accuracy
) * 100

f1_gap = (
    best_validation_f1
    - test_macro_f1
) * 100

print(
    f"Validation Accuracy : "
    f"{best_validation_acc * 100:.2f}%"
)

print(
    f"Test Accuracy       : "
    f"{test_accuracy * 100:.2f}%"
)

print(
    f"Accuracy Gap        : "
    f"{accuracy_gap:.2f} percentage points"
)

print()

print(
    f"Validation Macro-F1 : "
    f"{best_validation_f1 * 100:.2f}%"
)

print(
    f"Test Macro-F1       : "
    f"{test_macro_f1 * 100:.2f}%"
)

print(
    f"Macro-F1 Gap        : "
    f"{f1_gap:.2f} percentage points"
)


# ================================================================
# [14] PER-CLASS PERFORMANCE
# ================================================================

class_names = [
    id_to_label[i]
    for i in range(NUM_CLASSES)
]

print("\n" + "=" * 80)
print("[6] PER-CLASS TEST PERFORMANCE")
print("=" * 80)

report_dict = classification_report(
    test_labels,
    predictions,
    target_names=class_names,
    output_dict=True,
    zero_division=0
)

per_class_rows = []

for class_name in class_names:

    per_class_rows.append({

        "Class": class_name,

        "Precision":
            report_dict[class_name]["precision"],

        "Recall":
            report_dict[class_name]["recall"],

        "F1":
            report_dict[class_name]["f1-score"],

        "Support":
            int(report_dict[class_name]["support"])
    })


per_class_df = pd.DataFrame(
    per_class_rows
)

display_per_class = per_class_df.copy()

display_per_class[
    ["Precision", "Recall", "F1"]
] *= 100

display_per_class[
    ["Precision", "Recall", "F1"]
] = display_per_class[
    ["Precision", "Recall", "F1"]
].round(2)

print(
    display_per_class.to_string(
        index=False
    )
)


# ================================================================
# [15] CLASSIFICATION REPORT
# ================================================================

print("\n" + "=" * 80)
print("[7] COMPLETE CLASSIFICATION REPORT")
print("=" * 80)

print(
    classification_report(
        test_labels,
        predictions,
        target_names=class_names,
        digits=4,
        zero_division=0
    )
)


# ================================================================
# [16] CONFUSION MATRIX
# ================================================================

cm = confusion_matrix(
    test_labels,
    predictions
)

print("\n" + "=" * 80)
print("[8] CONFUSION MATRIX")
print("=" * 80)

print(cm)


# ================================================================
# [17] NORMALIZED CONFUSION MATRIX
# ================================================================

cm_normalized = (
    cm.astype(np.float64)
    /
    cm.sum(
        axis=1,
        keepdims=True
    )
)

cm_normalized = np.nan_to_num(
    cm_normalized
)

plt.figure(
    figsize=(12, 10)
)

sns.heatmap(
    cm_normalized,
    annot=True,
    fmt=".2f",
    cmap="Blues",
    xticklabels=class_names,
    yticklabels=class_names
)

plt.title(
    f"Step 13.4 — {best_model_name}\n"
    "Normalized Test Confusion Matrix"
)

plt.xlabel(
    "Predicted Class"
)

plt.ylabel(
    "True Class"
)

plt.xticks(
    rotation=45,
    ha="right"
)

plt.yticks(
    rotation=0
)

plt.tight_layout()

plt.show()


# ================================================================
# [18] RAW CONFUSION MATRIX
# ================================================================

plt.figure(
    figsize=(12, 10)
)

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=class_names,
    yticklabels=class_names
)

plt.title(
    f"Step 13.4 — {best_model_name}\n"
    "Test Confusion Matrix"
)

plt.xlabel(
    "Predicted Class"
)

plt.ylabel(
    "True Class"
)

plt.xticks(
    rotation=45,
    ha="right"
)

plt.yticks(
    rotation=0
)

plt.tight_layout()

plt.show()


# ================================================================
# [19] CONFIDENCE DISTRIBUTION
# ================================================================

plt.figure(
    figsize=(10, 6)
)

plt.hist(
    confidence,
    bins=20,
    edgecolor="black"
)

plt.axvline(
    mean_confidence,
    linestyle="--",
    linewidth=2,
    label=(
        f"Mean = "
        f"{mean_confidence:.3f}"
    )
)

plt.title(
    f"{best_model_name} — Test Prediction Confidence"
)

plt.xlabel(
    "Prediction Confidence"
)

plt.ylabel(
    "Number of Samples"
)

plt.legend()

plt.grid(
    alpha=0.3
)

plt.tight_layout()

plt.show()


# ================================================================
# [20] VALIDATION VS TEST COMPARISON
# ================================================================

comparison_df = pd.DataFrame({

    "Metric": [
        "Accuracy",
        "Macro Precision",
        "Macro Recall",
        "Macro-F1",
        "Balanced Accuracy"
    ],

    "Validation": [

        best_validation_acc * 100,

        results_df.loc[
            results_df["Model"] == best_model_name,
            "Validation Precision"
        ].iloc[0] * 100,

        results_df.loc[
            results_df["Model"] == best_model_name,
            "Validation Recall"
        ].iloc[0] * 100,

        best_validation_f1 * 100,

        np.nan
    ],

    "Test": [

        test_accuracy * 100,

        test_precision * 100,

        test_recall * 100,

        test_macro_f1 * 100,

        test_balanced_accuracy * 100
    ]
})

print("\n" + "=" * 80)
print("[9] VALIDATION VS TEST")
print("=" * 80)

print(
    comparison_df.round(2).to_string(
        index=False
    )
)


# ================================================================
# [21] PARAMETER COMPLEXITY
# ================================================================

total_parameters = sum(
    p.numel()
    for p in final_model.parameters()
)

trainable_parameters = sum(
    p.numel()
    for p in final_model.parameters()
    if p.requires_grad
)

non_trainable_parameters = (
    total_parameters
    - trainable_parameters
)

parameter_size_mb = (
    total_parameters * 4
) / (
    1024 ** 2
)


print("\n" + "=" * 80)
print("[10] MODEL COMPLEXITY")
print("=" * 80)

print(
    f"Total Parameters       : "
    f"{total_parameters:,}"
)

print(
    f"Trainable Parameters   : "
    f"{trainable_parameters:,}"
)

print(
    f"Non-trainable Params   : "
    f"{non_trainable_parameters:,}"
)

print(
    f"Approx. FP32 Size      : "
    f"{parameter_size_mb:.3f} MB"
)


# ================================================================
# [22] FINAL RESULT TABLE
# ================================================================

final_results = pd.DataFrame([{

    "Model":
        best_model_name,

    "Validation Accuracy (%)":
        best_validation_acc * 100,

    "Validation Macro-F1 (%)":
        best_validation_f1 * 100,

    "Test Accuracy (%)":
        test_accuracy * 100,

    "Test Balanced Accuracy (%)":
        test_balanced_accuracy * 100,

    "Test Precision (%)":
        test_precision * 100,

    "Test Recall (%)":
        test_recall * 100,

    "Test Macro-F1 (%)":
        test_macro_f1 * 100,

    "Test Weighted-F1 (%)":
        test_weighted_f1 * 100,

    "MCC":
        test_mcc,

    "Cohen Kappa":
        test_kappa,

    "Mean Confidence (%)":
        mean_confidence * 100,

    "Inference Time (sec)":
        inference_time,

    "Total Parameters":
        total_parameters,

    "Trainable Parameters":
        trainable_parameters,

    "Model Size (MB)":
        parameter_size_mb
}])


print("\n" + "=" * 80)
print("[11] FINAL STEP 13.4 RESULT")
print("=" * 80)

print(
    final_results.round(4).to_string(
        index=False
    )
)


# ================================================================
# [23] SAVE FINAL MODEL
# ================================================================

FINAL_MODEL_PATH = (
    "/kaggle/working/"
    "step13_4_final_model.pth"
)

torch.save(
    {
        "model_name":
            best_model_name,

        "model_state_dict":
            final_model.state_dict(),

        "class_names":
            class_names,

        "num_classes":
            NUM_CLASSES,

        "num_nodes":
            globals().get(
                "NUM_NODES",
                None
            ),

        "features_per_node":
            globals().get(
                "FEATURES_PER_NODE",
                None
            ),

        "validation_macro_f1":
            best_validation_f1,

        "test_accuracy":
            test_accuracy,

        "test_macro_f1":
            test_macro_f1,

        "seed":
            SEED
    },
    FINAL_MODEL_PATH
)

print("\n✓ Final model saved:")
print(FINAL_MODEL_PATH)


# ================================================================
# [24] SAVE RESULTS
# ================================================================

FINAL_RESULTS_PATH = (
    "/kaggle/working/"
    "step13_4_final_results.csv"
)

PER_CLASS_PATH = (
    "/kaggle/working/"
    "step13_4_per_class_results.csv"
)

COMPARISON_PATH = (
    "/kaggle/working/"
    "step13_4_validation_test_comparison.csv"
)

final_results.to_csv(
    FINAL_RESULTS_PATH,
    index=False
)

per_class_df.to_csv(
    PER_CLASS_PATH,
    index=False
)

comparison_df.to_csv(
    COMPARISON_PATH,
    index=False
)

print("\n✓ Results saved:")
print(FINAL_RESULTS_PATH)
print(PER_CLASS_PATH)
print(COMPARISON_PATH)


# ================================================================
# [25] FINAL SCIENTIFIC INTERPRETATION
# ================================================================

print("\n" + "=" * 80)
print("[12] FINAL INTERPRETATION")
print("=" * 80)

if f1_gap >= 20:

    print(
        "⚠ Large validation-to-test Macro-F1 gap detected."
    )

    print(
        "This indicates limited cross-domain generalization."
    )

elif f1_gap >= 10:

    print(
        "⚠ Moderate validation-to-test Macro-F1 gap detected."
    )

else:

    print(
        "✓ Validation-to-test Macro-F1 gap is relatively small."
    )


if test_macro_f1 > best_validation_f1:

    print(
        "✓ Test Macro-F1 exceeds validation Macro-F1."
    )

else:

    print(
        "✓ Final test performance was evaluated "
        "without using the test set for model selection."
    )


print(
    "\nIMPORTANT:"
)

print(
    "The final model was selected using Validation Macro-F1."
)

print(
    "The Test set was reserved for final unbiased evaluation."
)

print(
    "Do NOT report Test Macro-F1 as the model-selection criterion."
)


# ================================================================
# [26] FINAL ASSERTIONS
# ================================================================

print("\n" + "=" * 80)
print("STEP 13.4 ASSERTIONS")
print("=" * 80)

assert len(test_labels) == 360
assert len(predictions) == 360
assert cm.shape == (
    NUM_CLASSES,
    NUM_CLASSES
)

assert not np.isnan(
    predictions
).any()

assert not np.isnan(
    confidence
).any()

assert 0 <= test_accuracy <= 1
assert 0 <= test_macro_f1 <= 1

print("✓ 360 test samples evaluated")
print("✓ 12-class confusion matrix verified")
print("✓ Predictions verified")
print("✓ Confidence values verified")
print("✓ Final model selected by Validation Macro-F1")
print("✓ Test set NOT used for model selection")
print("✓ Step 13.4 complete")

print("\n" + "=" * 80)
print("STEP 13.4 FINISHED")
print("=" * 80)

In [ ]:
# ============================================================
# STEP 13.5 — FINAL CONFUSION MATRIX & CLASS-WISE ANALYSIS
# ============================================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.metrics import (
    confusion_matrix,
    classification_report,
    accuracy_score,
    balanced_accuracy_score,
    f1_score,
    precision_score,
    recall_score
)

print("=" * 80)
print("STEP 13.5 — FINAL CONFUSION MATRIX & CLASS-WISE ANALYSIS")
print("=" * 80)


# ============================================================
# [1] CHECK REQUIRED VARIABLES
# ============================================================

print("\n[1] CHECKING REQUIRED VARIABLES")
print("=" * 80)

required_vars = ["y_test"]

missing = [v for v in required_vars if v not in globals()]

if missing:
    raise NameError(
        f"Missing required variables: {missing}. "
        "Please run Step 13.4 first."
    )

print("✓ y_test found")


# ============================================================
# [2] OBTAIN FINAL TEST PREDICTIONS
# ============================================================

print("\n[2] OBTAINING FINAL TEST PREDICTIONS")
print("=" * 80)

# ------------------------------------------------------------
# Try to reuse predictions already created in Step 13.4
# ------------------------------------------------------------

prediction_candidates = [
    "y_test_pred",
    "test_preds",
    "test_predictions",
    "predictions",
    "y_pred"
]

y_pred = None

for var in prediction_candidates:
    if var in globals():
        candidate = globals()[var]

        try:
            candidate = np.asarray(candidate).reshape(-1)

            if len(candidate) == len(y_test):
                y_pred = candidate
                print(f"✓ Using predictions from: {var}")
                break

        except Exception:
            pass


# ------------------------------------------------------------
# If predictions do not already exist, generate them
# ------------------------------------------------------------

if y_pred is None:

    print("Existing predictions not found.")
    print("Attempting to generate predictions from the final model...")

    model_candidates = [
        "best_model",
        "final_model",
        "model",
        "best_mlp",
        "mlp_model"
    ]

    final_model = None

    for var in model_candidates:
        if var in globals():
            candidate = globals()[var]

            # Check whether this looks like a PyTorch model
            if hasattr(candidate, "eval") and hasattr(candidate, "parameters"):
                final_model = candidate
                print(f"✓ Using model variable: {var}")
                break

    if final_model is None:
        raise NameError(
            "Could not find test predictions or the final Flat MLP model. "
            "Please run Step 13.4 again."
        )

    # --------------------------------------------------------
    # Find test feature variable
    # --------------------------------------------------------

    X_test_candidates = [
        "X_test",
        "Xte",
        "X_test_np",
        "test_X"
    ]

    X_test_current = None

    for var in X_test_candidates:
        if var in globals():
            X_test_current = globals()[var]
            print(f"✓ Using test features: {var}")
            break

    if X_test_current is None:
        raise NameError(
            "X_test was not found. Please run Step 13.4 again."
        )

    # --------------------------------------------------------
    # Generate predictions
    # --------------------------------------------------------

    import torch

    final_model.eval()

    if not torch.is_tensor(X_test_current):
        X_test_tensor = torch.tensor(
            X_test_current,
            dtype=torch.float32
        )
    else:
        X_test_tensor = X_test_current.float()

    # Determine device
    try:
        device_current = next(final_model.parameters()).device
    except Exception:
        device_current = torch.device(
            "cuda" if torch.cuda.is_available() else "cpu"
        )

    X_test_tensor = X_test_tensor.to(device_current)

    with torch.no_grad():
        output = final_model(X_test_tensor)

        # Handle tuple/list outputs
        if isinstance(output, (tuple, list)):
            output = output[0]

        y_pred = torch.argmax(output, dim=1).cpu().numpy()

    print("✓ Test predictions generated")


y_test_array = np.asarray(y_test).reshape(-1)
y_pred = np.asarray(y_pred).reshape(-1)

print(f"Test samples      : {len(y_test_array)}")
print(f"Predictions       : {len(y_pred)}")

if len(y_test_array) != len(y_pred):
    raise ValueError(
        f"Prediction length mismatch: "
        f"y_test={len(y_test_array)}, predictions={len(y_pred)}"
    )

print("✓ Prediction length verified")


# ============================================================
# [3] IDENTIFY CLASS LABELS
# ============================================================

print("\n[3] CLASS INFORMATION")
print("=" * 80)

classes = np.unique(
    np.concatenate([
        y_test_array,
        y_pred
    ])
)

print(f"Number of classes: {len(classes)}")
print(f"Class IDs: {classes.tolist()}")


# Try to find original class names
class_name_candidates = [
    "class_names",
    "classes",
    "class_labels",
    "target_names"
]

class_names = None

for var in class_name_candidates:

    if var in globals():

        candidate = globals()[var]

        try:
            candidate = list(candidate)

            if len(candidate) == len(classes):
                class_names = [
                    str(x) for x in candidate
                ]
                print(f"✓ Class names found from: {var}")
                break

        except Exception:
            pass


# If no names exist, use class IDs
if class_names is None:
    class_names = [
        str(int(c)) if float(c).is_integer() else str(c)
        for c in classes
    ]

    print("ℹ Class names not found; using class IDs.")


print("\nClasses:")
for cid, cname in zip(classes, class_names):
    print(f"  {cid} → {cname}")


# ============================================================
# [4] CONFUSION MATRIX
# ============================================================

print("\n[4] CONFUSION MATRIX")
print("=" * 80)

cm = confusion_matrix(
    y_test_array,
    y_pred,
    labels=classes
)

print(cm)


# ============================================================
# [5] PLOT RAW CONFUSION MATRIX
# ============================================================

plt.figure(figsize=(11, 9))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=class_names,
    yticklabels=class_names,
    cbar=True
)

plt.title(
    "Step 13.5 — Final Test Confusion Matrix",
    fontsize=16,
    fontweight="bold"
)

plt.xlabel("Predicted Class", fontsize=13)
plt.ylabel("True Class", fontsize=13)

plt.xticks(rotation=45, ha="right")
plt.yticks(rotation=0)

plt.tight_layout()
plt.show()


# ============================================================
# [6] NORMALIZED CONFUSION MATRIX
# ============================================================

print("\n[6] NORMALIZED CONFUSION MATRIX")
print("=" * 80)

# Normalize each row so values represent recall percentages
cm_normalized = cm.astype(float) / np.maximum(
    cm.sum(axis=1, keepdims=True),
    1
)

cm_percentage = cm_normalized * 100

plt.figure(figsize=(11, 9))

sns.heatmap(
    cm_percentage,
    annot=True,
    fmt=".1f",
    cmap="YlGnBu",
    xticklabels=class_names,
    yticklabels=class_names,
    vmin=0,
    vmax=100,
    cbar_kws={"label": "Percentage (%)"}
)

plt.title(
    "Step 13.5 — Normalized Test Confusion Matrix",
    fontsize=16,
    fontweight="bold"
)

plt.xlabel("Predicted Class", fontsize=13)
plt.ylabel("True Class", fontsize=13)

plt.xticks(rotation=45, ha="right")
plt.yticks(rotation=0)

plt.tight_layout()
plt.show()


# ============================================================
# [7] CLASS-WISE METRICS
# ============================================================

print("\n[7] CLASS-WISE TEST PERFORMANCE")
print("=" * 80)

report_dict = classification_report(
    y_test_array,
    y_pred,
    labels=classes,
    target_names=class_names,
    output_dict=True,
    zero_division=0
)

class_rows = []

for cid, cname in zip(classes, class_names):

    row = report_dict[cname]

    class_rows.append({
        "Class ID": cid,
        "Class": cname,
        "Precision (%)": row["precision"] * 100,
        "Recall (%)": row["recall"] * 100,
        "F1 (%)": row["f1-score"] * 100,
        "Support": int(row["support"])
    })

class_metrics_df = pd.DataFrame(class_rows)

print(
    class_metrics_df.to_string(
        index=False,
        float_format=lambda x: f"{x:.2f}"
    )
)


# ============================================================
# [8] CLASS-WISE F1 SCORE PLOT
# ============================================================

plt.figure(figsize=(12, 6))

bars = plt.bar(
    class_metrics_df["Class"].astype(str),
    class_metrics_df["F1 (%)"]
)

plt.axhline(
    class_metrics_df["F1 (%)"].mean(),
    linestyle="--",
    linewidth=2,
    label=f"Macro-F1 = {class_metrics_df['F1 (%)'].mean():.2f}%"
)

plt.title(
    "Step 13.5 — Class-wise Test F1 Score",
    fontsize=16,
    fontweight="bold"
)

plt.xlabel("Class", fontsize=13)
plt.ylabel("F1 Score (%)", fontsize=13)

plt.ylim(0, 100)

plt.xticks(rotation=45, ha="right")

plt.legend()

plt.tight_layout()
plt.show()


# ============================================================
# [9] CLASS-WISE RECALL / SENSITIVITY
# ============================================================

plt.figure(figsize=(12, 6))

plt.bar(
    class_metrics_df["Class"].astype(str),
    class_metrics_df["Recall (%)"]
)

plt.axhline(
    class_metrics_df["Recall (%)"].mean(),
    linestyle="--",
    linewidth=2,
    label=f"Macro Recall = {class_metrics_df['Recall (%)'].mean():.2f}%"
)

plt.title(
    "Step 13.5 — Class-wise Recall / Sensitivity",
    fontsize=16,
    fontweight="bold"
)

plt.xlabel("Class", fontsize=13)
plt.ylabel("Recall / Sensitivity (%)", fontsize=13)

plt.ylim(0, 100)

plt.xticks(rotation=45, ha="right")

plt.legend()

plt.tight_layout()
plt.show()


# ============================================================
# [10] MOST CONFUSED CLASS PAIRS
# ============================================================

print("\n[10] MOST CONFUSED CLASS PAIRS")
print("=" * 80)

confusion_pairs = []

for i in range(len(classes)):

    for j in range(len(classes)):

        if i != j and cm[i, j] > 0:

            confusion_pairs.append({
                "True Class": class_names[i],
                "Predicted Class": class_names[j],
                "Misclassified Samples": int(cm[i, j])
            })

confusion_pairs_df = pd.DataFrame(confusion_pairs)

if len(confusion_pairs_df) > 0:

    confusion_pairs_df = confusion_pairs_df.sort_values(
        "Misclassified Samples",
        ascending=False
    )

    print(
        confusion_pairs_df.head(15).to_string(
            index=False
        )
    )

else:

    print("No misclassification pairs found.")


# ============================================================
# [11] CORRECT VS INCORRECT PREDICTIONS
# ============================================================

correct = np.sum(y_test_array == y_pred)
incorrect = np.sum(y_test_array != y_pred)

print("\n[11] PREDICTION SUMMARY")
print("=" * 80)

print(f"Correct predictions   : {correct}")
print(f"Incorrect predictions : {incorrect}")
print(f"Total test samples    : {len(y_test_array)}")

print(
    f"Correct percentage    : "
    f"{correct / len(y_test_array) * 100:.2f}%"
)

print(
    f"Incorrect percentage  : "
    f"{incorrect / len(y_test_array) * 100:.2f}%"
)


# ============================================================
# [12] FINAL METRICS
# ============================================================

accuracy = accuracy_score(
    y_test_array,
    y_pred
)

balanced_acc = balanced_accuracy_score(
    y_test_array,
    y_pred
)

macro_precision = precision_score(
    y_test_array,
    y_pred,
    average="macro",
    zero_division=0
)

macro_recall = recall_score(
    y_test_array,
    y_pred,
    average="macro",
    zero_division=0
)

macro_f1 = f1_score(
    y_test_array,
    y_pred,
    average="macro",
    zero_division=0
)

weighted_f1 = f1_score(
    y_test_array,
    y_pred,
    average="weighted",
    zero_division=0
)

print("\n[12] FINAL TEST METRICS")
print("=" * 80)

print(f"Accuracy          : {accuracy * 100:.2f}%")
print(f"Balanced Accuracy : {balanced_acc * 100:.2f}%")
print(f"Macro Precision   : {macro_precision * 100:.2f}%")
print(f"Macro Recall      : {macro_recall * 100:.2f}%")
print(f"Macro F1          : {macro_f1 * 100:.2f}%")
print(f"Weighted F1       : {weighted_f1 * 100:.2f}%")


# ============================================================
# [13] SAVE CLASS-WISE RESULTS
# ============================================================

class_metrics_df.to_csv(
    "/kaggle/working/step_13_5_class_metrics.csv",
    index=False
)

pd.DataFrame(
    cm,
    index=class_names,
    columns=class_names
).to_csv(
    "/kaggle/working/step_13_5_confusion_matrix.csv"
)

print("\n✓ Class metrics saved:")
print("  /kaggle/working/step_13_5_class_metrics.csv")

print("✓ Confusion matrix saved:")
print("  /kaggle/working/step_13_5_confusion_matrix.csv")


# ============================================================
# [14] FINAL STEP 13.5 SUMMARY
# ============================================================

print("\n")
print("=" * 80)
print("STEP 13.5 FINAL SUMMARY")
print("=" * 80)

print(f"Test Accuracy          : {accuracy * 100:.2f}%")
print(f"Balanced Accuracy      : {balanced_acc * 100:.2f}%")
print(f"Macro Precision        : {macro_precision * 100:.2f}%")
print(f"Macro Recall           : {macro_recall * 100:.2f}%")
print(f"Macro F1               : {macro_f1 * 100:.2f}%")
print(f"Weighted F1            : {weighted_f1 * 100:.2f}%")
print(f"Correct Predictions    : {correct}/{len(y_test_array)}")
print(f"Incorrect Predictions  : {incorrect}/{len(y_test_array)}")

print("\n✓ STEP 13.5 COMPLETED")
print("=" * 80)

In [ ]:
# ============================================================
# STEP 13.5A — VERIFY STEP 13.4 vs STEP 13.5 PREDICTIONS
# ============================================================

import numpy as np

print("=" * 80)
print("STEP 13.5A — PREDICTION CONSISTENCY CHECK")
print("=" * 80)

# ------------------------------------------------------------
# Check all prediction variables currently in memory
# ------------------------------------------------------------

prediction_vars = [
    "y_test_pred",
    "test_preds",
    "test_predictions",
    "predictions",
    "y_pred"
]

found = []

for name in prediction_vars:

    if name in globals():

        try:
            arr = np.asarray(globals()[name]).reshape(-1)

            if len(arr) == len(y_test):

                acc = np.mean(
                    arr == np.asarray(y_test).reshape(-1)
                ) * 100

                found.append((name, arr, acc))

                print(
                    f"{name:<20} "
                    f"Samples = {len(arr):<5} "
                    f"Accuracy = {acc:.2f}%"
                )

        except Exception as e:
            print(f"{name}: could not evaluate ({e})")


# ------------------------------------------------------------
# Compare predictions pairwise
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("PAIRWISE PREDICTION COMPARISON")
print("=" * 80)

for i in range(len(found)):

    for j in range(i + 1, len(found)):

        name1, pred1, acc1 = found[i]
        name2, pred2, acc2 = found[j]

        same = np.mean(pred1 == pred2) * 100

        print(
            f"{name1} vs {name2}: "
            f"{same:.2f}% identical predictions"
        )


# ------------------------------------------------------------
# Explicitly print the current Step 13.5 prediction accuracy
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("CURRENT STEP 13.5 RESULT")
print("=" * 80)

print(
    f"Current y_pred accuracy: "
    f"{np.mean(y_pred == np.asarray(y_test).reshape(-1)) * 100:.2f}%"
)

print("\nIMPORTANT:")
print("Step 13.4 reported Test Accuracy = 47.22%")
print("Step 13.5 reported Test Accuracy = 58.89%")
print("These must be reconciled before selecting the final result.")

In [ ]:
# ============================================================
# STEP 13.5B — FINAL FLAT MLP PREDICTION VERIFICATION
# ============================================================

import numpy as np
import torch
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

print("=" * 80)
print("STEP 13.5B — FINAL FLAT MLP PREDICTION VERIFICATION")
print("=" * 80)


# ============================================================
# [1] CHECK AVAILABLE MODEL VARIABLES
# ============================================================

print("\n[1] SEARCHING FOR FINAL FLAT MLP MODEL")
print("=" * 80)

model_candidates = [
    "best_model",
    "final_model",
    "model",
    "best_mlp",
    "mlp_model"
]

available_models = []

for name in model_candidates:

    if name in globals():

        obj = globals()[name]

        if hasattr(obj, "eval") and hasattr(obj, "parameters"):

            available_models.append(name)

            try:
                params = sum(
                    p.numel()
                    for p in obj.parameters()
                )
            except:
                params = "Unknown"

            print(
                f"✓ {name:<20} "
                f"Parameters: {params}"
            )


if len(available_models) == 0:

    raise NameError(
        "No PyTorch model was found in memory. "
        "Please run the Step 13.4 model-selection/training cell first."
    )


# ============================================================
# [2] CHECK MODEL PARAMETER COUNT
# ============================================================

print("\n[2] MODEL IDENTIFICATION")
print("=" * 80)

for name in available_models:

    obj = globals()[name]

    try:

        total_params = sum(
            p.numel()
            for p in obj.parameters()
        )

        trainable_params = sum(
            p.numel()
            for p in obj.parameters()
            if p.requires_grad
        )

        print(f"\nModel variable : {name}")
        print(f"Total params   : {total_params:,}")
        print(f"Trainable      : {trainable_params:,}")

    except Exception as e:

        print(f"{name}: {e}")


# ============================================================
# [3] USE THE 34,828-PARAMETER MODEL
# ============================================================

print("\n[3] SELECTING FLAT MLP")
print("=" * 80)

final_model = None
final_model_name = None

for name in available_models:

    obj = globals()[name]

    try:

        total_params = sum(
            p.numel()
            for p in obj.parameters()
        )

        # Your Step 13.4 Flat MLP has exactly 34,828 parameters
        if total_params == 34828:

            final_model = obj
            final_model_name = name
            break

    except:
        pass


if final_model is None:

    print(
        "⚠ Could not automatically identify the "
        "34,828-parameter model."
    )

    print(
        "\nAvailable model variables:",
        available_models
    )

    raise ValueError(
        "Please check which model variable corresponds "
        "to the final Flat MLP."
    )


print(
    f"✓ Final Flat MLP identified as: "
    f"{final_model_name}"
)

print("✓ Parameter count: 34,828")


# ============================================================
# [4] FIND TEST FEATURES
# ============================================================

print("\n[4] FINDING TEST FEATURES")
print("=" * 80)

X_test_candidates = [
    "X_test",
    "Xte",
    "X_test_np",
    "test_X"
]

X_test_current = None
X_test_name = None

for name in X_test_candidates:

    if name in globals():

        candidate = globals()[name]

        try:

            shape = np.asarray(candidate).shape

            if len(shape) == 2 and shape[0] == len(y_test):

                X_test_current = candidate
                X_test_name = name
                break

        except:
            pass


if X_test_current is None:

    raise NameError(
        "Could not find X_test with 360 samples. "
        "Please run the Step 13.4 data preparation cell."
    )


print(f"✓ Test features found: {X_test_name}")
print(f"✓ Test shape: {np.asarray(X_test_current).shape}")


# ============================================================
# [5] GENERATE FRESH FLAT MLP PREDICTIONS
# ============================================================

print("\n[5] GENERATING FRESH FLAT MLP PREDICTIONS")
print("=" * 80)

final_model.eval()

try:
    device_final = next(
        final_model.parameters()
    ).device
except:
    device_final = torch.device(
        "cuda" if torch.cuda.is_available()
        else "cpu"
    )

print(f"Device: {device_final}")


# Convert test features to tensor
if torch.is_tensor(X_test_current):

    X_test_tensor = X_test_current.float()

else:

    X_test_tensor = torch.tensor(
        np.asarray(X_test_current),
        dtype=torch.float32
    )


X_test_tensor = X_test_tensor.to(device_final)


# Generate predictions WITHOUT using any previous prediction array
with torch.no_grad():

    output = final_model(
        X_test_tensor
    )

    # Handle tuple/list model outputs
    if isinstance(output, (tuple, list)):

        output = output[0]

    fresh_flat_mlp_pred = (
        torch.argmax(
            output,
            dim=1
        )
        .cpu()
        .numpy()
    )


y_test_clean = np.asarray(
    y_test
).reshape(-1)


# ============================================================
# [6] CALCULATE FRESH PERFORMANCE
# ============================================================

fresh_accuracy = accuracy_score(
    y_test_clean,
    fresh_flat_mlp_pred
)

fresh_balanced_accuracy = balanced_accuracy_score(
    y_test_clean,
    fresh_flat_mlp_pred
)

fresh_precision = precision_score(
    y_test_clean,
    fresh_flat_mlp_pred,
    average="macro",
    zero_division=0
)

fresh_recall = recall_score(
    y_test_clean,
    fresh_flat_mlp_pred,
    average="macro",
    zero_division=0
)

fresh_macro_f1 = f1_score(
    y_test_clean,
    fresh_flat_mlp_pred,
    average="macro",
    zero_division=0
)

fresh_weighted_f1 = f1_score(
    y_test_clean,
    fresh_flat_mlp_pred,
    average="weighted",
    zero_division=0
)


# ============================================================
# [7] COMPARE WITH STEP 13.4
# ============================================================

print("\n[6] FRESH FLAT MLP TEST PERFORMANCE")
print("=" * 80)

print(
    f"Test Accuracy          : "
    f"{fresh_accuracy * 100:.2f}%"
)

print(
    f"Balanced Accuracy      : "
    f"{fresh_balanced_accuracy * 100:.2f}%"
)

print(
    f"Macro Precision        : "
    f"{fresh_precision * 100:.2f}%"
)

print(
    f"Macro Recall           : "
    f"{fresh_recall * 100:.2f}%"
)

print(
    f"Macro F1               : "
    f"{fresh_macro_f1 * 100:.2f}%"
)

print(
    f"Weighted F1            : "
    f"{fresh_weighted_f1 * 100:.2f}%"
)


# ============================================================
# [8] COMPARE WITH THE ORIGINAL STEP 13.4 PREDICTIONS
# ============================================================

print("\n[7] COMPARISON WITH STEP 13.4 PREDICTIONS")
print("=" * 80)

if "predictions" in globals():

    old_predictions = np.asarray(
        predictions
    ).reshape(-1)

    if len(old_predictions) == len(
        fresh_flat_mlp_pred
    ):

        agreement = np.mean(
            old_predictions ==
            fresh_flat_mlp_pred
        ) * 100

        old_accuracy = accuracy_score(
            y_test_clean,
            old_predictions
        )

        print(
            f"Step 13.4 predictions accuracy : "
            f"{old_accuracy * 100:.2f}%"
        )

        print(
            f"Fresh Flat MLP accuracy        : "
            f"{fresh_accuracy * 100:.2f}%"
        )

        print(
            f"Prediction agreement           : "
            f"{agreement:.2f}%"
        )

    else:

        print(
            "⚠ Prediction arrays have different lengths."
        )

else:

    print(
        "No previous 'predictions' variable found."
    )


# ============================================================
# [9] CONFUSION MATRIX
# ============================================================

print("\n[8] FINAL FLAT MLP CONFUSION MATRIX")
print("=" * 80)

classes_final = np.unique(
    np.concatenate([
        y_test_clean,
        fresh_flat_mlp_pred
    ])
)

cm_final = confusion_matrix(
    y_test_clean,
    fresh_flat_mlp_pred,
    labels=classes_final
)

print(cm_final)


# ============================================================
# [10] CLASSIFICATION REPORT
# ============================================================

print("\n[9] FINAL FLAT MLP CLASSIFICATION REPORT")
print("=" * 80)

print(
    classification_report(
        y_test_clean,
        fresh_flat_mlp_pred,
        labels=classes_final,
        zero_division=0
    )
)


# ============================================================
# [11] FINAL DECISION
# ============================================================

print("\n" + "=" * 80)
print("STEP 13.5B FINAL DECISION")
print("=" * 80)

if abs(
    fresh_accuracy * 100 - 47.2222
) < 0.1:

    print(
        "✓ VERIFIED"
    )

    print(
        "The final Flat MLP Test Accuracy is "
        "47.22%."
    )

    print(
        "The 58.89% result came from a different "
        "prediction/model variable."
    )

elif abs(
    fresh_accuracy * 100 - 58.8889
) < 0.1:

    print(
        "⚠ IMPORTANT"
    )

    print(
        "The currently loaded 34,828-parameter model "
        "produces 58.89%."
    )

    print(
        "This means the model in memory differs from "
        "the model used for the original Step 13.4 result."
    )

else:

    print(
        f"Fresh Flat MLP accuracy = "
        f"{fresh_accuracy * 100:.2f}%"
    )

    print(
        "This differs from both 47.22% and 58.89%."
    )

    print(
        "Do NOT finalize the result until the model "
        "checkpoint/selection is verified."
    )

print("=" * 80)

In [ ]:
# ============================================================
# STEP 13.6 — FINAL MODEL VISUALIZATION & DIAGNOSTIC FIGURES
# ============================================================
# Purpose:
#   1. Verify final Flat MLP predictions
#   2. Plot confusion matrix
#   3. Plot per-class Precision / Recall / F1
#   4. Plot Validation vs Test performance
#   5. Plot prediction confidence distribution
#   6. Plot domain/generalization gap
#
# IMPORTANT:
#   - Uses best_model = FINAL Flat MLP
#   - Uses Xte / yte for final test evaluation
#   - Does NOT retrain the model
#   - Does NOT use the 58.89% prediction variable
# ============================================================

import numpy as np
import pandas as pd
import torch
import matplotlib.pyplot as plt

from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

# ------------------------------------------------------------
# [1] CONFIGURATION
# ------------------------------------------------------------

SEED = 42
np.random.seed(SEED)
torch.manual_seed(SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("=" * 80)
print("STEP 13.6 — FINAL MODEL VISUALIZATION & DIAGNOSTIC FIGURES")
print("=" * 80)

print(f"Device : {device}")


# ------------------------------------------------------------
# [2] CHECK REQUIRED VARIABLES
# ------------------------------------------------------------

required = ["best_model", "Xte", "yte"]

missing = [v for v in required if v not in globals()]

if missing:
    raise NameError(
        f"Missing required variables: {missing}. "
        "Please run the previous steps first."
    )

print("\n[1] REQUIRED VARIABLES")
print("=" * 80)
print("✓ best_model found")
print("✓ Xte found")
print("✓ yte found")


# ------------------------------------------------------------
# [3] PREPARE FINAL MODEL
# ------------------------------------------------------------

best_model = best_model.to(device)
best_model.eval()

print("\n[2] FINAL MODEL")
print("=" * 80)

total_params = sum(p.numel() for p in best_model.parameters())

print(f"Model              : Flat MLP")
print(f"Total Parameters    : {total_params:,}")
print(f"Test samples       : {len(yte)}")
print(f"Test features      : {Xte.shape[1]}")


# ------------------------------------------------------------
# [4] GENERATE FRESH FINAL PREDICTIONS
# ------------------------------------------------------------

# Convert data safely to tensors
if isinstance(Xte, torch.Tensor):
    Xte_tensor = Xte.float().to(device)
else:
    Xte_tensor = torch.tensor(
        np.asarray(Xte),
        dtype=torch.float32,
        device=device
    )

yte_np = np.asarray(yte).astype(int)

with torch.no_grad():

    logits = best_model(Xte_tensor)

    probabilities = torch.softmax(logits, dim=1)

    final_pred = torch.argmax(
        probabilities,
        dim=1
    ).cpu().numpy()

    final_confidence = (
        probabilities.max(dim=1)[0]
        .cpu()
        .numpy()
    )

print("\n[3] FINAL PREDICTIONS")
print("=" * 80)

print(f"Samples             : {len(final_pred)}")
print(
    f"Final Test Accuracy : "
    f"{accuracy_score(yte_np, final_pred) * 100:.2f}%"
)


# ------------------------------------------------------------
# [5] FINAL METRICS
# ------------------------------------------------------------

final_accuracy = accuracy_score(
    yte_np,
    final_pred
)

final_balanced_accuracy = balanced_accuracy_score(
    yte_np,
    final_pred
)

final_precision = precision_score(
    yte_np,
    final_pred,
    average="macro",
    zero_division=0
)

final_recall = recall_score(
    yte_np,
    final_pred,
    average="macro",
    zero_division=0
)

final_f1 = f1_score(
    yte_np,
    final_pred,
    average="macro",
    zero_division=0
)

final_weighted_f1 = f1_score(
    yte_np,
    final_pred,
    average="weighted",
    zero_division=0
)

print("\n[4] FINAL VERIFIED TEST METRICS")
print("=" * 80)

print(f"Accuracy           : {final_accuracy * 100:.2f}%")
print(f"Balanced Accuracy  : {final_balanced_accuracy * 100:.2f}%")
print(f"Macro Precision    : {final_precision * 100:.2f}%")
print(f"Macro Recall       : {final_recall * 100:.2f}%")
print(f"Macro F1           : {final_f1 * 100:.2f}%")
print(f"Weighted F1        : {final_weighted_f1 * 100:.2f}%")
print(f"Mean Confidence    : {final_confidence.mean() * 100:.2f}%")
print(f"Median Confidence  : {np.median(final_confidence) * 100:.2f}%")


# ============================================================
# [6] CONFUSION MATRIX
# ============================================================

cm = confusion_matrix(
    yte_np,
    final_pred
)

print("\n[5] CONFUSION MATRIX")
print("=" * 80)
print(cm)


plt.figure(figsize=(10, 8))

plt.imshow(cm, interpolation="nearest")

plt.title(
    "Final Flat MLP — Test Confusion Matrix",
    fontsize=16,
    fontweight="bold"
)

plt.xlabel("Predicted Class", fontsize=12)
plt.ylabel("True Class", fontsize=12)

plt.xticks(
    np.arange(cm.shape[1]),
    np.arange(cm.shape[1])
)

plt.yticks(
    np.arange(cm.shape[0]),
    np.arange(cm.shape[0])
)

# Add numbers inside cells
threshold = cm.max() / 2.0

for i in range(cm.shape[0]):
    for j in range(cm.shape[1]):

        plt.text(
            j,
            i,
            str(cm[i, j]),
            ha="center",
            va="center",
            fontsize=10,
            fontweight="bold",
            color="white" if cm[i, j] > threshold else "black"
        )

plt.colorbar()

plt.tight_layout()
plt.show()


# ============================================================
# [7] NORMALIZED CONFUSION MATRIX
# ============================================================

cm_normalized = cm.astype(float) / cm.sum(
    axis=1,
    keepdims=True
)

cm_normalized = np.nan_to_num(cm_normalized)

plt.figure(figsize=(10, 8))

plt.imshow(
    cm_normalized,
    interpolation="nearest",
    vmin=0,
    vmax=1
)

plt.title(
    "Final Flat MLP — Normalized Test Confusion Matrix",
    fontsize=16,
    fontweight="bold"
)

plt.xlabel("Predicted Class", fontsize=12)
plt.ylabel("True Class", fontsize=12)

plt.xticks(
    np.arange(cm.shape[1]),
    np.arange(cm.shape[1])
)

plt.yticks(
    np.arange(cm.shape[0]),
    np.arange(cm.shape[0])
)

for i in range(cm_normalized.shape[0]):
    for j in range(cm_normalized.shape[1]):

        plt.text(
            j,
            i,
            f"{cm_normalized[i, j] * 100:.1f}%",
            ha="center",
            va="center",
            fontsize=9,
            fontweight="bold"
        )

plt.colorbar(label="Proportion")

plt.tight_layout()
plt.show()


# ============================================================
# [8] PER-CLASS PERFORMANCE
# ============================================================

report_dict = classification_report(
    yte_np,
    final_pred,
    output_dict=True,
    zero_division=0
)

class_ids = sorted(
    [
        int(k)
        for k in report_dict.keys()
        if k.isdigit()
    ]
)

precision_values = [
    report_dict[str(c)]["precision"] * 100
    for c in class_ids
]

recall_values = [
    report_dict[str(c)]["recall"] * 100
    for c in class_ids
]

f1_values = [
    report_dict[str(c)]["f1-score"] * 100
    for c in class_ids
]

performance_df = pd.DataFrame({
    "Class": class_ids,
    "Precision (%)": precision_values,
    "Recall (%)": recall_values,
    "F1 (%)": f1_values
})

print("\n[6] PER-CLASS PERFORMANCE")
print("=" * 80)
print(performance_df.to_string(index=False))


# ------------------------------------------------------------
# Per-class bar chart
# ------------------------------------------------------------

x = np.arange(len(class_ids))
width = 0.25

plt.figure(figsize=(13, 7))

plt.bar(
    x - width,
    precision_values,
    width,
    label="Precision"
)

plt.bar(
    x,
    recall_values,
    width,
    label="Recall"
)

plt.bar(
    x + width,
    f1_values,
    width,
    label="F1"
)

plt.xlabel("Class", fontsize=12)
plt.ylabel("Score (%)", fontsize=12)

plt.title(
    "Final Flat MLP — Per-Class Test Performance",
    fontsize=16,
    fontweight="bold"
)

plt.xticks(x, class_ids)
plt.ylim(0, 110)

plt.legend()

plt.grid(
    axis="y",
    alpha=0.25
)

plt.tight_layout()
plt.show()


# ============================================================
# [9] VALIDATION VS TEST PERFORMANCE
# ============================================================

# Values verified from Step 13.4 / 13.5B
validation_accuracy = 74.7222
validation_f1 = 74.0415

test_accuracy = final_accuracy * 100
test_f1 = final_f1 * 100

metrics = [
    "Accuracy",
    "Macro-F1"
]

validation_values = [
    validation_accuracy,
    validation_f1
]

test_values = [
    test_accuracy,
    test_f1
]

x = np.arange(len(metrics))
width = 0.35

plt.figure(figsize=(9, 6))

plt.bar(
    x - width / 2,
    validation_values,
    width,
    label="Validation"
)

plt.bar(
    x + width / 2,
    test_values,
    width,
    label="Test"
)

for i, value in enumerate(validation_values):
    plt.text(
        i - width / 2,
        value + 1,
        f"{value:.2f}%",
        ha="center",
        fontweight="bold"
    )

for i, value in enumerate(test_values):
    plt.text(
        i + width / 2,
        value + 1,
        f"{value:.2f}%",
        ha="center",
        fontweight="bold"
    )

plt.xticks(x, metrics)

plt.ylabel("Performance (%)")

plt.title(
    "Validation vs Test Performance — Final Flat MLP",
    fontsize=15,
    fontweight="bold"
)

plt.ylim(0, 100)

plt.legend()

plt.grid(
    axis="y",
    alpha=0.25
)

plt.tight_layout()
plt.show()


# ============================================================
# [10] GENERALIZATION GAP
# ============================================================

accuracy_gap = validation_accuracy - test_accuracy
f1_gap = validation_f1 - test_f1

gap_names = [
    "Accuracy Gap",
    "Macro-F1 Gap"
]

gap_values = [
    accuracy_gap,
    f1_gap
]

plt.figure(figsize=(8, 6))

bars = plt.bar(
    gap_names,
    gap_values
)

for bar, value in zip(bars, gap_values):

    plt.text(
        bar.get_x() + bar.get_width() / 2,
        value + 0.5,
        f"{value:.2f} pp",
        ha="center",
        fontweight="bold"
    )

plt.ylabel("Percentage Points")

plt.title(
    "Final Flat MLP — Generalization Gap",
    fontsize=15,
    fontweight="bold"
)

plt.ylim(0, max(gap_values) + 10)

plt.grid(
    axis="y",
    alpha=0.25
)

plt.tight_layout()
plt.show()


# ============================================================
# [11] CONFIDENCE DISTRIBUTION
# ============================================================

plt.figure(figsize=(9, 6))

plt.hist(
    final_confidence * 100,
    bins=20,
    edgecolor="black"
)

plt.axvline(
    final_confidence.mean() * 100,
    linestyle="--",
    linewidth=2,
    label=f"Mean = {final_confidence.mean()*100:.2f}%"
)

plt.xlabel("Prediction Confidence (%)")

plt.ylabel("Number of Samples")

plt.title(
    "Final Flat MLP — Test Prediction Confidence",
    fontsize=15,
    fontweight="bold"
)

plt.legend()

plt.grid(
    axis="y",
    alpha=0.25
)

plt.tight_layout()
plt.show()


# ============================================================
# [12] MOST CONFUSED CLASS PAIRS
# ============================================================

cm_no_diag = cm.copy()

np.fill_diagonal(
    cm_no_diag,
    0
)

pairs = []

for i in range(cm_no_diag.shape[0]):

    for j in range(cm_no_diag.shape[1]):

        if cm_no_diag[i, j] > 0:

            pairs.append(
                (
                    i,
                    j,
                    cm_no_diag[i, j]
                )
            )

pairs = sorted(
    pairs,
    key=lambda x: x[2],
    reverse=True
)

confusion_df = pd.DataFrame(
    pairs[:15],
    columns=[
        "True Class",
        "Predicted Class",
        "Misclassified Samples"
    ]
)

print("\n[7] TOP 15 MOST CONFUSED CLASS PAIRS")
print("=" * 80)

print(
    confusion_df.to_string(index=False)
)


# ============================================================
# [13] FINAL VISUALIZATION SUMMARY
# ============================================================

print("\n")
print("=" * 80)
print("STEP 13.6 FINAL SUMMARY")
print("=" * 80)

print(f"Final Model              : Flat MLP")
print(f"Validation Accuracy      : {validation_accuracy:.2f}%")
print(f"Validation Macro-F1      : {validation_f1:.2f}%")
print(f"Final Test Accuracy      : {test_accuracy:.2f}%")
print(f"Final Test Macro-F1      : {test_f1:.2f}%")
print(f"Accuracy Generalization Gap : {accuracy_gap:.2f} pp")
print(f"Macro-F1 Generalization Gap : {f1_gap:.2f} pp")
print(f"Mean Test Confidence     : {final_confidence.mean()*100:.2f}%")

print("\n✓ Final Flat MLP predictions regenerated")
print("✓ Confusion matrix generated")
print("✓ Normalized confusion matrix generated")
print("✓ Per-class performance generated")
print("✓ Validation vs Test comparison generated")
print("✓ Generalization gap generated")
print("✓ Confidence distribution generated")
print("✓ Most-confused class pairs generated")

print("\nIMPORTANT:")
print("Use 47.22% as the official final Flat MLP Test Accuracy.")
print("Do NOT use the earlier 58.89% result.")
print("=" * 80)

In [ ]:
# ============================================================
# STEP 13.7 — FINAL RESEARCH RESULTS & STATISTICAL SUMMARY
# ============================================================
#
# Purpose:
#   1. Create final model comparison table
#   2. Create final Flat MLP performance table
#   3. Create baseline comparison table
#   4. Summarize domain-shift findings
#   5. Summarize mitigation results
#   6. Calculate generalization gaps
#   7. Export all results to CSV/Excel
#   8. Generate final comparison figures
#
# IMPORTANT:
#   Official Flat MLP Test Accuracy = 47.22%
#   Official Flat MLP Test Macro-F1  = 40.70%
#   DO NOT use the previous 58.89% result.
# ============================================================

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    matthews_corrcoef,
    cohen_kappa_score
)

print("=" * 80)
print("STEP 13.7 — FINAL RESEARCH RESULTS & STATISTICAL SUMMARY")
print("=" * 80)


# ============================================================
# [1] FINAL VERIFIED FLAT MLP VALUES
# ============================================================

FINAL_MODEL = "Flat MLP"

VAL_ACCURACY = 74.7222
VAL_MACRO_F1 = 74.0415

TEST_ACCURACY = 47.2222
TEST_BALANCED_ACCURACY = 47.2222
TEST_PRECISION = 53.3948
TEST_RECALL = 47.2222
TEST_MACRO_F1 = 40.6977
TEST_WEIGHTED_F1 = 40.6977

MCC = 0.4403
COHEN_KAPPA = 0.4242

MEAN_CONFIDENCE = 58.5054
INFERENCE_TIME = 0.000662

TOTAL_PARAMETERS = 34828
TRAINABLE_PARAMETERS = 34828
MODEL_SIZE_MB = 0.1329


# ============================================================
# [2] GENERALIZATION GAP
# ============================================================

ACCURACY_GAP = VAL_ACCURACY - TEST_ACCURACY
MACRO_F1_GAP = VAL_MACRO_F1 - TEST_MACRO_F1

print("\n[1] FINAL GENERALIZATION RESULTS")
print("=" * 80)

print(f"Validation Accuracy : {VAL_ACCURACY:.2f}%")
print(f"Test Accuracy       : {TEST_ACCURACY:.2f}%")
print(f"Accuracy Gap        : {ACCURACY_GAP:.2f} percentage points")

print()

print(f"Validation Macro-F1 : {VAL_MACRO_F1:.2f}%")
print(f"Test Macro-F1       : {TEST_MACRO_F1:.2f}%")
print(f"Macro-F1 Gap        : {MACRO_F1_GAP:.2f} percentage points")


# ============================================================
# [3] FINAL FLAT MLP PERFORMANCE TABLE
# ============================================================

final_performance_df = pd.DataFrame({

    "Model": [FINAL_MODEL],

    "Validation Accuracy (%)": [
        VAL_ACCURACY
    ],

    "Validation Macro-F1 (%)": [
        VAL_MACRO_F1
    ],

    "Test Accuracy (%)": [
        TEST_ACCURACY
    ],

    "Test Balanced Accuracy (%)": [
        TEST_BALANCED_ACCURACY
    ],

    "Test Precision (%)": [
        TEST_PRECISION
    ],

    "Test Recall (%)": [
        TEST_RECALL
    ],

    "Test Macro-F1 (%)": [
        TEST_MACRO_F1
    ],

    "Test Weighted-F1 (%)": [
        TEST_WEIGHTED_F1
    ],

    "MCC": [
        MCC
    ],

    "Cohen Kappa": [
        COHEN_KAPPA
    ],

    "Mean Confidence (%)": [
        MEAN_CONFIDENCE
    ],

    "Inference Time (sec)": [
        INFERENCE_TIME
    ],

    "Total Parameters": [
        TOTAL_PARAMETERS
    ],

    "Trainable Parameters": [
        TRAINABLE_PARAMETERS
    ],

    "Model Size (MB)": [
        MODEL_SIZE_MB
    ]
})


print("\n[2] FINAL FLAT MLP PERFORMANCE")
print("=" * 80)

print(
    final_performance_df.to_string(index=False)
)


# ============================================================
# [4] COMPLETE MODEL COMPARISON
# ============================================================
#
# Values are taken from your previous verified steps.
# Selection is based on Validation Macro-F1.
# Test results are reported only for final comparison.
# ============================================================

model_comparison_df = pd.DataFrame({

    "Model": [
        "Flat MLP",
        "GAT + Fusion",
        "GAT",
        "GraphSAGE",
        "GCN"
    ],

    "Validation Accuracy (%)": [
        74.7222,
        71.1111,
        21.9444,
        20.0000,
        8.3333
    ],

    "Validation Macro-F1 (%)": [
        74.0415,
        70.4541,
        17.5526,
        14.3190,
        1.2821
    ],

    "Test Accuracy (%)": [
        47.2222,
        51.3889,
        17.5000,
        12.7778,
        8.3333
    ],

    "Test Macro-F1 (%)": [
        40.6977,
        44.8834,
        10.4757,
        9.8807,
        1.2821
    ]
})


# Rank using validation Macro-F1
model_comparison_df = model_comparison_df.sort_values(
    "Validation Macro-F1 (%)",
    ascending=False
).reset_index(drop=True)

model_comparison_df.insert(
    0,
    "Rank",
    np.arange(1, len(model_comparison_df) + 1)
)


print("\n[3] COMPLETE MODEL COMPARISON")
print("=" * 80)

print(
    model_comparison_df.to_string(index=False)
)


# ============================================================
# [5] ADD XGBOOST BASELINE
# ============================================================

xgb_accuracy = 58.89
xgb_macro_f1 = 55.79

xgb_comparison_df = pd.DataFrame({

    "Model": [
        "XGBoost",
        "Flat MLP",
        "GAT + Fusion",
        "GAT",
        "GraphSAGE",
        "GCN"
    ],

    "Test Accuracy (%)": [
        xgb_accuracy,
        47.2222,
        51.3889,
        17.5000,
        12.7778,
        8.3333
    ],

    "Test Macro-F1 (%)": [
        xgb_macro_f1,
        40.6977,
        44.8834,
        10.4757,
        9.8807,
        1.2821
    ]
})


print("\n[4] BASELINE COMPARISON — XGBOOST")
print("=" * 80)

print(
    xgb_comparison_df.to_string(index=False)
)


# ============================================================
# [6] XGBOOST VS FINAL FLAT MLP
# ============================================================

accuracy_difference = TEST_ACCURACY - xgb_accuracy
f1_difference = TEST_MACRO_F1 - xgb_macro_f1

print("\n[5] XGBOOST VS FINAL FLAT MLP")
print("=" * 80)

print(
    f"XGBoost Test Accuracy : "
    f"{xgb_accuracy:.2f}%"
)

print(
    f"Flat MLP Test Accuracy : "
    f"{TEST_ACCURACY:.2f}%"
)

print(
    f"Accuracy Difference : "
    f"{accuracy_difference:+.2f} percentage points"
)

print()

print(
    f"XGBoost Macro-F1 : "
    f"{xgb_macro_f1:.2f}%"
)

print(
    f"Flat MLP Macro-F1 : "
    f"{TEST_MACRO_F1:.2f}%"
)

print(
    f"Macro-F1 Difference : "
    f"{f1_difference:+.2f} percentage points"
)


# ============================================================
# [7] DOMAIN SHIFT SUMMARY
# ============================================================

domain_shift_df = pd.DataFrame({

    "Diagnostic": [

        "Train → Validation Domain Accuracy",
        "Train → Test Domain Accuracy",
        "Significant KS Features Train → Validation",
        "Significant KS Features Train → Test",
        "Validation NN Accuracy",
        "Test NN Accuracy",
        "Validation / Train NN Ratio",
        "Test / Train NN Ratio"
    ],

    "Result": [

        "98.95%",
        "98.89%",
        "119 / 128",
        "123 / 128",
        "48.06%",
        "44.44%",
        "1.801",
        "1.887"
    ],

    "Interpretation": [

        "Strong domain separation",
        "Strong domain separation",
        "92.97% of features shifted",
        "96.09% of features shifted",
        "Low nearest-neighbor class consistency",
        "Low nearest-neighbor class consistency",
        "Validation is farther from train",
        "Test is farther from train"
    ]
})


print("\n[6] DOMAIN SHIFT SUMMARY")
print("=" * 80)

print(
    domain_shift_df.to_string(index=False)
)


# ============================================================
# [8] DISTRIBUTION SHIFT METRICS
# ============================================================

distribution_shift_df = pd.DataFrame({

    "Metric": [

        "KS shifted features Train → Validation",
        "KS shifted features Train → Test",
        "Mean Wasserstein Train → Validation",
        "Mean Wasserstein Train → Test",
        "Max Wasserstein Train → Validation",
        "Max Wasserstein Train → Test",
        "Domain classifier Train/Val/Test accuracy"
    ],

    "Value": [

        "119 / 128 (92.97%)",
        "123 / 128 (96.09%)",
        0.34335,
        0.27360,
        1.12027,
        1.01715,
        "98.39%"
    ]
})


print("\n[7] DISTRIBUTION SHIFT METRICS")
print("=" * 80)

print(
    distribution_shift_df.to_string(index=False)
)


# ============================================================
# [9] MITIGATION RESULTS
# ============================================================

mitigation_df = pd.DataFrame({

    "Strategy": [

        "Original Features",
        "Feature Removal",
        "50% Domain Downweight",
        "25% Domain Downweight"
    ],

    "Features": [
        128,
        115,
        128,
        128
    ],

    "Validation Accuracy (%)": [
        74.72,
        72.22,
        73.89,
        72.78
    ],

    "Validation Macro-F1 (%)": [
        74.04,
        71.52,
        72.60,
        71.47
    ],

    "Best Epoch": [
        "-",
        27,
        41,
        38
    ],

    "Selected": [
        "YES",
        "NO",
        "NO",
        "NO"
    ]
})


print("\n[8] DOMAIN-SHIFT MITIGATION")
print("=" * 80)

print(
    mitigation_df.to_string(index=False)
)


# ============================================================
# [10] CLASS-WISE FINAL PERFORMANCE
# ============================================================

# From verified Step 13.5B
class_performance_df = pd.DataFrame({

    "Class": list(range(12)),

    "Precision (%)": [
        39.13,
        0.00,
        40.00,
        80.00,
        100.00,
        37.50,
        63.16,
        85.71,
        59.18,
        34.85,
        65.91,
        35.29
    ],

    "Recall (%)": [
        30.00,
        0.00,
        6.67,
        26.67,
        13.33,
        60.00,
        40.00,
        20.00,
        96.67,
        76.67,
        96.67,
        100.00
    ],

    "F1 (%)": [
        33.96,
        0.00,
        11.43,
        40.00,
        23.53,
        46.15,
        48.98,
        32.43,
        73.42,
        47.92,
        78.38,
        52.17
    ],

    "Support": [
        30, 30, 30, 30, 30, 30,
        30, 30, 30, 30, 30, 30
    ]
})


print("\n[9] FINAL CLASS-WISE PERFORMANCE")
print("=" * 80)

print(
    class_performance_df.to_string(index=False)
)


# ============================================================
# [11] MOST CONFUSED CLASS PAIRS
# ============================================================

confused_pairs_df = pd.DataFrame({

    "True Class": [
        7, 4, 1, 0, 2,
        6, 1, 3, 2, 3,
        0, 2, 5, 6, 4
    ],

    "Predicted Class": [
        8, 11, 9, 5, 11,
        0, 11, 9, 9, 5,
        6, 10, 10, 9, 5
    ],

    "Misclassified Samples": [
        19, 17, 15, 14, 13,
        13, 11, 10, 9, 9,
        7, 6, 6, 5, 4
    ]
})


print("\n[10] MOST CONFUSED CLASS PAIRS")
print("=" * 80)

print(
    confused_pairs_df.to_string(index=False)
)


# ============================================================
# [12] FINAL RESEARCH SCORECARD
# ============================================================

research_scorecard = pd.DataFrame({

    "Research Component": [

        "Best model",
        "Validation Accuracy",
        "Validation Macro-F1",
        "Test Accuracy",
        "Test Macro-F1",
        "Accuracy Generalization Gap",
        "Macro-F1 Generalization Gap",
        "Mean Test Confidence",
        "Train-Test Domain Accuracy",
        "Train-Val Domain Accuracy",
        "Train-Test Shifted Features",
        "Train-Val Shifted Features",
        "Test NN Accuracy",
        "Validation NN Accuracy",
        "Best Mitigation Strategy",
        "XGBoost Test Accuracy",
        "XGBoost Test Macro-F1"
    ],

    "Final Result": [

        "Flat MLP",
        "74.72%",
        "74.04%",
        "47.22%",
        "40.70%",
        "27.50 pp",
        "33.34 pp",
        "58.51%",
        "98.89%",
        "98.95%",
        "123 / 128 (96.09%)",
        "119 / 128 (92.97%)",
        "44.44%",
        "48.06%",
        "Original Features",
        "58.89%",
        "55.79%"
    ]
})


print("\n[11] FINAL RESEARCH SCORECARD")
print("=" * 80)

print(
    research_scorecard.to_string(index=False)
)


# ============================================================
# [13] FINAL MODEL COMPARISON FIGURE
# ============================================================

plot_df = xgb_comparison_df.sort_values(
    "Test Accuracy (%)",
    ascending=True
)

plt.figure(figsize=(10, 7))

bars = plt.barh(
    plot_df["Model"],
    plot_df["Test Accuracy (%)"]
)

for bar, value in zip(
    bars,
    plot_df["Test Accuracy (%)"]
):

    plt.text(
        value + 1,
        bar.get_y() + bar.get_height() / 2,
        f"{value:.2f}%",
        va="center",
        fontweight="bold"
    )

plt.xlabel("Test Accuracy (%)")

plt.ylabel("Model")

plt.title(
    "Final Test Accuracy Comparison",
    fontsize=16,
    fontweight="bold"
)

plt.xlim(
    0,
    max(plot_df["Test Accuracy (%)"]) + 15
)

plt.grid(
    axis="x",
    alpha=0.25
)

plt.tight_layout()
plt.show()


# ============================================================
# [14] FINAL MACRO-F1 COMPARISON FIGURE
# ============================================================

plot_f1 = xgb_comparison_df.sort_values(
    "Test Macro-F1 (%)",
    ascending=True
)

plt.figure(figsize=(10, 7))

bars = plt.barh(
    plot_f1["Model"],
    plot_f1["Test Macro-F1 (%)"]
)

for bar, value in zip(
    bars,
    plot_f1["Test Macro-F1 (%)"]
):

    plt.text(
        value + 1,
        bar.get_y() + bar.get_height() / 2,
        f"{value:.2f}%",
        va="center",
        fontweight="bold"
    )

plt.xlabel("Test Macro-F1 (%)")

plt.ylabel("Model")

plt.title(
    "Final Test Macro-F1 Comparison",
    fontsize=16,
    fontweight="bold"
)

plt.xlim(
    0,
    max(plot_f1["Test Macro-F1 (%)"]) + 15
)

plt.grid(
    axis="x",
    alpha=0.25
)

plt.tight_layout()
plt.show()


# ============================================================
# [15] VALIDATION-TEST GENERALIZATION FIGURE
# ============================================================

generalization_df = pd.DataFrame({

    "Metric": [
        "Accuracy",
        "Macro-F1"
    ],

    "Validation": [
        VAL_ACCURACY,
        VAL_MACRO_F1
    ],

    "Test": [
        TEST_ACCURACY,
        TEST_MACRO_F1
    ]
})

x = np.arange(len(generalization_df))
width = 0.35

plt.figure(figsize=(9, 6))

plt.bar(
    x - width / 2,
    generalization_df["Validation"],
    width,
    label="Validation"
)

plt.bar(
    x + width / 2,
    generalization_df["Test"],
    width,
    label="Test"
)

for i in range(len(x)):

    plt.text(
        i - width / 2,
        generalization_df["Validation"][i] + 1,
        f"{generalization_df['Validation'][i]:.2f}%",
        ha="center",
        fontsize=10,
        fontweight="bold"
    )

    plt.text(
        i + width / 2,
        generalization_df["Test"][i] + 1,
        f"{generalization_df['Test'][i]:.2f}%",
        ha="center",
        fontsize=10,
        fontweight="bold"
    )

plt.xticks(
    x,
    generalization_df["Metric"]
)

plt.ylabel("Score (%)")

plt.title(
    "Final Model Generalization: Validation vs Test",
    fontsize=15,
    fontweight="bold"
)

plt.ylim(0, 100)

plt.legend()

plt.grid(
    axis="y",
    alpha=0.25
)

plt.tight_layout()
plt.show()


# ============================================================
# [16] EXPORT RESULTS
# ============================================================

OUTPUT_DIR = "/kaggle/working/step_13_7_results"

os.makedirs(
    OUTPUT_DIR,
    exist_ok=True
)


# CSV files
final_performance_df.to_csv(
    f"{OUTPUT_DIR}/final_flat_mlp_performance.csv",
    index=False
)

model_comparison_df.to_csv(
    f"{OUTPUT_DIR}/model_comparison.csv",
    index=False
)

xgb_comparison_df.to_csv(
    f"{OUTPUT_DIR}/xgboost_baseline_comparison.csv",
    index=False
)

domain_shift_df.to_csv(
    f"{OUTPUT_DIR}/domain_shift_summary.csv",
    index=False
)

distribution_shift_df.to_csv(
    f"{OUTPUT_DIR}/distribution_shift_metrics.csv",
    index=False
)

mitigation_df.to_csv(
    f"{OUTPUT_DIR}/mitigation_results.csv",
    index=False
)

class_performance_df.to_csv(
    f"{OUTPUT_DIR}/class_wise_performance.csv",
    index=False
)

confused_pairs_df.to_csv(
    f"{OUTPUT_DIR}/most_confused_class_pairs.csv",
    index=False
)

research_scorecard.to_csv(
    f"{OUTPUT_DIR}/final_research_scorecard.csv",
    index=False
)


# ============================================================
# [17] EXCEL WORKBOOK
# ============================================================

excel_path = (
    f"{OUTPUT_DIR}/STEP_13_7_FINAL_RESEARCH_RESULTS.xlsx"
)

with pd.ExcelWriter(excel_path) as writer:

    final_performance_df.to_excel(
        writer,
        sheet_name="Final Flat MLP",
        index=False
    )

    model_comparison_df.to_excel(
        writer,
        sheet_name="Model Comparison",
        index=False
    )

    xgb_comparison_df.to_excel(
        writer,
        sheet_name="XGBoost Baseline",
        index=False
    )

    domain_shift_df.to_excel(
        writer,
        sheet_name="Domain Shift",
        index=False
    )

    distribution_shift_df.to_excel(
        writer,
        sheet_name="Distribution Shift",
        index=False
    )

    mitigation_df.to_excel(
        writer,
        sheet_name="Mitigation",
        index=False
    )

    class_performance_df.to_excel(
        writer,
        sheet_name="Class Performance",
        index=False
    )

    confused_pairs_df.to_excel(
        writer,
        sheet_name="Confused Pairs",
        index=False
    )

    research_scorecard.to_excel(
        writer,
        sheet_name="Research Scorecard",
        index=False
    )


# ============================================================
# [18] FINAL SUMMARY
# ============================================================

print("\n")
print("=" * 80)
print("STEP 13.7 FINAL SUMMARY")
print("=" * 80)

print(f"Final Model               : {FINAL_MODEL}")

print(
    f"Validation Accuracy      : "
    f"{VAL_ACCURACY:.2f}%"
)

print(
    f"Validation Macro-F1      : "
    f"{VAL_MACRO_F1:.2f}%"
)

print(
    f"Official Test Accuracy   : "
    f"{TEST_ACCURACY:.2f}%"
)

print(
    f"Official Test Macro-F1   : "
    f"{TEST_MACRO_F1:.2f}%"
)

print(
    f"Accuracy Generalization Gap : "
    f"{ACCURACY_GAP:.2f} pp"
)

print(
    f"Macro-F1 Generalization Gap : "
    f"{MACRO_F1_GAP:.2f} pp"
)

print(
    f"Train-Test Domain Accuracy : "
    f"98.89%"
)

print(
    f"Significant Train-Test Shift : "
    f"123 / 128 features"
)

print(
    f"XGBoost Test Accuracy : "
    f"{xgb_accuracy:.2f}%"
)

print(
    f"XGBoost Test Macro-F1 : "
    f"{xgb_macro_f1:.2f}%"
)

print("\n✓ Final model comparison completed")
print("✓ Domain-shift summary completed")
print("✓ Mitigation summary completed")
print("✓ Class-wise results consolidated")
print("✓ Research scorecard created")
print("✓ CSV files exported")
print("✓ Excel workbook exported")

print("\nOutput directory:")
print(OUTPUT_DIR)

print("\nExcel file:")
print(excel_path)

print("\nIMPORTANT:")
print("Official Flat MLP Test Accuracy = 47.22%")
print("Official Flat MLP Test Macro-F1  = 40.70%")
print("The previous 58.89% result is NOT used.")
print("=" * 80)

In [ ]:
# ============================================================
# STEP 13.8 — FINAL PUBLICATION-QUALITY VISUALIZATION
# ============================================================
# Purpose:
#   1. Final confusion matrix
#   2. Normalized confusion matrix
#   3. Validation vs Test performance
#   4. Generalization gap
#   5. Per-class Precision / Recall / F1
#   6. Test confidence distribution
#   7. Domain-shift summary
#
# IMPORTANT:
#   Official Flat MLP Test Accuracy = 47.22%
#   Official Flat MLP Test Macro-F1  = 40.70%
# ============================================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.metrics import (
    confusion_matrix,
    classification_report,
    accuracy_score,
    f1_score
)

print("=" * 80)
print("STEP 13.8 — FINAL PUBLICATION-QUALITY VISUALIZATION")
print("=" * 80)

# ============================================================
# [1] FIND FINAL VARIABLES
# ============================================================

print("\n[1] CHECKING FINAL VARIABLES")
print("=" * 80)

# ------------------------------------------------------------
# Test labels
# ------------------------------------------------------------

possible_y_test = [
    "y_test",
    "yte",
    "y_test_true",
    "y_true_test",
    "test_labels"
]

y_true = None
y_true_name = None

for name in possible_y_test:
    if name in globals():
        try:
            arr = np.asarray(globals()[name]).reshape(-1)
            if len(arr) == 360:
                y_true = arr.astype(int)
                y_true_name = name
                break
        except:
            pass

if y_true is None:
    raise NameError(
        "Could not find the 360 test labels. "
        "Expected one of: y_test, yte, y_test_true, "
        "y_true_test, test_labels."
    )

print(f"✓ Test labels found: {y_true_name}")
print(f"✓ Test samples: {len(y_true)}")


# ------------------------------------------------------------
# Final Flat MLP predictions
# ------------------------------------------------------------

possible_y_pred = [
    "final_y_pred",
    "flat_mlp_y_pred",
    "y_pred",
    "predictions"
]

y_pred_final = None
y_pred_name = None

for name in possible_y_pred:
    if name in globals():
        try:
            arr = np.asarray(globals()[name]).reshape(-1)
            if len(arr) == 360:
                y_pred_final = arr.astype(int)
                y_pred_name = name
                break
        except:
            pass

if y_pred_final is None:
    raise NameError(
        "Could not find final Flat MLP predictions. "
        "Run Step 13.5B first."
    )

print(f"✓ Predictions found: {y_pred_name}")
print(f"✓ Prediction samples: {len(y_pred_final)}")


# ============================================================
# [2] VERIFY OFFICIAL PERFORMANCE
# ============================================================

print("\n[2] OFFICIAL FINAL PERFORMANCE")
print("=" * 80)

official_test_accuracy = 47.22
official_test_macro_f1 = 40.70
official_val_accuracy = 74.72
official_val_macro_f1 = 74.04

calculated_accuracy = accuracy_score(y_true, y_pred_final) * 100
calculated_macro_f1 = f1_score(
    y_true,
    y_pred_final,
    average="macro",
    zero_division=0
) * 100

print(f"Official Test Accuracy : {official_test_accuracy:.2f}%")
print(f"Calculated Accuracy    : {calculated_accuracy:.2f}%")

print(f"Official Test Macro-F1 : {official_test_macro_f1:.2f}%")
print(f"Calculated Macro-F1    : {calculated_macro_f1:.2f}%")

if abs(calculated_accuracy - official_test_accuracy) < 0.01:
    print("✓ Official accuracy verified")
else:
    print("⚠ WARNING: prediction accuracy differs from official result")


# ============================================================
# [3] CLASS NAMES
# ============================================================

print("\n[3] CLASS INFORMATION")
print("=" * 80)

# ------------------------------------------------------------
# Try to recover class names automatically
# ------------------------------------------------------------

class_names = None

possible_class_vars = [
    "class_names",
    "classes",
    "class_labels",
    "target_names"
]

for name in possible_class_vars:
    if name in globals():
        try:
            candidate = list(globals()[name])
            if len(candidate) == 12:
                class_names = [str(x) for x in candidate]
                print(f"✓ Class names found from: {name}")
                break
        except:
            pass

if class_names is None:
    class_names = [str(i) for i in range(12)]
    print("⚠ Class names not found.")
    print("  Using Class 0–11.")

print("Classes:", class_names)


# ============================================================
# [4] CONFUSION MATRIX
# ============================================================

print("\n[4] CONFUSION MATRIX")
print("=" * 80)

cm = confusion_matrix(
    y_true,
    y_pred_final,
    labels=np.arange(12)
)

print(cm)


# ------------------------------------------------------------
# Plot raw confusion matrix
# ------------------------------------------------------------

plt.figure(figsize=(11, 9))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    cbar=True,
    xticklabels=class_names,
    yticklabels=class_names
)

plt.title(
    "Final Flat MLP — Test Confusion Matrix",
    fontsize=16,
    fontweight="bold"
)

plt.xlabel("Predicted Class", fontsize=13)
plt.ylabel("True Class", fontsize=13)

plt.xticks(rotation=45, ha="right")
plt.yticks(rotation=0)

plt.tight_layout()
plt.show()


# ============================================================
# [5] NORMALIZED CONFUSION MATRIX
# ============================================================

print("\n[5] NORMALIZED CONFUSION MATRIX")
print("=" * 80)

cm_normalized = cm.astype(float) / cm.sum(
    axis=1,
    keepdims=True
)

cm_normalized = np.nan_to_num(cm_normalized)

plt.figure(figsize=(11, 9))

sns.heatmap(
    cm_normalized,
    annot=True,
    fmt=".2f",
    cmap="Greens",
    cbar=True,
    xticklabels=class_names,
    yticklabels=class_names,
    vmin=0,
    vmax=1
)

plt.title(
    "Final Flat MLP — Normalized Test Confusion Matrix",
    fontsize=16,
    fontweight="bold"
)

plt.xlabel("Predicted Class", fontsize=13)
plt.ylabel("True Class", fontsize=13)

plt.xticks(rotation=45, ha="right")
plt.yticks(rotation=0)

plt.tight_layout()
plt.show()


# ============================================================
# [6] PER-CLASS PERFORMANCE
# ============================================================

print("\n[6] PER-CLASS PERFORMANCE")
print("=" * 80)

report_dict = classification_report(
    y_true,
    y_pred_final,
    labels=np.arange(12),
    target_names=class_names,
    output_dict=True,
    zero_division=0
)

per_class_df = pd.DataFrame(report_dict).T

per_class_df = per_class_df.iloc[:12][
    ["precision", "recall", "f1-score", "support"]
].copy()

per_class_df["precision"] *= 100
per_class_df["recall"] *= 100
per_class_df["f1-score"] *= 100

per_class_df.columns = [
    "Precision (%)",
    "Recall (%)",
    "F1 (%)",
    "Support"
]

print(per_class_df.round(2))


# ============================================================
# [7] PER-CLASS METRICS PLOT
# ============================================================

print("\n[7] PER-CLASS METRICS PLOT")
print("=" * 80)

plot_df = per_class_df[
    ["Precision (%)", "Recall (%)", "F1 (%)"]
]

ax = plot_df.plot(
    kind="bar",
    figsize=(14, 7)
)

plt.title(
    "Final Flat MLP — Per-Class Test Performance",
    fontsize=16,
    fontweight="bold"
)

plt.xlabel("Class", fontsize=13)
plt.ylabel("Score (%)", fontsize=13)

plt.xticks(
    range(12),
    class_names,
    rotation=45,
    ha="right"
)

plt.ylim(0, 105)
plt.grid(axis="y", alpha=0.25)

plt.legend(
    title="Metric",
    loc="upper right"
)

plt.tight_layout()
plt.show()


# ============================================================
# [8] VALIDATION VS TEST COMPARISON
# ============================================================

print("\n[8] VALIDATION VS TEST COMPARISON")
print("=" * 80)

comparison_df = pd.DataFrame({
    "Validation": [
        official_val_accuracy,
        official_val_macro_f1
    ],
    "Test": [
        official_test_accuracy,
        official_test_macro_f1
    ]
}, index=[
    "Accuracy",
    "Macro-F1"
])

print(comparison_df)


# ------------------------------------------------------------
# Plot
# ------------------------------------------------------------

ax = comparison_df.plot(
    kind="bar",
    figsize=(9, 6)
)

plt.title(
    "Flat MLP — Validation vs Test Performance",
    fontsize=16,
    fontweight="bold"
)

plt.ylabel("Score (%)", fontsize=13)
plt.xlabel("Metric", fontsize=13)

plt.xticks(rotation=0)
plt.ylim(0, 100)

plt.grid(axis="y", alpha=0.25)

plt.legend(
    title="Dataset"
)

plt.tight_layout()
plt.show()


# ============================================================
# [9] GENERALIZATION GAP
# ============================================================

print("\n[9] GENERALIZATION GAP")
print("=" * 80)

accuracy_gap = official_val_accuracy - official_test_accuracy
macro_f1_gap = official_val_macro_f1 - official_test_macro_f1

gap_df = pd.DataFrame({
    "Gap": [
        accuracy_gap,
        macro_f1_gap
    ]
}, index=[
    "Accuracy Gap",
    "Macro-F1 Gap"
])

print(gap_df.round(2))

ax = gap_df.plot(
    kind="bar",
    figsize=(8, 6),
    legend=False
)

plt.title(
    "Flat MLP — Validation-to-Test Generalization Gap",
    fontsize=16,
    fontweight="bold"
)

plt.ylabel("Gap (percentage points)", fontsize=13)
plt.xticks(rotation=0)

plt.grid(axis="y", alpha=0.25)

plt.tight_layout()
plt.show()


# ============================================================
# [10] DOMAIN SHIFT SUMMARY
# ============================================================

print("\n[10] DOMAIN SHIFT SUMMARY")
print("=" * 80)

domain_summary = pd.DataFrame({
    "Measure": [
        "Train-Test Domain Accuracy",
        "Train-Val Domain Accuracy",
        "Train-Test Shifted Features",
        "Train-Val Shifted Features",
        "Test NN Accuracy",
        "Validation NN Accuracy"
    ],
    "Value": [
        98.89,
        98.95,
        96.09,
        92.97,
        44.44,
        48.06
    ],
    "Unit": [
        "%",
        "%",
        "%",
        "%",
        "%",
        "%"
    ]
})

print(domain_summary.to_string(index=False))


# ============================================================
# [11] DOMAIN SHIFT VISUALIZATION
# ============================================================

print("\n[11] DOMAIN SHIFT VISUALIZATION")
print("=" * 80)

domain_plot = pd.Series({
    "Train-Test\nDomain Accuracy": 98.89,
    "Train-Val\nDomain Accuracy": 98.95,
    "Train-Test\nShifted Features": 96.09,
    "Train-Val\nShifted Features": 92.97,
    "Test NN\nAccuracy": 44.44,
    "Validation NN\nAccuracy": 48.06
})

plt.figure(figsize=(12, 7))

bars = plt.bar(
    domain_plot.index,
    domain_plot.values
)

plt.title(
    "Dataset Domain-Shift Diagnostics",
    fontsize=16,
    fontweight="bold"
)

plt.ylabel("Percentage (%)", fontsize=13)

plt.ylim(0, 110)

plt.grid(
    axis="y",
    alpha=0.25
)

for bar, value in zip(bars, domain_plot.values):
    plt.text(
        bar.get_x() + bar.get_width() / 2,
        value + 2,
        f"{value:.2f}%",
        ha="center",
        fontsize=11
    )

plt.tight_layout()
plt.show()


# ============================================================
# [12] FINAL RESEARCH PERFORMANCE DASHBOARD
# ============================================================

print("\n[12] FINAL RESEARCH PERFORMANCE DASHBOARD")
print("=" * 80)

dashboard_df = pd.DataFrame({
    "Metric": [
        "Validation Accuracy",
        "Validation Macro-F1",
        "Test Accuracy",
        "Test Macro-F1",
        "Accuracy Gap",
        "Macro-F1 Gap",
        "Mean Confidence",
        "Train-Test Domain Accuracy",
        "Train-Val Domain Accuracy",
        "Test NN Accuracy"
    ],
    "Result (%)": [
        74.72,
        74.04,
        47.22,
        40.70,
        27.50,
        33.34,
        58.51,
        98.89,
        98.95,
        44.44
    ]
})

print(
    dashboard_df.to_string(index=False)
)


# ============================================================
# [13] SAVE VISUALIZATION DATA
# ============================================================

print("\n[13] SAVING FINAL TABLES")
print("=" * 80)

per_class_df.to_csv(
    "/kaggle/working/step_13_8_per_class_performance.csv"
)

comparison_df.to_csv(
    "/kaggle/working/step_13_8_validation_test_comparison.csv"
)

gap_df.to_csv(
    "/kaggle/working/step_13_8_generalization_gap.csv"
)

domain_summary.to_csv(
    "/kaggle/working/step_13_8_domain_shift_summary.csv",
    index=False
)

dashboard_df.to_csv(
    "/kaggle/working/step_13_8_final_dashboard.csv",
    index=False
)

print("✓ Per-class performance saved")
print("✓ Validation/Test comparison saved")
print("✓ Generalization gap saved")
print("✓ Domain-shift summary saved")
print("✓ Final dashboard saved")


# ============================================================
# [14] FINAL STEP 13.8 SUMMARY
# ============================================================

print("\n")
print("=" * 80)
print("STEP 13.8 FINAL SUMMARY")
print("=" * 80)

print(f"Final Model              : Flat MLP")
print(f"Validation Accuracy      : {official_val_accuracy:.2f}%")
print(f"Validation Macro-F1      : {official_val_macro_f1:.2f}%")
print(f"Final Test Accuracy      : {official_test_accuracy:.2f}%")
print(f"Final Test Macro-F1      : {official_test_macro_f1:.2f}%")
print(f"Accuracy Generalization Gap : {accuracy_gap:.2f} pp")
print(f"Macro-F1 Generalization Gap : {macro_f1_gap:.2f} pp")

print("\n✓ Raw confusion matrix generated")
print("✓ Normalized confusion matrix generated")
print("✓ Per-class performance generated")
print("✓ Validation vs Test comparison generated")
print("✓ Generalization-gap visualization generated")
print("✓ Domain-shift visualization generated")
print("✓ Final research dashboard generated")
print("✓ All result tables exported")

print("\nIMPORTANT:")
print("Official Flat MLP Test Accuracy = 47.22%")
print("Official Flat MLP Test Macro-F1  = 40.70%")
print("Do NOT replace these with the earlier 58.89% result.")

print("=" * 80)

In [ ]:
# ============================================================
# STEP 13.9 — FINAL RESULTS EXPORT & REPRODUCIBILITY PACKAGE
# ============================================================

import os
import json
import numpy as np
import pandas as pd
import torch
from datetime import datetime

print("=" * 80)
print("STEP 13.9 — FINAL RESULTS EXPORT & REPRODUCIBILITY")
print("=" * 80)

# ------------------------------------------------------------
# [1] OUTPUT DIRECTORY
# ------------------------------------------------------------

OUTPUT_DIR = "/kaggle/working/step_13_final_results"
os.makedirs(OUTPUT_DIR, exist_ok=True)

print(f"\nOutput directory: {OUTPUT_DIR}")

# ------------------------------------------------------------
# [2] FINAL OFFICIAL RESULTS
# ------------------------------------------------------------

final_results = {
    "Final Model": "Flat MLP",

    "Validation Accuracy (%)": 74.72,
    "Validation Macro-F1 (%)": 74.04,

    "Test Accuracy (%)": 47.22,
    "Test Macro-F1 (%)": 40.70,

    "Test Balanced Accuracy (%)": 47.22,
    "Test Macro Precision (%)": 53.39,
    "Test Macro Recall (%)": 47.22,
    "Test Weighted-F1 (%)": 40.70,

    "MCC": 0.4403,
    "Cohen Kappa": 0.4242,

    "Accuracy Generalization Gap (pp)": 27.50,
    "Macro-F1 Generalization Gap (pp)": 33.34,

    "Mean Test Confidence (%)": 58.51,

    "Train-Test Domain Accuracy (%)": 98.89,
    "Train-Validation Domain Accuracy (%)": 98.95,

    "Train-Test Shifted Features": "123 / 128",
    "Train-Test Shift Percentage (%)": 96.09,

    "Train-Validation Shifted Features": "119 / 128",
    "Train-Validation Shift Percentage (%)": 92.97,

    "Test Nearest-Neighbor Accuracy (%)": 44.44,
    "Validation Nearest-Neighbor Accuracy (%)": 48.06,

    "Best Mitigation Strategy": "Original Features",

    "XGBoost Test Accuracy (%)": 58.89,
    "XGBoost Test Macro-F1 (%)": 55.79,

    "Total Parameters": 34828,
    "Trainable Parameters": 34828,
    "Model Size (MB)": 0.1329,

    "Random Seed": 42
}

results_df = pd.DataFrame(
    list(final_results.items()),
    columns=["Research Component", "Final Result"]
)

print("\n[3] FINAL RESEARCH RESULTS")
print("=" * 80)
print(results_df.to_string(index=False))

# ------------------------------------------------------------
# [4] SAVE SCORECARD
# ------------------------------------------------------------

scorecard_path = os.path.join(
    OUTPUT_DIR,
    "final_research_scorecard.csv"
)

results_df.to_csv(scorecard_path, index=False)

print(f"\n✓ Scorecard saved:")
print(scorecard_path)

# ------------------------------------------------------------
# [5] SAVE CONFUSION MATRIX
# ------------------------------------------------------------

cm = None

# Try common variable names
for var_name in [
    "cm",
    "conf_matrix",
    "confusion_mat",
    "confusion_matrix_test"
]:
    if var_name in globals():
        candidate = globals()[var_name]

        if isinstance(candidate, np.ndarray):
            if candidate.ndim == 2:
                cm = candidate
                break

if cm is not None:

    cm_df = pd.DataFrame(cm)

    cm_path = os.path.join(
        OUTPUT_DIR,
        "final_test_confusion_matrix.csv"
    )

    cm_df.to_csv(cm_path, index=False)

    print(f"✓ Confusion matrix saved: {cm_path}")

else:
    print("⚠ Confusion matrix variable not found.")

# ------------------------------------------------------------
# [6] SAVE NORMALIZED CONFUSION MATRIX
# ------------------------------------------------------------

if cm is not None:

    row_sums = cm.sum(axis=1, keepdims=True)

    normalized_cm = np.divide(
        cm,
        row_sums,
        out=np.zeros_like(cm, dtype=float),
        where=row_sums != 0
    )

    norm_cm_df = pd.DataFrame(normalized_cm)

    norm_cm_path = os.path.join(
        OUTPUT_DIR,
        "normalized_confusion_matrix.csv"
    )

    norm_cm_df.to_csv(norm_cm_path, index=False)

    print(f"✓ Normalized confusion matrix saved: {norm_cm_path}")

# ------------------------------------------------------------
# [7] SAVE CLASSIFICATION REPORT IF AVAILABLE
# ------------------------------------------------------------

classification_df = None

for var_name in [
    "classification_report_df",
    "class_report_df",
    "report_df"
]:

    if var_name in globals():

        candidate = globals()[var_name]

        if isinstance(candidate, pd.DataFrame):
            classification_df = candidate
            break

if classification_df is not None:

    report_path = os.path.join(
        OUTPUT_DIR,
        "final_classification_report.csv"
    )

    classification_df.to_csv(report_path)

    print(f"✓ Classification report saved: {report_path}")

else:
    print("⚠ Classification report DataFrame not found.")

# ------------------------------------------------------------
# [8] SAVE TOP CONFUSED PAIRS IF AVAILABLE
# ------------------------------------------------------------

confused_df = None

for var_name in [
    "confused_pairs_df",
    "confusion_pairs_df",
    "top_confused_pairs",
    "most_confused_pairs"
]:

    if var_name in globals():

        candidate = globals()[var_name]

        if isinstance(candidate, pd.DataFrame):
            confused_df = candidate
            break

if confused_df is not None:

    confused_path = os.path.join(
        OUTPUT_DIR,
        "top_confused_class_pairs.csv"
    )

    confused_df.to_csv(confused_path, index=False)

    print(f"✓ Confused class pairs saved: {confused_path}")

else:
    print("⚠ Confused-pair DataFrame not found.")

# ------------------------------------------------------------
# [9] SAVE MODEL INFORMATION
# ------------------------------------------------------------

model_info = {
    "model_name": "Flat MLP",
    "total_parameters": 34828,
    "trainable_parameters": 34828,
    "non_trainable_parameters": 0,
    "approx_model_size_MB": 0.1329,
    "device": str(
        next(best_model.parameters()).device
    ) if "best_model" in globals() else "unknown",
    "random_seed": 42
}

model_info_path = os.path.join(
    OUTPUT_DIR,
    "model_information.json"
)

with open(model_info_path, "w") as f:
    json.dump(model_info, f, indent=4)

print(f"✓ Model information saved: {model_info_path}")

# ------------------------------------------------------------
# [10] SAVE FINAL SUMMARY JSON
# ------------------------------------------------------------

summary = {
    "project": "12-Class Feature-Based Classification",
    "final_model": "Flat MLP",

    "validation": {
        "accuracy_percent": 74.72,
        "macro_f1_percent": 74.04
    },

    "test": {
        "accuracy_percent": 47.22,
        "macro_f1_percent": 40.70,
        "balanced_accuracy_percent": 47.22,
        "macro_precision_percent": 53.39,
        "macro_recall_percent": 47.22,
        "weighted_f1_percent": 40.70,
        "mcc": 0.4403,
        "cohen_kappa": 0.4242,
        "mean_confidence_percent": 58.51
    },

    "generalization": {
        "accuracy_gap_pp": 27.50,
        "macro_f1_gap_pp": 33.34
    },

    "domain_shift": {
        "train_test_domain_accuracy_percent": 98.89,
        "train_validation_domain_accuracy_percent": 98.95,
        "train_test_shifted_features": 123,
        "train_test_total_features": 128,
        "train_test_shift_percentage": 96.09,
        "train_validation_shifted_features": 119,
        "train_validation_total_features": 128,
        "train_validation_shift_percentage": 92.97
    },

    "nearest_neighbor": {
        "validation_accuracy_percent": 48.06,
        "test_accuracy_percent": 44.44
    },

    "baseline": {
        "model": "XGBoost",
        "test_accuracy_percent": 58.89,
        "test_macro_f1_percent": 55.79
    },

    "mitigation": {
        "selected_strategy": "Original Features",
        "improvement_over_original": 0.0
    },

    "reproducibility": {
        "random_seed": 42
    },

    "generated_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
}

summary_path = os.path.join(
    OUTPUT_DIR,
    "final_project_summary.json"
)

with open(summary_path, "w") as f:
    json.dump(summary, f, indent=4)

print(f"✓ Final summary saved: {summary_path}")

# ------------------------------------------------------------
# [11] SAVE TEXT REPORT
# ------------------------------------------------------------

report_path = os.path.join(
    OUTPUT_DIR,
    "FINAL_RESEARCH_REPORT.txt"
)

with open(report_path, "w") as f:

    f.write("=" * 80 + "\n")
    f.write("FINAL RESEARCH REPORT\n")
    f.write("=" * 80 + "\n\n")

    f.write("FINAL MODEL\n")
    f.write("Flat MLP\n\n")

    f.write("VALIDATION PERFORMANCE\n")
    f.write("Validation Accuracy : 74.72%\n")
    f.write("Validation Macro-F1 : 74.04%\n\n")

    f.write("FINAL TEST PERFORMANCE\n")
    f.write("Test Accuracy       : 47.22%\n")
    f.write("Test Macro-F1       : 40.70%\n")
    f.write("Balanced Accuracy   : 47.22%\n")
    f.write("Macro Precision     : 53.39%\n")
    f.write("Macro Recall        : 47.22%\n")
    f.write("Weighted F1         : 40.70%\n")
    f.write("MCC                 : 0.4403\n")
    f.write("Cohen Kappa         : 0.4242\n\n")

    f.write("GENERALIZATION\n")
    f.write("Accuracy Gap        : 27.50 percentage points\n")
    f.write("Macro-F1 Gap        : 33.34 percentage points\n\n")

    f.write("DOMAIN SHIFT\n")
    f.write("Train-Test Domain Accuracy : 98.89%\n")
    f.write("Train-Val Domain Accuracy  : 98.95%\n")
    f.write("Train-Test Shifted Features: 123/128 (96.09%)\n")
    f.write("Train-Val Shifted Features : 119/128 (92.97%)\n\n")

    f.write("NEAREST NEIGHBOR\n")
    f.write("Validation NN Accuracy : 48.06%\n")
    f.write("Test NN Accuracy       : 44.44%\n\n")

    f.write("BASELINE\n")
    f.write("XGBoost Test Accuracy : 58.89%\n")
    f.write("XGBoost Test Macro-F1 : 55.79%\n\n")

    f.write("MODEL COMPLEXITY\n")
    f.write("Total Parameters      : 34,828\n")
    f.write("Trainable Parameters  : 34,828\n")
    f.write("Model Size            : 0.1329 MB\n\n")

    f.write("IMPORTANT FINAL DECISION\n")
    f.write("Official Flat MLP Test Accuracy = 47.22%\n")
    f.write("Official Flat MLP Test Macro-F1 = 40.70%\n")

print(f"✓ Final text report saved: {report_path}")

# ------------------------------------------------------------
# [12] LIST ALL SAVED FILES
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("STEP 13.9 COMPLETE")
print("=" * 80)

print("\nSaved files:")

for file_name in sorted(os.listdir(OUTPUT_DIR)):
    full_path = os.path.join(OUTPUT_DIR, file_name)

    if os.path.isfile(full_path):
        size_kb = os.path.getsize(full_path) / 1024
        print(f"✓ {file_name:<40} {size_kb:.2f} KB")

print("\n" + "=" * 80)
print("OFFICIAL FINAL RESULT")
print("=" * 80)

print("Final Model       : Flat MLP")
print("Validation Acc    : 74.72%")
print("Validation Macro-F1: 74.04%")
print("Test Accuracy     : 47.22%")
print("Test Macro-F1     : 40.70%")
print("XGBoost Test Acc  : 58.89%")
print("=" * 80)

print("\n✓ No retraining performed.")
print("✓ Test set was not used for model selection.")
print("✓ Results exported for thesis/report use.")

In [ ]:
# ============================================================
# STEP 14 — FINAL RESEARCH VISUALIZATION & FIGURES
# ============================================================


import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.metrics import confusion_matrix

# ------------------------------------------------------------
# [0] SETTINGS
# ------------------------------------------------------------

OUTPUT_DIR = "/kaggle/working/step_14_final_figures"
os.makedirs(OUTPUT_DIR, exist_ok=True)

plt.rcParams.update({
    "figure.dpi": 120,
    "savefig.dpi": 300,
    "font.size": 11,
    "axes.titlesize": 14,
    "axes.labelsize": 12,
    "xtick.labelsize": 10,
    "ytick.labelsize": 10
})

print("=" * 80)
print("STEP 14 — FINAL RESEARCH VISUALIZATION")
print("=" * 80)

# ============================================================
# FINAL OFFICIAL RESULTS
# ============================================================

classes = [str(i) for i in range(12)]

# Official Flat MLP
val_accuracy = 74.72
val_macro_f1 = 74.04

test_accuracy = 47.22
test_macro_f1 = 40.70

# XGBoost baseline
xgb_accuracy = 58.89
xgb_macro_f1 = 55.79

# Domain shift
train_test_domain = 98.89
train_val_domain = 98.95

train_test_shift = 96.09
train_val_shift = 92.97

nn_val = 48.06
nn_test = 44.44

# ============================================================
# [1] CONFUSION MATRIX
# ============================================================

print("\n[1] CONFUSION MATRIX")

# Official Flat MLP confusion matrix from Step 13.5B
cm = np.array([
    [ 9, 0, 0, 0, 0,14, 7, 0, 0, 0, 0, 0],
    [ 0, 0, 1, 2, 0, 1, 0, 0, 0,15, 0,11],
    [ 0, 0, 2, 0, 0, 0, 0, 0, 0, 9, 6,13],
    [ 0, 0, 0, 8, 0, 9, 0, 0, 0,10, 0, 3],
    [ 0, 0, 0, 0, 4, 4, 0, 0, 0, 3, 2,17],
    [ 1, 0, 0, 0, 0,18, 0, 0, 1, 1, 6, 3],
    [13, 0, 0, 0, 0, 0,12, 0, 0, 5, 0, 0],
    [ 0, 0, 0, 0, 0, 1, 0, 6,19, 0, 1, 3],
    [ 0, 0, 0, 0, 0, 0, 0, 0,29, 0, 0, 1],
    [ 0, 0, 2, 0, 0, 1, 0, 0, 0,23, 0, 4],
    [ 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,29, 0],
    [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,30]
])

plt.figure(figsize=(10, 8))
plt.imshow(cm, interpolation="nearest", aspect="auto")
plt.colorbar(label="Number of Samples")

plt.xticks(range(12), classes)
plt.yticks(range(12), classes)

plt.xlabel("Predicted Class")
plt.ylabel("True Class")
plt.title("Flat MLP — Test Confusion Matrix")

for i in range(12):
    for j in range(12):
        plt.text(
            j, i, str(cm[i, j]),
            ha="center",
            va="center",
            fontsize=9
        )

plt.tight_layout()

path = os.path.join(
    OUTPUT_DIR,
    "01_flat_mlp_confusion_matrix.png"
)

plt.savefig(path, bbox_inches="tight")
plt.show()
plt.close()

print(f"✓ Saved: {path}")

# ============================================================
# [2] NORMALIZED CONFUSION MATRIX
# ============================================================

print("\n[2] NORMALIZED CONFUSION MATRIX")

row_sum = cm.sum(axis=1, keepdims=True)

cm_norm = np.divide(
    cm,
    row_sum,
    out=np.zeros_like(cm, dtype=float),
    where=row_sum != 0
)

plt.figure(figsize=(10, 8))
plt.imshow(cm_norm, interpolation="nearest", aspect="auto")
plt.colorbar(label="Recall")

plt.xticks(range(12), classes)
plt.yticks(range(12), classes)

plt.xlabel("Predicted Class")
plt.ylabel("True Class")
plt.title("Flat MLP — Normalized Test Confusion Matrix")

for i in range(12):
    for j in range(12):
        plt.text(
            j,
            i,
            f"{cm_norm[i, j]:.2f}",
            ha="center",
            va="center",
            fontsize=8
        )

plt.tight_layout()

path = os.path.join(
    OUTPUT_DIR,
    "02_normalized_confusion_matrix.png"
)

plt.savefig(path, bbox_inches="tight")
plt.show()
plt.close()

print(f"✓ Saved: {path}")

# ============================================================
# [3] VALIDATION VS TEST PERFORMANCE
# ============================================================

print("\n[3] VALIDATION VS TEST PERFORMANCE")

metrics = ["Accuracy", "Macro-F1"]

validation = [
    val_accuracy,
    val_macro_f1
]

test = [
    test_accuracy,
    test_macro_f1
]

x = np.arange(len(metrics))
width = 0.35

plt.figure(figsize=(8, 6))

plt.bar(
    x - width/2,
    validation,
    width,
    label="Validation"
)

plt.bar(
    x + width/2,
    test,
    width,
    label="Test"
)

plt.xticks(x, metrics)
plt.ylabel("Score (%)")
plt.ylim(0, 100)
plt.title("Flat MLP — Validation vs Test Performance")
plt.legend()

for i, value in enumerate(validation):
    plt.text(
        i - width/2,
        value + 2,
        f"{value:.2f}%",
        ha="center"
    )

for i, value in enumerate(test):
    plt.text(
        i + width/2,
        value + 2,
        f"{value:.2f}%",
        ha="center"
    )

plt.tight_layout()

path = os.path.join(
    OUTPUT_DIR,
    "03_validation_vs_test_performance.png"
)

plt.savefig(path, bbox_inches="tight")
plt.show()
plt.close()

print(f"✓ Saved: {path}")

# ============================================================
# [4] GENERALIZATION GAP
# ============================================================

print("\n[4] GENERALIZATION GAP")

gap_accuracy = val_accuracy - test_accuracy
gap_f1 = val_macro_f1 - test_macro_f1

gap_values = [
    gap_accuracy,
    gap_f1
]

plt.figure(figsize=(8, 6))

bars = plt.bar(
    ["Accuracy Gap", "Macro-F1 Gap"],
    gap_values
)

plt.ylabel("Generalization Gap (percentage points)")
plt.title("Flat MLP — Validation-to-Test Generalization Gap")

for bar, value in zip(bars, gap_values):
    plt.text(
        bar.get_x() + bar.get_width()/2,
        value + 1,
        f"{value:.2f} pp",
        ha="center"
    )

plt.ylim(0, max(gap_values) + 10)

plt.tight_layout()

path = os.path.join(
    OUTPUT_DIR,
    "04_generalization_gap.png"
)

plt.savefig(path, bbox_inches="tight")
plt.show()
plt.close()

print(f"✓ Saved: {path}")

# ============================================================
# [5] MODEL COMPARISON
# ============================================================

print("\n[5] MODEL COMPARISON")

models = [
    "GCN",
    "GraphSAGE",
    "GAT",
    "GAT + Fusion",
    "Flat MLP",
    "XGBoost"
]

test_acc = [
    8.33,
    12.78,
    17.50,
    51.39,
    47.22,
    58.89
]

test_f1 = [
    1.28,
    9.88,
    10.48,
    44.88,
    40.70,
    55.79
]

x = np.arange(len(models))
width = 0.36

plt.figure(figsize=(11, 6))

plt.bar(
    x - width/2,
    test_acc,
    width,
    label="Test Accuracy"
)

plt.bar(
    x + width/2,
    test_f1,
    width,
    label="Test Macro-F1"
)

plt.xticks(x, models, rotation=20)
plt.ylabel("Performance (%)")
plt.ylim(0, 100)
plt.title("Final Model Comparison on Test Set")
plt.legend()

for i, value in enumerate(test_acc):
    plt.text(
        i - width/2,
        value + 1.5,
        f"{value:.1f}",
        ha="center",
        fontsize=9
    )

for i, value in enumerate(test_f1):
    plt.text(
        i + width/2,
        value + 1.5,
        f"{value:.1f}",
        ha="center",
        fontsize=9
    )

plt.tight_layout()

path = os.path.join(
    OUTPUT_DIR,
    "05_final_model_comparison.png"
)

plt.savefig(path, bbox_inches="tight")
plt.show()
plt.close()

print(f"✓ Saved: {path}")

# ============================================================
# [6] CLASS-WISE PERFORMANCE
# ============================================================

print("\n[6] CLASS-WISE TEST PERFORMANCE")

precision = [
    39.0, 0.0, 40.0, 80.0,
    100.0, 38.0, 63.0, 86.0,
    59.0, 35.0, 66.0, 35.0
]

recall = [
    30.0, 0.0, 6.7, 26.7,
    13.3, 60.0, 40.0, 20.0,
    96.7, 76.7, 96.7, 100.0
]

f1 = [
    34.0, 0.0, 11.4, 40.0,
    23.5, 46.0, 49.0, 32.4,
    73.4, 47.9, 78.4, 52.2
]

x = np.arange(12)
width = 0.25

plt.figure(figsize=(13, 7))

plt.bar(
    x - width,
    precision,
    width,
    label="Precision"
)

plt.bar(
    x,
    recall,
    width,
    label="Recall"
)

plt.bar(
    x + width,
    f1,
    width,
    label="F1-score"
)

plt.xticks(x, classes)
plt.xlabel("Class")
plt.ylabel("Score (%)")
plt.ylim(0, 110)
plt.title("Flat MLP — Class-wise Test Performance")
plt.legend()

plt.tight_layout()

path = os.path.join(
    OUTPUT_DIR,
    "06_classwise_test_performance.png"
)

plt.savefig(path, bbox_inches="tight")
plt.show()
plt.close()

print(f"✓ Saved: {path}")

# ============================================================
# [7] DOMAIN CLASSIFICATION ACCURACY
# ============================================================

print("\n[7] DOMAIN SHIFT")

domains = [
    "Train → Test",
    "Train → Validation"
]

domain_acc = [
    train_test_domain,
    train_val_domain
]

plt.figure(figsize=(8, 6))

bars = plt.bar(
    domains,
    domain_acc
)

plt.ylabel("Domain Classifier Accuracy (%)")
plt.ylim(0, 105)
plt.title("Evidence of Dataset Domain Shift")

for bar, value in zip(bars, domain_acc):
    plt.text(
        bar.get_x() + bar.get_width()/2,
        value + 1,
        f"{value:.2f}%",
        ha="center"
    )

plt.tight_layout()

path = os.path.join(
    OUTPUT_DIR,
    "07_domain_shift_accuracy.png"
)

plt.savefig(path, bbox_inches="tight")
plt.show()
plt.close()

print(f"✓ Saved: {path}")

# ============================================================
# [8] FEATURE DISTRIBUTION SHIFT
# ============================================================

print("\n[8] FEATURE DISTRIBUTION SHIFT")

shift_values = [
    train_test_shift,
    train_val_shift
]

labels = [
    "Train → Test",
    "Train → Validation"
]

plt.figure(figsize=(8, 6))

bars = plt.bar(
    labels,
    shift_values
)

plt.ylabel("Shifted Features (%)")
plt.ylim(0, 105)
plt.title("Percentage of Features Showing Significant Distribution Shift")

for bar, value in zip(bars, shift_values):
    plt.text(
        bar.get_x() + bar.get_width()/2,
        value + 1,
        f"{value:.2f}%",
        ha="center"
    )

plt.tight_layout()

path = os.path.join(
    OUTPUT_DIR,
    "08_feature_distribution_shift.png"
)

plt.savefig(path, bbox_inches="tight")
plt.show()
plt.close()

print(f"✓ Saved: {path}")

# ============================================================
# [9] NEAREST-NEIGHBOR GENERALIZATION
# ============================================================

print("\n[9] NEAREST-NEIGHBOR CLASS CONSISTENCY")

nn_values = [
    nn_val,
    nn_test
]

plt.figure(figsize=(8, 6))

bars = plt.bar(
    ["Validation", "Test"],
    nn_values
)

plt.ylabel("Nearest-Neighbor Accuracy (%)")
plt.ylim(0, 100)
plt.title("Nearest-Neighbor Class Consistency")

for bar, value in zip(bars, nn_values):
    plt.text(
        bar.get_x() + bar.get_width()/2,
        value + 2,
        f"{value:.2f}%",
        ha="center"
    )

plt.tight_layout()

path = os.path.join(
    OUTPUT_DIR,
    "09_nearest_neighbor_accuracy.png"
)

plt.savefig(path, bbox_inches="tight")
plt.show()
plt.close()

print(f"✓ Saved: {path}")

# ============================================================
# [10] TOP CONFUSED CLASS PAIRS
# ============================================================

print("\n[10] TOP CONFUSED CLASS PAIRS")

confused_true = [7, 4, 1, 0, 2, 6, 1, 3, 2, 3]
confused_pred = [8,11, 9, 5,11, 0,11, 9, 9, 5]
confused_count = [19,17,15,14,13,13,11,10,9,9]

pair_labels = [
    f"{a} → {b}"
    for a, b in zip(confused_true, confused_pred)
]

plt.figure(figsize=(10, 6))

bars = plt.barh(
    pair_labels[::-1],
    confused_count[::-1]
)

plt.xlabel("Misclassified Samples")
plt.ylabel("True → Predicted")
plt.title("Top 10 Most Confused Class Pairs")

for bar, value in zip(
    bars,
    confused_count[::-1]
):
    plt.text(
        value + 0.3,
        bar.get_y() + bar.get_height()/2,
        str(value),
        va="center"
    )

plt.tight_layout()

path = os.path.join(
    OUTPUT_DIR,
    "10_top_confused_class_pairs.png"
)

plt.savefig(path, bbox_inches="tight")
plt.show()
plt.close()

print(f"✓ Saved: {path}")

# ============================================================
# [11] FINAL PERFORMANCE SUMMARY FIGURE
# ============================================================

print("\n[11] FINAL RESEARCH SUMMARY")

summary_labels = [
    "Val Accuracy",
    "Val Macro-F1",
    "Test Accuracy",
    "Test Macro-F1",
    "XGBoost Accuracy",
    "XGBoost Macro-F1"
]

summary_values = [
    val_accuracy,
    val_macro_f1,
    test_accuracy,
    test_macro_f1,
    xgb_accuracy,
    xgb_macro_f1
]

plt.figure(figsize=(11, 6))

bars = plt.bar(
    summary_labels,
    summary_values
)

plt.ylabel("Performance (%)")
plt.ylim(0, 100)
plt.title("Final Research Performance Summary")

plt.xticks(
    rotation=20,
    ha="right"
)

for bar, value in zip(
    bars,
    summary_values
):
    plt.text(
        bar.get_x() + bar.get_width()/2,
        value + 1.5,
        f"{value:.2f}%",
        ha="center",
        fontsize=9
    )

plt.tight_layout()

path = os.path.join(
    OUTPUT_DIR,
    "11_final_research_performance_summary.png"
)

plt.savefig(path, bbox_inches="tight")
plt.show()
plt.close()

print(f"✓ Saved: {path}")

# ============================================================
# [12] SAVE ALL NUMERICAL VISUALIZATION DATA
# ============================================================

visualization_data = pd.DataFrame({
    "Metric": summary_labels,
    "Value (%)": summary_values
})

csv_path = os.path.join(
    OUTPUT_DIR,
    "visualization_summary.csv"
)

visualization_data.to_csv(
    csv_path,
    index=False
)

print(f"\n✓ Visualization data saved: {csv_path}")

# ============================================================
# [13] FINAL FILE LIST
# ============================================================

print("\n" + "=" * 80)
print("STEP 14 COMPLETE")
print("=" * 80)

files = sorted(os.listdir(OUTPUT_DIR))

print(f"\nGenerated {len(files)} files:\n")

for i, file_name in enumerate(files, 1):

    full_path = os.path.join(
        OUTPUT_DIR,
        file_name
    )

    size_kb = os.path.getsize(full_path) / 1024

    print(
        f"{i:02d}. {file_name:<50} "
        f"{size_kb:.1f} KB"
    )

print("\n" + "=" * 80)
print("OFFICIAL VALUES USED")
print("=" * 80)

print(f"Flat MLP Validation Accuracy : {val_accuracy:.2f}%")
print(f"Flat MLP Validation Macro-F1 : {val_macro_f1:.2f}%")
print(f"Flat MLP Test Accuracy       : {test_accuracy:.2f}%")
print(f"Flat MLP Test Macro-F1       : {test_macro_f1:.2f}%")
print(f"XGBoost Test Accuracy        : {xgb_accuracy:.2f}%")
print(f"XGBoost Test Macro-F1        : {xgb_macro_f1:.2f}%")

print("\n✓ Step 14 finished.")
print("✓ No model was retrained.")
print("✓ Official Flat MLP test result remains 47.22%.")

In [ ]:
# ============================================================
# STEP 15 — FINAL RESEARCH INTERPRETATION & DISCUSSION
# ============================================================
# Purpose:
#   Convert the completed experimental results into a concise,
#   scientifically defensible interpretation.
#
# IMPORTANT:
#   - No retraining
#   - No test-set model selection
#   - Official Flat MLP Test Accuracy = 47.22%
#   - Official Flat MLP Test Macro-F1 = 40.70%
#   - XGBoost baseline = 58.89% Accuracy / 55.79% Macro-F1
# ============================================================

import os
import pandas as pd

OUTPUT_DIR = "/kaggle/working/step_15_research_interpretation"
os.makedirs(OUTPUT_DIR, exist_ok=True)

print("=" * 80)
print("STEP 15 — FINAL RESEARCH INTERPRETATION & DISCUSSION")
print("=" * 80)

# ============================================================
# [1] OFFICIAL RESULTS
# ============================================================

final_model = "Flat MLP"

val_acc = 74.72
val_f1 = 74.04

test_acc = 47.22
test_f1 = 40.70

xgb_acc = 58.89
xgb_f1 = 55.79

accuracy_gap = 27.50
f1_gap = 33.34

domain_train_test = 98.89
domain_train_val = 98.95

shift_train_test = 96.09
shift_train_val = 92.97

nn_val = 48.06
nn_test = 44.44

mean_confidence = 58.51

print("\n[1] OFFICIAL RESULTS LOADED")
print("-" * 80)

print(f"Final model             : {final_model}")
print(f"Validation Accuracy     : {val_acc:.2f}%")
print(f"Validation Macro-F1     : {val_f1:.2f}%")
print(f"Test Accuracy           : {test_acc:.2f}%")
print(f"Test Macro-F1           : {test_f1:.2f}%")
print(f"XGBoost Test Accuracy   : {xgb_acc:.2f}%")
print(f"XGBoost Test Macro-F1   : {xgb_f1:.2f}%")

# ============================================================
# [2] GENERALIZATION ANALYSIS
# ============================================================

print("\n[2] GENERALIZATION ANALYSIS")
print("-" * 80)

if accuracy_gap >= 20:
    generalization_status = "SEVERE"
elif accuracy_gap >= 10:
    generalization_status = "MODERATE"
else:
    generalization_status = "LOW"

print(f"Accuracy generalization gap : {accuracy_gap:.2f} pp")
print(f"Macro-F1 generalization gap : {f1_gap:.2f} pp")
print(f"Generalization issue        : {generalization_status}")

# ============================================================
# [3] DOMAIN SHIFT ANALYSIS
# ============================================================

print("\n[3] DOMAIN SHIFT ANALYSIS")
print("-" * 80)

if domain_train_test >= 90:
    domain_status = "VERY STRONG"
elif domain_train_test >= 75:
    domain_status = "STRONG"
else:
    domain_status = "MODERATE"

print(
    f"Train-Test domain accuracy : "
    f"{domain_train_test:.2f}%"
)

print(
    f"Train-Val domain accuracy  : "
    f"{domain_train_val:.2f}%"
)

print(
    f"Train-Test shifted features: "
    f"{shift_train_test:.2f}%"
)

print(
    f"Train-Val shifted features : "
    f"{shift_train_val:.2f}%"
)

print(f"Domain shift severity      : {domain_status}")

# ============================================================
# [4] MODEL COMPARISON
# ============================================================

print("\n[4] MODEL COMPARISON")
print("-" * 80)

model_comparison = pd.DataFrame({

    "Model": [
        "GCN",
        "GraphSAGE",
        "GAT",
        "GAT + Fusion",
        "Flat MLP",
        "XGBoost"
    ],

    "Test Accuracy (%)": [
        8.33,
        12.78,
        17.50,
        51.39,
        47.22,
        58.89
    ],

    "Test Macro-F1 (%)": [
        1.28,
        9.88,
        10.48,
        44.88,
        40.70,
        55.79
    ]
})

print(model_comparison.to_string(index=False))

best_model_test_acc = model_comparison.loc[
    model_comparison["Test Accuracy (%)"].idxmax()
]

best_model_test_f1 = model_comparison.loc[
    model_comparison["Test Macro-F1 (%)"].idxmax()
]

print("\nBest Test Accuracy:")
print(
    f"{best_model_test_acc['Model']} "
    f"({best_model_test_acc['Test Accuracy (%)']:.2f}%)"
)

print("\nBest Test Macro-F1:")
print(
    f"{best_model_test_f1['Model']} "
    f"({best_model_test_f1['Test Macro-F1 (%)']:.2f}%)"
)

# ============================================================
# [5] CLASS-WISE INTERPRETATION
# ============================================================

print("\n[5] CLASS-WISE INTERPRETATION")
print("-" * 80)

class_f1 = {
    0: 34.0,
    1: 0.0,
    2: 11.4,
    3: 40.0,
    4: 23.5,
    5: 46.0,
    6: 49.0,
    7: 32.4,
    8: 73.4,
    9: 47.9,
    10: 78.4,
    11: 52.2
}

best_class = max(
    class_f1,
    key=class_f1.get
)

worst_class = min(
    class_f1,
    key=class_f1.get
)

print(
    f"Best-performing class : {best_class} "
    f"(F1 = {class_f1[best_class]:.1f}%)"
)

print(
    f"Worst-performing class: {worst_class} "
    f"(F1 = {class_f1[worst_class]:.1f}%)"
)

# ============================================================
# [6] NEAREST-NEIGHBOR INTERPRETATION
# ============================================================

print("\n[6] NEAREST-NEIGHBOR ANALYSIS")
print("-" * 80)

print(f"Validation NN accuracy : {nn_val:.2f}%")
print(f"Test NN accuracy       : {nn_test:.2f}%")

if nn_test < 50:
    nn_interpretation = (
        "Low nearest-neighbor class consistency indicates that "
        "test samples are not strongly aligned with class-consistent "
        "training representations."
    )
else:
    nn_interpretation = (
        "Nearest-neighbor analysis indicates relatively strong "
        "class consistency."
    )

print(nn_interpretation)

# ============================================================
# [7] CONFIDENCE INTERPRETATION
# ============================================================

print("\n[7] CONFIDENCE ANALYSIS")
print("-" * 80)

print(f"Mean test confidence : {mean_confidence:.2f}%")

if mean_confidence > 80:
    confidence_interpretation = (
        "The model is highly confident in its predictions."
    )
elif mean_confidence >= 50:
    confidence_interpretation = (
        "The model shows moderate prediction confidence."
    )
else:
    confidence_interpretation = (
        "The model shows relatively low prediction confidence."
    )

print(confidence_interpretation)

# ============================================================
# [8] MITIGATION INTERPRETATION
# ============================================================

print("\n[8] DOMAIN-SHIFT MITIGATION")
print("-" * 80)

print("Selected strategy : Original Features")
print("Feature removal   : No improvement")
print("50% downweighting : No improvement")
print("25% downweighting : No improvement")

mitigation_interpretation = (
    "The evaluated feature-level mitigation strategies did not "
    "improve validation Macro-F1 over the original feature set. "
    "Therefore, the original feature representation was retained "
    "as the final configuration."
)

print(mitigation_interpretation)

# ============================================================
# [9] SCIENTIFIC INTERPRETATION
# ============================================================

print("\n[9] SCIENTIFIC INTERPRETATION")
print("-" * 80)

scientific_interpretation = f"""
The experimental results demonstrate a substantial discrepancy
between validation and independent test performance. The selected
Flat MLP achieved {val_acc:.2f}% validation accuracy and
{val_f1:.2f}% validation Macro-F1, whereas its independently
verified test performance decreased to {test_acc:.2f}% accuracy
and {test_f1:.2f}% Macro-F1. This corresponds to a
{accuracy_gap:.2f}-percentage-point accuracy gap and a
{f1_gap:.2f}-percentage-point Macro-F1 gap.

The diagnostic analysis provides strong evidence that this
performance degradation is associated with dataset domain shift.
A classifier trained to distinguish training samples from test
samples achieved {domain_train_test:.2f}% accuracy, while the
train-versus-validation domain classifier achieved
{domain_train_val:.2f}% accuracy. Furthermore, {shift_train_test:.2f}%
of the features exhibited significant train-to-test distribution
shift and {shift_train_val:.2f}% exhibited significant
train-to-validation shift.

Nearest-neighbor analysis also showed limited class consistency,
with {nn_val:.2f}% validation accuracy and {nn_test:.2f}% test
accuracy. These findings indicate that the feature representation
does not provide sufficiently stable class-consistent neighborhoods
across dataset partitions.

Although the Flat MLP achieved the highest validation Macro-F1
among the evaluated models, XGBoost produced stronger independent
test performance, achieving {xgb_acc:.2f}% test accuracy and
{xgb_f1:.2f}% Macro-F1. Therefore, validation performance alone
would have provided an overly optimistic estimate of real-world
generalization.

The mitigation experiments did not improve the original feature
representation. Consequently, the original feature configuration
was retained. Overall, the experiments demonstrate that dataset
distribution shift and cross-domain generalization are major
factors affecting classification performance in this feature-based
12-class classification task.
"""

print(scientific_interpretation)

# ============================================================
# [10] KEY RESEARCH FINDINGS
# ============================================================

print("\n[10] KEY RESEARCH FINDINGS")
print("-" * 80)

key_findings = [

    "1. Flat MLP achieved the strongest validation performance "
    "among the evaluated models.",

    "2. Independent test performance was substantially lower "
    "than validation performance.",

    "3. Train-test domain classification accuracy of 98.89% "
    "provides strong evidence of distribution shift.",

    "4. 123 of 128 features (96.09%) showed significant "
    "train-test distribution shift.",

    "5. Nearest-neighbor test accuracy of 44.44% indicates "
    "limited class-consistent feature neighborhoods.",

    "6. XGBoost outperformed Flat MLP on the independent test set.",

    "7. The tested feature-level mitigation strategies did not "
    "improve the original feature representation.",

    "8. Test-set performance should be emphasized rather than "
    "validation performance when discussing generalization."
]

for finding in key_findings:
    print(finding)

# ============================================================
# [11] LIMITATIONS
# ============================================================

print("\n[11] RESEARCH LIMITATIONS")
print("-" * 80)

limitations = [

    "1. Strong distribution differences exist between dataset splits.",

    "2. The Flat MLP exhibits a substantial validation-to-test "
    "generalization gap.",

    "3. Several classes have weak test-set F1 scores.",

    "4. The investigated feature-level mitigation methods were "
    "insufficient to remove the observed domain shift.",

    "5. The final results should therefore be interpreted as "
    "evidence of limited cross-domain generalization rather than "
    "as evidence of universally high classification performance."
]

for item in limitations:
    print(item)

# ============================================================
# [12] FUTURE WORK
# ============================================================

print("\n[12] RECOMMENDED FUTURE WORK")
print("-" * 80)

future_work = [

    "1. Investigate domain-adaptive feature normalization.",

    "2. Evaluate domain-adversarial representation learning.",

    "3. Perform feature-level harmonization before classification.",

    "4. Increase the diversity and size of the training data.",

    "5. Evaluate the approach on an independent external dataset.",

    "6. Investigate class-specific feature representations.",

    "7. Perform repeated cross-validation to estimate robustness.",

    "8. Evaluate calibration and uncertainty on the external test set."
]

for item in future_work:
    print(item)

# ============================================================
# [13] SAVE INTERPRETATION TO TXT
# ============================================================

txt_path = os.path.join(
    OUTPUT_DIR,
    "step_15_final_research_interpretation.txt"
)

with open(txt_path, "w", encoding="utf-8") as f:

    f.write("=" * 80 + "\n")
    f.write("STEP 15 — FINAL RESEARCH INTERPRETATION\n")
    f.write("=" * 80 + "\n\n")

    f.write("FINAL MODEL\n")
    f.write(f"{final_model}\n\n")

    f.write("VALIDATION PERFORMANCE\n")
    f.write(f"Accuracy : {val_acc:.2f}%\n")
    f.write(f"Macro-F1 : {val_f1:.2f}%\n\n")

    f.write("FINAL TEST PERFORMANCE\n")
    f.write(f"Accuracy : {test_acc:.2f}%\n")
    f.write(f"Macro-F1 : {test_f1:.2f}%\n\n")

    f.write("GENERALIZATION GAP\n")
    f.write(f"Accuracy Gap : {accuracy_gap:.2f} pp\n")
    f.write(f"Macro-F1 Gap : {f1_gap:.2f} pp\n\n")

    f.write("DOMAIN SHIFT\n")
    f.write(
        f"Train-Test Domain Accuracy : "
        f"{domain_train_test:.2f}%\n"
    )
    f.write(
        f"Train-Val Domain Accuracy : "
        f"{domain_train_val:.2f}%\n"
    )
    f.write(
        f"Train-Test Shifted Features : "
        f"{shift_train_test:.2f}%\n"
    )
    f.write(
        f"Train-Val Shifted Features : "
        f"{shift_train_val:.2f}%\n\n"
    )

    f.write("BASELINE\n")
    f.write(f"XGBoost Accuracy : {xgb_acc:.2f}%\n")
    f.write(f"XGBoost Macro-F1 : {xgb_f1:.2f}%\n\n")

    f.write("SCIENTIFIC INTERPRETATION\n")
    f.write(scientific_interpretation)

    f.write("\n\nKEY FINDINGS\n")
    for finding in key_findings:
        f.write(finding + "\n")

    f.write("\nLIMITATIONS\n")
    for item in limitations:
        f.write(item + "\n")

    f.write("\nFUTURE WORK\n")
    for item in future_work:
        f.write(item + "\n")

print(f"\n✓ Saved interpretation report:")
print(txt_path)

# ============================================================
# [14] SAVE SUMMARY TABLE
# ============================================================

summary_table = pd.DataFrame({
    "Research Component": [
        "Final Model",
        "Validation Accuracy",
        "Validation Macro-F1",
        "Test Accuracy",
        "Test Macro-F1",
        "Accuracy Gap",
        "Macro-F1 Gap",
        "Mean Test Confidence",
        "Train-Test Domain Accuracy",
        "Train-Val Domain Accuracy",
        "Train-Test Shifted Features",
        "Train-Val Shifted Features",
        "Validation NN Accuracy",
        "Test NN Accuracy",
        "XGBoost Test Accuracy",
        "XGBoost Test Macro-F1"
    ],

    "Result": [
        final_model,
        f"{val_acc:.2f}%",
        f"{val_f1:.2f}%",
        f"{test_acc:.2f}%",
        f"{test_f1:.2f}%",
        f"{accuracy_gap:.2f} pp",
        f"{f1_gap:.2f} pp",
        f"{mean_confidence:.2f}%",
        f"{domain_train_test:.2f}%",
        f"{domain_train_val:.2f}%",
        f"{shift_train_test:.2f}%",
        f"{shift_train_val:.2f}%",
        f"{nn_val:.2f}%",
        f"{nn_test:.2f}%",
        f"{xgb_acc:.2f}%",
        f"{xgb_f1:.2f}%"
    ]
})

csv_path = os.path.join(
    OUTPUT_DIR,
    "step_15_research_summary.csv"
)

summary_table.to_csv(
    csv_path,
    index=False
)

print(f"✓ Saved summary table:")
print(csv_path)

# ============================================================
# [15] FINAL MESSAGE
# ============================================================

print("\n" + "=" * 80)
print("STEP 15 COMPLETE")
print("=" * 80)

print("""
Your experimental findings are now scientifically interpreted.

OFFICIAL RESULTS:
    Flat MLP Validation Accuracy : 74.72%
    Flat MLP Validation Macro-F1 : 74.04%
    Flat MLP Test Accuracy       : 47.22%
    Flat MLP Test Macro-F1       : 40.70%

BASELINE:
    XGBoost Test Accuracy        : 58.89%
    XGBoost Test Macro-F1        : 55.79%

MAIN FINDING:
    Strong train/test domain shift is associated with poor
    cross-domain generalization.

NEXT:
    STEP 16 — FINAL RESULTS TABLE + THESIS/PAPER CONCLUSION
""")

In [ ]:
# ============================================================
# STEP 16 — CROSS-VALIDATION + STATISTICAL TEST + EXPLAINABILITY
# ============================================================
# IMPORTANT:
# - Uses existing Xtr, ytr, Xte, yte variables.
# - NEVER invents subject IDs.
# - If real subject IDs are available, grouped CV is used.
# - Otherwise, stratified sample-level 5-fold CV is performed
#   and explicitly reported as a limitation.
# - SHAP and LIME explanations are generated when available.
# ============================================================

import os
import sys
import time
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import StratifiedKFold, GroupKFold
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    precision_score,
    recall_score,
    balanced_accuracy_score,
    matthews_corrcoef
)
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.neural_network import MLPClassifier
from sklearn.base import clone

from scipy.stats import wilcoxon, ttest_rel

RANDOM_SEED = 42
N_SPLITS = 5

np.random.seed(RANDOM_SEED)

print("=" * 80)
print("STEP 16 — CROSS-VALIDATION + STATISTICAL TEST + EXPLAINABILITY")
print("=" * 80)
print("Random seed :", RANDOM_SEED)
print("=" * 80)


# ============================================================
# [1] FIND EXISTING DATA
# ============================================================

print("\n[1] CHECKING REQUIRED DATA")
print("=" * 80)

required = ["Xtr", "ytr"]

missing = [v for v in required if v not in globals()]

if missing:
    raise RuntimeError(
        f"Required variables missing: {missing}\n"
        "Expected Xtr and ytr from previous steps."
    )

X = np.asarray(Xtr)
y = np.asarray(ytr).ravel()

print("Xtr shape :", X.shape)
print("ytr shape :", y.shape)

if X.ndim != 2:
    raise ValueError("Xtr must be a 2D feature matrix.")

if len(X) != len(y):
    raise ValueError("Xtr and ytr have different numbers of samples.")

N, D = X.shape

print("Samples   :", N)
print("Features  :", D)
print("Classes   :", len(np.unique(y)))


# ============================================================
# [2] SEARCH FOR REAL SUBJECT IDS SAFELY
# ============================================================

print("\n[2] SEARCHING FOR SUBJECT/GROUP IDS")
print("=" * 80)

candidate_names = [
    "subject_ids",
    "subject_id",
    "subjects",
    "subject",
    "group_ids",
    "group_id",
    "groups",
    "group",
    "participant_ids",
    "participant_id",
    "participants",
    "patient_ids",
    "patient_id",
    "patient",
    "session_ids",
    "session_id"
]

found_group_name = None
found_groups = None

# IMPORTANT:
# list(...) prevents "dictionary changed size during iteration"
global_items = list(globals().items())

for name, obj in global_items:

    if name not in candidate_names:
        continue

    try:
        arr = np.asarray(obj)

        # Must be a genuine 1-D array
        if arr.ndim != 1:
            continue

        if len(arr) != N:
            continue

        # Must have more than one group
        unique_count = len(np.unique(arr))

        if unique_count < 2:
            continue

        found_group_name = name
        found_groups = arr.copy()

        break

    except Exception:
        continue


# ============================================================
# [3] GROUPING DECISION
# ============================================================

print("\n[3] CROSS-VALIDATION MODE")
print("=" * 80)

if found_groups is not None:

    print("✓ REAL SUBJECT/GROUP VARIABLE FOUND")
    print("Variable :", found_group_name)
    print("Groups   :", len(np.unique(found_groups)))

    CV_MODE = "GROUPED"

else:

    print("⚠ No real subject/group ID array was found.")
    print()
    print("Therefore a TRUE subject-grouped CV cannot be performed")
    print("from the currently available variables.")
    print()
    print("Using stratified sample-level 5-fold CV as a fallback.")
    print("This must NOT be described as subject-independent CV.")
    print()

    CV_MODE = "STRATIFIED"


# ============================================================
# [4] DEFINE CROSS-VALIDATION
# ============================================================

print("\n[4] CREATING 5-FOLD SPLITS")
print("=" * 80)

if CV_MODE == "GROUPED":

    cv = GroupKFold(n_splits=N_SPLITS)

    splits = list(
        cv.split(
            X,
            y,
            groups=found_groups
        )
    )

else:

    cv = StratifiedKFold(
        n_splits=N_SPLITS,
        shuffle=True,
        random_state=RANDOM_SEED
    )

    splits = list(
        cv.split(X, y)
    )

print("Number of folds :", len(splits))


# ============================================================
# [5] DEFINE FLAT MLP
# ============================================================

print("\n[5] DEFINING FLAT MLP")
print("=" * 80)

# Use the same general architecture as the final model:
# 128 input features → hidden layers → 12 classes

n_classes = len(np.unique(y))

mlp_model = Pipeline([
    (
        "scaler",
        StandardScaler()
    ),
    (
        "mlp",
        MLPClassifier(
            hidden_layer_sizes=(64, 32),
            activation="relu",
            solver="adam",
            alpha=1e-4,
            batch_size=32,
            learning_rate_init=1e-4,
            max_iter=100,
            early_stopping=True,
            validation_fraction=0.15,
            n_iter_no_change=10,
            random_state=RANDOM_SEED
        )
    )
])

print("Model : Flat MLP")
print("Architecture : 128 → 64 → 32 →", n_classes)


# ============================================================
# [6] XGBOOST MODEL
# ============================================================

print("\n[6] CHECKING XGBOOST")
print("=" * 80)

try:

    from xgboost import XGBClassifier

    xgb_available = True

    xgb_model = XGBClassifier(
        n_estimators=200,
        max_depth=6,
        learning_rate=0.05,
        subsample=0.9,
        colsample_bytree=0.9,
        objective="multi:softprob",
        num_class=n_classes,
        eval_metric="mlogloss",
        random_state=RANDOM_SEED,
        n_jobs=-1
    )

    print("✓ XGBoost available")

except Exception as e:

    xgb_available = False
    xgb_model = None

    print("⚠ XGBoost unavailable")
    print("Reason:", str(e))


# ============================================================
# [7] CROSS-VALIDATION
# ============================================================

print("\n[7] RUNNING 5-FOLD CROSS-VALIDATION")
print("=" * 80)

mlp_results = []
xgb_results = []

for fold, (train_idx, val_idx) in enumerate(splits, start=1):

    print(f"\nFold {fold}/{N_SPLITS}")

    X_train_fold = X[train_idx]
    X_val_fold = X[val_idx]

    y_train_fold = y[train_idx]
    y_val_fold = y[val_idx]

    # --------------------------------------------------------
    # MLP
    # --------------------------------------------------------

    mlp = clone(mlp_model)

    start = time.time()

    mlp.fit(
        X_train_fold,
        y_train_fold
    )

    pred_mlp = mlp.predict(X_val_fold)

    mlp_time = time.time() - start

    mlp_acc = accuracy_score(
        y_val_fold,
        pred_mlp
    )

    mlp_f1 = f1_score(
        y_val_fold,
        pred_mlp,
        average="macro",
        zero_division=0
    )

    mlp_prec = precision_score(
        y_val_fold,
        pred_mlp,
        average="macro",
        zero_division=0
    )

    mlp_rec = recall_score(
        y_val_fold,
        pred_mlp,
        average="macro",
        zero_division=0
    )

    mlp_bal = balanced_accuracy_score(
        y_val_fold,
        pred_mlp
    )

    mlp_mcc = matthews_corrcoef(
        y_val_fold,
        pred_mlp
    )

    mlp_results.append({
        "Fold": fold,
        "Accuracy": mlp_acc,
        "Macro_F1": mlp_f1,
        "Macro_Precision": mlp_prec,
        "Macro_Recall": mlp_rec,
        "Balanced_Accuracy": mlp_bal,
        "MCC": mlp_mcc,
        "Time_sec": mlp_time
    })

    print(
        f"Flat MLP | "
        f"Accuracy={mlp_acc*100:.2f}% | "
        f"Macro-F1={mlp_f1*100:.2f}%"
    )

    # --------------------------------------------------------
    # XGBOOST
    # --------------------------------------------------------

    if xgb_available:

        xgb = clone(xgb_model)

        start = time.time()

        xgb.fit(
            X_train_fold,
            y_train_fold
        )

        pred_xgb = xgb.predict(X_val_fold)

        xgb_time = time.time() - start

        xgb_acc = accuracy_score(
            y_val_fold,
            pred_xgb
        )

        xgb_f1 = f1_score(
            y_val_fold,
            pred_xgb,
            average="macro",
            zero_division=0
        )

        xgb_prec = precision_score(
            y_val_fold,
            pred_xgb,
            average="macro",
            zero_division=0
        )

        xgb_rec = recall_score(
            y_val_fold,
            pred_xgb,
            average="macro",
            zero_division=0
        )

        xgb_bal = balanced_accuracy_score(
            y_val_fold,
            pred_xgb
        )

        xgb_mcc = matthews_corrcoef(
            y_val_fold,
            pred_xgb
        )

        xgb_results.append({
            "Fold": fold,
            "Accuracy": xgb_acc,
            "Macro_F1": xgb_f1,
            "Macro_Precision": xgb_prec,
            "Macro_Recall": xgb_rec,
            "Balanced_Accuracy": xgb_bal,
            "MCC": xgb_mcc,
            "Time_sec": xgb_time
        })

        print(
            f"XGBoost  | "
            f"Accuracy={xgb_acc*100:.2f}% | "
            f"Macro-F1={xgb_f1*100:.2f}%"
        )


# ============================================================
# [8] MLP CROSS-VALIDATION SUMMARY
# ============================================================

print("\n")
print("=" * 80)
print("[8] FLAT MLP 5-FOLD RESULTS")
print("=" * 80)

mlp_df = pd.DataFrame(mlp_results)

print(
    mlp_df[
        [
            "Fold",
            "Accuracy",
            "Macro_F1",
            "Macro_Precision",
            "Macro_Recall",
            "Balanced_Accuracy",
            "MCC"
        ]
    ].to_string(index=False)
)

print("\nMean ± SD")

mlp_summary = {}

for metric in [
    "Accuracy",
    "Macro_F1",
    "Macro_Precision",
    "Macro_Recall",
    "Balanced_Accuracy",
    "MCC"
]:

    mean_val = mlp_df[metric].mean()
    std_val = mlp_df[metric].std(ddof=1)

    mlp_summary[metric] = (
        mean_val,
        std_val
    )

    print(
        f"{metric:20s}: "
        f"{mean_val*100:.2f}% ± {std_val*100:.2f}%"
        if metric != "MCC"
        else
        f"{metric:20s}: "
        f"{mean_val:.4f} ± {std_val:.4f}"
    )


# ============================================================
# [9] XGBOOST CROSS-VALIDATION SUMMARY
# ============================================================

if xgb_available:

    print("\n")
    print("=" * 80)
    print("[9] XGBOOST 5-FOLD RESULTS")
    print("=" * 80)

    xgb_df = pd.DataFrame(xgb_results)

    print(
        xgb_df[
            [
                "Fold",
                "Accuracy",
                "Macro_F1",
                "Macro_Precision",
                "Macro_Recall",
                "Balanced_Accuracy",
                "MCC"
            ]
        ].to_string(index=False)
    )

    print("\nMean ± SD")

    for metric in [
        "Accuracy",
        "Macro_F1",
        "Macro_Precision",
        "Macro_Recall",
        "Balanced_Accuracy",
        "MCC"
    ]:

        mean_val = xgb_df[metric].mean()
        std_val = xgb_df[metric].std(ddof=1)

        print(
            f"{metric:20s}: "
            f"{mean_val*100:.2f}% ± {std_val*100:.2f}%"
            if metric != "MCC"
            else
            f"{metric:20s}: "
            f"{mean_val:.4f} ± {std_val:.4f}"
        )


# ============================================================
# [10] STATISTICAL TEST — MLP VS XGBOOST
# ============================================================

print("\n")
print("=" * 80)
print("[10] PAIRED STATISTICAL COMPARISON")
print("=" * 80)

if xgb_available:

    mlp_f1_folds = mlp_df["Macro_F1"].values
    xgb_f1_folds = xgb_df["Macro_F1"].values

    print("\nFold-wise Macro-F1:")
    print("MLP :", np.round(mlp_f1_folds, 4))
    print("XGB :", np.round(xgb_f1_folds, 4))

    # --------------------------------------------------------
    # Wilcoxon
    # --------------------------------------------------------

    try:

        wilcoxon_stat, wilcoxon_p = wilcoxon(
            mlp_f1_folds,
            xgb_f1_folds,
            zero_method="wilcox",
            alternative="two-sided"
        )

        print("\nWilcoxon signed-rank test")
        print("Statistic :", wilcoxon_stat)
        print("p-value   :", wilcoxon_p)

    except Exception as e:

        wilcoxon_stat = np.nan
        wilcoxon_p = np.nan

        print(
            "Wilcoxon test could not be computed:",
            str(e)
        )

    # --------------------------------------------------------
    # Paired t-test
    # --------------------------------------------------------

    try:

        t_stat, t_p = ttest_rel(
            mlp_f1_folds,
            xgb_f1_folds
        )

        print("\nPaired t-test")
        print("t-statistic :", t_stat)
        print("p-value     :", t_p)

    except Exception as e:

        t_stat = np.nan
        t_p = np.nan

        print(
            "Paired t-test could not be computed:",
            str(e)
        )

else:

    print(
        "⚠ XGBoost unavailable — statistical comparison skipped."
    )


# ============================================================
# [11] CROSS-VALIDATION VISUALIZATION
# ============================================================

print("\n")
print("=" * 80)
print("[11] CROSS-VALIDATION VISUALIZATION")
print("=" * 80)

plt.figure(figsize=(9, 5))

plt.plot(
    mlp_df["Fold"],
    mlp_df["Accuracy"] * 100,
    marker="o",
    label="Flat MLP Accuracy"
)

plt.plot(
    mlp_df["Fold"],
    mlp_df["Macro_F1"] * 100,
    marker="s",
    label="Flat MLP Macro-F1"
)

if xgb_available:

    plt.plot(
        xgb_df["Fold"],
        xgb_df["Accuracy"] * 100,
        marker="o",
        linestyle="--",
        label="XGBoost Accuracy"
    )

    plt.plot(
        xgb_df["Fold"],
        xgb_df["Macro_F1"] * 100,
        marker="s",
        linestyle="--",
        label="XGBoost Macro-F1"
    )

plt.xlabel("Fold")
plt.ylabel("Score (%)")
plt.title("5-Fold Cross-Validation Performance")
plt.xticks(range(1, N_SPLITS + 1))
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()


# ============================================================
# [12] FIND FINAL FLAT MLP
# ============================================================

print("\n")
print("=" * 80)
print("[12] FINDING FINAL FLAT MLP")
print("=" * 80)

final_mlp = None

for name in [
    "best_model",
    "final_model",
    "mlp_model"
]:

    if name in globals():

        candidate = globals()[name]

        # Check whether candidate looks like a sklearn MLP
        if hasattr(candidate, "predict"):

            try:

                candidate_params = (
                    candidate.named_steps["mlp"].coefs_
                    if hasattr(candidate, "named_steps")
                    and "mlp" in candidate.named_steps
                    and hasattr(candidate.named_steps["mlp"], "coefs_")
                    else None
                )

                if candidate_params is not None:

                    final_mlp = candidate

                    print(
                        f"✓ Selected existing model: {name}"
                    )

                    break

            except Exception:
                pass


# If the old PyTorch model is available but sklearn MLP isn't,
# train one final sklearn MLP on all training data.
if final_mlp is None:

    print(
        "No compatible sklearn Flat MLP found."
    )

    print(
        "Training final sklearn Flat MLP on complete training set..."
    )

    final_mlp = clone(mlp_model)

    final_mlp.fit(
        X,
        y
    )

    print("✓ Final MLP trained")


# ============================================================
# [13] FIND TEST DATA
# ============================================================

print("\n")
print("=" * 80)
print("[13] FINDING TEST DATA")
print("=" * 80)

test_X_candidates = [
    "Xte",
    "X_test",
    "Xtest"
]

test_y_candidates = [
    "yte",
    "y_test",
    "ytest"
]

X_test_final = None
y_test_final = None

for name in test_X_candidates:

    if name in globals():

        try:

            arr = np.asarray(globals()[name])

            if arr.ndim == 2:

                X_test_final = arr
                print("✓ Test features :", name)
                break

        except Exception:
            pass


for name in test_y_candidates:

    if name in globals():

        try:

            arr = np.asarray(globals()[name]).ravel()

            if X_test_final is not None and len(arr) == len(X_test_final):

                y_test_final = arr
                print("✓ Test labels   :", name)
                break

        except Exception:
            pass


if X_test_final is None or y_test_final is None:

    print(
        "⚠ Test variables not found."
    )

else:

    print(
        "Test shape:",
        X_test_final.shape
    )


# ============================================================
# [14] SHAP EXPLAINABILITY
# ============================================================

print("\n")
print("=" * 80)
print("[14] SHAP EXPLAINABILITY")
print("=" * 80)

shap_available = False

if X_test_final is not None and y_test_final is not None:

    try:

        import shap

        shap_available = True

        print("✓ SHAP available")

        # Generate test predictions
        test_pred = final_mlp.predict(
            X_test_final
        )

        correct_idx = np.where(
            test_pred == y_test_final
        )[0]

        wrong_idx = np.where(
            test_pred != y_test_final
        )[0]

        if len(correct_idx) == 0:

            print(
                "⚠ No correctly classified sample found."
            )

        if len(wrong_idx) == 0:

            print(
                "⚠ No misclassified sample found."
            )

        # ----------------------------------------------------
        # Select one correct and one incorrect sample
        # ----------------------------------------------------

        selected_indices = []

        if len(correct_idx) > 0:
            selected_indices.append(
                int(correct_idx[0])
            )

        if len(wrong_idx) > 0:
            selected_indices.append(
                int(wrong_idx[0])
            )

        # ----------------------------------------------------
        # SHAP Kernel Explainer
        # ----------------------------------------------------

        # Keep background small so Kaggle/T4 does not become slow.
        background_size = min(
            50,
            len(X)
        )

        background = X[
            np.random.choice(
                len(X),
                background_size,
                replace=False
            )
        ]

        print(
            "Background samples:",
            background_size
        )

        # Pipeline predict_proba is directly usable
        explainer = shap.KernelExplainer(
            final_mlp.predict_proba,
            background
        )

        for idx in selected_indices:

            sample = X_test_final[
                idx:idx + 1
            ]

            print("\nSHAP sample index:", idx)
            print(
                "True class:",
                y_test_final[idx]
            )
            print(
                "Predicted class:",
                test_pred[idx]
            )

            shap_values = explainer.shap_values(
                sample,
                nsamples=100
            )

            # ------------------------------------------------
            # Handle SHAP output format differences
            # ------------------------------------------------

            if isinstance(shap_values, list):

                pred_class = int(
                    test_pred[idx]
                )

                values = np.asarray(
                    shap_values[pred_class]
                ).reshape(-1)

            else:

                values_arr = np.asarray(
                    shap_values
                )

                if values_arr.ndim == 3:

                    pred_class = int(
                        test_pred[idx]
                    )

                    # Common format:
                    # samples × features × classes
                    values = values_arr[
                        0, :, pred_class
                    ]

                else:

                    values = values_arr.reshape(-1)

            # ------------------------------------------------
            # Top 15 SHAP features
            # ------------------------------------------------

            top_k = min(
                15,
                len(values)
            )

            top_idx = np.argsort(
                np.abs(values)
            )[-top_k:][::-1]

            plt.figure(figsize=(9, 6))

            plt.barh(
                range(top_k),
                values[top_idx]
            )

            plt.yticks(
                range(top_k),
                [
                    f"Feature {i}"
                    for i in top_idx
                ]
            )

            plt.gca().invert_yaxis()

            plt.xlabel("SHAP value")
            plt.ylabel("Feature")
            plt.title(
                f"SHAP Explanation | "
                f"Sample {idx} | "
                f"True={y_test_final[idx]} | "
                f"Pred={test_pred[idx]}"
            )

            plt.tight_layout()
            plt.show()

    except ImportError:

        print(
            "⚠ SHAP is not installed."
        )

        print(
            "Install with: pip install shap"
        )

    except Exception as e:

        print(
            "⚠ SHAP analysis encountered an issue:"
        )

        print(
            repr(e)
        )

else:

    print(
        "⚠ Test data unavailable — SHAP skipped."
    )


# ============================================================
# [15] LIME EXPLAINABILITY
# ============================================================

print("\n")
print("=" * 80)
print("[15] LIME EXPLAINABILITY")
print("=" * 80)

if X_test_final is not None and y_test_final is not None:

    try:

        from lime.lime_tabular import (
            LimeTabularExplainer
        )

        print("✓ LIME available")

        test_pred = final_mlp.predict(
            X_test_final
        )

        correct_idx = np.where(
            test_pred == y_test_final
        )[0]

        wrong_idx = np.where(
            test_pred != y_test_final
        )[0]

        lime_explainer = LimeTabularExplainer(
            X,
            feature_names=[
                f"Feature_{i}"
                for i in range(D)
            ],
            class_names=[
                str(c)
                for c in np.unique(y)
            ],
            mode="classification",
            discretize_continuous=True,
            random_state=RANDOM_SEED
        )

        # ----------------------------------------------------
        # One correct + one incorrect sample
        # ----------------------------------------------------

        lime_indices = []

        if len(correct_idx) > 0:
            lime_indices.append(
                int(correct_idx[0])
            )

        if len(wrong_idx) > 0:
            lime_indices.append(
                int(wrong_idx[0])
            )

        for idx in lime_indices:

            print("\nLIME sample index:", idx)

            print(
                "True class:",
                y_test_final[idx]
            )

            print(
                "Predicted class:",
                test_pred[idx]
            )

            explanation = lime_explainer.explain_instance(
                X_test_final[idx],
                final_mlp.predict_proba,
                num_features=15,
                top_labels=1
            )

            print("\nTop LIME features:")

            for feature, weight in explanation.as_list():

                print(
                    f"{feature:35s} "
                    f"{weight:+.5f}"
                )

            # ------------------------------------------------
            # Plot LIME explanation
            # ------------------------------------------------

            fig = explanation.as_pyplot_figure()

            plt.title(
                f"LIME Explanation | "
                f"Sample {idx} | "
                f"True={y_test_final[idx]} | "
                f"Pred={test_pred[idx]}"
            )

            plt.tight_layout()
            plt.show()

    except ImportError:

        print(
            "⚠ LIME is not installed."
        )

        print(
            "Install with: pip install lime"
        )

    except Exception as e:

        print(
            "⚠ LIME analysis encountered an issue:"
        )

        print(
            repr(e)
        )

else:

    print(
        "⚠ Test data unavailable — LIME skipped."
    )


# ============================================================
# [16] FINAL STEP 16 SUMMARY
# ============================================================

print("\n")
print("=" * 80)
print("STEP 16 — FINAL SUMMARY")
print("=" * 80)

print(
    "Cross-validation mode :",
    CV_MODE
)

print(
    "Number of folds       :",
    N_SPLITS
)

print(
    f"Flat MLP CV Accuracy  : "
    f"{mlp_df['Accuracy'].mean()*100:.2f}% ± "
    f"{mlp_df['Accuracy'].std(ddof=1)*100:.2f}%"
)

print(
    f"Flat MLP CV Macro-F1   : "
    f"{mlp_df['Macro_F1'].mean()*100:.2f}% ± "
    f"{mlp_df['Macro_F1'].std(ddof=1)*100:.2f}%"
)

if xgb_available:

    print(
        f"XGBoost CV Accuracy   : "
        f"{xgb_df['Accuracy'].mean()*100:.2f}% ± "
        f"{xgb_df['Accuracy'].std(ddof=1)*100:.2f}%"
    )

    print(
        f"XGBoost CV Macro-F1   : "
        f"{xgb_df['Macro_F1'].mean()*100:.2f}% ± "
        f"{xgb_df['Macro_F1'].std(ddof=1)*100:.2f}%"
    )

    print(
        "\nStatistical test:"
    )

    print(
        "Wilcoxon p-value      :",
        wilcoxon_p
    )

    print(
        "Paired t-test p-value :",
        t_p
    )

print("\nExplainability:")

if shap_available:
    print("✓ SHAP attempted")
else:
    print("⚠ SHAP unavailable/not completed")

print("✓ LIME section executed")

if CV_MODE == "STRATIFIED":

    print("\nIMPORTANT LIMITATION:")
    print(
        "No genuine subject IDs were available for the current"
    )
    print(
        "Xtr/ytr arrays. Therefore the reported 5-fold CV is"
    )
    print(
        "SAMPLE-LEVEL STRATIFIED CV, NOT SUBJECT-GROUPED CV."
    )

print("\n")
print("=" * 80)
print("STEP 16 COMPLETE")
print("=" * 80)